// CtorDtorPlacement — OpenMFC implementation.
// Sources: global_ctordtor_placement.cpp

// AUTO-GENERATED by tools/harvest/gen_ctordtor.py -- real default-ctor/dtor thunks
// for header-defined constructible classes.
#include "openmfc/afxwin.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxole.h"
#include "openmfc/afxdisp.h"
#include "openmfc/afxdao.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include <new>
#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

// Symbol: ??0CCmdTarget@@QEAA@XZ
extern "C" void* MS_ABI impl___0CCmdTarget__QEAA_XZ(void* pThis) { return new (pThis) CCmdTarget(); }
