// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CFrameWndEx@@IEAA@XZ
// Constructor: CFrameWndEx::CFrameWndEx
extern "C" void* MS_ABI impl___0CFrameWndEx__IEAA_XZ(void* pThis) {
    return new(pThis) CFrameWndEx();
}
// Symbol: ??0CMDIChildWnd@@QEAA@XZ
// Constructor: CMDIChildWnd::CMDIChildWnd
extern "C" void* MS_ABI impl___0CMDIChildWnd__QEAA_XZ(void* pThis) {
    return new(pThis) CMDIChildWnd();
}
// Symbol: ??0CMDIChildWndEx@@IEAA@XZ
// Constructor: CMDIChildWndEx::CMDIChildWndEx
extern "C" void* MS_ABI impl___0CMDIChildWndEx__IEAA_XZ(void* pThis) {
    return new(pThis) CMDIChildWndEx();
}
// Symbol: ??0CMDIFrameWnd@@QEAA@XZ
// Constructor: CMDIFrameWnd::CMDIFrameWnd
extern "C" void* MS_ABI impl___0CMDIFrameWnd__QEAA_XZ(void* pThis) {
    return new(pThis) CMDIFrameWnd();
}
// Symbol: ??0CMDIFrameWndEx@@IEAA@XZ
// Constructor: CMDIFrameWndEx::CMDIFrameWndEx
extern "C" void* MS_ABI impl___0CMDIFrameWndEx__IEAA_XZ(void* pThis) {
    return new(pThis) CMDIFrameWndEx();
}
// Symbol: ??0CMiniFrameWnd@@QEAA@XZ
// Constructor: CMiniFrameWnd::CMiniFrameWnd
extern "C" void* MS_ABI impl___0CMiniFrameWnd__QEAA_XZ(void* pThis) {
    return new(pThis) CMiniFrameWnd();
}
// Symbol: ??0CSplitterWnd@@QEAA@XZ
// Constructor: CSplitterWnd::CSplitterWnd
extern "C" void* MS_ABI impl___0CSplitterWnd__QEAA_XZ(void* pThis) {
    return new(pThis) CSplitterWnd();
}
// Symbol: ??1CFrameWndEx@@MEAA@XZ
// Destructor: CFrameWndEx::~CFrameWndEx
extern "C" void MS_ABI impl___1CFrameWndEx__MEAA_XZ(void* pThis) {
    ((CFrameWndEx*)pThis)->~CFrameWndEx();
}
// Symbol: ??1CMDIChildWndEx@@MEAA@XZ
// Destructor: CMDIChildWndEx::~CMDIChildWndEx
extern "C" void MS_ABI impl___1CMDIChildWndEx__MEAA_XZ(void* pThis) {
    ((CMDIChildWndEx*)pThis)->~CMDIChildWndEx();
}
// Symbol: ??1CMDIFrameWndEx@@MEAA@XZ
// Destructor: CMDIFrameWndEx::~CMDIFrameWndEx
extern "C" void MS_ABI impl___1CMDIFrameWndEx__MEAA_XZ(void* pThis) {
    ((CMDIFrameWndEx*)pThis)->~CMDIFrameWndEx();
}
// Symbol: ??1CMiniFrameWnd@@UEAA@XZ
// Destructor: CMiniFrameWnd::~CMiniFrameWnd
extern "C" void MS_ABI impl___1CMiniFrameWnd__UEAA_XZ(void* pThis) {
    ((CMiniFrameWnd*)pThis)->~CMiniFrameWnd();
}
// Symbol: ??1CSplitterWnd@@UEAA@XZ
// Destructor: CSplitterWnd::~CSplitterWnd
extern "C" void MS_ABI impl___1CSplitterWnd__UEAA_XZ(void* pThis) {
    ((CSplitterWnd*)pThis)->~CSplitterWnd();
}
// Symbol: ?ActivateFrame@CFrameWnd@@UEAAXH@Z
// CFrameWnd::ActivateFrame
extern "C" void MS_ABI impl__ActivateFrame_CFrameWnd__UEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->ActivateFrame(p0);
}
// Symbol: ?ActivateFrame@CMDIChildWnd@@UEAAXH@Z
// CMDIChildWnd::ActivateFrame
extern "C" void MS_ABI impl__ActivateFrame_CMDIChildWnd__UEAAXH_Z(CMDIChildWnd* pThis, int p0) {
    pThis->ActivateFrame(p0);
}
// Symbol: ?ActivateNext@CSplitterWnd@@UEAAXH@Z
// CSplitterWnd::ActivateNext
extern "C" void MS_ABI impl__ActivateNext_CSplitterWnd__UEAAXH_Z(CSplitterWnd* pThis, int p0) {
    pThis->ActivateNext(p0);
}
// Symbol: ?AddFrameWnd@CFrameWnd@@IEAAXXZ
// CFrameWnd::AddFrameWnd
extern "C" void MS_ABI impl__AddFrameWnd_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->AddFrameWnd();
}
// Symbol: ?BeginModalState@CFrameWnd@@UEAAXXZ
// CFrameWnd::BeginModalState
extern "C" void MS_ABI impl__BeginModalState_CFrameWnd__UEAAXXZ(CFrameWnd* pThis) {
    pThis->BeginModalState();
}
// Symbol: ?BringToTop@CFrameWnd@@IEAAXH@Z
// CFrameWnd::BringToTop
extern "C" void MS_ABI impl__BringToTop_CFrameWnd__IEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->BringToTop(p0);
}
// Symbol: ?CanActivateNext@CSplitterWnd@@UEAAHH@Z
// CSplitterWnd::CanActivateNext
extern "C" int MS_ABI impl__CanActivateNext_CSplitterWnd__UEAAHH_Z(CSplitterWnd* pThis, int p0) {
    return (int)pThis->CanActivateNext(p0);
}
// Symbol: ?CanDock@CFrameWnd@@QEAAKVCRect@@KPEAPEAVCDockBar@@@Z
// CFrameWnd::CanDock
extern "C" unsigned long MS_ABI impl__CanDock_CFrameWnd__QEAAKVCRect__KPEAPEAVCDockBar___Z(CFrameWnd* pThis, CRect p0, unsigned long p1, CDockBar** p2) {
    return (unsigned long)pThis->CanDock(p0, p1, p2);
}
// Symbol: ?CanEnterHelpMode@CFrameWnd@@QEAAHXZ
// CFrameWnd::CanEnterHelpMode
extern "C" int MS_ABI impl__CanEnterHelpMode_CFrameWnd__QEAAHXZ(CFrameWnd* pThis) {
    return (int)pThis->CanEnterHelpMode();
}
// Symbol: ?Create@CMDIChildWnd@@UEAAHPEB_W0KAEBUtagRECT@@PEAVCMDIFrameWnd@@PEAUCCreateContext@@@Z
// CMDIChildWnd::Create
extern "C" int MS_ABI impl__Create_CMDIChildWnd__UEAAHPEB_W0KAEBUtagRECT__PEAVCMDIFrameWnd__PEAUCCreateContext___Z(CMDIChildWnd* pThis, const wchar_t* p0, const wchar_t* p1, unsigned long p2, const RECT* p3, CMDIFrameWnd* p4, CCreateContext* p5) {
    return (int)pThis->Create(p0, p1, p2, (*p3), p4, p5);
}
// Symbol: ?Create@CSplitterWnd@@UEAAHPEAVCWnd@@HHUtagSIZE@@PEAUCCreateContext@@KI@Z
// CSplitterWnd::Create
extern "C" int MS_ABI impl__Create_CSplitterWnd__UEAAHPEAVCWnd__HHUtagSIZE__PEAUCCreateContext__KI_Z(CSplitterWnd* pThis, CWnd* p0, int p1, int p2, SIZE p3, CCreateContext* p4, unsigned long p5, unsigned int p6) {
    return (int)pThis->Create(p0, p1, p2, p3, p4, p5, p6);
}
// Symbol: ?CreateClient@CMDIFrameWnd@@UEAAHPEAUtagCREATESTRUCTW@@PEAVCMenu@@@Z
// CMDIFrameWnd::CreateClient
extern "C" int MS_ABI impl__CreateClient_CMDIFrameWnd__UEAAHPEAUtagCREATESTRUCTW__PEAVCMenu___Z(CMDIFrameWnd* pThis, CREATESTRUCTW* p0, CMenu* p1) {
    return (int)pThis->CreateClient(p0, p1);
}
// Symbol: ?CreateFloatingFrame@CFrameWnd@@QEAAPEAVCMiniDockFrameWnd@@K@Z
// CFrameWnd::CreateFloatingFrame
extern "C" CMiniDockFrameWnd* MS_ABI impl__CreateFloatingFrame_CFrameWnd__QEAAPEAVCMiniDockFrameWnd__K_Z(CFrameWnd* pThis, unsigned long p0) {
    return (CMiniDockFrameWnd*)pThis->CreateFloatingFrame(p0);
}
// Symbol: ?CreateStatic@CSplitterWnd@@UEAAHPEAVCWnd@@HHKI@Z
// CSplitterWnd::CreateStatic
extern "C" int MS_ABI impl__CreateStatic_CSplitterWnd__UEAAHPEAVCWnd__HHKI_Z(CSplitterWnd* pThis, CWnd* p0, int p1, int p2, unsigned long p3, unsigned int p4) {
    return (int)pThis->CreateStatic(p0, p1, p2, p3, p4);
}
// Symbol: ?CreateView@CFrameWnd@@QEAAPEAVCWnd@@PEAUCCreateContext@@I@Z
// CFrameWnd::CreateView
extern "C" CWnd* MS_ABI impl__CreateView_CFrameWnd__QEAAPEAVCWnd__PEAUCCreateContext__I_Z(CFrameWnd* pThis, CCreateContext* p0, unsigned int p1) {
    return (CWnd*)pThis->CreateView(p0, p1);
}
// Symbol: ?CreateView@CSplitterWnd@@UEAAHHHPEAUCRuntimeClass@@UtagSIZE@@PEAUCCreateContext@@@Z
// CSplitterWnd::CreateView
extern "C" int MS_ABI impl__CreateView_CSplitterWnd__UEAAHHHPEAUCRuntimeClass__UtagSIZE__PEAUCCreateContext___Z(CSplitterWnd* pThis, int p0, int p1, CRuntimeClass* p2, SIZE p3, CCreateContext* p4) {
    return (int)pThis->CreateView(p0, p1, p2, p3, p4);
}
// Symbol: ?DelayUpdateFrameMenu@CFrameWnd@@UEAAXPEAUHMENU__@@@Z
// CFrameWnd::DelayUpdateFrameMenu
extern "C" void MS_ABI impl__DelayUpdateFrameMenu_CFrameWnd__UEAAXPEAUHMENU_____Z(CFrameWnd* pThis, HMENU__* p0) {
    pThis->DelayUpdateFrameMenu(p0);
}
// Symbol: ?DestroyDockBars@CFrameWnd@@QEAAXXZ
// CFrameWnd::DestroyDockBars
extern "C" void MS_ABI impl__DestroyDockBars_CFrameWnd__QEAAXXZ(CFrameWnd* pThis) {
    pThis->DestroyDockBars();
}
// Symbol: ?DestroyWindow@CMDIChildWnd@@UEAAHXZ
// CMDIChildWnd::DestroyWindow
extern "C" int MS_ABI impl__DestroyWindow_CMDIChildWnd__UEAAHXZ(CMDIChildWnd* pThis) {
    return (int)pThis->DestroyWindow();
}
// Symbol: ?DockControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@IPEBUtagRECT@@@Z
// CFrameWnd::DockControlBar
extern "C" void MS_ABI impl__DockControlBar_CFrameWnd__QEAAXPEAVCControlBar__IPEBUtagRECT___Z(CFrameWnd* pThis, CControlBar* p0, unsigned int p1, const RECT* p2) {
    pThis->DockControlBar(p0, p1, p2);
}
// Symbol: ?DockControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@PEAVCDockBar@@PEBUtagRECT@@@Z
// CFrameWnd::DockControlBar
extern "C" void MS_ABI impl__DockControlBar_CFrameWnd__QEAAXPEAVCControlBar__PEAVCDockBar__PEBUtagRECT___Z(CFrameWnd* pThis, CControlBar* p0, CDockBar* p1, const RECT* p2) {
    pThis->DockControlBar(p0, p1, p2);
}
// Symbol: ?DoKeyboardSplit@CSplitterWnd@@UEAAHXZ
// CSplitterWnd::DoKeyboardSplit
extern "C" int MS_ABI impl__DoKeyboardSplit_CSplitterWnd__UEAAHXZ(CSplitterWnd* pThis) {
    return (int)pThis->DoKeyboardSplit();
}
// Symbol: ?EnableDocking@CFrameWnd@@QEAAXK@Z
// CFrameWnd::EnableDocking
extern "C" void MS_ABI impl__EnableDocking_CFrameWnd__QEAAXK_Z(CFrameWnd* pThis, unsigned long p0) {
    pThis->EnableDocking(p0);
}
// Symbol: ?EnableDocking@CFrameWndEx@@QEAAHK@Z
// CFrameWndEx::EnableDocking
extern "C" int MS_ABI impl__EnableDocking_CFrameWndEx__QEAAHK_Z(CFrameWndEx* pThis, unsigned long p0) {
    return (int)pThis->EnableDocking(p0);
}
// Symbol: ?EndModalState@CFrameWnd@@UEAAXXZ
// CFrameWnd::EndModalState
extern "C" void MS_ABI impl__EndModalState_CFrameWnd__UEAAXXZ(CFrameWnd* pThis) {
    pThis->EndModalState();
}
// Symbol: ?ExitHelpMode@CFrameWnd@@UEAAXXZ
// CFrameWnd::ExitHelpMode
extern "C" void MS_ABI impl__ExitHelpMode_CFrameWnd__UEAAXXZ(CFrameWnd* pThis) {
    pThis->ExitHelpMode();
}
// Symbol: ?FloatControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@VCPoint@@K@Z
// CFrameWnd::FloatControlBar
extern "C" void MS_ABI impl__FloatControlBar_CFrameWnd__QEAAXPEAVCControlBar__VCPoint__K_Z(CFrameWnd* pThis, CControlBar* p0, CPoint p1, unsigned long p2) {
    pThis->FloatControlBar(p0, p1, p2);
}
// Symbol: ?GetActiveDocument@CFrameWnd@@UEAAPEAVCDocument@@XZ
// CFrameWnd::GetActiveDocument
extern "C" CDocument* MS_ABI impl__GetActiveDocument_CFrameWnd__UEAAPEAVCDocument__XZ(CFrameWnd* pThis) {
    return (CDocument*)pThis->GetActiveDocument();
}
// Symbol: ?GetActiveFrame@CFrameWnd@@UEAAPEAV1@XZ
// CFrameWnd::GetActiveFrame
extern "C" void* MS_ABI impl__GetActiveFrame_CFrameWnd__UEAAPEAV1_XZ(CFrameWnd* pThis) {
    return (void*)pThis->GetActiveFrame();
}
// Symbol: ?GetActiveView@CFrameWnd@@QEBAPEAVCView@@XZ
// CFrameWnd::GetActiveView
extern "C" CView* MS_ABI impl__GetActiveView_CFrameWnd__QEBAPEAVCView__XZ(const CFrameWnd* pThis) {
    return (CView*)pThis->GetActiveView();
}
// Symbol: ?GetColumnInfo@CSplitterWnd@@QEBAXHAEAH0@Z
// CSplitterWnd::GetColumnInfo
extern "C" void MS_ABI impl__GetColumnInfo_CSplitterWnd__QEBAXHAEAH0_Z(const CSplitterWnd* pThis, int p0, int* p1, int p2) {
    pThis->GetColumnInfo(p0, (*p1), p2);
}
// Symbol: ?GetControlBar@CFrameWnd@@QEAAPEAVCControlBar@@I@Z
// CFrameWnd::GetControlBar
extern "C" CControlBar* MS_ABI impl__GetControlBar_CFrameWnd__QEAAPEAVCControlBar__I_Z(CFrameWnd* pThis, unsigned int p0) {
    return (CControlBar*)pThis->GetControlBar(p0);
}
// Symbol: ?GetDefaultAccelerator@CFrameWnd@@UEAAPEAUHACCEL__@@XZ
// CFrameWnd::GetDefaultAccelerator
extern "C" HACCEL__* MS_ABI impl__GetDefaultAccelerator_CFrameWnd__UEAAPEAUHACCEL____XZ(CFrameWnd* pThis) {
    return (HACCEL__*)pThis->GetDefaultAccelerator();
}
// Symbol: ?GetDockState@CFrameWnd@@QEBAXAEAVCDockState@@@Z
// CFrameWnd::GetDockState
extern "C" void MS_ABI impl__GetDockState_CFrameWnd__QEBAXAEAVCDockState___Z(const CFrameWnd* pThis, CDockState* p0) {
    pThis->GetDockState((*p0));
}
// Symbol: ?GetIconWndClass@CFrameWnd@@IEAAPEB_WKI@Z
// CFrameWnd::GetIconWndClass
extern "C" const wchar_t* MS_ABI impl__GetIconWndClass_CFrameWnd__IEAAPEB_WKI_Z(CFrameWnd* pThis, unsigned long p0, unsigned int p1) {
    return (const wchar_t*)pThis->GetIconWndClass(p0, p1);
}
// Symbol: ?GetMDIFrame@CMDIChildWnd@@QEAAPEAVCMDIFrameWnd@@XZ
// CMDIChildWnd::GetMDIFrame
extern "C" CMDIFrameWnd* MS_ABI impl__GetMDIFrame_CMDIChildWnd__QEAAPEAVCMDIFrameWnd__XZ(CMDIChildWnd* pThis) {
    return (CMDIFrameWnd*)pThis->GetMDIFrame();
}
// Symbol: ?GetMenu@CFrameWnd@@UEBAPEAVCMenu@@XZ
// CFrameWnd::GetMenu
extern "C" CMenu* MS_ABI impl__GetMenu_CFrameWnd__UEBAPEAVCMenu__XZ(const CFrameWnd* pThis) {
    return (CMenu*)pThis->GetMenu();
}
// Symbol: ?GetMenuBarInfo@CFrameWnd@@QEBAHJJPEAUtagMENUBARINFO@@@Z
// CFrameWnd::GetMenuBarInfo
extern "C" int MS_ABI impl__GetMenuBarInfo_CFrameWnd__QEBAHJJPEAUtagMENUBARINFO___Z(const CFrameWnd* pThis, long p0, long p1, MENUBARINFO* p2) {
    return (int)pThis->GetMenuBarInfo(p0, p1, p2);
}
// Symbol: ?GetMenuBarState@CFrameWnd@@UEBAKXZ
// CFrameWnd::GetMenuBarState
extern "C" unsigned long MS_ABI impl__GetMenuBarState_CFrameWnd__UEBAKXZ(const CFrameWnd* pThis) {
    return (unsigned long)pThis->GetMenuBarState();
}
// Symbol: ?GetMenuBarVisibility@CFrameWnd@@UEBAKXZ
// CFrameWnd::GetMenuBarVisibility
extern "C" unsigned long MS_ABI impl__GetMenuBarVisibility_CFrameWnd__UEBAKXZ(const CFrameWnd* pThis) {
    return (unsigned long)pThis->GetMenuBarVisibility();
}
// Symbol: ?GetMessageBar@CFrameWnd@@UEAAPEAVCWnd@@XZ
// CFrameWnd::GetMessageBar
extern "C" CWnd* MS_ABI impl__GetMessageBar_CFrameWnd__UEAAPEAVCWnd__XZ(CFrameWnd* pThis) {
    return (CWnd*)pThis->GetMessageBar();
}
// Symbol: ?GetPane@CSplitterWnd@@QEBAPEAVCWnd@@HH@Z
// CSplitterWnd::GetPane
extern "C" CWnd* MS_ABI impl__GetPane_CSplitterWnd__QEBAPEAVCWnd__HH_Z(const CSplitterWnd* pThis, int p0, int p1) {
    return (CWnd*)pThis->GetPane(p0, p1);
}
// Symbol: ?GetRowInfo@CSplitterWnd@@QEBAXHAEAH0@Z
// CSplitterWnd::GetRowInfo
extern "C" void MS_ABI impl__GetRowInfo_CSplitterWnd__QEBAXHAEAH0_Z(const CSplitterWnd* pThis, int p0, int* p1, int p2) {
    pThis->GetRowInfo(p0, (*p1), p2);
}
// Symbol: ?InitialUpdateFrame@CFrameWnd@@QEAAXPEAVCDocument@@H@Z
// CFrameWnd::InitialUpdateFrame
extern "C" void MS_ABI impl__InitialUpdateFrame_CFrameWnd__QEAAXPEAVCDocument__H_Z(CFrameWnd* pThis, CDocument* p0, int p1) {
    pThis->InitialUpdateFrame(p0, p1);
}
// Symbol: ?IsFrameWnd@CFrameWnd@@UEBAHXZ
// CFrameWnd::IsFrameWnd
extern "C" int MS_ABI impl__IsFrameWnd_CFrameWnd__UEBAHXZ(const CFrameWnd* pThis) {
    return (int)pThis->IsFrameWnd();
}
// Symbol: ?IsTracking@CFrameWnd@@QEAAHXZ
// CFrameWnd::IsTracking
extern "C" int MS_ABI impl__IsTracking_CFrameWnd__QEAAHXZ(CFrameWnd* pThis) {
    return (int)pThis->IsTracking();
}
// Symbol: ?LoadAccelTable@CFrameWnd@@QEAAHPEB_W@Z
// CFrameWnd::LoadAccelTable
extern "C" int MS_ABI impl__LoadAccelTable_CFrameWnd__QEAAHPEB_W_Z(CFrameWnd* pThis, const wchar_t* p0) {
    return (int)pThis->LoadAccelTable(p0);
}
// Symbol: ?LoadBarState@CFrameWnd@@QEAAXPEB_W@Z
// CFrameWnd::LoadBarState
extern "C" void MS_ABI impl__LoadBarState_CFrameWnd__QEAAXPEB_W_Z(CFrameWnd* pThis, const wchar_t* p0) {
    pThis->LoadBarState(p0);
}
// Symbol: ?LoadFrame@CFrameWndEx@@UEAAHIKPEAVCWnd@@PEAUCCreateContext@@@Z
// CFrameWndEx::LoadFrame
extern "C" int MS_ABI impl__LoadFrame_CFrameWndEx__UEAAHIKPEAVCWnd__PEAUCCreateContext___Z(CFrameWndEx* pThis, unsigned int p0, unsigned long p1, CWnd* p2, CCreateContext* p3) {
    return (int)pThis->LoadFrame(p0, p1, p2, p3);
}
// Symbol: ?MDIGetActive@CMDIFrameWnd@@QEBAPEAVCMDIChildWnd@@PEAH@Z
// CMDIFrameWnd::MDIGetActive
extern "C" CMDIChildWnd* MS_ABI impl__MDIGetActive_CMDIFrameWnd__QEBAPEAVCMDIChildWnd__PEAH_Z(const CMDIFrameWnd* pThis, int* p0) {
    return (CMDIChildWnd*)pThis->MDIGetActive(p0);
}
// Symbol: ?NegotiateBorderSpace@CFrameWnd@@UEAAHIPEAUtagRECT@@@Z
// CFrameWnd::NegotiateBorderSpace
extern "C" int MS_ABI impl__NegotiateBorderSpace_CFrameWnd__UEAAHIPEAUtagRECT___Z(CFrameWnd* pThis, unsigned int p0, RECT* p1) {
    return (int)pThis->NegotiateBorderSpace(p0, p1);
}
// Symbol: ?NotifyFloatingWindows@CFrameWnd@@QEAAXK@Z
// CFrameWnd::NotifyFloatingWindows
extern "C" void MS_ABI impl__NotifyFloatingWindows_CFrameWnd__QEAAXK_Z(CFrameWnd* pThis, unsigned long p0) {
    pThis->NotifyFloatingWindows(p0);
}
// Symbol: ?OnActivate@CFrameWnd@@IEAAXIPEAVCWnd@@H@Z
// CFrameWnd::OnActivate
extern "C" void MS_ABI impl__OnActivate_CFrameWnd__IEAAXIPEAVCWnd__H_Z(CFrameWnd* pThis, unsigned int p0, CWnd* p1, int p2) {
    pThis->OnActivate(p0, p1, p2);
}
// Symbol: ?OnActivateTopLevel@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnActivateTopLevel
extern "C" __int64 MS_ABI impl__OnActivateTopLevel_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnActivateTopLevel(p0, p1);
}
// Symbol: ?OnBarCheck@CFrameWnd@@QEAAHI@Z
// CFrameWnd::OnBarCheck
extern "C" int MS_ABI impl__OnBarCheck_CFrameWnd__QEAAHI_Z(CFrameWnd* pThis, unsigned int p0) {
    return (int)pThis->OnBarCheck(p0);
}
// Symbol: ?OnChevronPushed@CFrameWnd@@IEAAHIPEAUtagNMHDR@@PEA_J@Z
// CFrameWnd::OnChevronPushed
extern "C" int MS_ABI impl__OnChevronPushed_CFrameWnd__IEAAHIPEAUtagNMHDR__PEA_J_Z(CFrameWnd* pThis, unsigned int p0, NMHDR* p1, __int64* p2) {
    return (int)pThis->OnChevronPushed(p0, p1, p2);
}
// Symbol: ?OnClose@CFrameWnd@@IEAAXXZ
// CFrameWnd::OnClose
extern "C" void MS_ABI impl__OnClose_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->OnClose();
}
// Symbol: ?OnCommandHelp@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnCommandHelp
extern "C" __int64 MS_ABI impl__OnCommandHelp_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnCommandHelp(p0, p1);
}
// Symbol: ?OnContextHelp@CFrameWnd@@QEAAXXZ
// CFrameWnd::OnContextHelp
extern "C" void MS_ABI impl__OnContextHelp_CFrameWnd__QEAAXXZ(CFrameWnd* pThis) {
    pThis->OnContextHelp();
}
// Symbol: ?OnCreate@CFrameWnd@@IEAAHPEAUtagCREATESTRUCTW@@@Z
// CFrameWnd::OnCreate
extern "C" int MS_ABI impl__OnCreate_CFrameWnd__IEAAHPEAUtagCREATESTRUCTW___Z(CFrameWnd* pThis, CREATESTRUCTW* p0) {
    return (int)pThis->OnCreate(p0);
}
// Symbol: ?OnCreateClient@CFrameWnd@@MEAAHPEAUtagCREATESTRUCTW@@PEAUCCreateContext@@@Z
// CFrameWnd::OnCreateClient
extern "C" int MS_ABI impl__OnCreateClient_CFrameWnd__MEAAHPEAUtagCREATESTRUCTW__PEAUCCreateContext___Z(CFrameWnd* pThis, CREATESTRUCTW* p0, CCreateContext* p1) {
    return (int)pThis->OnCreateClient(p0, p1);
}
// Symbol: ?OnCreateHelper@CFrameWnd@@IEAAHPEAUtagCREATESTRUCTW@@PEAUCCreateContext@@@Z
// CFrameWnd::OnCreateHelper
extern "C" int MS_ABI impl__OnCreateHelper_CFrameWnd__IEAAHPEAUtagCREATESTRUCTW__PEAUCCreateContext___Z(CFrameWnd* pThis, CREATESTRUCTW* p0, CCreateContext* p1) {
    return (int)pThis->OnCreateHelper(p0, p1);
}
// Symbol: ?OnDDEExecute@CFrameWnd@@IEAAXPEAVCWnd@@PEAX@Z
// CFrameWnd::OnDDEExecute
extern "C" void MS_ABI impl__OnDDEExecute_CFrameWnd__IEAAXPEAVCWnd__PEAX_Z(CFrameWnd* pThis, CWnd* p0, void* p1) {
    pThis->OnDDEExecute(p0, p1);
}
// Symbol: ?OnDDEInitiate@CFrameWnd@@IEAAXPEAVCWnd@@II@Z
// CFrameWnd::OnDDEInitiate
extern "C" void MS_ABI impl__OnDDEInitiate_CFrameWnd__IEAAXPEAVCWnd__II_Z(CFrameWnd* pThis, CWnd* p0, unsigned int p1, unsigned int p2) {
    pThis->OnDDEInitiate(p0, p1, p2);
}
// Symbol: ?OnDDETerminate@CFrameWnd@@IEAAXPEAVCWnd@@@Z
// CFrameWnd::OnDDETerminate
extern "C" void MS_ABI impl__OnDDETerminate_CFrameWnd__IEAAXPEAVCWnd___Z(CFrameWnd* pThis, CWnd* p0) {
    pThis->OnDDETerminate(p0);
}
// Symbol: ?OnDestroy@CFrameWnd@@IEAAXXZ
// CFrameWnd::OnDestroy
extern "C" void MS_ABI impl__OnDestroy_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->OnDestroy();
}
// Symbol: ?OnDropFiles@CFrameWnd@@IEAAXPEAUHDROP__@@@Z
// CFrameWnd::OnDropFiles
extern "C" void MS_ABI impl__OnDropFiles_CFrameWnd__IEAAXPEAUHDROP_____Z(CFrameWnd* pThis, HDROP__* p0) {
    pThis->OnDropFiles(p0);
}
// Symbol: ?OnEnable@CFrameWnd@@IEAAXH@Z
// CFrameWnd::OnEnable
extern "C" void MS_ABI impl__OnEnable_CFrameWnd__IEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->OnEnable(p0);
}
// Symbol: ?OnEndSession@CFrameWnd@@IEAAXH@Z
// CFrameWnd::OnEndSession
extern "C" void MS_ABI impl__OnEndSession_CFrameWnd__IEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->OnEndSession(p0);
}
// Symbol: ?OnEnterIdle@CFrameWnd@@IEAAXIPEAVCWnd@@@Z
// CFrameWnd::OnEnterIdle
extern "C" void MS_ABI impl__OnEnterIdle_CFrameWnd__IEAAXIPEAVCWnd___Z(CFrameWnd* pThis, unsigned int p0, CWnd* p1) {
    pThis->OnEnterIdle(p0, p1);
}
// Symbol: ?OnEraseBkgnd@CFrameWnd@@IEAAHPEAVCDC@@@Z
// CFrameWnd::OnEraseBkgnd
extern "C" int MS_ABI impl__OnEraseBkgnd_CFrameWnd__IEAAHPEAVCDC___Z(CFrameWnd* pThis, CDC* p0) {
    return (int)pThis->OnEraseBkgnd(p0);
}
// Symbol: ?OnHelp@CFrameWnd@@IEAAXXZ
// CFrameWnd::OnHelp
extern "C" void MS_ABI impl__OnHelp_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->OnHelp();
}
// Symbol: ?OnHelpHitTest@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnHelpHitTest
extern "C" __int64 MS_ABI impl__OnHelpHitTest_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnHelpHitTest(p0, p1);
}
// Symbol: ?OnHelpPromptAddr@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnHelpPromptAddr
extern "C" __int64 MS_ABI impl__OnHelpPromptAddr_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnHelpPromptAddr(p0, p1);
}
// Symbol: ?OnHideMenuBar@CFrameWnd@@MEAAXXZ
// CFrameWnd::OnHideMenuBar
extern "C" void MS_ABI impl__OnHideMenuBar_CFrameWnd__MEAAXXZ(CFrameWnd* pThis) {
    pThis->OnHideMenuBar();
}
// Symbol: ?OnHScroll@CFrameWnd@@IEAAXIIPEAVCScrollBar@@@Z
// CFrameWnd::OnHScroll
extern "C" void MS_ABI impl__OnHScroll_CFrameWnd__IEAAXIIPEAVCScrollBar___Z(CFrameWnd* pThis, unsigned int p0, unsigned int p1, CScrollBar* p2) {
    pThis->OnHScroll(p0, p1, p2);
}
// Symbol: ?OnIdleUpdateCmdUI@CFrameWnd@@IEAAXXZ
// CFrameWnd::OnIdleUpdateCmdUI
extern "C" void MS_ABI impl__OnIdleUpdateCmdUI_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->OnIdleUpdateCmdUI();
}
// Symbol: ?OnInitMenu@CFrameWnd@@IEAAXPEAVCMenu@@@Z
// CFrameWnd::OnInitMenu
extern "C" void MS_ABI impl__OnInitMenu_CFrameWnd__IEAAXPEAVCMenu___Z(CFrameWnd* pThis, CMenu* p0) {
    pThis->OnInitMenu(p0);
}
// Symbol: ?OnInitMenuPopup@CFrameWnd@@IEAAXPEAVCMenu@@IH@Z
// CFrameWnd::OnInitMenuPopup
extern "C" void MS_ABI impl__OnInitMenuPopup_CFrameWnd__IEAAXPEAVCMenu__IH_Z(CFrameWnd* pThis, CMenu* p0, unsigned int p1, int p2) {
    pThis->OnInitMenuPopup(p0, p1, p2);
}
// Symbol: ?OnInvertTracker@CSplitterWnd@@MEAAXAEBVCRect@@@Z
// CSplitterWnd::OnInvertTracker
extern "C" void MS_ABI impl__OnInvertTracker_CSplitterWnd__MEAAXAEBVCRect___Z(CSplitterWnd* pThis, const CRect* p0) {
    pThis->OnInvertTracker((*p0));
}
// Symbol: ?OnMenuChar@CFrameWnd@@IEAA_JIIPEAVCMenu@@@Z
// CFrameWnd::OnMenuChar
extern "C" __int64 MS_ABI impl__OnMenuChar_CFrameWnd__IEAA_JIIPEAVCMenu___Z(CFrameWnd* pThis, unsigned int p0, unsigned int p1, CMenu* p2) {
    return (__int64)pThis->OnMenuChar(p0, p1, p2);
}
// Symbol: ?OnMenuSelect@CFrameWnd@@IEAAXIIPEAUHMENU__@@@Z
// CFrameWnd::OnMenuSelect
extern "C" void MS_ABI impl__OnMenuSelect_CFrameWnd__IEAAXIIPEAUHMENU_____Z(CFrameWnd* pThis, unsigned int p0, unsigned int p1, HMENU__* p2) {
    pThis->OnMenuSelect(p0, p1, p2);
}
// Symbol: ?OnNcActivate@CFrameWnd@@IEAAHH@Z
// CFrameWnd::OnNcActivate
extern "C" int MS_ABI impl__OnNcActivate_CFrameWnd__IEAAHH_Z(CFrameWnd* pThis, int p0) {
    return (int)pThis->OnNcActivate(p0);
}
// Symbol: ?OnPaletteChanged@CFrameWnd@@IEAAXPEAVCWnd@@@Z
// CFrameWnd::OnPaletteChanged
extern "C" void MS_ABI impl__OnPaletteChanged_CFrameWnd__IEAAXPEAVCWnd___Z(CFrameWnd* pThis, CWnd* p0) {
    pThis->OnPaletteChanged(p0);
}
// Symbol: ?OnPopMessageString@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnPopMessageString
extern "C" __int64 MS_ABI impl__OnPopMessageString_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnPopMessageString(p0, p1);
}
// Symbol: ?OnQueryEndSession@CFrameWnd@@IEAAHXZ
// CFrameWnd::OnQueryEndSession
extern "C" int MS_ABI impl__OnQueryEndSession_CFrameWnd__IEAAHXZ(CFrameWnd* pThis) {
    return (int)pThis->OnQueryEndSession();
}
// Symbol: ?OnQueryNewPalette@CFrameWnd@@IEAAHXZ
// CFrameWnd::OnQueryNewPalette
extern "C" int MS_ABI impl__OnQueryNewPalette_CFrameWnd__IEAAHXZ(CFrameWnd* pThis) {
    return (int)pThis->OnQueryNewPalette();
}
// Symbol: ?OnSetCursor@CFrameWnd@@IEAAHPEAVCWnd@@II@Z
// CFrameWnd::OnSetCursor
extern "C" int MS_ABI impl__OnSetCursor_CFrameWnd__IEAAHPEAVCWnd__II_Z(CFrameWnd* pThis, CWnd* p0, unsigned int p1, unsigned int p2) {
    return (int)pThis->OnSetCursor(p0, p1, p2);
}
// Symbol: ?OnSetFocus@CFrameWnd@@IEAAXPEAVCWnd@@@Z
// CFrameWnd::OnSetFocus
extern "C" void MS_ABI impl__OnSetFocus_CFrameWnd__IEAAXPEAVCWnd___Z(CFrameWnd* pThis, CWnd* p0) {
    pThis->OnSetFocus(p0);
}
// Symbol: ?OnSetMessageString@CFrameWnd@@IEAA_J_K_J@Z
// CFrameWnd::OnSetMessageString
extern "C" __int64 MS_ABI impl__OnSetMessageString_CFrameWnd__IEAA_J_K_J_Z(CFrameWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnSetMessageString(p0, p1);
}
// Symbol: ?OnSetPreviewMode@CFrameWnd@@UEAAXHPEAUCPrintPreviewState@@@Z
// CFrameWnd::OnSetPreviewMode
extern "C" void MS_ABI impl__OnSetPreviewMode_CFrameWnd__UEAAXHPEAUCPrintPreviewState___Z(CFrameWnd* pThis, int p0, CPrintPreviewState* p1) {
    pThis->OnSetPreviewMode(p0, p1);
}
// Symbol: ?OnShowMenuBar@CFrameWnd@@MEAAXXZ
// CFrameWnd::OnShowMenuBar
extern "C" void MS_ABI impl__OnShowMenuBar_CFrameWnd__MEAAXXZ(CFrameWnd* pThis) {
    pThis->OnShowMenuBar();
}
// Symbol: ?OnSize@CFrameWnd@@IEAAXIHH@Z
// CFrameWnd::OnSize
extern "C" void MS_ABI impl__OnSize_CFrameWnd__IEAAXIHH_Z(CFrameWnd* pThis, unsigned int p0, int p1, int p2) {
    pThis->OnSize(p0, p1, p2);
}
// Symbol: ?OnSysCommand@CFrameWnd@@IEAAXI_J@Z
// CFrameWnd::OnSysCommand
extern "C" void MS_ABI impl__OnSysCommand_CFrameWnd__IEAAXI_J_Z(CFrameWnd* pThis, unsigned int p0, __int64 p1) {
    pThis->OnSysCommand(p0, p1);
}
// Symbol: ?OnToolTipText@CFrameWnd@@IEAAHIPEAUtagNMHDR@@PEA_J@Z
// CFrameWnd::OnToolTipText
extern "C" int MS_ABI impl__OnToolTipText_CFrameWnd__IEAAHIPEAUtagNMHDR__PEA_J_Z(CFrameWnd* pThis, unsigned int p0, NMHDR* p1, __int64* p2) {
    return (int)pThis->OnToolTipText(p0, p1, p2);
}
// Symbol: ?OnUpdateContextHelp@CFrameWnd@@IEAAXPEAVCCmdUI@@@Z
// CFrameWnd::OnUpdateContextHelp
extern "C" void MS_ABI impl__OnUpdateContextHelp_CFrameWnd__IEAAXPEAVCCmdUI___Z(CFrameWnd* pThis, CCmdUI* p0) {
    pThis->OnUpdateContextHelp(p0);
}
// Symbol: ?OnUpdateControlBarMenu@CFrameWnd@@QEAAXPEAVCCmdUI@@@Z
// CFrameWnd::OnUpdateControlBarMenu
extern "C" void MS_ABI impl__OnUpdateControlBarMenu_CFrameWnd__QEAAXPEAVCCmdUI___Z(CFrameWnd* pThis, CCmdUI* p0) {
    pThis->OnUpdateControlBarMenu(p0);
}
// Symbol: ?OnUpdateFrameMenu@CFrameWnd@@UEAAXPEAUHMENU__@@@Z
// CFrameWnd::OnUpdateFrameMenu
extern "C" void MS_ABI impl__OnUpdateFrameMenu_CFrameWnd__UEAAXPEAUHMENU_____Z(CFrameWnd* pThis, HMENU__* p0) {
    pThis->OnUpdateFrameMenu(p0);
}
// Symbol: ?OnUpdateFrameTitle@CFrameWnd@@UEAAXH@Z
// CFrameWnd::OnUpdateFrameTitle
extern "C" void MS_ABI impl__OnUpdateFrameTitle_CFrameWnd__UEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->OnUpdateFrameTitle(p0);
}
// Symbol: ?OnUpdateKeyIndicator@CFrameWnd@@IEAAXPEAVCCmdUI@@@Z
// CFrameWnd::OnUpdateKeyIndicator
extern "C" void MS_ABI impl__OnUpdateKeyIndicator_CFrameWnd__IEAAXPEAVCCmdUI___Z(CFrameWnd* pThis, CCmdUI* p0) {
    pThis->OnUpdateKeyIndicator(p0);
}
// Symbol: ?OnVScroll@CFrameWnd@@IEAAXIIPEAVCScrollBar@@@Z
// CFrameWnd::OnVScroll
extern "C" void MS_ABI impl__OnVScroll_CFrameWnd__IEAAXIIPEAVCScrollBar___Z(CFrameWnd* pThis, unsigned int p0, unsigned int p1, CScrollBar* p2) {
    pThis->OnVScroll(p0, p1, p2);
}
// Symbol: ?PostNcDestroy@CFrameWnd@@MEAAXXZ
// CFrameWnd::PostNcDestroy
extern "C" void MS_ABI impl__PostNcDestroy_CFrameWnd__MEAAXXZ(CFrameWnd* pThis) {
    pThis->PostNcDestroy();
}
// Symbol: ?ProcessHelpMsg@CFrameWnd@@IEAAHAEAUtagMSG@@PEAK@Z
// CFrameWnd::ProcessHelpMsg
extern "C" int MS_ABI impl__ProcessHelpMsg_CFrameWnd__IEAAHAEAUtagMSG__PEAK_Z(CFrameWnd* pThis, MSG* p0, unsigned long* p1) {
    return (int)pThis->ProcessHelpMsg((*p0), p1);
}
// Symbol: ?RecalcLayout@CFrameWnd@@UEAAXH@Z
// CFrameWnd::RecalcLayout
extern "C" void MS_ABI impl__RecalcLayout_CFrameWnd__UEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->RecalcLayout(p0);
}
// Symbol: ?RecalcLayout@CSplitterWnd@@UEAAXXZ
// CSplitterWnd::RecalcLayout
extern "C" void MS_ABI impl__RecalcLayout_CSplitterWnd__UEAAXXZ(CSplitterWnd* pThis) {
    pThis->RecalcLayout();
}
// Symbol: ?ReDockControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@PEAVCDockBar@@PEBUtagRECT@@@Z
// CFrameWnd::ReDockControlBar
extern "C" void MS_ABI impl__ReDockControlBar_CFrameWnd__QEAAXPEAVCControlBar__PEAVCDockBar__PEBUtagRECT___Z(CFrameWnd* pThis, CControlBar* p0, CDockBar* p1, const RECT* p2) {
    pThis->ReDockControlBar(p0, p1, p2);
}
// Symbol: ?RemoveControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@@Z
// CFrameWnd::RemoveControlBar
extern "C" void MS_ABI impl__RemoveControlBar_CFrameWnd__QEAAXPEAVCControlBar___Z(CFrameWnd* pThis, CControlBar* p0) {
    pThis->RemoveControlBar(p0);
}
// Symbol: ?RemoveFrameWnd@CFrameWnd@@IEAAXXZ
// CFrameWnd::RemoveFrameWnd
extern "C" void MS_ABI impl__RemoveFrameWnd_CFrameWnd__IEAAXXZ(CFrameWnd* pThis) {
    pThis->RemoveFrameWnd();
}
// Symbol: ?SaveBarState@CFrameWnd@@QEBAXPEB_W@Z
// CFrameWnd::SaveBarState
extern "C" void MS_ABI impl__SaveBarState_CFrameWnd__QEBAXPEB_W_Z(const CFrameWnd* pThis, const wchar_t* p0) {
    pThis->SaveBarState(p0);
}
// Symbol: ?SetActivePane@CSplitterWnd@@UEAAXHHPEAVCWnd@@@Z
// CSplitterWnd::SetActivePane
extern "C" void MS_ABI impl__SetActivePane_CSplitterWnd__UEAAXHHPEAVCWnd___Z(CSplitterWnd* pThis, int p0, int p1, CWnd* p2) {
    pThis->SetActivePane(p0, p1, p2);
}
// Symbol: ?SetActivePreviewView@CFrameWnd@@QEAAXPEAVCView@@@Z
// CFrameWnd::SetActivePreviewView
extern "C" void MS_ABI impl__SetActivePreviewView_CFrameWnd__QEAAXPEAVCView___Z(CFrameWnd* pThis, CView* p0) {
    pThis->SetActivePreviewView(p0);
}
// Symbol: ?SetActiveView@CFrameWnd@@QEAAXPEAVCView@@H@Z
// CFrameWnd::SetActiveView
extern "C" void MS_ABI impl__SetActiveView_CFrameWnd__QEAAXPEAVCView__H_Z(CFrameWnd* pThis, CView* p0, int p1) {
    pThis->SetActiveView(p0, p1);
}
// Symbol: ?SetColumnInfo@CSplitterWnd@@QEAAXHHH@Z
// CSplitterWnd::SetColumnInfo
extern "C" void MS_ABI impl__SetColumnInfo_CSplitterWnd__QEAAXHHH_Z(CSplitterWnd* pThis, int p0, int p1, int p2) {
    pThis->SetColumnInfo(p0, p1, p2);
}
// Symbol: ?SetDockState@CFrameWnd@@QEAAXAEBVCDockState@@@Z
// CFrameWnd::SetDockState
extern "C" void MS_ABI impl__SetDockState_CFrameWnd__QEAAXAEBVCDockState___Z(CFrameWnd* pThis, const CDockState* p0) {
    pThis->SetDockState((*p0));
}
// Symbol: ?SetHelpCapture@CFrameWnd@@IEAAPEAUHWND__@@UtagPOINT@@PEAH@Z
// CFrameWnd::SetHelpCapture
extern "C" HWND__* MS_ABI impl__SetHelpCapture_CFrameWnd__IEAAPEAUHWND____UtagPOINT__PEAH_Z(CFrameWnd* pThis, POINT p0, int* p1) {
    return (HWND__*)pThis->SetHelpCapture(p0, p1);
}
// Symbol: ?SetMenu@CFrameWnd@@UEAAHPEAVCMenu@@@Z
// CFrameWnd::SetMenu
extern "C" int MS_ABI impl__SetMenu_CFrameWnd__UEAAHPEAVCMenu___Z(CFrameWnd* pThis, CMenu* p0) {
    return (int)pThis->SetMenu(p0);
}
// Symbol: ?SetMenuBarState@CFrameWnd@@UEAAHK@Z
// CFrameWnd::SetMenuBarState
extern "C" int MS_ABI impl__SetMenuBarState_CFrameWnd__UEAAHK_Z(CFrameWnd* pThis, unsigned long p0) {
    return (int)pThis->SetMenuBarState(p0);
}
// Symbol: ?SetMenuBarVisibility@CFrameWnd@@UEAAXK@Z
// CFrameWnd::SetMenuBarVisibility
extern "C" void MS_ABI impl__SetMenuBarVisibility_CFrameWnd__UEAAXK_Z(CFrameWnd* pThis, unsigned long p0) {
    pThis->SetMenuBarVisibility(p0);
}
// Symbol: ?SetMessageText@CFrameWnd@@QEAAXI@Z
// CFrameWnd::SetMessageText
extern "C" void MS_ABI impl__SetMessageText_CFrameWnd__QEAAXI_Z(CFrameWnd* pThis, unsigned int p0) {
    pThis->SetMessageText(p0);
}
// Symbol: ?SetMessageText@CFrameWnd@@QEAAXPEB_W@Z
// CFrameWnd::SetMessageText
extern "C" void MS_ABI impl__SetMessageText_CFrameWnd__QEAAXPEB_W_Z(CFrameWnd* pThis, const wchar_t* p0) {
    pThis->SetMessageText(p0);
}
// Symbol: ?SetProgressBarPosition@CFrameWnd@@QEAAXH@Z
// CFrameWnd::SetProgressBarPosition
extern "C" void MS_ABI impl__SetProgressBarPosition_CFrameWnd__QEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->SetProgressBarPosition(p0);
}
// Symbol: ?SetProgressBarRange@CFrameWnd@@QEAAXHH@Z
// CFrameWnd::SetProgressBarRange
extern "C" void MS_ABI impl__SetProgressBarRange_CFrameWnd__QEAAXHH_Z(CFrameWnd* pThis, int p0, int p1) {
    pThis->SetProgressBarRange(p0, p1);
}
// Symbol: ?SetProgressBarState@CFrameWnd@@QEAAXW4TBPFLAG@@@Z
// CFrameWnd::SetProgressBarState
extern "C" void MS_ABI impl__SetProgressBarState_CFrameWnd__QEAAXW4TBPFLAG___Z(CFrameWnd* pThis, TBPFLAG p0) {
    pThis->SetProgressBarState(p0);
}
// Symbol: ?SetRowInfo@CSplitterWnd@@QEAAXHHH@Z
// CSplitterWnd::SetRowInfo
extern "C" void MS_ABI impl__SetRowInfo_CSplitterWnd__QEAAXHHH_Z(CSplitterWnd* pThis, int p0, int p1, int p2) {
    pThis->SetRowInfo(p0, p1, p2);
}
// Symbol: ?SetSplitCursor@CSplitterWnd@@MEAAXH@Z
// CSplitterWnd::SetSplitCursor
extern "C" void MS_ABI impl__SetSplitCursor_CSplitterWnd__MEAAXH_Z(CSplitterWnd* pThis, int p0) {
    pThis->SetSplitCursor(p0);
}
// Symbol: ?SetTaskbarOverlayIcon@CFrameWnd@@QEAAHIPEB_W@Z
// CFrameWnd::SetTaskbarOverlayIcon
extern "C" int MS_ABI impl__SetTaskbarOverlayIcon_CFrameWnd__QEAAHIPEB_W_Z(CFrameWnd* pThis, unsigned int p0, const wchar_t* p1) {
    return (int)pThis->SetTaskbarOverlayIcon(p0, p1);
}
// Symbol: ?SetTaskbarOverlayIcon@CFrameWnd@@QEAAHPEAUHICON__@@PEB_W@Z
// CFrameWnd::SetTaskbarOverlayIcon
extern "C" int MS_ABI impl__SetTaskbarOverlayIcon_CFrameWnd__QEAAHPEAUHICON____PEB_W_Z(CFrameWnd* pThis, HICON__* p0, const wchar_t* p1) {
    return (int)pThis->SetTaskbarOverlayIcon(p0, p1);
}
// Symbol: ?ShowControlBar@CFrameWnd@@QEAAXPEAVCControlBar@@HH@Z
// CFrameWnd::ShowControlBar
extern "C" void MS_ABI impl__ShowControlBar_CFrameWnd__QEAAXPEAVCControlBar__HH_Z(CFrameWnd* pThis, CControlBar* p0, int p1, int p2) {
    pThis->ShowControlBar(p0, p1, p2);
}
// Symbol: ?ShowOwnedWindows@CFrameWnd@@QEAAXH@Z
// CFrameWnd::ShowOwnedWindows
extern "C" void MS_ABI impl__ShowOwnedWindows_CFrameWnd__QEAAXH_Z(CFrameWnd* pThis, int p0) {
    pThis->ShowOwnedWindows(p0);
}
// Symbol: ?UpdateFrameTitleForDocument@CFrameWnd@@QEAAXPEB_W@Z
// CFrameWnd::UpdateFrameTitleForDocument
extern "C" void MS_ABI impl__UpdateFrameTitleForDocument_CFrameWnd__QEAAXPEB_W_Z(CFrameWnd* pThis, const wchar_t* p0) {
    pThis->UpdateFrameTitleForDocument(p0);
}
