// Thunks — OpenMFC implementation.
// Sources: manual_thunks.cpp, thunks.cpp

#define OPENMFC_APPCORE_IMPL

#include "detail/ManualThunksSupport.h"

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??1CDataSourceControl@@UEAA@XZ
extern "C" void* MS_ABI impl___1CDataSourceControl__UEAA_XZ(void* pThis) {
    std::lock_guard<std::mutex> lock(g_manualThunkStateMutex);
    g_dataSourceControlState.erase(pThis);
    return pThis;
}
// Symbol: ?ToVariant@CDataSourceControl@@QEAA?AVCOleVariant@@H@Z
// COleVariant returned by value via sret. MSVC x64 ABI: RCX=sret, RDX=this, R8D=nType.
extern "C" void* MS_ABI impl__ToVariant_CDataSourceControl__QEAA_AVCOleVariant__H_Z(
    COleVariant* sret, void* pThis, int nType) {
    (void)pThis; (void)nType;
    // No real bound-field machinery; construct an empty COleVariant in
    // the caller-provided return slot and return the sret pointer.
    new(sret) COleVariant();
    return sret;
}
// Symbol: ??0CDatabase@@QEAA@XZ
// Constructor: CDatabase::CDatabase
extern "C" void* MS_ABI impl___0CDatabase__QEAA_XZ(void* pThis) {
    return new(pThis) CDatabase();
}
// Symbol: ??1CDatabase@@UEAA@XZ
// Destructor: CDatabase::~CDatabase
extern "C" void MS_ABI impl___1CDatabase__UEAA_XZ(void* pThis) {
    ((CDatabase*)pThis)->~CDatabase();
}
// Symbol: ??1CRecordset@@UEAA@XZ
// Destructor: CRecordset::~CRecordset
extern "C" void MS_ABI impl___1CRecordset__UEAA_XZ(void* pThis) {
    ((CRecordset*)pThis)->~CRecordset();
}
// Symbol: ?AddNew@CRecordset@@UEAAXXZ
// CRecordset::AddNew
extern "C" void MS_ABI impl__AddNew_CRecordset__UEAAXXZ(CRecordset* pThis) {
    pThis->AddNew();
}
// Symbol: ?BeginTrans@CDatabase@@QEAAHXZ
// CDatabase::BeginTrans
extern "C" int MS_ABI impl__BeginTrans_CDatabase__QEAAHXZ(CDatabase* pThis) {
    return (int)pThis->BeginTrans();
}
// Symbol: ?Cancel@CDatabase@@QEAAXXZ
// CDatabase::Cancel
extern "C" void MS_ABI impl__Cancel_CDatabase__QEAAXXZ(CDatabase* pThis) {
    pThis->Cancel();
}
// Symbol: ?CancelUpdate@CRecordset@@QEAAXXZ
// CRecordset::CancelUpdate
extern "C" void MS_ABI impl__CancelUpdate_CRecordset__QEAAXXZ(CRecordset* pThis) {
    pThis->CancelUpdate();
}
// Symbol: ?ClearDirtyFieldStatus@CRecordset@@QEAAXK@Z
// CRecordset::ClearDirtyFieldStatus
extern "C" void MS_ABI impl__ClearDirtyFieldStatus_CRecordset__QEAAXK_Z(CRecordset* pThis, unsigned long p0) {
    pThis->ClearDirtyFieldStatus(p0);
}
// Symbol: ?Close@CDatabase@@UEAAXXZ
// CDatabase::Close
extern "C" void MS_ABI impl__Close_CDatabase__UEAAXXZ(CDatabase* pThis) {
    pThis->Close();
}
// Symbol: ?Close@CRecordset@@UEAAXXZ
// CRecordset::Close
extern "C" void MS_ABI impl__Close_CRecordset__UEAAXXZ(CRecordset* pThis) {
    pThis->Close();
}
// Symbol: ?CommitTrans@CDatabase@@QEAAHXZ
// CDatabase::CommitTrans
extern "C" int MS_ABI impl__CommitTrans_CDatabase__QEAAHXZ(CDatabase* pThis) {
    return (int)pThis->CommitTrans();
}
// Symbol: ?Delete@CRecordset@@UEAAXXZ
// CRecordset::Delete
extern "C" void MS_ABI impl__Delete_CRecordset__UEAAXXZ(CRecordset* pThis) {
    pThis->Delete();
}
// Symbol: ?DoFieldExchange@CRecordset@@UEAAXPEAVCFieldExchange@@@Z
// CRecordset::DoFieldExchange
extern "C" void MS_ABI impl__DoFieldExchange_CRecordset__UEAAXPEAVCFieldExchange___Z(CRecordset* pThis, CFieldExchange* p0) {
    pThis->DoFieldExchange(p0);
}
// Symbol: ?Edit@CRecordset@@UEAAXXZ
// CRecordset::Edit
extern "C" void MS_ABI impl__Edit_CRecordset__UEAAXXZ(CRecordset* pThis) {
    pThis->Edit();
}
// Symbol: ?ExecuteSQL@CDatabase@@QEAAXPEB_W@Z
// CDatabase::ExecuteSQL
extern "C" void MS_ABI impl__ExecuteSQL_CDatabase__QEAAXPEB_W_Z(CDatabase* pThis, const wchar_t* p0) {
    pThis->ExecuteSQL(p0);
}
// Symbol: ?IsFieldDirty@CRecordset@@QEAAHPEAX@Z
// CRecordset::IsFieldDirty
extern "C" int MS_ABI impl__IsFieldDirty_CRecordset__QEAAHPEAX_Z(CRecordset* pThis, void* p0) {
    return (int)pThis->IsFieldDirty(p0);
}
// Symbol: ?IsFieldNull@CRecordset@@QEAAHPEAX@Z
// CRecordset::IsFieldNull
extern "C" int MS_ABI impl__IsFieldNull_CRecordset__QEAAHPEAX_Z(CRecordset* pThis, void* p0) {
    return (int)pThis->IsFieldNull(p0);
}
// Symbol: ?IsFieldType@CFieldExchange@@QEAAHPEAI@Z
// CFieldExchange::IsFieldType
extern "C" int MS_ABI impl__IsFieldType_CFieldExchange__QEAAHPEAI_Z(CFieldExchange* pThis, unsigned int* p0) {
    return (int)pThis->IsFieldType(p0);
}
// Symbol: ?Move@CRecordset@@UEAAXJG@Z
// CRecordset::Move
extern "C" void MS_ABI impl__Move_CRecordset__UEAAXJG_Z(CRecordset* pThis, long p0, unsigned short p1) {
    pThis->Move(p0, p1);
}
// Symbol: ?OnSetOptions@CRecordset@@UEAAXPEAX@Z
// CRecordset::OnSetOptions
extern "C" void MS_ABI impl__OnSetOptions_CRecordset__UEAAXPEAX_Z(CRecordset* pThis, void* p0) {
    pThis->OnSetOptions(p0);
}
// Symbol: ?Open@CDatabase@@UEAAHPEB_WHH0H@Z
// CDatabase::Open
extern "C" int MS_ABI impl__Open_CDatabase__UEAAHPEB_WHH0H_Z(CDatabase* pThis, const wchar_t* p0, int p1, int p2, const wchar_t* p3, int p4) {
    return (int)pThis->Open(p0, p1, p2, p3, p4);
}
// Symbol: ?Open@CRecordset@@UEAAHIPEB_WK@Z
// CRecordset::Open
extern "C" int MS_ABI impl__Open_CRecordset__UEAAHIPEB_WK_Z(CRecordset* pThis, unsigned int p0, const wchar_t* p1, unsigned long p2) {
    return (int)pThis->Open(p0, p1, p2);
}
// Symbol: ?Rollback@CDatabase@@QEAAHXZ
// CDatabase::Rollback
extern "C" int MS_ABI impl__Rollback_CDatabase__QEAAHXZ(CDatabase* pThis) {
    return (int)pThis->Rollback();
}
// Symbol: ?SetDirtyFieldStatus@CRecordset@@QEAAXK@Z
// CRecordset::SetDirtyFieldStatus
extern "C" void MS_ABI impl__SetDirtyFieldStatus_CRecordset__QEAAXK_Z(CRecordset* pThis, unsigned long p0) {
    pThis->SetDirtyFieldStatus(p0);
}
// Symbol: ?SetFieldNull@CRecordset@@QEAAXPEAXH@Z
// CRecordset::SetFieldNull
extern "C" void MS_ABI impl__SetFieldNull_CRecordset__QEAAXPEAXH_Z(CRecordset* pThis, void* p0, int p1) {
    pThis->SetFieldNull(p0, p1);
}
// Symbol: ?SetParamNull@CRecordset@@QEAAXHH@Z
// CRecordset::SetParamNull
extern "C" void MS_ABI impl__SetParamNull_CRecordset__QEAAXHH_Z(CRecordset* pThis, int p0, int p1) {
    pThis->SetParamNull(p0, p1);
}
// Symbol: ?SetRowsetSize@CRecordset@@UEAAXK@Z
// CRecordset::SetRowsetSize
extern "C" void MS_ABI impl__SetRowsetSize_CRecordset__UEAAXK_Z(CRecordset* pThis, unsigned long p0) {
    pThis->SetRowsetSize(p0);
}
// Symbol: ?Update@CRecordset@@UEAAHXZ
// CRecordset::Update
extern "C" int MS_ABI impl__Update_CRecordset__UEAAHXZ(CRecordset* pThis) {
    return (int)pThis->Update();
}
