#pragma once
// Shared internals of the former global_interface_maps.cpp translation unit.
// Definitions live in detail/InterfaceMapsSupport.cpp, so file-scope state keeps a
// single instance across the classes this unit was split into.
namespace openmfc { namespace detail { namespace interfacemaps {} } }
using namespace openmfc::detail::interfacemaps;
// AUTO-GENERATED by tools/harvest/gen_ifacemap.py -- DO NOT EDIT BY HAND.
// Real AFX_INTERFACEMAP for the CCmdTarget OLE-class family (see the generator header).
#include <cstddef>

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif
#if defined(_MSC_VER) || defined(__MINGW32__)
  #define AFXAPI __cdecl
#else
  #define AFXAPI
#endif

struct AFX_INTERFACEMAP_ENTRY { const void* piid; size_t nOffset; };
struct AFX_INTERFACEMAP { const AFX_INTERFACEMAP* (AFXAPI* pfnGetBaseMap)(); const AFX_INTERFACEMAP_ENTRY* pEntries; };

// Empty terminator shared by every map (real IID->offset entries are mfc140u addresses).
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP_ENTRY g_ifaceEnd[];
} } }

extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CDocObjectServer__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnPoints__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnections__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumFormatEtc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumOleVerb__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumUnknown__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CHtmlControlSite__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CMFCBaseAccessibleObject__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleClientItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControl__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlContainer__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlSite__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDataSource__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDocObjectItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropSource__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropTarget__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleFrameHook__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleLinkingDoc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleMessageFilter__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleObjectFactory__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COlePropertyPage__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerDoc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CRichEditView__KAPEBUAFX_INTERFACEMAP__XZ();

namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CCmdTarget;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CDocObjectServer();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CDocObjectServer;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CEnumConnPoints();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CEnumConnPoints;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CEnumConnections();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CEnumConnections;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CEnumFormatEtc();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CEnumFormatEtc;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CEnumOleVerb();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CEnumOleVerb;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CEnumUnknown();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CEnumUnknown;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CHtmlControlSite();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CHtmlControlSite;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CMFCBaseAccessibleObject();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CMFCBaseAccessibleObject;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleClientItem();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleClientItem;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleControl();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleControl;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleControlContainer();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleControlContainer;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleControlSite();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleControlSite;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleDataSource();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleDataSource;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleDocObjectItem();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleDocObjectItem;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleDropSource();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleDropSource;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleDropTarget();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleDropTarget;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleFrameHook();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleFrameHook;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleLinkingDoc();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleLinkingDoc;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleMessageFilter();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleMessageFilter;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleObjectFactory();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleObjectFactory;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COlePropertyPage();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COlePropertyPage;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleServerDoc();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleServerDoc;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_COleServerItem();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_COleServerItem;
} } }

namespace openmfc { namespace detail { namespace interfacemaps {
const AFX_INTERFACEMAP* AFXAPI gib_CRichEditView();
} } }
namespace openmfc { namespace detail { namespace interfacemaps {
extern const AFX_INTERFACEMAP g_imap_CRichEditView;
} } }

