#pragma once
// Shared internals of the former manual_thunks.cpp translation unit.
// Definitions live in detail/ManualThunksSupport.cpp, so file-scope state keeps a
// single instance across the classes this unit was split into.
namespace openmfc { namespace detail { namespace manualthunks {} } }
using namespace openmfc::detail::manualthunks;
// Manually-written thunks for symbols the auto-generator cannot handle.
// Generated by tools/gen_manual_thunks.py
// These thunks provide proper parameter counts and return types (ABI-compatible),
// but return default values since our C++ method signatures differ from
// the MSVC DLL exports for these symbols.

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
#define MS_ABI __attribute__((ms_abi))
#else
#define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"
#include <cwchar>
#include <cstring>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>


namespace openmfc { namespace detail { namespace manualthunks {
struct RibbonWriteState {
    std::vector<std::wstring> events;
};
} } }

namespace openmfc { namespace detail { namespace manualthunks {
extern std::mutex g_manualThunkStateMutex;
} } }
namespace openmfc { namespace detail { namespace manualthunks {
extern std::unordered_map<void*, RibbonWriteState> g_ribbonWriterState;
} } }
namespace openmfc { namespace detail { namespace manualthunks {
extern std::unordered_map<void*, int> g_dynamicLayoutState;
} } }
namespace openmfc { namespace detail { namespace manualthunks {
extern std::unordered_map<void*, int> g_dataSourceControlState;
} } }

namespace openmfc { namespace detail { namespace manualthunks {
std::wstring ManualThunkCStringText(const CString* text);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
int RecordRibbonWrite(void* parser, const wchar_t* name);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
int RecordRibbonAttribute(void* parser, const CString* name, const std::wstring& value);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
std::wstring ManualThunkIntText(int value, int defaultValue);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
std::wstring ManualThunkUIntText(unsigned int value, unsigned int defaultValue);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
std::wstring ManualThunkULongText(unsigned long value, unsigned long defaultValue);
} } }

namespace openmfc { namespace detail { namespace manualthunks {
std::wstring ManualThunkSizeText(const CSize* value, const CSize* defaultValue);
} } }
























//=== XElementProgressBar (CMFCRibbonInfo inner class) =========================




//=== CDataSourceControl::ToVariant ============================================

