#pragma once
// Shared internals of the former global_string_atl_thunks.cpp translation unit.
// Definitions live in detail/StringAtlThunksSupport.cpp, so file-scope state keeps a
// single instance across the classes this unit was split into.
namespace openmfc { namespace detail { namespace stringatlthunks {} } }
using namespace openmfc::detail::stringatlthunks;
// AUTO-GENERATED by tools/harvest/gen_string_thunks.py -- DO NOT EDIT BY HAND.
// Real implementations of the exported ATL CStringT<char>/CStringT<wchar_t> (and their
// CSimpleStringT bases) methods.  Each forwards to the ATL-binary-compatible AtlStrT<CH>
// core.  See gen_string_thunks.py for the authoritative signature tables.
#include "detail/AtlStrTCore.h"

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

// Resolve the module whose string resources CStringT::LoadString / Format(nID) use.
HINSTANCE AFXAPI AfxGetResourceHandle();
HINSTANCE AFXAPI AfxGetInstanceHandle();
namespace openmfc { namespace detail { namespace stringatlthunks {
HINSTANCE GetResHandle();
} } }
namespace openmfc { namespace detail { namespace stringatlthunks {
template <class CH>
void Trim_StringAtlThunks(openmfc_str::AtlStrT<CH>* s, CH ch, const CH* set, int mode) {
    // mode bit1=left, bit2=right.  ch!=0 -> trim that char; set!=0 -> trim any in set;
    // else whitespace.
    auto match = [&](CH c) -> bool {
        if (ch) return c == ch;
        if (set) { for (const CH* q = set; *q; ++q) if (*q == c) return true; return false; }
        return c == (CH)' ' || c == (CH)'\t' || c == (CH)'\r' || c == (CH)'\n' ||
               c == (CH)'\v' || c == (CH)'\f';
    };
    int len = s->GetLength();
    if (len == 0) return;
    const CH* p = s->GetString();
    int start = 0, end = len;
    if (mode & 2) { while (end > 0 && match(p[end - 1])) --end; }
    if (mode & 1) { while (start < end && match(p[start])) ++start; }
    if (start == 0 && end == len) return;
    openmfc_str::AtlStrT<CH> tmp; tmp.ConstructPszN(s->GetString() + start, end - start);
    s->AssignCopy(tmp); tmp.Destruct();
}
} } }

namespace openmfc { namespace detail { namespace stringatlthunks {
template <class CH>
int ReplaceStr(openmfc_str::AtlStrT<CH>* s, const CH* oldS, const CH* newS) {
    if (!oldS || !*oldS) return 0;
    if (!newS) { static const CH z = 0; newS = &z; }
    int oldL = 0; while (oldS[oldL]) ++oldL;
    int newL = 0; while (newS[newL]) ++newL;
    // count occurrences
    int cnt = 0; const CH* src = s->GetString();
    for (const CH* p = src; *p; ) {
        const CH* a = p; const CH* b = oldS;
        while (*a && *b && *a == *b) { ++a; ++b; }
        if (!*b) { ++cnt; p += oldL; } else ++p;
    }
    if (cnt == 0) return 0;
    int srcL = s->GetLength();
    int outL = srcL + (newL - oldL) * cnt;
    openmfc_str::AtlStrT<CH> out; out.ConstructChRep((CH)' ', outL);
    CH* w = out.Buffer(); const CH* p = s->GetString();
    while (*p) {
        const CH* a = p; const CH* b = oldS;
        while (*a && *b && *a == *b) { ++a; ++b; }
        if (!*b) { for (int i = 0; i < newL; ++i) *w++ = newS[i]; p += oldL; }
        else *w++ = *p++;
    }
    *w = 0;
    s->AssignCopy(out); out.Destruct();
    return cnt;
}
} } }

namespace openmfc { namespace detail { namespace stringatlthunks {
template <class CH>
void Tokenize(const openmfc_str::AtlStrT<CH>* s, openmfc_str::AtlStrT<CH>* r,
              const CH* toks, int& iStart) {
    auto isTok = [&](CH c) -> bool { for (const CH* q = toks; q && *q; ++q) if (*q == c) return true; return false; };
    int len = s->GetLength();
    const CH* p = s->GetString();
    if (iStart < 0 || iStart > len || !toks) { r->Construct(); iStart = -1; return; }
    int i = iStart;
    while (i < len && isTok(p[i])) ++i;        // skip leading delimiters
    if (i >= len) { r->Construct(); iStart = -1; return; }
    int start = i;
    while (i < len && !isTok(p[i])) ++i;        // scan token
    r->ConstructPszN(p + start, i - start);
    iStart = (i < len) ? i + 1 : len + 1;
}
} } }






























































































































































































































































