#!/usr/bin/env python3
# Generate a <class>_virt_ords.h {name->ordinal} table for a class's EXPORTED virtual
# methods (mangling calling-convention U == public virtual: UEAA/UEBA), derived from the
# canonical mfc_complete_ordinal_mapping.json. This is the single source of truth; the
# header is a build artifact and is NOT checked in (see .gitignore). build_family_probe.sh
# regenerates any *_virt_ords.h a probe #includes before compiling.
#
# Usage: gen_virt_ords.py <ClassName|path/to/<class>_virt_ords.h> [out.h]
#   - If given a header path, the class name is the lowercased filename stem (minus
#     _virt_ords) matched case-insensitively against the class names in the JSON.
#   - Writes to out.h if given, else stdout.
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
# gen lives in tools/harvest/family; the JSON is at the repo root — walk up to find it.
MAP, d = None, HERE
while d != "/":
    cand = os.path.join(d, "mfc_complete_ordinal_mapping.json")
    if os.path.exists(cand):
        MAP = cand; break
    d = os.path.dirname(d)
if not MAP:
    sys.exit("gen_virt_ords: mfc_complete_ordinal_mapping.json not found above " + HERE)

def resolve_class(arg, names):
    base = os.path.basename(arg)
    stem = re.sub(r"_virt_ords\.h$", "", base)
    stem = re.sub(r"\.h$", "", stem)
    # exact class name passed?
    if arg in names:
        return arg
    low = stem.lower()
    for n in names:
        if n.lower() == low:
            return n
    sys.exit(f"gen_virt_ords: no class in {os.path.basename(MAP)} matches '{arg}' (stem '{stem}')")

def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_virt_ords.py <ClassName|<class>_virt_ords.h> [out.h]")
    m = json.load(open(MAP))
    exps = m["exports"]["mfc140u"]
    names = {re.match(r"\?\w+@(\w+)@@", e["symbol"]).group(1)
             for e in exps if re.match(r"\?\w+@(\w+)@@", e["symbol"])}
    cls = resolve_class(sys.argv[1], names)
    rows, seen = [], set()
    for e in exps:
        mt = re.match(rf"\?(\w+)@{re.escape(cls)}@@(UEAA|UEBA)", e["symbol"])
        if mt and mt.group(1) not in seen:
            seen.add(mt.group(1)); rows.append((mt.group(1), e["ordinal"]))
    rows.sort(key=lambda x: x[0])
    out = ["// GENERATED by gen_virt_ords.py from mfc_complete_ordinal_mapping.json — do not edit / do not commit.",
           f"// Exported virtuals (UEAA/UEBA) of {cls}, name->ordinal.",
           "struct V{const char*n;int ord;};", "static V VIRT[]={"]
    out += [f'  {{"{n}",{o}}},' for n, o in rows]
    out += ["};"]
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 2:
        open(sys.argv[2], "w").write(text)
    else:
        sys.stdout.write(text)

if __name__ == "__main__":
    main()
