// MFC Smoke Test - Comprehensive functionality test
// Tests actual MFC behavior using compile-time linking (NOT LoadLibrary!)
//
// This test verifies MSVC can link against OpenMFC at compile time.
// If cl.exe links successfully against openmfc.lib, the test passes.
// The mangled names generated by MSVC must match what's in the .def file.
//
// IMPORTANT: This test is meant to be compiled with MSVC only.
// MinGW cannot link against MSVC-mangled exports directly.

#include <cstdio>
#include <cstdint>

// =============================================================================
// MFC-style declarations - C++ linkage produces MSVC-mangled names
// =============================================================================

// When MSVC compiles these declarations, it generates mangled names:
//   ?AfxGetDllVersion@@YAKXZ
//   ?AfxThrowMemoryException@@YAXXZ
//   ?AfxThrowResourceException@@YAXXZ
//   etc.
//
// The linker must find these in openmfc.lib (generated from openmfc.def).
// If linking succeeds, the mangled names match.

// Version function
__declspec(dllimport) unsigned long __cdecl AfxGetDllVersion();

// Exception functions
__declspec(dllimport) void __cdecl AfxThrowMemoryException();
__declspec(dllimport) void __cdecl AfxThrowResourceException();
__declspec(dllimport) void __cdecl AfxThrowNotSupportedException();
__declspec(dllimport) void __cdecl AfxThrowUserException();
__declspec(dllimport) void __cdecl AfxThrowInvalidArgException();
__declspec(dllimport) void __cdecl AfxThrowFileException(int cause, long lOsError, const wchar_t* lpszFileName);

// Test framework
class MFCTest {
    int passed;
    int failed;
    
public:
    MFCTest() : passed(0), failed(0) {}
    
    void test(const char* name, bool condition) {
        printf("  %s: %s\n", name, condition ? "PASS" : "FAIL");
        if (condition) {
            passed++;
        } else {
            failed++;
        }
    }
    
    int run() {
        printf("=== OpenMFC Smoke Test (Compile-time Linked) ===\n\n");
        
        // If we reach main(), MSVC successfully linked against openmfc.lib.
        printf("Link test PASSED: MSVC resolved all imported symbols.\n\n");
        
        test_version();
        test_exceptions();
        
        printf("\n=== Results: %d passed, %d failed ===\n", passed, failed);
        return failed == 0 ? 0 : 1;
    }
    
private:
    void test_version() {
        printf("Testing version functions:\n");
        
        uint32_t version = AfxGetDllVersion();
        
        test("Version non-zero", version != 0);
        
        uint16_t major = (version >> 8) & 0xFF;
        
        // MFC 14.0 returns 0x0E00 (14.0)
        test("Version format valid (major 12-15)", major >= 12 && major <= 15);
        
        // Multiple calls consistency
        uint32_t v2 = AfxGetDllVersion();
        uint32_t v3 = AfxGetDllVersion();
        test("Version consistent", version == v2 && version == v3);
        
        printf("  AfxGetDllVersion() = 0x%04X (major=%d, minor=%d)\n", 
               version, (version >> 8) & 0xFF, version & 0xFF);
    }
    
    void test_exceptions() {
        printf("\nTesting exception functions (they should throw):\n");
        
        // Test AfxThrowMemoryException
        printf("  AfxThrowMemoryException: ");
        try {
            AfxThrowMemoryException();
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
        
        // Test AfxThrowResourceException
        printf("  AfxThrowResourceException: ");
        try {
            AfxThrowResourceException();
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
        
        // Test AfxThrowNotSupportedException
        printf("  AfxThrowNotSupportedException: ");
        try {
            AfxThrowNotSupportedException();
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
        
        // Test AfxThrowUserException
        printf("  AfxThrowUserException: ");
        try {
            AfxThrowUserException();
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
        
        // Test AfxThrowInvalidArgException
        printf("  AfxThrowInvalidArgException: ");
        try {
            AfxThrowInvalidArgException();
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
        
        // Test AfxThrowFileException
        printf("  AfxThrowFileException: ");
        try {
            AfxThrowFileException(2, -1, L"test.txt");  // fileNotFound=2
            printf("FAIL (no exception thrown)\n");
            failed++;
        } catch (...) {
            printf("PASS (exception caught)\n");
            passed++;
        }
    }
};

int main() {
    MFCTest test;
    return test.run();
}