// MSVC Linking Test for OpenMFC
//
// This test verifies MSVC can LINK against OpenMFC at compile time.
// NO runtime checks (LoadLibrary/GetProcAddress) - those are cheating.
//
// The test: declare functions with __declspec(dllimport) and call them.
// If cl.exe links successfully against openmfc.lib, the test passes.
// The mangled names generated by MSVC must match what's in the .def file.

#include <cstdio>

// =============================================================================
// MFC-style declarations - C++ linkage produces MSVC-mangled names
// =============================================================================

// When MSVC compiles these declarations, it generates mangled names:
//   ?AfxThrowMemoryException@@YAXXZ
//   ?AfxThrowNotSupportedException@@YAXXZ
//   ?AfxThrowInvalidArgException@@YAXXZ
//
// The linker must find these in openmfc.lib (generated from openmfc.def).
// If linking succeeds, the mangled names match.

__declspec(dllimport) void __cdecl AfxThrowMemoryException();
__declspec(dllimport) void __cdecl AfxThrowNotSupportedException();
__declspec(dllimport) void __cdecl AfxThrowInvalidArgException();

int main() {
    printf("=== OpenMFC MSVC Link Test ===\n\n");

    // If we reach main(), MSVC successfully linked against openmfc.lib.
    // The import library resolved our __declspec(dllimport) references.
    printf("Link test PASSED: MSVC resolved all imported symbols.\n\n");

    // Now call the functions to verify runtime behavior
    printf("Calling functions (may throw exceptions)...\n");

    try {
        AfxThrowMemoryException();
        printf("  AfxThrowMemoryException - OK (no exception)\n");
    } catch (...) {
        printf("  AfxThrowMemoryException - OK (exception caught)\n");
    }

    try {
        AfxThrowNotSupportedException();
        printf("  AfxThrowNotSupportedException - OK (no exception)\n");
    } catch (...) {
        printf("  AfxThrowNotSupportedException - OK (exception caught)\n");
    }

    try {
        AfxThrowInvalidArgException();
        printf("  AfxThrowInvalidArgException - OK (no exception)\n");
    } catch (...) {
        printf("  AfxThrowInvalidArgException - OK (exception caught)\n");
    }

    printf("\n=== All tests passed ===\n");
    return 0;
}
