// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CMFCVisualManager@@QEAA@H@Z
// Constructor: CMFCVisualManager::CMFCVisualManager
extern "C" void* MS_ABI impl___0CMFCVisualManager__QEAA_H_Z(void* pThis, int p0) {
    return new(pThis) CMFCVisualManager(p0);
}
// Symbol: ??0CMFCVisualManagerOffice2003@@QEAA@XZ
// Constructor: CMFCVisualManagerOffice2003::CMFCVisualManagerOffice2003
extern "C" void* MS_ABI impl___0CMFCVisualManagerOffice2003__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCVisualManagerOffice2003();
}
// Symbol: ??0CMFCVisualManagerOffice2007@@IEAA@XZ
// Constructor: CMFCVisualManagerOffice2007::CMFCVisualManagerOffice2007
extern "C" void* MS_ABI impl___0CMFCVisualManagerOffice2007__IEAA_XZ(void* pThis) {
    return new(pThis) CMFCVisualManagerOffice2007();
}
// Symbol: ??0CMFCVisualManagerVS2005@@QEAA@XZ
// Constructor: CMFCVisualManagerVS2005::CMFCVisualManagerVS2005
extern "C" void* MS_ABI impl___0CMFCVisualManagerVS2005__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCVisualManagerVS2005();
}
// Symbol: ??0CMFCVisualManagerWindows@@QEAA@H@Z
// Constructor: CMFCVisualManagerWindows::CMFCVisualManagerWindows
extern "C" void* MS_ABI impl___0CMFCVisualManagerWindows__QEAA_H_Z(void* pThis, int p0) {
    return new(pThis) CMFCVisualManagerWindows(p0);
}
// Symbol: ??0CMFCVisualManagerWindows7@@QEAA@XZ
// Constructor: CMFCVisualManagerWindows7::CMFCVisualManagerWindows7
extern "C" void* MS_ABI impl___0CMFCVisualManagerWindows7__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCVisualManagerWindows7();
}
// Symbol: ??1CMFCVisualManager@@UEAA@XZ
// Destructor: CMFCVisualManager::~CMFCVisualManager
extern "C" void MS_ABI impl___1CMFCVisualManager__UEAA_XZ(void* pThis) {
    ((CMFCVisualManager*)pThis)->~CMFCVisualManager();
}
// Symbol: ??1CMFCVisualManagerOffice2003@@UEAA@XZ
// Destructor: CMFCVisualManagerOffice2003::~CMFCVisualManagerOffice2003
extern "C" void MS_ABI impl___1CMFCVisualManagerOffice2003__UEAA_XZ(void* pThis) {
    ((CMFCVisualManagerOffice2003*)pThis)->~CMFCVisualManagerOffice2003();
}
// Symbol: ??1CMFCVisualManagerOffice2007@@MEAA@XZ
// Destructor: CMFCVisualManagerOffice2007::~CMFCVisualManagerOffice2007
extern "C" void MS_ABI impl___1CMFCVisualManagerOffice2007__MEAA_XZ(void* pThis) {
    ((CMFCVisualManagerOffice2007*)pThis)->~CMFCVisualManagerOffice2007();
}
// Symbol: ??1CMFCVisualManagerOfficeXP@@UEAA@XZ
// Destructor: CMFCVisualManagerOfficeXP::~CMFCVisualManagerOfficeXP
extern "C" void MS_ABI impl___1CMFCVisualManagerOfficeXP__UEAA_XZ(void* pThis) {
    ((CMFCVisualManagerOfficeXP*)pThis)->~CMFCVisualManagerOfficeXP();
}
// Symbol: ??1CMFCVisualManagerVS2005@@UEAA@XZ
// Destructor: CMFCVisualManagerVS2005::~CMFCVisualManagerVS2005
extern "C" void MS_ABI impl___1CMFCVisualManagerVS2005__UEAA_XZ(void* pThis) {
    ((CMFCVisualManagerVS2005*)pThis)->~CMFCVisualManagerVS2005();
}
// Symbol: ??1CMFCVisualManagerWindows@@UEAA@XZ
// Destructor: CMFCVisualManagerWindows::~CMFCVisualManagerWindows
extern "C" void MS_ABI impl___1CMFCVisualManagerWindows__UEAA_XZ(void* pThis) {
    ((CMFCVisualManagerWindows*)pThis)->~CMFCVisualManagerWindows();
}
// Symbol: ??1CMFCVisualManagerWindows7@@UEAA@XZ
// Destructor: CMFCVisualManagerWindows7::~CMFCVisualManagerWindows7
extern "C" void MS_ABI impl___1CMFCVisualManagerWindows7__UEAA_XZ(void* pThis) {
    ((CMFCVisualManagerWindows7*)pThis)->~CMFCVisualManagerWindows7();
}
// Symbol: ?OnDrawBarGripper@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HPEAVCBasePane@@@Z
// CMFCVisualManager::OnDrawBarGripper
extern "C" void MS_ABI impl__OnDrawBarGripper_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HPEAVCBasePane___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, CBasePane* p3) {
    pThis->OnDrawBarGripper(p0, p1, p2, p3);
}
// Symbol: ?OnDrawCheckBoxEx@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHHH@Z
// CMFCVisualManager::OnDrawCheckBoxEx
extern "C" void MS_ABI impl__OnDrawCheckBoxEx_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHHH_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, int p4, int p5) {
    pThis->OnDrawCheckBoxEx(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawComboBorder@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHHPEAVCMFCToolBarComboBoxButton@@@Z
// CMFCVisualManager::OnDrawComboBorder
extern "C" void MS_ABI impl__OnDrawComboBorder_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHHPEAVCMFCToolBarComboBoxButton___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, int p4, CMFCToolBarComboBoxButton* p5) {
    pThis->OnDrawComboBorder(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawComboDropButton@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHHPEAVCMFCToolBarComboBoxButton@@@Z
// CMFCVisualManager::OnDrawComboDropButton
extern "C" void MS_ABI impl__OnDrawComboDropButton_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHHPEAVCMFCToolBarComboBoxButton___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, int p4, CMFCToolBarComboBoxButton* p5) {
    pThis->OnDrawComboDropButton(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawControlBorder@CMFCVisualManager@@UEAAXPEAVCWnd@@@Z
// CMFCVisualManager::OnDrawControlBorder
extern "C" void MS_ABI impl__OnDrawControlBorder_CMFCVisualManager__UEAAXPEAVCWnd___Z(CMFCVisualManager* pThis, CWnd* p0) {
    pThis->OnDrawControlBorder(p0);
}
// Symbol: ?OnDrawEditBorder@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHPEAVCMFCToolBarEditBoxButton@@@Z
// CMFCVisualManager::OnDrawEditBorder
extern "C" void MS_ABI impl__OnDrawEditBorder_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHPEAVCMFCToolBarEditBoxButton___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, CMFCToolBarEditBoxButton* p4) {
    pThis->OnDrawEditBorder(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawExpandingBox@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HK@Z
// CMFCVisualManager::OnDrawExpandingBox
extern "C" void MS_ABI impl__OnDrawExpandingBox_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HK_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, unsigned long p3) {
    pThis->OnDrawExpandingBox(p0, p1, p2, p3);
}
// Symbol: ?OnDrawHeaderCtrlBorder@CMFCVisualManager@@UEAAXPEAVCMFCHeaderCtrl@@PEAVCDC@@AEAVCRect@@HH@Z
// CMFCVisualManager::OnDrawHeaderCtrlBorder
extern "C" void MS_ABI impl__OnDrawHeaderCtrlBorder_CMFCVisualManager__UEAAXPEAVCMFCHeaderCtrl__PEAVCDC__AEAVCRect__HH_Z(CMFCVisualManager* pThis, CMFCHeaderCtrl* p0, CDC* p1, CRect* p2, int p3, int p4) {
    pThis->OnDrawHeaderCtrlBorder(p0, p1, (*p2), p3, p4);
}
// Symbol: ?OnDrawHeaderCtrlSortArrow@CMFCVisualManager@@UEAAXPEAVCMFCHeaderCtrl@@PEAVCDC@@AEAVCRect@@H@Z
// CMFCVisualManager::OnDrawHeaderCtrlSortArrow
extern "C" void MS_ABI impl__OnDrawHeaderCtrlSortArrow_CMFCVisualManager__UEAAXPEAVCMFCHeaderCtrl__PEAVCDC__AEAVCRect__H_Z(CMFCVisualManager* pThis, CMFCHeaderCtrl* p0, CDC* p1, CRect* p2, int p3) {
    pThis->OnDrawHeaderCtrlSortArrow(p0, p1, (*p2), p3);
}
// Symbol: ?OnDrawMenuArrowOnCustomizeList@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@H@Z
// CMFCVisualManager::OnDrawMenuArrowOnCustomizeList
extern "C" void MS_ABI impl__OnDrawMenuArrowOnCustomizeList_CMFCVisualManager__UEAAXPEAVCDC__VCRect__H_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2) {
    pThis->OnDrawMenuArrowOnCustomizeList(p0, p1, p2);
}
// Symbol: ?OnDrawMenuBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCPopupMenu@@VCRect@@@Z
// CMFCVisualManager::OnDrawMenuBorder
extern "C" void MS_ABI impl__OnDrawMenuBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCPopupMenu__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCPopupMenu* p1, CRect p2) {
    pThis->OnDrawMenuBorder(p0, p1, p2);
}
// Symbol: ?OnDrawMenuCheck@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCToolBarMenuButton@@VCRect@@HH@Z
// CMFCVisualManager::OnDrawMenuCheck
extern "C" void MS_ABI impl__OnDrawMenuCheck_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCToolBarMenuButton__VCRect__HH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCToolBarMenuButton* p1, CRect p2, int p3, int p4) {
    pThis->OnDrawMenuCheck(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawMenuItemButton@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCToolBarMenuButton@@VCRect@@HH@Z
// CMFCVisualManager::OnDrawMenuItemButton
extern "C" void MS_ABI impl__OnDrawMenuItemButton_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCToolBarMenuButton__VCRect__HH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCToolBarMenuButton* p1, CRect p2, int p3, int p4) {
    pThis->OnDrawMenuItemButton(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawMenuResizeBar@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@H@Z
// CMFCVisualManager::OnDrawMenuResizeBar
extern "C" void MS_ABI impl__OnDrawMenuResizeBar_CMFCVisualManager__UEAAXPEAVCDC__VCRect__H_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2) {
    pThis->OnDrawMenuResizeBar(p0, p1, p2);
}
// Symbol: ?OnDrawMenuScrollButton@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHHH@Z
// CMFCVisualManager::OnDrawMenuScrollButton
extern "C" void MS_ABI impl__OnDrawMenuScrollButton_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHHH_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, int p4, int p5) {
    pThis->OnDrawMenuScrollButton(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawMenuSystemButton@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@IIH@Z
// CMFCVisualManager::OnDrawMenuSystemButton
extern "C" void MS_ABI impl__OnDrawMenuSystemButton_CMFCVisualManager__UEAAXPEAVCDC__VCRect__IIH_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, unsigned int p2, unsigned int p3, int p4) {
    pThis->OnDrawMenuSystemButton(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawMiniFrameBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCPaneFrameWnd@@VCRect@@2@Z
// CMFCVisualManager::OnDrawMiniFrameBorder
extern "C" void MS_ABI impl__OnDrawMiniFrameBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCPaneFrameWnd__VCRect__2_Z(CMFCVisualManager* pThis, CDC* p0, CPaneFrameWnd* p1, CRect p2, CRect p3) {
    pThis->OnDrawMiniFrameBorder(p0, p1, p2, p3);
}
// Symbol: ?OnDrawOutlookBarSplitter@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@@Z
// CMFCVisualManager::OnDrawOutlookBarSplitter
extern "C" void MS_ABI impl__OnDrawOutlookBarSplitter_CMFCVisualManager__UEAAXPEAVCDC__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1) {
    pThis->OnDrawOutlookBarSplitter(p0, p1);
}
// Symbol: ?OnDrawOutlookPageButtonBorder@CMFCVisualManager@@UEAAXPEAVCDC@@AEAVCRect@@HH@Z
// CMFCVisualManager::OnDrawOutlookPageButtonBorder
extern "C" void MS_ABI impl__OnDrawOutlookPageButtonBorder_CMFCVisualManager__UEAAXPEAVCDC__AEAVCRect__HH_Z(CMFCVisualManager* pThis, CDC* p0, CRect* p1, int p2, int p3) {
    pThis->OnDrawOutlookPageButtonBorder(p0, (*p1), p2, p3);
}
// Symbol: ?OnDrawPaneBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCBasePane@@AEAVCRect@@@Z
// CMFCVisualManager::OnDrawPaneBorder
extern "C" void MS_ABI impl__OnDrawPaneBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCBasePane__AEAVCRect___Z(CMFCVisualManager* pThis, CDC* p0, CBasePane* p1, CRect* p2) {
    pThis->OnDrawPaneBorder(p0, p1, (*p2));
}
// Symbol: ?OnDrawPaneCaption@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCDockablePane@@HVCRect@@2@Z
// CMFCVisualManager::OnDrawPaneCaption
extern "C" unsigned long MS_ABI impl__OnDrawPaneCaption_CMFCVisualManager__UEAAKPEAVCDC__PEAVCDockablePane__HVCRect__2_Z(CMFCVisualManager* pThis, CDC* p0, CDockablePane* p1, int p2, CRect p3, int p4) {
    return (unsigned long)pThis->OnDrawPaneCaption(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawPaneDivider@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCPaneDivider@@VCRect@@H@Z
// CMFCVisualManager::OnDrawPaneDivider
extern "C" void MS_ABI impl__OnDrawPaneDivider_CMFCVisualManager__UEAAXPEAVCDC__PEAVCPaneDivider__VCRect__H_Z(CMFCVisualManager* pThis, CDC* p0, CPaneDivider* p1, CRect p2, int p3) {
    pThis->OnDrawPaneDivider(p0, p1, p2, p3);
}
// Symbol: ?OnDrawPopupWindowBorder@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@@Z
// CMFCVisualManager::OnDrawPopupWindowBorder
extern "C" void MS_ABI impl__OnDrawPopupWindowBorder_CMFCVisualManager__UEAAXPEAVCDC__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1) {
    pThis->OnDrawPopupWindowBorder(p0, p1);
}
// Symbol: ?OnDrawPopupWindowButtonBorder@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@PEAVCMFCDesktopAlertWndButton@@@Z
// CMFCVisualManager::OnDrawPopupWindowButtonBorder
extern "C" void MS_ABI impl__OnDrawPopupWindowButtonBorder_CMFCVisualManager__UEAAXPEAVCDC__VCRect__PEAVCMFCDesktopAlertWndButton___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, CMFCDesktopAlertWndButton* p2) {
    pThis->OnDrawPopupWindowButtonBorder(p0, p1, p2);
}
// Symbol: ?OnDrawPopupWindowCaption@CMFCVisualManager@@UEAAKPEAVCDC@@VCRect@@PEAVCMFCDesktopAlertWnd@@@Z
// CMFCVisualManager::OnDrawPopupWindowCaption
extern "C" unsigned long MS_ABI impl__OnDrawPopupWindowCaption_CMFCVisualManager__UEAAKPEAVCDC__VCRect__PEAVCMFCDesktopAlertWnd___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, CMFCDesktopAlertWnd* p2) {
    return (unsigned long)pThis->OnDrawPopupWindowCaption(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonApplicationButton@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonButton@@@Z
// CMFCVisualManager::OnDrawRibbonApplicationButton
extern "C" void MS_ABI impl__OnDrawRibbonApplicationButton_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButton* p1) {
    pThis->OnDrawRibbonApplicationButton(p0, p1);
}
// Symbol: ?OnDrawRibbonButtonBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonButton@@@Z
// CMFCVisualManager::OnDrawRibbonButtonBorder
extern "C" void MS_ABI impl__OnDrawRibbonButtonBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButton* p1) {
    pThis->OnDrawRibbonButtonBorder(p0, p1);
}
// Symbol: ?OnDrawRibbonButtonsGroup@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonButtonsGroup@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonButtonsGroup
extern "C" unsigned long MS_ABI impl__OnDrawRibbonButtonsGroup_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonButtonsGroup__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButtonsGroup* p1, CRect p2) {
    return (unsigned long)pThis->OnDrawRibbonButtonsGroup(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonCaption@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonBar@@VCRect@@2@Z
// CMFCVisualManager::OnDrawRibbonCaption
extern "C" void MS_ABI impl__OnDrawRibbonCaption_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonBar__VCRect__2_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonBar* p1, CRect p2, CRect p3) {
    pThis->OnDrawRibbonCaption(p0, p1, p2, p3);
}
// Symbol: ?OnDrawRibbonCaptionButton@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonCaptionButton@@@Z
// CMFCVisualManager::OnDrawRibbonCaptionButton
extern "C" void MS_ABI impl__OnDrawRibbonCaptionButton_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonCaptionButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonCaptionButton* p1) {
    pThis->OnDrawRibbonCaptionButton(p0, p1);
}
// Symbol: ?OnDrawRibbonCategory@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonCategory@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonCategory
extern "C" void MS_ABI impl__OnDrawRibbonCategory_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonCategory__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonCategory* p1, CRect p2) {
    pThis->OnDrawRibbonCategory(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonCategoryCaption@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonContextCaption@@@Z
// CMFCVisualManager::OnDrawRibbonCategoryCaption
extern "C" unsigned long MS_ABI impl__OnDrawRibbonCategoryCaption_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonContextCaption___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonContextCaption* p1) {
    return (unsigned long)pThis->OnDrawRibbonCategoryCaption(p0, p1);
}
// Symbol: ?OnDrawRibbonCategoryTab@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonTab@@H@Z
// CMFCVisualManager::OnDrawRibbonCategoryTab
extern "C" unsigned long MS_ABI impl__OnDrawRibbonCategoryTab_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonTab__H_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonTab* p1, int p2) {
    return (unsigned long)pThis->OnDrawRibbonCategoryTab(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonCheckBoxOnList@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonCheckBox@@VCRect@@HH@Z
// CMFCVisualManager::OnDrawRibbonCheckBoxOnList
extern "C" void MS_ABI impl__OnDrawRibbonCheckBoxOnList_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonCheckBox__VCRect__HH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonCheckBox* p1, CRect p2, int p3, int p4) {
    pThis->OnDrawRibbonCheckBoxOnList(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawRibbonDefaultPaneButton@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonButton@@@Z
// CMFCVisualManager::OnDrawRibbonDefaultPaneButton
extern "C" void MS_ABI impl__OnDrawRibbonDefaultPaneButton_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButton* p1) {
    pThis->OnDrawRibbonDefaultPaneButton(p0, p1);
}
// Symbol: ?OnDrawRibbonDefaultPaneButtonContext@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonButton@@@Z
// CMFCVisualManager::OnDrawRibbonDefaultPaneButtonContext
extern "C" void MS_ABI impl__OnDrawRibbonDefaultPaneButtonContext_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButton* p1) {
    pThis->OnDrawRibbonDefaultPaneButtonContext(p0, p1);
}
// Symbol: ?OnDrawRibbonGalleryBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonGallery@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonGalleryBorder
extern "C" void MS_ABI impl__OnDrawRibbonGalleryBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonGallery__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonGallery* p1, CRect p2) {
    pThis->OnDrawRibbonGalleryBorder(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonLabel@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonLabel@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonLabel
extern "C" void MS_ABI impl__OnDrawRibbonLabel_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonLabel__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonLabel* p1, CRect p2) {
    pThis->OnDrawRibbonLabel(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonMainPanelButtonBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonButton@@@Z
// CMFCVisualManager::OnDrawRibbonMainPanelButtonBorder
extern "C" void MS_ABI impl__OnDrawRibbonMainPanelButtonBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonButton___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonButton* p1) {
    pThis->OnDrawRibbonMainPanelButtonBorder(p0, p1);
}
// Symbol: ?OnDrawRibbonMainPanelFrame@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonMainPanel@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonMainPanelFrame
extern "C" void MS_ABI impl__OnDrawRibbonMainPanelFrame_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonMainPanel__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonMainPanel* p1, CRect p2) {
    pThis->OnDrawRibbonMainPanelFrame(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonPanel@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonPanel@@VCRect@@2@Z
// CMFCVisualManager::OnDrawRibbonPanel
extern "C" unsigned long MS_ABI impl__OnDrawRibbonPanel_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonPanel__VCRect__2_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonPanel* p1, CRect p2, CRect p3) {
    return (unsigned long)pThis->OnDrawRibbonPanel(p0, p1, p2, p3);
}
// Symbol: ?OnDrawRibbonPanelCaption@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonPanel@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonPanelCaption
extern "C" void MS_ABI impl__OnDrawRibbonPanelCaption_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonPanel__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonPanel* p1, CRect p2) {
    pThis->OnDrawRibbonPanelCaption(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonProgressBar@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonProgressBar@@VCRect@@2H@Z
// CMFCVisualManager::OnDrawRibbonProgressBar
extern "C" void MS_ABI impl__OnDrawRibbonProgressBar_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonProgressBar__VCRect__2H_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonProgressBar* p1, CRect p2, CRect p3, int p4) {
    pThis->OnDrawRibbonProgressBar(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawRibbonQuickAccessToolBarSeparator@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonSeparator@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonQuickAccessToolBarSeparator
extern "C" void MS_ABI impl__OnDrawRibbonQuickAccessToolBarSeparator_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonSeparator__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonSeparator* p1, CRect p2) {
    pThis->OnDrawRibbonQuickAccessToolBarSeparator(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonSliderChannel@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonSlider@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonSliderChannel
extern "C" void MS_ABI impl__OnDrawRibbonSliderChannel_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonSlider__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonSlider* p1, CRect p2) {
    pThis->OnDrawRibbonSliderChannel(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonSliderThumb@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonSlider@@VCRect@@HHH@Z
// CMFCVisualManager::OnDrawRibbonSliderThumb
extern "C" void MS_ABI impl__OnDrawRibbonSliderThumb_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonSlider__VCRect__HHH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonSlider* p1, CRect p2, int p3, int p4, int p5) {
    pThis->OnDrawRibbonSliderThumb(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawRibbonSliderZoomButton@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCRibbonSlider@@VCRect@@HHHH@Z
// CMFCVisualManager::OnDrawRibbonSliderZoomButton
extern "C" void MS_ABI impl__OnDrawRibbonSliderZoomButton_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCRibbonSlider__VCRect__HHHH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonSlider* p1, CRect p2, int p3, int p4, int p5, int p6) {
    pThis->OnDrawRibbonSliderZoomButton(p0, p1, p2, p3, p4, p5, p6);
}
// Symbol: ?OnDrawRibbonStatusBarPane@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonStatusBar@@PEAVCMFCRibbonStatusBarPane@@@Z
// CMFCVisualManager::OnDrawRibbonStatusBarPane
extern "C" unsigned long MS_ABI impl__OnDrawRibbonStatusBarPane_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonStatusBar__PEAVCMFCRibbonStatusBarPane___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonStatusBar* p1, CMFCRibbonStatusBarPane* p2) {
    return (unsigned long)pThis->OnDrawRibbonStatusBarPane(p0, p1, p2);
}
// Symbol: ?OnDrawRibbonTabsFrame@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonBar@@VCRect@@@Z
// CMFCVisualManager::OnDrawRibbonTabsFrame
extern "C" unsigned long MS_ABI impl__OnDrawRibbonTabsFrame_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonBar__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCRibbonBar* p1, CRect p2) {
    return (unsigned long)pThis->OnDrawRibbonTabsFrame(p0, p1, p2);
}
// Symbol: ?OnDrawScrollButtons@CMFCVisualManager@@UEAAXPEAVCDC@@AEBVCRect@@HHH@Z
// CMFCVisualManager::OnDrawScrollButtons
extern "C" void MS_ABI impl__OnDrawScrollButtons_CMFCVisualManager__UEAAXPEAVCDC__AEBVCRect__HHH_Z(CMFCVisualManager* pThis, CDC* p0, const CRect* p1, int p2, int p3, int p4) {
    pThis->OnDrawScrollButtons(p0, (*p1), p2, p3, p4);
}
// Symbol: ?OnDrawSeparator@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCBasePane@@VCRect@@H@Z
// CMFCVisualManager::OnDrawSeparator
extern "C" void MS_ABI impl__OnDrawSeparator_CMFCVisualManager__UEAAXPEAVCDC__PEAVCBasePane__VCRect__H_Z(CMFCVisualManager* pThis, CDC* p0, CBasePane* p1, CRect p2, int p3) {
    pThis->OnDrawSeparator(p0, p1, p2, p3);
}
// Symbol: ?OnDrawStatusBarPaneBorder@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCStatusBar@@VCRect@@II@Z
// CMFCVisualManager::OnDrawStatusBarPaneBorder
extern "C" void MS_ABI impl__OnDrawStatusBarPaneBorder_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCStatusBar__VCRect__II_Z(CMFCVisualManager* pThis, CDC* p0, CMFCStatusBar* p1, CRect p2, unsigned int p3, unsigned int p4) {
    pThis->OnDrawStatusBarPaneBorder(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawStatusBarProgress@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCStatusBar@@VCRect@@HHKKKH@Z
// CMFCVisualManager::OnDrawStatusBarProgress
extern "C" void MS_ABI impl__OnDrawStatusBarProgress_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCStatusBar__VCRect__HHKKKH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCStatusBar* p1, CRect p2, int p3, int p4, unsigned long p5, unsigned long p6, unsigned long p7, int p8) {
    pThis->OnDrawStatusBarProgress(p0, p1, p2, p3, p4, p5, p6, p7, p8);
}
// Symbol: ?OnDrawStatusBarSizeBox@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCStatusBar@@VCRect@@@Z
// CMFCVisualManager::OnDrawStatusBarSizeBox
extern "C" void MS_ABI impl__OnDrawStatusBarSizeBox_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCStatusBar__VCRect___Z(CMFCVisualManager* pThis, CDC* p0, CMFCStatusBar* p1, CRect p2) {
    pThis->OnDrawStatusBarSizeBox(p0, p1, p2);
}
// Symbol: ?OnDrawTab@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHPEBVCMFCBaseTabCtrl@@@Z
// CMFCVisualManager::OnDrawTab
extern "C" void MS_ABI impl__OnDrawTab_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHPEBVCMFCBaseTabCtrl___Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, const CMFCBaseTabCtrl* p4) {
    pThis->OnDrawTab(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawTabCloseButton@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@PEBVCMFCBaseTabCtrl@@HHH@Z
// CMFCVisualManager::OnDrawTabCloseButton
extern "C" void MS_ABI impl__OnDrawTabCloseButton_CMFCVisualManager__UEAAXPEAVCDC__VCRect__PEBVCMFCBaseTabCtrl__HHH_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, const CMFCBaseTabCtrl* p2, int p3, int p4, int p5) {
    pThis->OnDrawTabCloseButton(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawTabContent@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HHPEBVCMFCBaseTabCtrl@@K@Z
// CMFCVisualManager::OnDrawTabContent
extern "C" void MS_ABI impl__OnDrawTabContent_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HHPEBVCMFCBaseTabCtrl__K_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3, const CMFCBaseTabCtrl* p4, unsigned long p5) {
    pThis->OnDrawTabContent(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?OnDrawTabsButtonBorder@CMFCVisualManager@@UEAAXPEAVCDC@@AEAVCRect@@PEAVCMFCButton@@IPEAVCMFCBaseTabCtrl@@@Z
// CMFCVisualManager::OnDrawTabsButtonBorder
extern "C" void MS_ABI impl__OnDrawTabsButtonBorder_CMFCVisualManager__UEAAXPEAVCDC__AEAVCRect__PEAVCMFCButton__IPEAVCMFCBaseTabCtrl___Z(CMFCVisualManager* pThis, CDC* p0, CRect* p1, CMFCButton* p2, unsigned int p3, CMFCBaseTabCtrl* p4) {
    pThis->OnDrawTabsButtonBorder(p0, (*p1), p2, p3, p4);
}
// Symbol: ?OnDrawTask@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCTasksPaneTask@@PEAVCImageList@@HH@Z
// CMFCVisualManager::OnDrawTask
extern "C" void MS_ABI impl__OnDrawTask_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCTasksPaneTask__PEAVCImageList__HH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCTasksPaneTask* p1, CImageList* p2, int p3, int p4) {
    pThis->OnDrawTask(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawTasksGroupAreaBorder@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@HH@Z
// CMFCVisualManager::OnDrawTasksGroupAreaBorder
extern "C" void MS_ABI impl__OnDrawTasksGroupAreaBorder_CMFCVisualManager__UEAAXPEAVCDC__VCRect__HH_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2, int p3) {
    pThis->OnDrawTasksGroupAreaBorder(p0, p1, p2, p3);
}
// Symbol: ?OnDrawTasksGroupCaption@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCMFCTasksPaneTaskGroup@@HHH@Z
// CMFCVisualManager::OnDrawTasksGroupCaption
extern "C" void MS_ABI impl__OnDrawTasksGroupCaption_CMFCVisualManager__UEAAXPEAVCDC__PEAVCMFCTasksPaneTaskGroup__HHH_Z(CMFCVisualManager* pThis, CDC* p0, CMFCTasksPaneTaskGroup* p1, int p2, int p3, int p4) {
    pThis->OnDrawTasksGroupCaption(p0, p1, p2, p3, p4);
}
// Symbol: ?OnDrawTearOffCaption@CMFCVisualManager@@UEAAXPEAVCDC@@VCRect@@H@Z
// CMFCVisualManager::OnDrawTearOffCaption
extern "C" void MS_ABI impl__OnDrawTearOffCaption_CMFCVisualManager__UEAAXPEAVCDC__VCRect__H_Z(CMFCVisualManager* pThis, CDC* p0, CRect p1, int p2) {
    pThis->OnDrawTearOffCaption(p0, p1, p2);
}
// Symbol: ?OnDrawToolBoxFrame@CMFCVisualManager@@UEAAXPEAVCDC@@AEBVCRect@@@Z
// CMFCVisualManager::OnDrawToolBoxFrame
extern "C" void MS_ABI impl__OnDrawToolBoxFrame_CMFCVisualManager__UEAAXPEAVCDC__AEBVCRect___Z(CMFCVisualManager* pThis, CDC* p0, const CRect* p1) {
    pThis->OnDrawToolBoxFrame(p0, (*p1));
}
// Symbol: ?OnFillBarBackground@CMFCVisualManager@@UEAAXPEAVCDC@@PEAVCBasePane@@VCRect@@2H@Z
// CMFCVisualManager::OnFillBarBackground
extern "C" void MS_ABI impl__OnFillBarBackground_CMFCVisualManager__UEAAXPEAVCDC__PEAVCBasePane__VCRect__2H_Z(CMFCVisualManager* pThis, CDC* p0, CBasePane* p1, CRect p2, CRect p3, int p4) {
    pThis->OnFillBarBackground(p0, p1, p2, p3, p4);
}
// Symbol: ?SetDefaultManager@CMFCVisualManager@@SAXPEAUCRuntimeClass@@@Z
// Static: CMFCVisualManager::SetDefaultManager
extern "C" void MS_ABI impl__SetDefaultManager_CMFCVisualManager__SAXPEAUCRuntimeClass___Z(CRuntimeClass* p0) {
    CMFCVisualManager::SetDefaultManager(p0);
}
