// CtorDtorPlacement — OpenMFC implementation.
// Sources: global_ctordtor_placement.cpp

// AUTO-GENERATED by tools/harvest/gen_ctordtor.py -- real default-ctor/dtor thunks
// for header-defined constructible classes.
#include "openmfc/afxwin.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxole.h"
#include "openmfc/afxdisp.h"
#include "openmfc/afxdao.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include <new>
#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

// Symbol: ??0CToolTipCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CToolTipCtrl__QEAA_XZ(void* pThis) { return new (pThis) CToolTipCtrl(); }
// Symbol: ??1CButton@@UEAA@XZ
extern "C" void MS_ABI impl___1CButton__UEAA_XZ(void* pThis) { static_cast<CButton*>(pThis)->~CButton(); }
// Symbol: ??1CComboBox@@UEAA@XZ
extern "C" void MS_ABI impl___1CComboBox__UEAA_XZ(void* pThis) { static_cast<CComboBox*>(pThis)->~CComboBox(); }
// Symbol: ??1CToolTipCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CToolTipCtrl__UEAA_XZ(void* pThis) { static_cast<CToolTipCtrl*>(pThis)->~CToolTipCtrl(); }
// Symbol: ??1CTreeCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CTreeCtrl__UEAA_XZ(void* pThis) { static_cast<CTreeCtrl*>(pThis)->~CTreeCtrl(); }
