// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??1CRichEditCtrl@@UEAA@XZ
// Destructor: CRichEditCtrl::~CRichEditCtrl
extern "C" void MS_ABI impl___1CRichEditCtrl__UEAA_XZ(void* pThis) {
    ((CRichEditCtrl*)pThis)->~CRichEditCtrl();
}
// Symbol: ?AddTool@CToolTipCtrl@@QEAAHPEAVCWnd@@PEB_WPEBUtagRECT@@_K@Z
// CToolTipCtrl::AddTool
extern "C" int MS_ABI impl__AddTool_CToolTipCtrl__QEAAHPEAVCWnd__PEB_WPEBUtagRECT___K_Z(CToolTipCtrl* pThis, CWnd* p0, const wchar_t* p1, const RECT* p2, unsigned __int64 p3) {
    return (int)pThis->AddTool(p0, p1, p2, p3);
}
// Symbol: ?CanPaste@CRichEditCtrl@@QEBAHI@Z
// CRichEditCtrl::CanPaste
extern "C" int MS_ABI impl__CanPaste_CRichEditCtrl__QEBAHI_Z(const CRichEditCtrl* pThis, unsigned int p0) {
    return (int)pThis->CanPaste(p0);
}
// Symbol: ?Create@CRichEditCtrl@@QEAAHKAEBUtagRECT@@PEAVCWnd@@I@Z
// CRichEditCtrl::Create
extern "C" int MS_ABI impl__Create_CRichEditCtrl__QEAAHKAEBUtagRECT__PEAVCWnd__I_Z(CRichEditCtrl* pThis, unsigned long p0, const RECT* p1, CWnd* p2, unsigned int p3) {
    return (int)pThis->Create(p0, (*p1), p2, p3);
}
// Symbol: ?Create@CToolTipCtrl@@UEAAHPEAVCWnd@@K@Z
// CToolTipCtrl::Create
extern "C" int MS_ABI impl__Create_CToolTipCtrl__UEAAHPEAVCWnd__K_Z(CToolTipCtrl* pThis, CWnd* p0, unsigned long p1) {
    return (int)pThis->Create(p0, p1);
}
// Symbol: ?CreateEx@CRichEditCtrl@@QEAAHKKAEBUtagRECT@@PEAVCWnd@@I@Z
// CRichEditCtrl::CreateEx
extern "C" int MS_ABI impl__CreateEx_CRichEditCtrl__QEAAHKKAEBUtagRECT__PEAVCWnd__I_Z(CRichEditCtrl* pThis, unsigned long p0, unsigned long p1, const RECT* p2, CWnd* p3, unsigned int p4) {
    return (int)pThis->CreateEx(p0, p1, (*p2), p3, p4);
}
// Symbol: ?GetDefaultCharFormat@CRichEditCtrl@@QEBAKAEAUCHARFORMAT2W@@@Z
// CRichEditCtrl::GetDefaultCharFormat
extern "C" unsigned long MS_ABI impl__GetDefaultCharFormat_CRichEditCtrl__QEBAKAEAUCHARFORMAT2W___Z(const CRichEditCtrl* pThis, CHARFORMAT2W* p0) {
    return (unsigned long)pThis->GetDefaultCharFormat((*p0));
}
// Symbol: ?GetIRichEditOle@CRichEditCtrl@@QEBAPEAUIRichEditOle@@XZ
// CRichEditCtrl::GetIRichEditOle
extern "C" IRichEditOle* MS_ABI impl__GetIRichEditOle_CRichEditCtrl__QEBAPEAUIRichEditOle__XZ(const CRichEditCtrl* pThis) {
    return (IRichEditOle*)pThis->GetIRichEditOle();
}
// Symbol: ?GetLine@CRichEditCtrl@@QEBAHHPEA_WH@Z
// CRichEditCtrl::GetLine
extern "C" int MS_ABI impl__GetLine_CRichEditCtrl__QEBAHHPEA_WH_Z(const CRichEditCtrl* pThis, int p0, wchar_t* p1, int p2) {
    return (int)pThis->GetLine(p0, p1, p2);
}
// Symbol: ?GetParaFormat@CRichEditCtrl@@QEBAKAEAUPARAFORMAT2@@@Z
// CRichEditCtrl::GetParaFormat
extern "C" unsigned long MS_ABI impl__GetParaFormat_CRichEditCtrl__QEBAKAEAUPARAFORMAT2___Z(const CRichEditCtrl* pThis, PARAFORMAT2* p0) {
    return (unsigned long)pThis->GetParaFormat((*p0));
}
// Symbol: ?GetSelectionCharFormat@CRichEditCtrl@@QEBAKAEAUCHARFORMAT2W@@@Z
// CRichEditCtrl::GetSelectionCharFormat
extern "C" unsigned long MS_ABI impl__GetSelectionCharFormat_CRichEditCtrl__QEBAKAEAUCHARFORMAT2W___Z(const CRichEditCtrl* pThis, CHARFORMAT2W* p0) {
    return (unsigned long)pThis->GetSelectionCharFormat((*p0));
}
// Symbol: ?GetTextLengthEx@CRichEditCtrl@@QEBAJKI@Z
// CRichEditCtrl::GetTextLengthEx
extern "C" long MS_ABI impl__GetTextLengthEx_CRichEditCtrl__QEBAJKI_Z(const CRichEditCtrl* pThis, unsigned long p0, unsigned int p1) {
    return (long)pThis->GetTextLengthEx(p0, p1);
}
// Symbol: ?LineIndex@CRichEditCtrl@@QEBAHH@Z
// CRichEditCtrl::LineIndex
extern "C" int MS_ABI impl__LineIndex_CRichEditCtrl__QEBAHH_Z(const CRichEditCtrl* pThis, int p0) {
    return (int)pThis->LineIndex(p0);
}
// Symbol: ?LineLength@CRichEditCtrl@@QEBAHH@Z
// CRichEditCtrl::LineLength
extern "C" int MS_ABI impl__LineLength_CRichEditCtrl__QEBAHH_Z(const CRichEditCtrl* pThis, int p0) {
    return (int)pThis->LineLength(p0);
}
// Symbol: ?LineScroll@CRichEditCtrl@@QEAAXHH@Z
// CRichEditCtrl::LineScroll
extern "C" void MS_ABI impl__LineScroll_CRichEditCtrl__QEAAXHH_Z(CRichEditCtrl* pThis, int p0, int p1) {
    pThis->LineScroll(p0, p1);
}
// Symbol: ?PasteSpecial@CRichEditCtrl@@QEAAXIKPEAUHMETAFILE__@@@Z
// CRichEditCtrl::PasteSpecial
extern "C" void MS_ABI impl__PasteSpecial_CRichEditCtrl__QEAAXIKPEAUHMETAFILE_____Z(CRichEditCtrl* pThis, unsigned int p0, unsigned long p1, HMETAFILE__* p2) {
    pThis->PasteSpecial(p0, p1, p2);
}
// Symbol: ?SetDefaultCharFormat@CRichEditCtrl@@QEAAHAEAUCHARFORMAT2W@@@Z
// CRichEditCtrl::SetDefaultCharFormat
extern "C" int MS_ABI impl__SetDefaultCharFormat_CRichEditCtrl__QEAAHAEAUCHARFORMAT2W___Z(CRichEditCtrl* pThis, CHARFORMAT2W* p0) {
    return (int)pThis->SetDefaultCharFormat((*p0));
}
// Symbol: ?SetParaFormat@CRichEditCtrl@@QEAAHAEAUPARAFORMAT2@@@Z
// CRichEditCtrl::SetParaFormat
extern "C" int MS_ABI impl__SetParaFormat_CRichEditCtrl__QEAAHAEAUPARAFORMAT2___Z(CRichEditCtrl* pThis, PARAFORMAT2* p0) {
    return (int)pThis->SetParaFormat((*p0));
}
// Symbol: ?SetSel@CRichEditCtrl@@QEAAXJJ@Z
// CRichEditCtrl::SetSel
extern "C" void MS_ABI impl__SetSel_CRichEditCtrl__QEAAXJJ_Z(CRichEditCtrl* pThis, long p0, long p1) {
    pThis->SetSel(p0, p1);
}
// Symbol: ?SetSelectionCharFormat@CRichEditCtrl@@QEAAHAEAUCHARFORMAT2W@@@Z
// CRichEditCtrl::SetSelectionCharFormat
extern "C" int MS_ABI impl__SetSelectionCharFormat_CRichEditCtrl__QEAAHAEAUCHARFORMAT2W___Z(CRichEditCtrl* pThis, CHARFORMAT2W* p0) {
    return (int)pThis->SetSelectionCharFormat((*p0));
}
// Symbol: ?SetWordCharFormat@CRichEditCtrl@@QEAAHAEAU_charformatw@@@Z
// CRichEditCtrl::SetWordCharFormat
extern "C" int MS_ABI impl__SetWordCharFormat_CRichEditCtrl__QEAAHAEAU_charformatw___Z(CRichEditCtrl* pThis, _charformatw* p0) {
    return (int)pThis->SetWordCharFormat((*p0));
}
// Symbol: ?SetWordCharFormat@CRichEditCtrl@@QEAAHAEAUCHARFORMAT2W@@@Z
// CRichEditCtrl::SetWordCharFormat
extern "C" int MS_ABI impl__SetWordCharFormat_CRichEditCtrl__QEAAHAEAUCHARFORMAT2W___Z(CRichEditCtrl* pThis, CHARFORMAT2W* p0) {
    return (int)pThis->SetWordCharFormat((*p0));
}
// Symbol: ?UpdateTipText@CToolTipCtrl@@QEAAXPEB_WPEAVCWnd@@_K@Z
// CToolTipCtrl::UpdateTipText
extern "C" void MS_ABI impl__UpdateTipText_CToolTipCtrl__QEAAXPEB_WPEAVCWnd___K_Z(CToolTipCtrl* pThis, const wchar_t* p0, CWnd* p1, unsigned __int64 p2) {
    pThis->UpdateTipText(p0, p1, p2);
}
