// AUTO-GENERATED by tools/harvest/gen_ctordtor.py -- real default-ctor/dtor thunks
// for header-defined constructible classes.
#include "openmfc/afxwin.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxole.h"
#include "openmfc/afxdisp.h"
#include "openmfc/afxdao.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include <new>
#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

// Symbol: ??0CCmdTarget@@QEAA@XZ
extern "C" void* MS_ABI impl___0CCmdTarget__QEAA_XZ(void* pThis) { return new (pThis) CCmdTarget(); }
// Symbol: ??0CCmdUI@@QEAA@XZ
extern "C" void* MS_ABI impl___0CCmdUI__QEAA_XZ(void* pThis) { return new (pThis) CCmdUI(); }
// Symbol: ??0CException@@QEAA@XZ
extern "C" void* MS_ABI impl___0CException__QEAA_XZ(void* pThis) { return new (pThis) CException(); }
// Symbol: ??0CMFCCaptionButton@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCCaptionButton__QEAA_XZ(void* pThis) { return new (pThis) CMFCCaptionButton(); }
// Symbol: ??0CMFCDesktopAlertWnd@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCDesktopAlertWnd__QEAA_XZ(void* pThis) { return new (pThis) CMFCDesktopAlertWnd(); }
// Symbol: ??0CMFCHeaderCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCHeaderCtrl__QEAA_XZ(void* pThis) { return new (pThis) CMFCHeaderCtrl(); }
// Symbol: ??0COleControlSiteOrWnd@@QEAA@XZ
extern "C" void* MS_ABI impl___0COleControlSiteOrWnd__QEAA_XZ(void* pThis) { return new (pThis) COleControlSiteOrWnd(); }
// Symbol: ??0CToolTipCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CToolTipCtrl__QEAA_XZ(void* pThis) { return new (pThis) CToolTipCtrl(); }
// Symbol: ??0CVSListBox@@QEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBox__QEAA_XZ(void* pThis) { return new (pThis) CVSListBox(); }
// Symbol: ??0CVSListBoxBase@@IEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBoxBase__IEAA_XZ(void* pThis) { return new (pThis) CVSListBoxBase(); }
// Symbol: ??0CVSListBoxEditCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBoxEditCtrl__QEAA_XZ(void* pThis) { return new (pThis) CVSListBoxEditCtrl(); }
// Symbol: ??0CWnd@@QEAA@XZ
extern "C" void* MS_ABI impl___0CWnd__QEAA_XZ(void* pThis) { return new (pThis) CWnd(); }
// Symbol: ??1CButton@@UEAA@XZ
extern "C" void MS_ABI impl___1CButton__UEAA_XZ(void* pThis) { static_cast<CButton*>(pThis)->~CButton(); }
// Symbol: ??1CComboBox@@UEAA@XZ
extern "C" void MS_ABI impl___1CComboBox__UEAA_XZ(void* pThis) { static_cast<CComboBox*>(pThis)->~CComboBox(); }
// Symbol: ??1CDBException@@UEAA@XZ
extern "C" void MS_ABI impl___1CDBException__UEAA_XZ(void* pThis) { static_cast<CDBException*>(pThis)->~CDBException(); }
// Symbol: ??1CMFCCaptionButton@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCCaptionButton__UEAA_XZ(void* pThis) { static_cast<CMFCCaptionButton*>(pThis)->~CMFCCaptionButton(); }
// Symbol: ??1CMFCDesktopAlertWnd@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCDesktopAlertWnd__UEAA_XZ(void* pThis) { static_cast<CMFCDesktopAlertWnd*>(pThis)->~CMFCDesktopAlertWnd(); }
// Symbol: ??1CMFCHeaderCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCHeaderCtrl__UEAA_XZ(void* pThis) { static_cast<CMFCHeaderCtrl*>(pThis)->~CMFCHeaderCtrl(); }
// Symbol: ??1CToolTipCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CToolTipCtrl__UEAA_XZ(void* pThis) { static_cast<CToolTipCtrl*>(pThis)->~CToolTipCtrl(); }
// Symbol: ??1CTreeCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CTreeCtrl__UEAA_XZ(void* pThis) { static_cast<CTreeCtrl*>(pThis)->~CTreeCtrl(); }
// Symbol: ??1CVSListBox@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBox__UEAA_XZ(void* pThis) { static_cast<CVSListBox*>(pThis)->~CVSListBox(); }
// Symbol: ??1CVSListBoxBase@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBoxBase__UEAA_XZ(void* pThis) { static_cast<CVSListBoxBase*>(pThis)->~CVSListBoxBase(); }
// Symbol: ??1CVSListBoxEditCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBoxEditCtrl__UEAA_XZ(void* pThis) { static_cast<CVSListBoxEditCtrl*>(pThis)->~CVSListBoxEditCtrl(); }
// Symbol: ??1CWnd@@UEAA@XZ
extern "C" void MS_ABI impl___1CWnd__UEAA_XZ(void* pThis) { static_cast<CWnd*>(pThis)->~CWnd(); }
