// AUTO-GENERATED by tools/harvest/gen_ifacemap.py -- DO NOT EDIT BY HAND.
// Real AFX_INTERFACEMAP for the CCmdTarget OLE-class family (see the generator header).
#include <cstddef>

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif
#if defined(_MSC_VER) || defined(__MINGW32__)
  #define AFXAPI __cdecl
#else
  #define AFXAPI
#endif

struct AFX_INTERFACEMAP_ENTRY { const void* piid; size_t nOffset; };
struct AFX_INTERFACEMAP { const AFX_INTERFACEMAP* (AFXAPI* pfnGetBaseMap)(); const AFX_INTERFACEMAP_ENTRY* pEntries; };

// Empty terminator shared by every map (real IID->offset entries are mfc140u addresses).
static const AFX_INTERFACEMAP_ENTRY g_ifaceEnd[] = { { nullptr, (size_t)-1 } };

extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CDocObjectServer__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnPoints__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnections__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumFormatEtc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumOleVerb__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumUnknown__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CHtmlControlSite__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CMFCBaseAccessibleObject__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleClientItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControl__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlContainer__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlSite__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDataSource__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDocObjectItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropSource__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropTarget__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleFrameHook__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleLinkingDoc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleMessageFilter__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleObjectFactory__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COlePropertyPage__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerDoc__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerItem__KAPEBUAFX_INTERFACEMAP__XZ();
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CRichEditView__KAPEBUAFX_INTERFACEMAP__XZ();

static const AFX_INTERFACEMAP g_imap_CCmdTarget = { nullptr, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CCmdTarget@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CCmdTarget; }
// Symbol: ?GetInterfaceMap@CCmdTarget@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CCmdTarget__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CCmdTarget; }

static const AFX_INTERFACEMAP* AFXAPI gib_CDocObjectServer() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CDocObjectServer = { gib_CDocObjectServer, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CDocObjectServer@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CDocObjectServer__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CDocObjectServer; }
// Symbol: ?GetInterfaceMap@CDocObjectServer@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CDocObjectServer__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CDocObjectServer; }

static const AFX_INTERFACEMAP* AFXAPI gib_CEnumConnPoints() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CEnumConnPoints = { gib_CEnumConnPoints, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CEnumConnPoints@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnPoints__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CEnumConnPoints; }
// Symbol: ?GetInterfaceMap@CEnumConnPoints@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CEnumConnPoints__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CEnumConnPoints; }

static const AFX_INTERFACEMAP* AFXAPI gib_CEnumConnections() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CEnumConnections = { gib_CEnumConnections, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CEnumConnections@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumConnections__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CEnumConnections; }
// Symbol: ?GetInterfaceMap@CEnumConnections@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CEnumConnections__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CEnumConnections; }

static const AFX_INTERFACEMAP* AFXAPI gib_CEnumFormatEtc() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CEnumFormatEtc = { gib_CEnumFormatEtc, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CEnumFormatEtc@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumFormatEtc__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CEnumFormatEtc; }
// Symbol: ?GetInterfaceMap@CEnumFormatEtc@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CEnumFormatEtc__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CEnumFormatEtc; }

static const AFX_INTERFACEMAP* AFXAPI gib_CEnumOleVerb() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CEnumOleVerb = { gib_CEnumOleVerb, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CEnumOleVerb@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumOleVerb__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CEnumOleVerb; }
// Symbol: ?GetInterfaceMap@CEnumOleVerb@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CEnumOleVerb__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CEnumOleVerb; }

static const AFX_INTERFACEMAP* AFXAPI gib_CEnumUnknown() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CEnumUnknown = { gib_CEnumUnknown, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CEnumUnknown@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CEnumUnknown__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CEnumUnknown; }
// Symbol: ?GetInterfaceMap@CEnumUnknown@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CEnumUnknown__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CEnumUnknown; }

static const AFX_INTERFACEMAP* AFXAPI gib_CHtmlControlSite() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CHtmlControlSite = { gib_CHtmlControlSite, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CHtmlControlSite@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CHtmlControlSite__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CHtmlControlSite; }
// Symbol: ?GetInterfaceMap@CHtmlControlSite@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CHtmlControlSite__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CHtmlControlSite; }

static const AFX_INTERFACEMAP* AFXAPI gib_CMFCBaseAccessibleObject() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CMFCBaseAccessibleObject = { gib_CMFCBaseAccessibleObject, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CMFCBaseAccessibleObject@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CMFCBaseAccessibleObject__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CMFCBaseAccessibleObject; }
// Symbol: ?GetInterfaceMap@CMFCBaseAccessibleObject@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CMFCBaseAccessibleObject__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CMFCBaseAccessibleObject; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleClientItem() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleClientItem = { gib_COleClientItem, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleClientItem@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleClientItem__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleClientItem; }
// Symbol: ?GetInterfaceMap@COleClientItem@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleClientItem__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleClientItem; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleControl() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleControl = { gib_COleControl, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleControl@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControl__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleControl; }
// Symbol: ?GetInterfaceMap@COleControl@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleControl__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleControl; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleControlContainer() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleControlContainer = { gib_COleControlContainer, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleControlContainer@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlContainer__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleControlContainer; }
// Symbol: ?GetInterfaceMap@COleControlContainer@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleControlContainer__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleControlContainer; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleControlSite() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleControlSite = { gib_COleControlSite, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleControlSite@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleControlSite__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleControlSite; }
// Symbol: ?GetInterfaceMap@COleControlSite@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleControlSite__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleControlSite; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleDataSource() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleDataSource = { gib_COleDataSource, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleDataSource@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDataSource__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleDataSource; }
// Symbol: ?GetInterfaceMap@COleDataSource@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleDataSource__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleDataSource; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleDocObjectItem() { return impl__GetThisInterfaceMap_COleClientItem__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleDocObjectItem = { gib_COleDocObjectItem, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleDocObjectItem@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDocObjectItem__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleDocObjectItem; }
// Symbol: ?GetInterfaceMap@COleDocObjectItem@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleDocObjectItem__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleDocObjectItem; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleDropSource() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleDropSource = { gib_COleDropSource, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleDropSource@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropSource__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleDropSource; }
// Symbol: ?GetInterfaceMap@COleDropSource@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleDropSource__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleDropSource; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleDropTarget() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleDropTarget = { gib_COleDropTarget, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleDropTarget@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleDropTarget__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleDropTarget; }
// Symbol: ?GetInterfaceMap@COleDropTarget@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleDropTarget__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleDropTarget; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleFrameHook() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleFrameHook = { gib_COleFrameHook, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleFrameHook@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleFrameHook__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleFrameHook; }
// Symbol: ?GetInterfaceMap@COleFrameHook@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleFrameHook__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleFrameHook; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleLinkingDoc() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleLinkingDoc = { gib_COleLinkingDoc, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleLinkingDoc@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleLinkingDoc__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleLinkingDoc; }
// Symbol: ?GetInterfaceMap@COleLinkingDoc@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleLinkingDoc__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleLinkingDoc; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleMessageFilter() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleMessageFilter = { gib_COleMessageFilter, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleMessageFilter@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleMessageFilter__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleMessageFilter; }
// Symbol: ?GetInterfaceMap@COleMessageFilter@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleMessageFilter__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleMessageFilter; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleObjectFactory() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleObjectFactory = { gib_COleObjectFactory, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleObjectFactory@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleObjectFactory__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleObjectFactory; }
// Symbol: ?GetInterfaceMap@COleObjectFactory@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleObjectFactory__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleObjectFactory; }

static const AFX_INTERFACEMAP* AFXAPI gib_COlePropertyPage() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COlePropertyPage = { gib_COlePropertyPage, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COlePropertyPage@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COlePropertyPage__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COlePropertyPage; }
// Symbol: ?GetInterfaceMap@COlePropertyPage@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COlePropertyPage__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COlePropertyPage; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleServerDoc() { return impl__GetThisInterfaceMap_COleLinkingDoc__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleServerDoc = { gib_COleServerDoc, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleServerDoc@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerDoc__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleServerDoc; }
// Symbol: ?GetInterfaceMap@COleServerDoc@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleServerDoc__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleServerDoc; }

static const AFX_INTERFACEMAP* AFXAPI gib_COleServerItem() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_COleServerItem = { gib_COleServerItem, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@COleServerItem@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_COleServerItem__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_COleServerItem; }
// Symbol: ?GetInterfaceMap@COleServerItem@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_COleServerItem__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_COleServerItem; }

static const AFX_INTERFACEMAP* AFXAPI gib_CRichEditView() { return impl__GetThisInterfaceMap_CCmdTarget__KAPEBUAFX_INTERFACEMAP__XZ(); }
static const AFX_INTERFACEMAP g_imap_CRichEditView = { gib_CRichEditView, g_ifaceEnd };
// Symbol: ?GetThisInterfaceMap@CRichEditView@@KAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CRichEditView__KAPEBUAFX_INTERFACEMAP__XZ() { return &g_imap_CRichEditView; }
// Symbol: ?GetInterfaceMap@CRichEditView@@MEBAPEBUAFX_INTERFACEMAP@@XZ
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CRichEditView__MEBAPEBUAFX_INTERFACEMAP__XZ(const void* pThis) { (void)pThis; return &g_imap_CRichEditView; }

