// AUTO-GENERATED by tools/harvest/gen_ddx.py -- DO NOT EDIT BY HAND.
// Real implementations of the exported DDX_/DDP_/DDV_ dialog-data-exchange helpers,
// forwarding to the Win32-control exchange core in ddx_core.h.
#include "ddx_core.h"

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif


// Symbol: ?DDP_Check@@YAXPEAVCDataExchange@@HAEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_Check__YAXPEAVCDataExchange__HAEAHPEB_W_Z(void* pDX, int nIDC, int* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::Check(pDX, nIDC, pv);
}

// Symbol: ?DDP_EndCheck@@YAXPEAVCDataExchange@@HPEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndCheck__YAXPEAVCDataExchange__HPEAHPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndRadio@@YAXPEAVCDataExchange@@HPEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndRadio__YAXPEAVCDataExchange__HPEAHPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAEPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAEPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAFPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAFPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAHPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAIPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAIPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAJPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAJPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAKPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAKPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAMPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAMPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEANPEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEANPEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_EndText@@YAXPEAVCDataExchange@@HPEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEB_W@Z
extern "C" void MS_ABI impl__DDP_EndText__YAXPEAVCDataExchange__HPEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)pDX;(void)nIDC;(void)pv;(void)name;
}

// Symbol: ?DDP_PostProcessing@@YAXPEAVCDataExchange@@@Z
extern "C" void MS_ABI impl__DDP_PostProcessing__YAXPEAVCDataExchange___Z(void* pDX) {
    openmfc_ddx::PostProcessing(pDX);
}

// Symbol: ?DDP_Radio@@YAXPEAVCDataExchange@@HAEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_Radio__YAXPEAVCDataExchange__HAEAHPEB_W_Z(void* pDX, int nIDC, int* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::Radio(pDX, nIDC, pv);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAEPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAEPEB_W_Z(void* pDX, int nIDC, unsigned char* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_BYTE);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAFPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAFPEB_W_Z(void* pDX, int nIDC, short* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_SHORT);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAHPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAHPEB_W_Z(void* pDX, int nIDC, int* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_INT);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAIPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAIPEB_W_Z(void* pDX, int nIDC, unsigned int* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_UINT);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAJPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAJPEB_W_Z(void* pDX, int nIDC, long* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_LONG);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAKPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAKPEB_W_Z(void* pDX, int nIDC, unsigned long* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DWORD);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAMPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAMPEB_W_Z(void* pDX, int nIDC, float* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_FLOAT);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEANPEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEANPEB_W_Z(void* pDX, int nIDC, double* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DOUBLE);
}

// Symbol: ?DDP_Text@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEB_W@Z
extern "C" void MS_ABI impl__DDP_Text__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEB_W_Z(void* pDX, int nIDC, void* pv, const wchar_t* name) {
    (void)name; openmfc_ddx::TextStr(pDX, nIDC, reinterpret_cast<CString*>(pv));
}

// Symbol: ?DDV_MaxChars@@YAXPEAVCDataExchange@@AEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@H@Z
extern "C" void MS_ABI impl__DDV_MaxChars__YAXPEAVCDataExchange__AEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__H_Z(void* pDX, const void* pv, int n) {
    openmfc_ddx::MaxChars(pDX, reinterpret_cast<const CString*>(pv), n);
}

// Symbol: ?DDV_MinMaxByte@@YAXPEAVCDataExchange@@EEE@Z
extern "C" void MS_ABI impl__DDV_MinMaxByte__YAXPEAVCDataExchange__EEE_Z(void* pDX, unsigned char v, unsigned char lo, unsigned char hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxDWord@@YAXPEAVCDataExchange@@KKK@Z
extern "C" void MS_ABI impl__DDV_MinMaxDWord__YAXPEAVCDataExchange__KKK_Z(void* pDX, unsigned long v, unsigned long lo, unsigned long hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxDouble@@YAXPEAVCDataExchange@@AEBNNN@Z
extern "C" void MS_ABI impl__DDV_MinMaxDouble__YAXPEAVCDataExchange__AEBNNN_Z(void* pDX, const double* v, double lo, double hi) {
    openmfc_ddx::MinMax(pDX, *v, lo, hi);
}

// Symbol: ?DDV_MinMaxFloat@@YAXPEAVCDataExchange@@AEBMMM@Z
extern "C" void MS_ABI impl__DDV_MinMaxFloat__YAXPEAVCDataExchange__AEBMMM_Z(void* pDX, const float* v, float lo, float hi) {
    openmfc_ddx::MinMax(pDX, *v, lo, hi);
}

// Symbol: ?DDV_MinMaxInt@@YAXPEAVCDataExchange@@HHH@Z
extern "C" void MS_ABI impl__DDV_MinMaxInt__YAXPEAVCDataExchange__HHH_Z(void* pDX, int v, int lo, int hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxLong@@YAXPEAVCDataExchange@@JJJ@Z
extern "C" void MS_ABI impl__DDV_MinMaxLong__YAXPEAVCDataExchange__JJJ_Z(void* pDX, long v, long lo, long hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxLongLong@@YAXPEAVCDataExchange@@_J11@Z
extern "C" void MS_ABI impl__DDV_MinMaxLongLong__YAXPEAVCDataExchange___J11_Z(void* pDX, long long v, long long lo, long long hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxShort@@YAXPEAVCDataExchange@@FFF@Z
extern "C" void MS_ABI impl__DDV_MinMaxShort__YAXPEAVCDataExchange__FFF_Z(void* pDX, short v, short lo, short hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxSlider@@YAXPEAVCDataExchange@@KKK@Z
extern "C" void MS_ABI impl__DDV_MinMaxSlider__YAXPEAVCDataExchange__KKK_Z(void* pDX, unsigned long v, unsigned long lo, unsigned long hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxUInt@@YAXPEAVCDataExchange@@III@Z
extern "C" void MS_ABI impl__DDV_MinMaxUInt__YAXPEAVCDataExchange__III_Z(void* pDX, unsigned int v, unsigned int lo, unsigned int hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDV_MinMaxULongLong@@YAXPEAVCDataExchange@@_K11@Z
extern "C" void MS_ABI impl__DDV_MinMaxULongLong__YAXPEAVCDataExchange___K11_Z(void* pDX, unsigned long long v, unsigned long long lo, unsigned long long hi) {
    openmfc_ddx::MinMax(pDX, v, lo, hi);
}

// Symbol: ?DDX_CBIndex@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_CBIndex__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::CBIndex(pDX, nIDC, pv);
}

// Symbol: ?DDX_CBString@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
extern "C" void MS_ABI impl__DDX_CBString__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::CBString(pDX, nIDC, reinterpret_cast<CString*>(pv), false);
}

// Symbol: ?DDX_CBStringExact@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
extern "C" void MS_ABI impl__DDX_CBStringExact__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::CBString(pDX, nIDC, reinterpret_cast<CString*>(pv), true);
}

// Symbol: ?DDX_Check@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_Check__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::Check(pDX, nIDC, pv);
}

// Symbol: ?DDX_Control@@YAXPEAVCDataExchange@@HAEAVCWnd@@@Z
extern "C" void MS_ABI impl__DDX_Control__YAXPEAVCDataExchange__HAEAVCWnd___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::Ctrl(pDX, nIDC);
}

// Symbol: ?DDX_FieldCBIndex@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldCBIndex__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::CBIndex(pDX, nIDC, pv);
}

// Symbol: ?DDX_FieldCBString@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldCBString__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEAVCRecordset___Z(void* pDX, int nIDC, void* pv, void* pRs) {
    (void)pRs; openmfc_ddx::CBString(pDX, nIDC, reinterpret_cast<CString*>(pv), false);
}

// Symbol: ?DDX_FieldCBStringExact@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldCBStringExact__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEAVCRecordset___Z(void* pDX, int nIDC, void* pv, void* pRs) {
    (void)pRs; openmfc_ddx::CBString(pDX, nIDC, reinterpret_cast<CString*>(pv), true);
}

// Symbol: ?DDX_FieldCheck@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldCheck__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::Check(pDX, nIDC, pv);
}

// Symbol: ?DDX_FieldLBIndex@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldLBIndex__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::LBIndex(pDX, nIDC, pv);
}

// Symbol: ?DDX_FieldLBString@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldLBString__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEAVCRecordset___Z(void* pDX, int nIDC, void* pv, void* pRs) {
    (void)pRs; openmfc_ddx::LBString(pDX, nIDC, reinterpret_cast<CString*>(pv), false);
}

// Symbol: ?DDX_FieldLBStringExact@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldLBStringExact__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEAVCRecordset___Z(void* pDX, int nIDC, void* pv, void* pRs) {
    (void)pRs; openmfc_ddx::LBString(pDX, nIDC, reinterpret_cast<CString*>(pv), true);
}

// Symbol: ?DDX_FieldRadio@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldRadio__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::Radio(pDX, nIDC, pv);
}

// Symbol: ?DDX_FieldScroll@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldScroll__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::ScrollPos(pDX, nIDC, pv);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAEPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAEPEAVCRecordset___Z(void* pDX, int nIDC, unsigned char* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_BYTE);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAHPEAVCRecordset___Z(void* pDX, int nIDC, int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_INT);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAIPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAIPEAVCRecordset___Z(void* pDX, int nIDC, unsigned int* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_UINT);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAJPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAJPEAVCRecordset___Z(void* pDX, int nIDC, long* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_LONG);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAKPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAKPEAVCRecordset___Z(void* pDX, int nIDC, unsigned long* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DWORD);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAMPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAMPEAVCRecordset___Z(void* pDX, int nIDC, float* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_FLOAT);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEANPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEANPEAVCRecordset___Z(void* pDX, int nIDC, double* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DOUBLE);
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@PEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__PEAVCRecordset___Z(void* pDX, int nIDC, void* pv, void* pRs) {
    (void)pRs; openmfc_ddx::TextStr(pDX, nIDC, reinterpret_cast<CString*>(pv));
}

// Symbol: ?DDX_FieldText@@YAXPEAVCDataExchange@@HPEA_WHPEAVCRecordset@@@Z
extern "C" void MS_ABI impl__DDX_FieldText__YAXPEAVCDataExchange__HPEA_WHPEAVCRecordset___Z(void* pDX, int nIDC, wchar_t* pv, int n, void* pRs) {
    (void)pRs; openmfc_ddx::TextBuf(pDX, nIDC, pv, n);
}

// Symbol: ?DDX_IPAddress@@YAXPEAVCDataExchange@@HAEAK@Z
extern "C" void MS_ABI impl__DDX_IPAddress__YAXPEAVCDataExchange__HAEAK_Z(void* pDX, int nIDC, unsigned long* pv) {
    openmfc_ddx::IPAddress(pDX, nIDC, pv);
}

// Symbol: ?DDX_LBIndex@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_LBIndex__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::LBIndex(pDX, nIDC, pv);
}

// Symbol: ?DDX_LBString@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
extern "C" void MS_ABI impl__DDX_LBString__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::LBString(pDX, nIDC, reinterpret_cast<CString*>(pv), false);
}

// Symbol: ?DDX_LBStringExact@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
extern "C" void MS_ABI impl__DDX_LBStringExact__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::LBString(pDX, nIDC, reinterpret_cast<CString*>(pv), true);
}

// Symbol: ?DDX_Radio@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_Radio__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::Radio(pDX, nIDC, pv);
}

// Symbol: ?DDX_Scroll@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_Scroll__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::ScrollPos(pDX, nIDC, pv);
}

// Symbol: ?DDX_Slider@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_Slider__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::SliderPos(pDX, nIDC, pv);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAE@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAE_Z(void* pDX, int nIDC, unsigned char* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_BYTE);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAF@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAF_Z(void* pDX, int nIDC, short* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_SHORT);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAH@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAH_Z(void* pDX, int nIDC, int* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_INT);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAI@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAI_Z(void* pDX, int nIDC, unsigned int* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_UINT);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAJ@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAJ_Z(void* pDX, int nIDC, long* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_LONG);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAK@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAK_Z(void* pDX, int nIDC, unsigned long* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DWORD);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAM@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAM_Z(void* pDX, int nIDC, float* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_FLOAT);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAN@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAN_Z(void* pDX, int nIDC, double* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_DOUBLE);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEAV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL___Z(void* pDX, int nIDC, void* pv) {
    openmfc_ddx::TextStr(pDX, nIDC, reinterpret_cast<CString*>(pv));
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEA_J@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEA_J_Z(void* pDX, int nIDC, long long* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_I64);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HAEA_K@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HAEA_K_Z(void* pDX, int nIDC, unsigned long long* pv) {
    openmfc_ddx::TextNum(pDX, nIDC, pv, openmfc_ddx::T_U64);
}

// Symbol: ?DDX_Text@@YAXPEAVCDataExchange@@HPEA_WH@Z
extern "C" void MS_ABI impl__DDX_Text__YAXPEAVCDataExchange__HPEA_WH_Z(void* pDX, int nIDC, wchar_t* pv, int n) {
    openmfc_ddx::TextBuf(pDX, nIDC, pv, n);
}
