// Manually-written thunks for symbols the auto-generator cannot handle.
// Generated by tools/gen_manual_thunks.py
// These thunks provide proper parameter counts and return types (ABI-compatible),
// but return default values since our C++ method signatures differ from
// the MSVC DLL exports for these symbols.

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
#define MS_ABI __attribute__((ms_abi))
#else
#define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"
#include <cstring>

