// Manually-written thunks for symbols the auto-generator cannot handle.
// Generated by tools/gen_manual_thunks.py
// These thunks provide proper parameter counts and return types (ABI-compatible),
// but return default values since our C++ method signatures differ from
// the MSVC DLL exports for these symbols.

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
#define MS_ABI __attribute__((ms_abi))
#else
#define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"
#include <cstring>

// Symbol: ??0CControlDataSource@COleControl@@QEAA@PEAV1@@Z
extern "C" void* MS_ABI impl___0CControlDataSource_COleControl__QEAA_PEAV1__Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return nullptr;
}

// Symbol: ??0CInternetSession@@QEAA@PEB_W_KK00K@Z
extern "C" void* MS_ABI impl___0CInternetSession__QEAA_PEB_W_KK00K_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    return nullptr;
}

// Symbol: ??0CWinThread@@QEAA@P6AIPEAX@Z0@Z
extern "C" void* MS_ABI impl___0CWinThread__QEAA_P6AIPEAX_Z0_Z(void* pThis, void* p0, void* p1, void* p2, void* p3) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    return nullptr;
}

// Symbol: ?AddCategory@CMFCRibbonBar@@QEAAPEAVCMFCRibbonCategory@@PEB_WIIVCSize@@1HPEAUCRuntimeClass@@@Z
extern "C" void* MS_ABI impl__AddCategory_CMFCRibbonBar__QEAAPEAVCMFCRibbonCategory__PEB_WIIVCSize__1HPEAUCRuntimeClass___Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5, void* p6) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    (void)p6;
    return nullptr;
}

// Symbol: ?AddPanel@CMFCRibbonCategory@@QEAAPEAVCMFCRibbonPanel@@PEB_WPEAUHICON__@@PEAUCRuntimeClass@@@Z
extern "C" void* MS_ABI impl__AddPanel_CMFCRibbonCategory__QEAAPEAVCMFCRibbonPanel__PEB_WPEAUHICON____PEAUCRuntimeClass___Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return nullptr;
}

// Symbol: ?AddProperty@CMFCPropertyGridCtrl@@QEAAHPEAVCMFCPropertyGridProperty@@HH@Z
extern "C" int MS_ABI impl__AddProperty_CMFCPropertyGridCtrl__QEAAHPEAVCMFCPropertyGridProperty__HH_Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0;
}

// Symbol: ?AddSubItem@CMFCPropertyGridProperty@@QEAAHPEAV1@@Z
extern "C" int MS_ABI impl__AddSubItem_CMFCPropertyGridProperty__QEAAHPEAV1__Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0;
}

// Symbol: ?AddTask@CMFCTasksPane@@QEAAHHPEB_WHI_K@Z
extern "C" int MS_ABI impl__AddTask_CMFCTasksPane__QEAAHHPEB_WHI_K_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    return 0;
}

// Symbol: ?AmbientDisplayName@COleControl@@QEAA?AV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@XZ
// Note: our C++ method is BOOL AmbientDisplayName(CString&) but MSVC exports CString AmbientDisplayName()
extern "C" void* MS_ABI impl__AmbientDisplayName_COleControl__QEAA_AV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__XZ(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return nullptr;
}

// Symbol: ?AmbientScaleUnits@COleControl@@QEAA?AV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@XZ
// Note: our C++ method is BOOL AmbientScaleUnits(CString&) but MSVC exports CString AmbientScaleUnits()
extern "C" void* MS_ABI impl__AmbientScaleUnits_COleControl__QEAA_AV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__XZ(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return nullptr;
}

// Symbol: ?Command@CFtpConnection@@QEAAPEAVCInternetFile@@PEB_WW4CmdResponseType@1@K_K@Z
extern "C" void* MS_ABI impl__Command_CFtpConnection__QEAAPEAVCInternetFile__PEB_WW4CmdResponseType_1_K_K_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5, void* p6, void* p7, void* p8, void* p9, void* p10, void* p11, void* p12, void* p13, void* p14, void* p15, void* p16, void* p17, void* p18, void* p19) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    (void)p6;
    (void)p7;
    (void)p8;
    (void)p9;
    (void)p10;
    (void)p11;
    (void)p12;
    (void)p13;
    (void)p14;
    (void)p15;
    (void)p16;
    (void)p17;
    (void)p18;
    (void)p19;
    return nullptr;
}

// Symbol: ?CreateItem@COleInsertDialog@@QEAAHPEAVCOleClientItem@@@Z
extern "C" int MS_ABI impl__CreateItem_COleInsertDialog__QEAAHPEAVCOleClientItem___Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0;
}

// Symbol: ?CreateItem@COlePasteSpecialDialog@@QEAAHPEAVCOleClientItem@@@Z
extern "C" int MS_ABI impl__CreateItem_COlePasteSpecialDialog__QEAAHPEAVCOleClientItem___Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0;
}

// Symbol: ?CreateLocator@CGopherConnection@@QEAA?AVCGopherLocator@@PEB_W0K@Z
extern "C" void* MS_ABI impl__CreateLocator_CGopherConnection__QEAA_AVCGopherLocator__PEB_W0K_Z(void* pThis, void* p0, void* p1, void* p2, void* p3) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    return nullptr;
}

// Symbol: ?CreateLocator@CGopherConnection@@SA?AVCGopherLocator@@PEB_W00KG@Z
extern "C" void* MS_ABI impl__CreateLocator_CGopherConnection__SA_AVCGopherLocator__PEB_W00KG_Z(void* p0, void* p1, void* p2, void* p3, void* p4, void* p5) {
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    return nullptr;
}

// Symbol: ?CreateLocator@CGopherConnection@@SA?AVCGopherLocator@@PEB_W@Z
extern "C" void* MS_ABI impl__CreateLocator_CGopherConnection__SA_AVCGopherLocator__PEB_W_Z(void* p0, void* p1) {
    (void)p0;
    (void)p1;
    return nullptr;
}

// Symbol: ?DoModal@COleInsertDialog@@QEAA_JK@Z
extern "C" __int64 MS_ABI impl__DoModal_COleInsertDialog__QEAA_JK_Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0LL;
}

// Symbol: ?DoVerb@COleClientItem@@UEAAHJPEAVCView@@PEAUtagMSG@@@Z
extern "C" int MS_ABI impl__DoVerb_COleClientItem__UEAAHJPEAVCView__PEAUtagMSG___Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0;
}

// Symbol: ?DockPaneLeftOf@CDockingManager@@QEAAHPEAVCPane@@0@Z
extern "C" int MS_ABI impl__DockPaneLeftOf_CDockingManager__QEAAHPEAVCPane__0_Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0;
}

// Symbol: ?ExecCommand@COleDocObjectItem@@QEAAJKKPEBU_GUID@@@Z
extern "C" long MS_ABI impl__ExecCommand_COleDocObjectItem__QEAAJKKPEBU_GUID___Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0L;
}

// Symbol: ?GetContainer@XOleClientSite@COleControlSite@@UEAAJPEAPEAUIOleContainer@@@Z
extern "C" long MS_ABI impl__GetContainer_XOleClientSite_COleControlSite__UEAAJPEAPEAUIOleContainer___Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0L;
}

// Symbol: ?GetCurrentFont@CFontDialog@@QEAAXPEAUtagLOGFONTW@@@Z
extern "C" void MS_ABI impl__GetCurrentFont_CFontDialog__QEAAXPEAUtagLOGFONTW___Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
}

// Symbol: ?GetElement@CDHtmlDialog@@QEAAJPEB_WPEAPEAUIDispatch@@PEAH@Z
extern "C" long MS_ABI impl__GetElement_CDHtmlDialog__QEAAJPEB_WPEAPEAUIDispatch__PEAH_Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0L;
}

// Symbol: ?GetElement@CDHtmlDialog@@QEAAJPEB_WPEAPEAUIHTMLElement@@@Z
extern "C" long MS_ABI impl__GetElement_CDHtmlDialog__QEAAJPEB_WPEAPEAUIHTMLElement___Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0L;
}

// Symbol: ?GetElementProperty@CDHtmlDialog@@QEAA?AUtagVARIANT@@PEB_WJ@Z
extern "C" void* MS_ABI impl__GetElementProperty_CDHtmlDialog__QEAA_AUtagVARIANT__PEB_WJ_Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return nullptr;
}

// Symbol: ?GetFtpConnection@CInternetSession@@QEAAPEAVCFtpConnection@@PEB_W00GH@Z
extern "C" void* MS_ABI impl__GetFtpConnection_CInternetSession__QEAAPEAVCFtpConnection__PEB_W00GH_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    return nullptr;
}

// Symbol: ?GetHttpConnection@CInternetSession@@QEAAPEAVCHttpConnection@@PEB_WG00@Z
extern "C" void* MS_ABI impl__GetHttpConnection_CInternetSession__QEAAPEAVCHttpConnection__PEB_WG00_Z(void* pThis, void* p0, void* p1, void* p2, void* p3) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    return nullptr;
}

// Symbol: ?GetHttpConnection@CInternetSession@@QEAAPEAVCHttpConnection@@PEB_WKG00@Z
extern "C" void* MS_ABI impl__GetHttpConnection_CInternetSession__QEAAPEAVCHttpConnection__PEB_WKG00_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    return nullptr;
}

// Symbol: ?GetReadyState@CHtmlView@@QEBA?AW4tagREADYSTATE@@XZ
extern "C" void* MS_ABI impl__GetReadyState_CHtmlView__QEBA_AW4tagREADYSTATE__XZ(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5, void* p6, void* p7, void* p8, void* p9, void* p10, void* p11) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    (void)p6;
    (void)p7;
    (void)p8;
    (void)p9;
    (void)p10;
    (void)p11;
    return nullptr;
}

// Symbol: ?GetScrollPosition@CScrollView@@QEBA?AVCPoint@@XZ
extern "C" void* MS_ABI impl__GetScrollPosition_CScrollView__QEBA_AVCPoint__XZ(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return nullptr;
}

// Symbol: ?GetStatus@CFile@@QEBAHAEAUCFileStatus@@@Z
extern "C" int MS_ABI impl__GetStatus_CFile__QEBAHAEAUCFileStatus___Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0;
}

// Symbol: ?GetStatus@CFile@@SAHPEB_WAEAUCFileStatus@@PEAVCAtlTransactionManager@ATL@@@Z
extern "C" int MS_ABI impl__GetStatus_CFile__SAHPEB_WAEAUCFileStatus__PEAVCAtlTransactionManager_ATL___Z(void* p0, void* p1, void* p2) {
    (void)p0;
    (void)p1;
    (void)p2;
    return 0;
}

// Symbol: ?GetWindow@XOleIPSite@COleControlSite@@UEAAJPEAPEAUHWND__@@@Z
extern "C" long MS_ABI impl__GetWindow_XOleIPSite_COleControlSite__UEAAJPEAPEAUHWND_____Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return 0L;
}

// Symbol: ?GetWindowMenuPopup@CMDIFrameWnd@@UEAAPEAUHMENU__@@PEAU2@@Z
extern "C" void* MS_ABI impl__GetWindowMenuPopup_CMDIFrameWnd__UEAAPEAUHMENU____PEAU2__Z(void* pThis, void* p0) {
    (void)pThis;
    (void)p0;
    return nullptr;
}

// Symbol: ?MatchDocType@CDocTemplate@@UEAA?AW4Confidence@1@PEB_WAEAPEAVCDocument@@@Z
extern "C" void* MS_ABI impl__MatchDocType_CDocTemplate__UEAA_AW4Confidence_1_PEB_WAEAPEAVCDocument___Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5, void* p6, void* p7, void* p8, void* p9, void* p10, void* p11, void* p12, void* p13) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    (void)p6;
    (void)p7;
    (void)p8;
    (void)p9;
    (void)p10;
    (void)p11;
    (void)p12;
    (void)p13;
    return nullptr;
}

// Symbol: ?OnDrawPaneCaption@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCDockablePane@@HVCRect@@2@Z
extern "C" unsigned long MS_ABI impl__OnDrawPaneCaption_CMFCVisualManager__UEAAKPEAVCDC__PEAVCDockablePane__HVCRect__2_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    return 0UL;
}

// Symbol: ?OnDrawRibbonButtonsGroup@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonButtonsGroup@@VCRect@@@Z
extern "C" unsigned long MS_ABI impl__OnDrawRibbonButtonsGroup_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonButtonsGroup__VCRect___Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0UL;
}

// Symbol: ?OnDrawRibbonCategoryCaption@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonContextCaption@@@Z
extern "C" unsigned long MS_ABI impl__OnDrawRibbonCategoryCaption_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonContextCaption___Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0UL;
}

// Symbol: ?OnDrawRibbonPanel@CMFCVisualManager@@UEAAKPEAVCDC@@PEAVCMFCRibbonPanel@@VCRect@@2@Z
extern "C" unsigned long MS_ABI impl__OnDrawRibbonPanel_CMFCVisualManager__UEAAKPEAVCDC__PEAVCMFCRibbonPanel__VCRect__2_Z(void* pThis, void* p0, void* p1, void* p2, void* p3) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    return 0UL;
}

// Symbol: ?OnProperties@COleControl@@UEAAHPEAUtagMSG@@PEAUHWND__@@PEBUtagRECT@@@Z
extern "C" int MS_ABI impl__OnProperties_COleControl__UEAAHPEAUtagMSG__PEAUHWND____PEBUtagRECT___Z(void* pThis, void* p0, void* p1, void* p2) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    return 0;
}

// Symbol: ?OnRenderFileData@COleDataSource@@UEAAHPEAUtagFORMATETC@@PEAVCFile@@@Z
extern "C" int MS_ABI impl__OnRenderFileData_COleDataSource__UEAAHPEAUtagFORMATETC__PEAVCFile___Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0;
}

// Symbol: ?OnRenderGlobalData@COleDataSource@@UEAAHPEAUtagFORMATETC@@PEAPEAX@Z
extern "C" int MS_ABI impl__OnRenderGlobalData_COleDataSource__UEAAHPEAUtagFORMATETC__PEAPEAX_Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0;
}

// Symbol: ?ReadString@CArchive@@QEAAPEA_WPEA_WI@Z
extern "C" void* MS_ABI impl__ReadString_CArchive__QEAAPEA_WPEA_WI_Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return nullptr;
}

// Symbol: ?RemoveTab@CMFCBaseTabCtrl@@UEAAHHH@Z
extern "C" int MS_ABI impl__RemoveTab_CMFCBaseTabCtrl__UEAAHHH_Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
    return 0;
}

// Symbol: ?SetAutoHideMode@CDockablePane@@UEAAPEAVCMFCAutoHideBar@@HKPEAV2@H@Z
extern "C" void* MS_ABI impl__SetAutoHideMode_CDockablePane__UEAAPEAVCMFCAutoHideBar__HKPEAV2_H_Z(void* pThis, void* p0, void* p1, void* p2, void* p3) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    return nullptr;
}

// Symbol: ?SetHostNames@COleClientItem@@QEAAXPEB_W0@Z
extern "C" void MS_ABI impl__SetHostNames_COleClientItem__QEAAXPEB_W0_Z(void* pThis, void* p0, void* p1) {
    (void)pThis;
    (void)p0;
    (void)p1;
}

// Symbol: ?SetWindowPos@CBasePane@@UEAAPEAXPEBVCWnd@@HHHHIPEAX@Z
extern "C" void* MS_ABI impl__SetWindowPos_CBasePane__UEAAPEAXPEBVCWnd__HHHHIPEAX_Z(void* pThis, void* p0, void* p1, void* p2, void* p3, void* p4, void* p5, void* p6) {
    (void)pThis;
    (void)p0;
    (void)p1;
    (void)p2;
    (void)p3;
    (void)p4;
    (void)p5;
    (void)p6;
    return nullptr;
}

// Generated 47 manual thunks
