// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CRecordView@@IEAA@I@Z
// Constructor: CRecordView::CRecordView
extern "C" void* MS_ABI impl___0CRecordView__IEAA_I_Z(void* pThis, unsigned int p0) {
    return new(pThis) CRecordView(p0);
}
// Symbol: ??0CRecordView@@IEAA@PEB_W@Z
// Constructor: CRecordView::CRecordView
extern "C" void* MS_ABI impl___0CRecordView__IEAA_PEB_W_Z(void* pThis, const wchar_t* p0) {
    return new(pThis) CRecordView(p0);
}
// Symbol: ??0CRichEditView@@QEAA@XZ
// Constructor: CRichEditView::CRichEditView
extern "C" void* MS_ABI impl___0CRichEditView__QEAA_XZ(void* pThis) {
    return new(pThis) CRichEditView();
}
// Symbol: ??0CScrollView@@IEAA@XZ
// Constructor: CScrollView::CScrollView
extern "C" void* MS_ABI impl___0CScrollView__IEAA_XZ(void* pThis) {
    return new(pThis) CScrollView();
}
// Symbol: ??1CRecordView@@UEAA@XZ
// Destructor: CRecordView::~CRecordView
extern "C" void MS_ABI impl___1CRecordView__UEAA_XZ(void* pThis) {
    ((CRecordView*)pThis)->~CRecordView();
}
// Symbol: ?CanPaste@CRichEditView@@QEBAHXZ
// CRichEditView::CanPaste
extern "C" int MS_ABI impl__CanPaste_CRichEditView__QEBAHXZ(const CRichEditView* pThis) {
    return (int)pThis->CanPaste();
}
// Symbol: ?Create@CFormView@@MEAAHPEB_W0KAEBUtagRECT@@PEAVCWnd@@IPEAUCCreateContext@@@Z
// CFormView::Create
extern "C" int MS_ABI impl__Create_CFormView__MEAAHPEB_W0KAEBUtagRECT__PEAVCWnd__IPEAUCCreateContext___Z(CFormView* pThis, const wchar_t* p0, const wchar_t* p1, unsigned long p2, const RECT* p3, CWnd* p4, unsigned int p5, CCreateContext* p6) {
    return (int)pThis->Create(p0, p1, p2, (*p3), p4, p5, p6);
}
// Symbol: ?CreateControlSite@CDHtmlDialog@@UEAAHPEAVCOleControlContainer@@PEAPEAVCOleControlSite@@IAEBU_GUID@@@Z
// CDHtmlDialog::CreateControlSite
extern "C" int MS_ABI impl__CreateControlSite_CDHtmlDialog__UEAAHPEAVCOleControlContainer__PEAPEAVCOleControlSite__IAEBU_GUID___Z(CDHtmlDialog* pThis, COleControlContainer* p0, COleControlSite** p1, unsigned int p2, const _GUID* p3) {
    return (int)pThis->CreateControlSite(p0, p1, p2, (*p3));
}
// Symbol: ?FillOutsideRect@CScrollView@@QEAAXPEAVCDC@@PEAVCBrush@@@Z
// CScrollView::FillOutsideRect
extern "C" void MS_ABI impl__FillOutsideRect_CScrollView__QEAAXPEAVCDC__PEAVCBrush___Z(CScrollView* pThis, CDC* p0, CBrush* p1) {
    pThis->FillOutsideRect(p0, p1);
}
// Symbol: ?FindTextW@CRichEditView@@QEAAHPEB_WHHH@Z
// CRichEditView::FindTextW
extern "C" int MS_ABI impl__FindTextW_CRichEditView__QEAAHPEB_WHHH_Z(CRichEditView* pThis, const wchar_t* p0, int p1, int p2, int p3) {
    return (int)pThis->FindTextW(p0, p1, p2, p3);
}
// Symbol: ?GetScrollPosition@CScrollView@@QEBA?AVCPoint@@XZ
// CScrollView::GetScrollPosition  [retval]
extern "C" void MS_ABI impl__GetScrollPosition_CScrollView__QEBA_AVCPoint__XZ(const CScrollView* pThis, CPoint* __ret) {
    *__ret = pThis->GetScrollPosition();
}
// Symbol: ?IsOnFirstRecord@CRecordView@@QEAAHXZ
// CRecordView::IsOnFirstRecord
extern "C" int MS_ABI impl__IsOnFirstRecord_CRecordView__QEAAHXZ(CRecordView* pThis) {
    return (int)pThis->IsOnFirstRecord();
}
// Symbol: ?IsOnLastRecord@CRecordView@@QEAAHXZ
// CRecordView::IsOnLastRecord
extern "C" int MS_ABI impl__IsOnLastRecord_CRecordView__QEAAHXZ(CRecordView* pThis) {
    return (int)pThis->IsOnLastRecord();
}
// Symbol: ?OnDraw@CFormView@@MEAAXPEAVCDC@@@Z
// CFormView::OnDraw
extern "C" void MS_ABI impl__OnDraw_CFormView__MEAAXPEAVCDC___Z(CFormView* pThis, CDC* p0) {
    pThis->OnDraw(p0);
}
// Symbol: ?OnInitialUpdate@CRichEditView@@MEAAXXZ
// CRichEditView::OnInitialUpdate
extern "C" void MS_ABI impl__OnInitialUpdate_CRichEditView__MEAAXXZ(CRichEditView* pThis) {
    pThis->OnInitialUpdate();
}
// Symbol: ?OnMove@CRecordView@@UEAAHI@Z
// CRecordView::OnMove
extern "C" int MS_ABI impl__OnMove_CRecordView__UEAAHI_Z(CRecordView* pThis, unsigned int p0) {
    return (int)pThis->OnMove(p0);
}
// Symbol: ?OnTextNotFound@CRichEditView@@MEAAXPEB_W@Z
// CRichEditView::OnTextNotFound
extern "C" void MS_ABI impl__OnTextNotFound_CRichEditView__MEAAXPEB_W_Z(CRichEditView* pThis, const wchar_t* p0) {
    pThis->OnTextNotFound(p0);
}
// Symbol: ?PrintInsideRect@CRichEditView@@QEAAJPEAVCDC@@AEAUtagRECT@@JJH@Z
// CRichEditView::PrintInsideRect
extern "C" long MS_ABI impl__PrintInsideRect_CRichEditView__QEAAJPEAVCDC__AEAUtagRECT__JJH_Z(CRichEditView* pThis, CDC* p0, RECT* p1, long p2, long p3, int p4) {
    return (long)pThis->PrintInsideRect(p0, (*p1), p2, p3, p4);
}
// Symbol: ?PrintPage@CRichEditView@@QEAAJPEAVCDC@@JJ@Z
// CRichEditView::PrintPage
extern "C" long MS_ABI impl__PrintPage_CRichEditView__QEAAJPEAVCDC__JJ_Z(CRichEditView* pThis, CDC* p0, long p1, long p2) {
    return (long)pThis->PrintPage(p0, p1, p2);
}
// Symbol: ?ResizeParentToFit@CScrollView@@QEAAXH@Z
// CScrollView::ResizeParentToFit
extern "C" void MS_ABI impl__ResizeParentToFit_CScrollView__QEAAXH_Z(CScrollView* pThis, int p0) {
    pThis->ResizeParentToFit(p0);
}
// Symbol: ?ScrollToPosition@CScrollView@@QEAAXUtagPOINT@@@Z
// CScrollView::ScrollToPosition
extern "C" void MS_ABI impl__ScrollToPosition_CScrollView__QEAAXUtagPOINT___Z(CScrollView* pThis, POINT p0) {
    pThis->ScrollToPosition(p0);
}
// Symbol: ?Serialize@CEditView@@UEAAXAEAVCArchive@@@Z
// CEditView::Serialize
extern "C" void MS_ABI impl__Serialize_CEditView__UEAAXAEAVCArchive___Z(CEditView* pThis, CArchive* p0) {
    pThis->Serialize((*p0));
}
// Symbol: ?Serialize@CRichEditView@@UEAAXAEAVCArchive@@@Z
// CRichEditView::Serialize
extern "C" void MS_ABI impl__Serialize_CRichEditView__UEAAXAEAVCArchive___Z(CRichEditView* pThis, CArchive* p0) {
    pThis->Serialize((*p0));
}
// Symbol: ?SetCharFormat@CRichEditView@@QEAAXUCHARFORMAT2W@@@Z
// CRichEditView::SetCharFormat
extern "C" void MS_ABI impl__SetCharFormat_CRichEditView__QEAAXUCHARFORMAT2W___Z(CRichEditView* pThis, CHARFORMAT2W p0) {
    pThis->SetCharFormat(p0);
}
// Symbol: ?SetParaFormat@CRichEditView@@QEAAHAEAUPARAFORMAT2@@@Z
// CRichEditView::SetParaFormat
extern "C" int MS_ABI impl__SetParaFormat_CRichEditView__QEAAHAEAUPARAFORMAT2___Z(CRichEditView* pThis, PARAFORMAT2* p0) {
    return (int)pThis->SetParaFormat((*p0));
}
// Symbol: ?Stream@CRichEditView@@QEAAXAEAVCArchive@@H@Z
// CRichEditView::Stream
extern "C" void MS_ABI impl__Stream_CRichEditView__QEAAXAEAVCArchive__H_Z(CRichEditView* pThis, CArchive* p0, int p1) {
    pThis->Stream((*p0), p1);
}
// Symbol: ?TextNotFound@CRichEditView@@QEAAXPEB_W@Z
// CRichEditView::TextNotFound
extern "C" void MS_ABI impl__TextNotFound_CRichEditView__QEAAXPEB_W_Z(CRichEditView* pThis, const wchar_t* p0) {
    pThis->TextNotFound(p0);
}
// Symbol: ?WrapChanged@CRichEditView@@MEAAXXZ
// CRichEditView::WrapChanged
extern "C" void MS_ABI impl__WrapChanged_CRichEditView__MEAAXXZ(CRichEditView* pThis) {
    pThis->WrapChanged();
}
