// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CBasePane@@QEAA@XZ
// Constructor: CBasePane::CBasePane
extern "C" void* MS_ABI impl___0CBasePane__QEAA_XZ(void* pThis) {
    return new(pThis) CBasePane();
}
// Symbol: ??0CDockablePane@@QEAA@XZ
// Constructor: CDockablePane::CDockablePane
extern "C" void* MS_ABI impl___0CDockablePane__QEAA_XZ(void* pThis) {
    return new(pThis) CDockablePane();
}
// Symbol: ??0CDockingManager@@QEAA@XZ
// Constructor: CDockingManager::CDockingManager
extern "C" void* MS_ABI impl___0CDockingManager__QEAA_XZ(void* pThis) {
    return new(pThis) CDockingManager();
}
// Symbol: ??0CPane@@IEAA@XZ
// Constructor: CPane::CPane
extern "C" void* MS_ABI impl___0CPane__IEAA_XZ(void* pThis) {
    return new(pThis) CPane();
}
// Symbol: ??0CPaneFrameWnd@@QEAA@XZ
// Constructor: CPaneFrameWnd::CPaneFrameWnd
extern "C" void* MS_ABI impl___0CPaneFrameWnd__QEAA_XZ(void* pThis) {
    return new(pThis) CPaneFrameWnd();
}
// Symbol: ??1CBasePane@@UEAA@XZ
// Destructor: CBasePane::~CBasePane
extern "C" void MS_ABI impl___1CBasePane__UEAA_XZ(void* pThis) {
    ((CBasePane*)pThis)->~CBasePane();
}
// Symbol: ??1CDockablePane@@UEAA@XZ
// Destructor: CDockablePane::~CDockablePane
extern "C" void MS_ABI impl___1CDockablePane__UEAA_XZ(void* pThis) {
    ((CDockablePane*)pThis)->~CDockablePane();
}
// Symbol: ??1CDockingManager@@UEAA@XZ
// Destructor: CDockingManager::~CDockingManager
extern "C" void MS_ABI impl___1CDockingManager__UEAA_XZ(void* pThis) {
    ((CDockingManager*)pThis)->~CDockingManager();
}
// Symbol: ??1CPane@@UEAA@XZ
// Destructor: CPane::~CPane
extern "C" void MS_ABI impl___1CPane__UEAA_XZ(void* pThis) {
    ((CPane*)pThis)->~CPane();
}
// Symbol: ??1CPaneFrameWnd@@UEAA@XZ
// Destructor: CPaneFrameWnd::~CPaneFrameWnd
extern "C" void MS_ABI impl___1CPaneFrameWnd__UEAA_XZ(void* pThis) {
    ((CPaneFrameWnd*)pThis)->~CPaneFrameWnd();
}
// Symbol: ?CanAutoHide@CDockablePane@@UEBAHXZ
// CDockablePane::CanAutoHide
extern "C" int MS_ABI impl__CanAutoHide_CDockablePane__UEBAHXZ(const CDockablePane* pThis) {
    return (int)pThis->CanAutoHide();
}
// Symbol: ?CanFloat@CBasePane@@UEBAHXZ
// CBasePane::CanFloat
extern "C" int MS_ABI impl__CanFloat_CBasePane__UEBAHXZ(const CBasePane* pThis) {
    return (int)pThis->CanFloat();
}
// Symbol: ?DockPane@CDockingManager@@QEAAXPEAVCBasePane@@IPEBUtagRECT@@@Z
// CDockingManager::DockPane
extern "C" void MS_ABI impl__DockPane_CDockingManager__QEAAXPEAVCBasePane__IPEBUtagRECT___Z(CDockingManager* pThis, CBasePane* p0, unsigned int p1, const RECT* p2) {
    pThis->DockPane(p0, p1, p2);
}
// Symbol: ?DockPaneLeftOf@CDockingManager@@QEAAHPEAVCPane@@0@Z
// CDockingManager::DockPaneLeftOf
extern "C" int MS_ABI impl__DockPaneLeftOf_CDockingManager__QEAAHPEAVCPane__0_Z(CDockingManager* pThis, CPane* p0, CPane* p1) {
    return (int)pThis->DockPaneLeftOf(p0, p1);
}
// Symbol: ?EnableDocking@CDockingManager@@QEAAHK@Z
// CDockingManager::EnableDocking
extern "C" int MS_ABI impl__EnableDocking_CDockingManager__QEAAHK_Z(CDockingManager* pThis, unsigned long p0) {
    return (int)pThis->EnableDocking(p0);
}
// Symbol: ?RecalcLayout@CPane@@UEAAXXZ
// CPane::RecalcLayout
extern "C" void MS_ABI impl__RecalcLayout_CPane__UEAAXXZ(CPane* pThis) {
    pThis->RecalcLayout();
}
// Symbol: ?SetAutoHideMode@CDockablePane@@UEAAPEAVCMFCAutoHideBar@@HKPEAV2@H@Z
// CDockablePane::SetAutoHideMode
extern "C" CMFCAutoHideBar* MS_ABI impl__SetAutoHideMode_CDockablePane__UEAAPEAVCMFCAutoHideBar__HKPEAV2_H_Z(CDockablePane* pThis, int p0, unsigned long p1, void* p2, int p3) {
    return (CMFCAutoHideBar*)pThis->SetAutoHideMode(p0, p1, p2, p3);
}
// Symbol: ?SetDockState@CDockingManager@@UEAAXXZ
// CDockingManager::SetDockState
extern "C" void MS_ABI impl__SetDockState_CDockingManager__UEAAXXZ(CDockingManager* pThis) {
    pThis->SetDockState();
}
// Symbol: ?SetWindowPos@CBasePane@@UEAAPEAXPEBVCWnd@@HHHHIPEAX@Z
// CBasePane::SetWindowPos
extern "C" void* MS_ABI impl__SetWindowPos_CBasePane__UEAAPEAXPEBVCWnd__HHHHIPEAX_Z(CBasePane* pThis, const CWnd* p0, int p1, int p2, int p3, int p4, unsigned int p5, void* p6) {
    return (void*)pThis->SetWindowPos(p0, p1, p2, p3, p4, p5, p6);
}
