#!/usr/bin/env python3
"""Generate the complete RTTI harvest inventory from the ordinal map.

The real MFC DLL exports GetThisClass and GetRuntimeClass in ordinal-only form.
Keeping the probe target list by hand caused the harvest campaign to stop at
158 classes even though the export map contains many more paired getters.

This generator writes:
  * rtti_targets.h: C++ target table used by rtti_probe.cpp
  * rtti_layout_targets.txt: one class per line for MSVC layout harvesting
  * rtti_targets.json: machine-readable ordinals and inventory diagnostics
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MAPPING = ROOT / "mfc_complete_ordinal_mapping.json"
DEFAULT_HEADER = ROOT / "tools/harvest/rtti_targets.h"
DEFAULT_LAYOUT_TARGETS = ROOT / "tools/harvest/rtti_layout_targets.txt"
DEFAULT_MANIFEST = ROOT / "tools/harvest/rtti_targets.json"

GET_THIS_RE = re.compile(
    r"^\?GetThisClass@([^@]+)@@SAPEAUCRuntimeClass@@XZ$"
)
GET_RUNTIME_RE = re.compile(
    r"^\?GetRuntimeClass@([^@]+)@@UEBAPEAUCRuntimeClass@@XZ$"
)


def load_exports(path: Path) -> list[dict]:
    document = json.loads(path.read_text(encoding="utf-8"))
    try:
        return document["exports"]["mfc140u"]
    except (KeyError, TypeError) as exc:
        raise SystemExit(f"unsupported ordinal-map schema in {path}") from exc


def collect_targets(exports: list[dict]) -> tuple[list[dict], list[str], list[str]]:
    get_this: dict[str, int] = {}
    get_runtime: dict[str, int] = {}

    for entry in exports:
        symbol = entry["symbol"]
        match = GET_THIS_RE.fullmatch(symbol)
        if match:
            get_this[match.group(1)] = int(entry["ordinal"])
            continue
        match = GET_RUNTIME_RE.fullmatch(symbol)
        if match:
            get_runtime[match.group(1)] = int(entry["ordinal"])

    paired = sorted(get_this.keys() & get_runtime.keys())
    targets = [
        {
            "class": class_name,
            "get_this_class_ordinal": get_this[class_name],
            "get_runtime_class_ordinal": get_runtime[class_name],
        }
        for class_name in paired
    ]
    return (
        targets,
        sorted(get_this.keys() - get_runtime.keys()),
        sorted(get_runtime.keys() - get_this.keys()),
    )


def render_header(targets: list[dict]) -> str:
    lines = [
        "// AUTO-GENERATED by tools/harvest/gen_rtti_targets.py -- DO NOT EDIT.",
        "// {class, GetThisClass ordinal, GetRuntimeClass ordinal}",
        "struct Target { const char* name; int ord_gt; int ord_grc; };",
        "static const Target g_targets[] = {",
    ]
    for target in targets:
        lines.append(
            f'  {{ "{target["class"]}", '
            f'{target["get_this_class_ordinal"]}, '
            f'{target["get_runtime_class_ordinal"]} }},'
        )
    lines.extend(
        [
            "};",
            f"static const int g_ntargets = {len(targets)};",
            "",
        ]
    )
    return "\n".join(lines)


def generated_outputs(mapping: Path) -> dict[Path, str]:
    exports = load_exports(mapping)
    targets, missing_runtime, missing_this = collect_targets(exports)
    if not targets:
        raise SystemExit("no paired RTTI getter exports found")

    mapping_sha256 = hashlib.sha256(mapping.read_bytes()).hexdigest()
    manifest = {
        "mapping": str(mapping.relative_to(ROOT)),
        "mapping_sha256": mapping_sha256,
        "target_count": len(targets),
        "missing_get_runtime_class": missing_runtime,
        "missing_get_this_class": missing_this,
        "targets": targets,
    }
    return {
        DEFAULT_HEADER: render_header(targets),
        DEFAULT_LAYOUT_TARGETS: "\n".join(t["class"] for t in targets) + "\n",
        DEFAULT_MANIFEST: json.dumps(manifest, indent=2, sort_keys=True) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mapping", type=Path, default=DEFAULT_MAPPING)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed generated files differ from the ordinal map",
    )
    args = parser.parse_args()

    outputs = generated_outputs(args.mapping.resolve())
    stale: list[Path] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT)}")

    if stale:
        for path in stale:
            print(f"stale generated file: {path.relative_to(ROOT)}")
        return 1
    if args.check:
        print(f"RTTI harvest inventory is current ({len(outputs)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
