#!/usr/bin/env python3
"""Generate real GetInterfaceMap / GetThisInterfaceMap exports for the 25 CCmdTarget-
derived OLE classes whose interface maps were null stubs (a real MSVC client crashed
walking the null map during QueryInterface / OLE interface routing).

Mirrors the merged message-map campaign: the handler entries are real mfc140u code
addresses we cannot replicate, so each map uses an empty terminator; the faithful,
verifiable part is a non-null AFX_INTERFACEMAP whose pfnGetBaseMap chains to the base's
exported map, terminating at CCmdTarget (root).  GetInterfaceMap (virtual) and
GetThisInterfaceMap (static) both return the class map, as BEGIN_INTERFACE_MAP declares.
"""
import json, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import stub_coverage as sc
import gen_weak_stubs as gw

OUT = ROOT / "phase4" / "src" / "global_interface_maps.cpp"

# Direct in-set interface-map parents (others chain straight to the CCmdTarget root).
PARENT = {
    'COleDocObjectItem': 'COleClientItem',
    'COleServerDoc': 'COleLinkingDoc',
}


def collect():
    m, _ = sc.load_current_manifest()
    classes = {}
    for e in m['stub']:
        x = e['symbol']
        mm = re.match(r'^\?(Get(?:This)?InterfaceMap)@([A-Za-z0-9_]+)@@', x)
        if mm:
            classes.setdefault(mm.group(2), {})[mm.group(1)] = (x, gw.generate_stub_name(x))
    return classes


def base_of(c):
    return PARENT.get(c, None if c == 'CCmdTarget' else 'CCmdTarget')


PRE = '''// AUTO-GENERATED by tools/harvest/gen_ifacemap.py -- DO NOT EDIT BY HAND.
// Real AFX_INTERFACEMAP for the CCmdTarget OLE-class family (see the generator header).
#include <cstddef>

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif
#if defined(_MSC_VER) || defined(__MINGW32__)
  #define AFXAPI __cdecl
#else
  #define AFXAPI
#endif

struct AFX_INTERFACEMAP_ENTRY { const void* piid; size_t nOffset; };
struct AFX_INTERFACEMAP { const AFX_INTERFACEMAP* (AFXAPI* pfnGetBaseMap)(); const AFX_INTERFACEMAP_ENTRY* pEntries; };

// Empty terminator shared by every map (real IID->offset entries are mfc140u addresses).
static const AFX_INTERFACEMAP_ENTRY g_ifaceEnd[] = { { nullptr, (size_t)-1 } };
'''


def main():
    classes = collect()
    order = ['CCmdTarget'] + sorted(c for c in classes if c != 'CCmdTarget')
    out = [PRE]
    # forward-declare each class's GetThisInterfaceMap thunk so base chains can reference it
    for c in order:
        gt = classes[c].get('GetThisInterfaceMap')
        if gt:
            out.append('extern "C" const AFX_INTERFACEMAP* MS_ABI %s();' % gt[1])
    out.append('')
    n = 0
    for c in order:
        base = base_of(c)
        entry = classes[c]
        # base thunk (AFXAPI) for pfnGetBaseMap
        if base is None:
            base_fn = 'nullptr'
        else:
            base_gt = classes.get(base, {}).get('GetThisInterfaceMap')
            base_fn = 'gib_%s' % c
            out.append('static const AFX_INTERFACEMAP* AFXAPI %s() { return %s(); }'
                       % (base_fn, base_gt[1]))
        out.append('static const AFX_INTERFACEMAP g_imap_%s = { %s, g_ifaceEnd };' % (c, base_fn))
        gt = entry.get('GetThisInterfaceMap')
        gi = entry.get('GetInterfaceMap')
        if gt:
            out.append('// Symbol: %s' % gt[0])
            out.append('extern "C" const AFX_INTERFACEMAP* MS_ABI %s() { return &g_imap_%s; }' % (gt[1], c))
            n += 1
        if gi:
            out.append('// Symbol: %s' % gi[0])
            out.append('extern "C" const AFX_INTERFACEMAP* MS_ABI %s(const void* pThis) { (void)pThis; return &g_imap_%s; }' % (gi[1], c))
            n += 1
        out.append('')
    OUT.write_text('\n'.join(out) + '\n', encoding='ascii')
    print("emitted %d interface-map exports (%d classes) -> %s" % (n, len(order), OUT))


if __name__ == '__main__':
    main()
