// AUTO-GENERATED layout probe for RTTI batch harvest. Touches each target so
// MSVC /d1reportSingleClassLayout<Class> emits its layout. Compile with cl.exe.
#ifndef _AFXDLL
#define _AFXDLL
#endif
#define _CRT_SECURE_NO_WARNINGS
#include <afxwin.h>
#include <afxext.h>
#include <afxcontrolbars.h>   // MFC Feature Pack umbrella: ribbon/toolbar/outlook/propgrid/docking
#include <afxole.h>
#include <afxdisp.h>
#include <afxoledb.h>
#include <afxinet.h>          // CGopherFile/CGopherFileFind
#include <afxtaskdialog.h>    // CTaskDialog
#include <afxdtctl.h>
#include <afxhtml.h>          // CHtmlEditView/CHtmlEditDoc
#include <afxrendertarget.h>  // CHwndRenderTarget/CBitmapRenderTarget/CRenderTarget

#define TOUCH(C) volatile size_t s_##C = sizeof(C);

TOUCH(CAutoHideDockSite)
TOUCH(CBaseKeyFrame)
TOUCH(CBaseTransition)
TOUCH(CBitmapRenderTarget)
TOUCH(CControlBar)
TOUCH(CDockBar)
TOUCH(CGopherFile)
TOUCH(CGopherFileFind)
TOUCH(CHelpComboBoxButton)
TOUCH(CHtmlEditDoc)
TOUCH(CHtmlEditView)
TOUCH(CHwndRenderTarget)
TOUCH(CKeyFrame)
TOUCH(CMDITabProxyWnd)
TOUCH(CMFCAutoHideBar)
TOUCH(CMFCAutoHideButton)
TOUCH(CMFCBaseAccessibleObject)
TOUCH(CMFCBaseTabCtrl)
TOUCH(CMFCBaseToolBar)
TOUCH(CMFCButton)
TOUCH(CMFCCaptionBar)
TOUCH(CMFCColorBar)
TOUCH(CMFCColorButton)
TOUCH(CMFCColorMenuButton)
TOUCH(CMFCColorPopupMenu)
TOUCH(CMFCColorPropertySheet)
TOUCH(CMFCControlRenderer)
TOUCH(CMFCCustomColorsPropertyPage)
TOUCH(CMFCCustomizeButton)
TOUCH(CMFCCustomizeMenuButton)
TOUCH(CMFCDesktopAlertDialog)
TOUCH(CMFCDesktopAlertWnd)
TOUCH(CMFCDropDownFrame)
TOUCH(CMFCDropDownListBox)
TOUCH(CMFCDropDownToolBar)
TOUCH(CMFCDropDownToolbarButton)
TOUCH(CMFCDynamicLayout)
TOUCH(CMFCEditBrowseCtrl)
TOUCH(CMFCHeaderCtrl)
TOUCH(CMFCLinkCtrl)
TOUCH(CMFCListCtrl)
TOUCH(CMFCMaskedEdit)
TOUCH(CMFCMenuBar)
TOUCH(CMFCMenuButton)
TOUCH(CMFCMousePropertyPage)
TOUCH(CMFCOutlookBar)
TOUCH(CMFCOutlookBarPane)
TOUCH(CMFCOutlookBarPaneAdapter)
TOUCH(CMFCOutlookBarPaneButton)
TOUCH(CMFCOutlookBarTabCtrl)
TOUCH(CMFCOutlookBarToolBar)
TOUCH(CMFCPopupMenu)
TOUCH(CMFCPopupMenuBar)
TOUCH(CMFCPreviewCtrlImpl)
TOUCH(CMFCPrintPreviewToolBar)
TOUCH(CMFCPropertyGridColorProperty)
TOUCH(CMFCPropertyGridCtrl)
TOUCH(CMFCPropertyGridFileProperty)
TOUCH(CMFCPropertyGridFontProperty)
TOUCH(CMFCPropertyGridProperty)
TOUCH(CMFCPropertyGridToolTipCtrl)
TOUCH(CMFCPropertyPage)
TOUCH(CMFCPropertySheet)
TOUCH(CMFCPropertySheetCategoryInfo)
TOUCH(CMFCReBar)
TOUCH(CMFCRibbonApplicationButton)
TOUCH(CMFCRibbonBaseElement)
TOUCH(CMFCRibbonButton)
TOUCH(CMFCRibbonButtonsGroup)
TOUCH(CMFCRibbonCaptionButton)
TOUCH(CMFCRibbonCheckBox)
TOUCH(CMFCRibbonColorButton)
TOUCH(CMFCRibbonColorMenuButton)
TOUCH(CMFCRibbonComboBox)
TOUCH(CMFCRibbonContextCaption)
TOUCH(CMFCRibbonCustomizeCategory)
TOUCH(CMFCRibbonCustomizeDialog)
TOUCH(CMFCRibbonCustomizePropertyPage)
TOUCH(CMFCRibbonDefaultPanelButton)
TOUCH(CMFCRibbonEdit)
TOUCH(CMFCRibbonFontComboBox)
TOUCH(CMFCRibbonGallery)
TOUCH(CMFCRibbonGalleryIcon)
TOUCH(CMFCRibbonGalleryMenuButton)
TOUCH(CMFCRibbonLabel)
TOUCH(CMFCRibbonLaunchButton)
TOUCH(CMFCRibbonLinkCtrl)
TOUCH(CMFCRibbonMainPanel)
TOUCH(CMFCRibbonMainPanelButton)
TOUCH(CMFCRibbonMiniToolBar)
TOUCH(CMFCRibbonPanelMenu)
TOUCH(CMFCRibbonPanelMenuBar)
TOUCH(CMFCRibbonProgressBar)
TOUCH(CMFCRibbonQuickAccessCustomizeButton)
TOUCH(CMFCRibbonQuickAccessToolBar)
TOUCH(CMFCRibbonRecentFilesList)
TOUCH(CMFCRibbonRichEditCtrl)
TOUCH(CMFCRibbonSeparator)
TOUCH(CMFCRibbonSlider)
TOUCH(CMFCRibbonStatusBar)
TOUCH(CMFCRibbonStatusBarCustomizeButton)
TOUCH(CMFCRibbonStatusBarPane)
TOUCH(CMFCRibbonTab)
TOUCH(CMFCRibbonTabsGroup)
TOUCH(CMFCRibbonUndoButton)
TOUCH(CMFCShadowRenderer)
TOUCH(CMFCShellListCtrl)
TOUCH(CMFCShellTreeCtrl)
TOUCH(CMFCShowAllButton)
TOUCH(CMFCStandardColorsPropertyPage)
TOUCH(CMFCStatusBar)
TOUCH(CMFCTabCtrl)
TOUCH(CMFCTasksPane)
TOUCH(CMFCTasksPaneFrameWnd)
TOUCH(CMFCTasksPaneToolBar)
TOUCH(CMFCToolBar)
TOUCH(CMFCToolBarButton)
TOUCH(CMFCToolBarColorButton)
TOUCH(CMFCToolBarComboBoxButton)
TOUCH(CMFCToolBarDateTimeCtrl)
TOUCH(CMFCToolBarEditBoxButton)
TOUCH(CMFCToolBarFontComboBox)
TOUCH(CMFCToolBarFontSizeComboBox)
TOUCH(CMFCToolBarMenuButton)
TOUCH(CMFCToolBarMenuButtonsButton)
TOUCH(CMFCToolBarSpinEditBoxButton)
TOUCH(CMFCToolBarSystemMenuButton)
TOUCH(CMFCToolBarsCommandsPropertyPage)
TOUCH(CMFCToolBarsCustomizeDialog)
TOUCH(CMFCToolBarsKeyboardPropertyPage)
TOUCH(CMFCToolBarsListPropertyPage)
TOUCH(CMFCToolBarsMenuPropertyPage)
TOUCH(CMFCToolBarsOptionsPropertyPage)
TOUCH(CMFCToolTipCtrl)
TOUCH(CMFCVisualManagerVS2008)
TOUCH(CMultiPaneFrameWnd)
TOUCH(COleCntrFrameWndEx)
TOUCH(COleDBRecordView)
TOUCH(COlePropertyPage)
TOUCH(COleResizeBar)
TOUCH(COutlookCustomizeButton)
TOUCH(CPreviewDC)
TOUCH(CPreviewView)
TOUCH(CPreviewViewEx)
TOUCH(CReBar)
TOUCH(CRibbonUndoLabel)
TOUCH(CRichEditCntrItem)
TOUCH(CRichEditDoc)
TOUCH(CSmartDockingGroupGuidesManager)
TOUCH(CSmartDockingStandaloneGuide)
TOUCH(CSplitterWnd)
TOUCH(CSplitterWndEx)
TOUCH(CStatusBar)
TOUCH(CTaskDialog)
TOUCH(CTasksPaneHistoryButton)
TOUCH(CTasksPaneMenuButton)
TOUCH(CTasksPaneNavigateButton)
TOUCH(CWindowlessDC)

int main(){return 0;}
