#ifndef _AFXDLL
#define _AFXDLL
#endif
#include <afxwin.h>
#include <afxext.h>
#include <afxadv.h>
#include <afxole.h>
#include <afxdisp.h>
#include <afxodlgs.h>
#include <afxdtctl.h>
#include <afxcview.h>
#include <afxrich.h>
#include <afxhtml.h>
#include <afxdhtml.h>
#include <afxctl.h>
#define TOUCH(C) volatile size_t s_##C = sizeof(C);
TOUCH(CCmdTarget)
TOUCH(CWnd)
TOUCH(CFrameWnd)
TOUCH(CMDIFrameWnd)
TOUCH(CMDIChildWnd)
TOUCH(CDialog)
TOUCH(CDialogEx)
TOUCH(CPropertyPage)
TOUCH(CPropertySheet)
TOUCH(CFileDialog)
TOUCH(CColorDialog)
TOUCH(CFontDialog)
TOUCH(CPrintDialog)
TOUCH(CPrintDialogEx)
TOUCH(CPageSetupDialog)
TOUCH(CWinApp)
TOUCH(CGdiObject)
TOUCH(CPen)
TOUCH(CBrush)
TOUCH(CFont)
TOUCH(CBitmap)
TOUCH(CPalette)
TOUCH(CRgn)
TOUCH(CDC)
TOUCH(CClientDC)
TOUCH(CPaintDC)
TOUCH(CWindowDC)
TOUCH(CMetaFileDC)
TOUCH(CMenu)
TOUCH(CImageList)
TOUCH(CDocument)
TOUCH(CView)
TOUCH(CScrollView)
TOUCH(CFormView)
TOUCH(CEditView)
TOUCH(CListView)
TOUCH(CTreeView)
TOUCH(CRichEditCtrl)
TOUCH(CRichEditView)
TOUCH(CHtmlView)
TOUCH(CDHtmlDialog)
TOUCH(CDocTemplate)
TOUCH(CSingleDocTemplate)
TOUCH(CMultiDocTemplate)
TOUCH(CControlBar)
TOUCH(CToolTipCtrl)
TOUCH(CToolBar)
TOUCH(CStatusBar)
TOUCH(CDialogBar)
TOUCH(CSplitterWnd)
TOUCH(CDocItem)
TOUCH(COleSafeArray)
TOUCH(COleDataSource)
TOUCH(COleDropTarget)
TOUCH(COleDropSource)
TOUCH(COleMessageFilter)
TOUCH(COleCmdUI)
TOUCH(COleFrameHook)
TOUCH(COleResizeBar)
TOUCH(COleStreamFile)
TOUCH(COlePropertyPage)
TOUCH(COleDocument)
TOUCH(COleLinkingDoc)
TOUCH(COleServerDoc)
TOUCH(COleClientItem)
TOUCH(COleDocObjectItem)
TOUCH(COleServerItem)
TOUCH(COleObjectFactory)
TOUCH(COleTemplateServer)
TOUCH(COleControlSite)
TOUCH(COleControlContainer)
TOUCH(COleIPFrameWnd)
TOUCH(CEnumFormatEtc)
TOUCH(COleDialog)
TOUCH(COleBusyDialog)
TOUCH(COleChangeIconDialog)
TOUCH(COleChangeSourceDialog)
TOUCH(COleConvertDialog)
TOUCH(COleInsertDialog)
TOUCH(COleLinksDialog)
TOUCH(COlePasteSpecialDialog)
TOUCH(COlePropertiesDialog)
TOUCH(COleUpdateDialog)
TOUCH(COleControl)
int main(){return 0;}
