// Thunks — OpenMFC implementation.
// Sources: manual_thunks.cpp, thunks.cpp

#define OPENMFC_APPCORE_IMPL

#include "detail/ManualThunksSupport.h"

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ?Write@XElementEdit@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementEdit_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementEdit");
}
// Symbol: ?Write@XElementFontComboBox@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementFontComboBox_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementFontComboBox");
}
// Symbol: ?Write@XElementGroup@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementGroup_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementGroup");
}
// Symbol: ?Write@XElementLabel@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementLabel_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementLabel");
}
// Symbol: ?Write@XElementProgressBar@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementProgressBar_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementProgressBar");
}
// Symbol: ?Write@XElementSeparator@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementSeparator_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementSeparator");
}
// Symbol: ?Write@XElementSlider@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XElementSlider_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XElementSlider");
}
// Symbol: ?Write@XGalleryGroup@XElementButtonGallery@CMFCRibbonInfo@@QEAAHAEAVXRibbonInfoParser@3@@Z
extern "C" int MS_ABI impl__Write_XGalleryGroup_XElementButtonGallery_CMFCRibbonInfo__QEAAHAEAVXRibbonInfoParser_3__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XGalleryGroup");
}
// Symbol: ?Write@XID@CMFCRibbonInfo@@QEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XID_CMFCRibbonInfo__QEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XID");
}
// Symbol: ?Write@XImage@CMFCRibbonInfo@@QEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XImage_CMFCRibbonInfo__QEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XImage");
}
// Symbol: ?Write@XPanel@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XPanel_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XPanel");
}
// Symbol: ?Write@XQAT@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XQAT_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XQAT");
}
// Symbol: ?Write@XQATItem@XQAT@CMFCRibbonInfo@@QEAAHAEAVXRibbonInfoParser@3@@Z
extern "C" int MS_ABI impl__Write_XQATItem_XQAT_CMFCRibbonInfo__QEAAHAEAVXRibbonInfoParser_3__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XQATItem");
}
// Symbol: ?Write@XRibbonBar@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Write_XRibbonBar_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* parser) {
    (void)pThis;
    return RecordRibbonWrite(parser, L"XRibbonBar");
}
// Symbol: ?WriteBool@XRibbonInfoParser@CMFCRibbonInfo@@UEAAHAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@HH@Z
extern "C" int MS_ABI impl__WriteBool_XRibbonInfoParser_CMFCRibbonInfo__UEAAHAEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__HH_Z(
    void* pThis, const CString* name, int value, int defaultValue) {
    return RecordRibbonAttribute(pThis, name, ManualThunkIntText(value, defaultValue));
}
// Symbol: ?WriteColor@XRibbonInfoParser@CMFCRibbonInfo@@UEAAHAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@KK@Z
extern "C" int MS_ABI impl__WriteColor_XRibbonInfoParser_CMFCRibbonInfo__UEAAHAEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__KK_Z(
    void* pThis, const CString* name, unsigned long value, unsigned long defaultValue) {
    return RecordRibbonAttribute(pThis, name, ManualThunkULongText(value, defaultValue));
}
// Symbol: ?WriteInt@XRibbonInfoParser@CMFCRibbonInfo@@UEAAHAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@HH@Z
extern "C" int MS_ABI impl__WriteInt_XRibbonInfoParser_CMFCRibbonInfo__UEAAHAEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__HH_Z(
    void* pThis, const CString* name, int value, int defaultValue) {
    return RecordRibbonAttribute(pThis, name, ManualThunkIntText(value, defaultValue));
}
// Symbol: ?WriteSize@XRibbonInfoParser@CMFCRibbonInfo@@UEAAHAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@AEBVCSize@@1@Z
extern "C" int MS_ABI impl__WriteSize_XRibbonInfoParser_CMFCRibbonInfo__UEAAHAEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__AEBVCSize__1_Z(
    void* pThis, const CString* name, const CSize* value, const CSize* defaultValue) {
    return RecordRibbonAttribute(pThis, name, ManualThunkSizeText(value, defaultValue));
}
// Symbol: ?WriteUInt@XRibbonInfoParser@CMFCRibbonInfo@@UEAAHAEBV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@II@Z
extern "C" int MS_ABI impl__WriteUInt_XRibbonInfoParser_CMFCRibbonInfo__UEAAHAEBV__CStringT__WV__StrTraitMFC_DLL__WV__ChTraitsCRT__W_ATL_____ATL__II_Z(
    void* pThis, const CString* name, unsigned int value, unsigned int defaultValue) {
    return RecordRibbonAttribute(pThis, name, ManualThunkUIntText(value, defaultValue));
}
// Symbol: ??0XElementProgressBar@CMFCRibbonInfo@@QEAA@XZ
extern "C" void* MS_ABI impl___0XElementProgressBar_CMFCRibbonInfo__QEAA_XZ(void* pThis) {
    (void)pThis;
    // XElementProgressBar has no declared class body; zero-initialize the memory.
    // sizeof is unknown; caller provides adequate storage via the export ordinal.
    return pThis;
}
// Symbol: ??1XElementProgressBar@CMFCRibbonInfo@@UEAA@XZ
extern "C" void MS_ABI impl___1XElementProgressBar_CMFCRibbonInfo__UEAA_XZ(void* pThis) {
    (void)pThis;
    // No declared dtor body; nothing to clean up.
}
// Symbol: ?Read@XElementProgressBar@CMFCRibbonInfo@@UEAAHAEAVXRibbonInfoParser@2@@Z
extern "C" int MS_ABI impl__Read_XElementProgressBar_CMFCRibbonInfo__UEAAHAEAVXRibbonInfoParser_2__Z(
    void* pThis, void* /*XRibbonInfoParser&*/ parser) {
    (void)pThis; (void)parser;
    return 1;  // success
}
// Symbol: ??0CMFCRibbonBaseElement@@QEAA@XZ
// Constructor: CMFCRibbonBaseElement::CMFCRibbonBaseElement
extern "C" void* MS_ABI impl___0CMFCRibbonBaseElement__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonBaseElement();
}
// Symbol: ??0CMFCRibbonButton@@QEAA@IPEB_WHHH@Z
// Constructor: CMFCRibbonButton::CMFCRibbonButton
extern "C" void* MS_ABI impl___0CMFCRibbonButton__QEAA_IPEB_WHHH_Z(void* pThis, unsigned int p0, const wchar_t* p1, int p2, int p3, int p4) {
    return new(pThis) CMFCRibbonButton(p0, p1, p2, p3, p4);
}
// Symbol: ??0CMFCRibbonButton@@QEAA@XZ
// Constructor: CMFCRibbonButton::CMFCRibbonButton
extern "C" void* MS_ABI impl___0CMFCRibbonButton__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonButton();
}
// Symbol: ??0CMFCRibbonButtonsGroup@@QEAA@XZ
// Constructor: CMFCRibbonButtonsGroup::CMFCRibbonButtonsGroup
extern "C" void* MS_ABI impl___0CMFCRibbonButtonsGroup__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonButtonsGroup();
}
// Symbol: ??0CMFCRibbonCheckBox@@QEAA@IPEB_W@Z
// Constructor: CMFCRibbonCheckBox::CMFCRibbonCheckBox
extern "C" void* MS_ABI impl___0CMFCRibbonCheckBox__QEAA_IPEB_W_Z(void* pThis, unsigned int p0, const wchar_t* p1) {
    return new(pThis) CMFCRibbonCheckBox(p0, p1);
}
// Symbol: ??0CMFCRibbonCheckBox@@QEAA@XZ
// Constructor: CMFCRibbonCheckBox::CMFCRibbonCheckBox
extern "C" void* MS_ABI impl___0CMFCRibbonCheckBox__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonCheckBox();
}
// Symbol: ??0CMFCRibbonEdit@@IEAA@XZ
// Constructor: CMFCRibbonEdit::CMFCRibbonEdit
extern "C" void* MS_ABI impl___0CMFCRibbonEdit__IEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonEdit();
}
// Symbol: ??0CMFCRibbonEdit@@QEAA@IHPEB_WH@Z
// Constructor: CMFCRibbonEdit::CMFCRibbonEdit
extern "C" void* MS_ABI impl___0CMFCRibbonEdit__QEAA_IHPEB_WH_Z(void* pThis, unsigned int p0, int p1, const wchar_t* p2, int p3) {
    return new(pThis) CMFCRibbonEdit(p0, p1, p2, p3);
}
// Symbol: ??0CMFCRibbonGallery@@QEAA@IPEB_WHHIH@Z
// Constructor: CMFCRibbonGallery::CMFCRibbonGallery
extern "C" void* MS_ABI impl___0CMFCRibbonGallery__QEAA_IPEB_WHHIH_Z(void* pThis, unsigned int p0, const wchar_t* p1, int p2, int p3, unsigned int p4, int p5) {
    return new(pThis) CMFCRibbonGallery(p0, p1, p2, p3, p4, p5);
}
// Symbol: ??0CMFCRibbonGallery@@QEAA@XZ
// Constructor: CMFCRibbonGallery::CMFCRibbonGallery
extern "C" void* MS_ABI impl___0CMFCRibbonGallery__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonGallery();
}
// Symbol: ??0CMFCRibbonLabel@@IEAA@XZ
// Constructor: CMFCRibbonLabel::CMFCRibbonLabel
extern "C" void* MS_ABI impl___0CMFCRibbonLabel__IEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonLabel();
}
// Symbol: ??0CMFCRibbonLabel@@QEAA@PEB_WH@Z
// Constructor: CMFCRibbonLabel::CMFCRibbonLabel
extern "C" void* MS_ABI impl___0CMFCRibbonLabel__QEAA_PEB_WH_Z(void* pThis, const wchar_t* p0, int p1) {
    return new(pThis) CMFCRibbonLabel(p0, p1);
}
// Symbol: ??0CMFCRibbonMainPanel@@QEAA@XZ
// Constructor: CMFCRibbonMainPanel::CMFCRibbonMainPanel
extern "C" void* MS_ABI impl___0CMFCRibbonMainPanel__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonMainPanel();
}
// Symbol: ??0CMFCRibbonProgressBar@@QEAA@IHH@Z
// Constructor: CMFCRibbonProgressBar::CMFCRibbonProgressBar
extern "C" void* MS_ABI impl___0CMFCRibbonProgressBar__QEAA_IHH_Z(void* pThis, unsigned int p0, int p1, int p2) {
    return new(pThis) CMFCRibbonProgressBar(p0, p1, p2);
}
// Symbol: ??0CMFCRibbonProgressBar@@QEAA@XZ
// Constructor: CMFCRibbonProgressBar::CMFCRibbonProgressBar
extern "C" void* MS_ABI impl___0CMFCRibbonProgressBar__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonProgressBar();
}
// Symbol: ??0CMFCRibbonSeparator@@QEAA@H@Z
// Constructor: CMFCRibbonSeparator::CMFCRibbonSeparator
extern "C" void* MS_ABI impl___0CMFCRibbonSeparator__QEAA_H_Z(void* pThis, int p0) {
    return new(pThis) CMFCRibbonSeparator(p0);
}
// Symbol: ??0CMFCRibbonSlider@@QEAA@IH@Z
// Constructor: CMFCRibbonSlider::CMFCRibbonSlider
extern "C" void* MS_ABI impl___0CMFCRibbonSlider__QEAA_IH_Z(void* pThis, unsigned int p0, int p1) {
    return new(pThis) CMFCRibbonSlider(p0, p1);
}
// Symbol: ??0CMFCRibbonSlider@@QEAA@XZ
// Constructor: CMFCRibbonSlider::CMFCRibbonSlider
extern "C" void* MS_ABI impl___0CMFCRibbonSlider__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonSlider();
}
// Symbol: ??0CMFCRibbonStatusBar@@QEAA@XZ
// Constructor: CMFCRibbonStatusBar::CMFCRibbonStatusBar
extern "C" void* MS_ABI impl___0CMFCRibbonStatusBar__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonStatusBar();
}
// Symbol: ??0CMFCRibbonStatusBarPane@@QEAA@XZ
// Constructor: CMFCRibbonStatusBarPane::CMFCRibbonStatusBarPane
extern "C" void* MS_ABI impl___0CMFCRibbonStatusBarPane__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonStatusBarPane();
}
// Symbol: ??0CMFCRibbonTab@@QEAA@XZ
// Constructor: CMFCRibbonTab::CMFCRibbonTab
extern "C" void* MS_ABI impl___0CMFCRibbonTab__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCRibbonTab();
}
// Symbol: ??1CMFCRibbonBaseElement@@UEAA@XZ
// Destructor: CMFCRibbonBaseElement::~CMFCRibbonBaseElement
extern "C" void MS_ABI impl___1CMFCRibbonBaseElement__UEAA_XZ(void* pThis) {
    ((CMFCRibbonBaseElement*)pThis)->~CMFCRibbonBaseElement();
}
// Symbol: ??1CMFCRibbonButton@@UEAA@XZ
// Destructor: CMFCRibbonButton::~CMFCRibbonButton
extern "C" void MS_ABI impl___1CMFCRibbonButton__UEAA_XZ(void* pThis) {
    ((CMFCRibbonButton*)pThis)->~CMFCRibbonButton();
}
// Symbol: ??1CMFCRibbonButtonsGroup@@UEAA@XZ
// Destructor: CMFCRibbonButtonsGroup::~CMFCRibbonButtonsGroup
extern "C" void MS_ABI impl___1CMFCRibbonButtonsGroup__UEAA_XZ(void* pThis) {
    ((CMFCRibbonButtonsGroup*)pThis)->~CMFCRibbonButtonsGroup();
}
// Symbol: ??1CMFCRibbonCheckBox@@UEAA@XZ
// Destructor: CMFCRibbonCheckBox::~CMFCRibbonCheckBox
extern "C" void MS_ABI impl___1CMFCRibbonCheckBox__UEAA_XZ(void* pThis) {
    ((CMFCRibbonCheckBox*)pThis)->~CMFCRibbonCheckBox();
}
// Symbol: ??1CMFCRibbonEdit@@UEAA@XZ
// Destructor: CMFCRibbonEdit::~CMFCRibbonEdit
extern "C" void MS_ABI impl___1CMFCRibbonEdit__UEAA_XZ(void* pThis) {
    ((CMFCRibbonEdit*)pThis)->~CMFCRibbonEdit();
}
// Symbol: ??1CMFCRibbonGallery@@UEAA@XZ
// Destructor: CMFCRibbonGallery::~CMFCRibbonGallery
extern "C" void MS_ABI impl___1CMFCRibbonGallery__UEAA_XZ(void* pThis) {
    ((CMFCRibbonGallery*)pThis)->~CMFCRibbonGallery();
}
// Symbol: ??1CMFCRibbonLabel@@UEAA@XZ
// Destructor: CMFCRibbonLabel::~CMFCRibbonLabel
extern "C" void MS_ABI impl___1CMFCRibbonLabel__UEAA_XZ(void* pThis) {
    ((CMFCRibbonLabel*)pThis)->~CMFCRibbonLabel();
}
// Symbol: ??1CMFCRibbonMainPanel@@UEAA@XZ
// Destructor: CMFCRibbonMainPanel::~CMFCRibbonMainPanel
extern "C" void MS_ABI impl___1CMFCRibbonMainPanel__UEAA_XZ(void* pThis) {
    ((CMFCRibbonMainPanel*)pThis)->~CMFCRibbonMainPanel();
}
// Symbol: ??1CMFCRibbonProgressBar@@UEAA@XZ
// Destructor: CMFCRibbonProgressBar::~CMFCRibbonProgressBar
extern "C" void MS_ABI impl___1CMFCRibbonProgressBar__UEAA_XZ(void* pThis) {
    ((CMFCRibbonProgressBar*)pThis)->~CMFCRibbonProgressBar();
}
// Symbol: ??1CMFCRibbonSlider@@UEAA@XZ
// Destructor: CMFCRibbonSlider::~CMFCRibbonSlider
extern "C" void MS_ABI impl___1CMFCRibbonSlider__UEAA_XZ(void* pThis) {
    ((CMFCRibbonSlider*)pThis)->~CMFCRibbonSlider();
}
// Symbol: ??1CMFCRibbonStatusBar@@UEAA@XZ
// Destructor: CMFCRibbonStatusBar::~CMFCRibbonStatusBar
extern "C" void MS_ABI impl___1CMFCRibbonStatusBar__UEAA_XZ(void* pThis) {
    ((CMFCRibbonStatusBar*)pThis)->~CMFCRibbonStatusBar();
}
// Symbol: ??1CMFCRibbonStatusBarPane@@UEAA@XZ
// Destructor: CMFCRibbonStatusBarPane::~CMFCRibbonStatusBarPane
extern "C" void MS_ABI impl___1CMFCRibbonStatusBarPane__UEAA_XZ(void* pThis) {
    ((CMFCRibbonStatusBarPane*)pThis)->~CMFCRibbonStatusBarPane();
}
// Symbol: ?Create@CMFCRibbonBar@@QEAAHPEAVCWnd@@KI@Z
// CMFCRibbonBar::Create
extern "C" int MS_ABI impl__Create_CMFCRibbonBar__QEAAHPEAVCWnd__KI_Z(CMFCRibbonBar* pThis, CWnd* p0, unsigned long p1, unsigned int p2) {
    return (int)pThis->Create(p0, p1, p2);
}
// Symbol: ?SetID@CMFCRibbonBaseElement@@UEAAXI@Z
// CMFCRibbonBaseElement::SetID
extern "C" void MS_ABI impl__SetID_CMFCRibbonBaseElement__UEAAXI_Z(CMFCRibbonBaseElement* pThis, unsigned int p0) {
    pThis->SetID(p0);
}
// Symbol: ?SetText@CMFCRibbonBaseElement@@UEAAXPEB_W@Z
// CMFCRibbonBaseElement::SetText
extern "C" void MS_ABI impl__SetText_CMFCRibbonBaseElement__UEAAXPEB_W_Z(CMFCRibbonBaseElement* pThis, const wchar_t* p0) {
    pThis->SetText(p0);
}
