// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CMFCPropertyGridCtrl@@QEAA@XZ
// Constructor: CMFCPropertyGridCtrl::CMFCPropertyGridCtrl
extern "C" void* MS_ABI impl___0CMFCPropertyGridCtrl__QEAA_XZ(void* pThis) {
    return new(pThis) CMFCPropertyGridCtrl();
}
// Symbol: ??1CMFCPropertyGridCtrl@@UEAA@XZ
// Destructor: CMFCPropertyGridCtrl::~CMFCPropertyGridCtrl
extern "C" void MS_ABI impl___1CMFCPropertyGridCtrl__UEAA_XZ(void* pThis) {
    ((CMFCPropertyGridCtrl*)pThis)->~CMFCPropertyGridCtrl();
}
// Symbol: ??1CMFCPropertyGridProperty@@UEAA@XZ
// Destructor: CMFCPropertyGridProperty::~CMFCPropertyGridProperty
extern "C" void MS_ABI impl___1CMFCPropertyGridProperty__UEAA_XZ(void* pThis) {
    ((CMFCPropertyGridProperty*)pThis)->~CMFCPropertyGridProperty();
}
// Symbol: ?AddOption@CMFCPropertyGridProperty@@QEAAHPEB_WH@Z
// CMFCPropertyGridProperty::AddOption
extern "C" int MS_ABI impl__AddOption_CMFCPropertyGridProperty__QEAAHPEB_WH_Z(CMFCPropertyGridProperty* pThis, const wchar_t* p0, int p1) {
    return (int)pThis->AddOption(p0, p1);
}
// Symbol: ?AddProperty@CMFCPropertyGridCtrl@@QEAAHPEAVCMFCPropertyGridProperty@@HH@Z
// CMFCPropertyGridCtrl::AddProperty
extern "C" int MS_ABI impl__AddProperty_CMFCPropertyGridCtrl__QEAAHPEAVCMFCPropertyGridProperty__HH_Z(CMFCPropertyGridCtrl* pThis, CMFCPropertyGridProperty* p0, int p1, int p2) {
    return (int)pThis->AddProperty(p0, p1, p2);
}
// Symbol: ?AdjustLayout@CMFCPropertyGridCtrl@@UEAAXXZ
// CMFCPropertyGridCtrl::AdjustLayout
extern "C" void MS_ABI impl__AdjustLayout_CMFCPropertyGridCtrl__UEAAXXZ(CMFCPropertyGridCtrl* pThis) {
    pThis->AdjustLayout();
}
// Symbol: ?CompareProps@CMFCPropertyGridCtrl@@MEBAHPEBVCMFCPropertyGridProperty@@0@Z
// CMFCPropertyGridCtrl::CompareProps
extern "C" int MS_ABI impl__CompareProps_CMFCPropertyGridCtrl__MEBAHPEBVCMFCPropertyGridProperty__0_Z(const CMFCPropertyGridCtrl* pThis, const CMFCPropertyGridProperty* p0, const CMFCPropertyGridProperty* p1) {
    return (int)pThis->CompareProps(p0, p1);
}
// Symbol: ?Create@CMFCPropertyGridCtrl@@UEAAHKAEBUtagRECT@@PEAVCWnd@@I@Z
// CMFCPropertyGridCtrl::Create
extern "C" int MS_ABI impl__Create_CMFCPropertyGridCtrl__UEAAHKAEBUtagRECT__PEAVCWnd__I_Z(CMFCPropertyGridCtrl* pThis, unsigned long p0, const RECT* p1, CWnd* p2, unsigned int p3) {
    return (int)pThis->Create(p0, (*p1), p2, p3);
}
// Symbol: ?DeleteProperty@CMFCPropertyGridCtrl@@QEAAHAEAPEAVCMFCPropertyGridProperty@@HH@Z
// CMFCPropertyGridCtrl::DeleteProperty
extern "C" int MS_ABI impl__DeleteProperty_CMFCPropertyGridCtrl__QEAAHAEAPEAVCMFCPropertyGridProperty__HH_Z(CMFCPropertyGridCtrl* pThis, CMFCPropertyGridProperty** p0, int p1, int p2) {
    return (int)pThis->DeleteProperty((*p0), p1, p2);
}
// Symbol: ?Enable@CMFCPropertyGridProperty@@QEAAXH@Z
// CMFCPropertyGridProperty::Enable
extern "C" void MS_ABI impl__Enable_CMFCPropertyGridProperty__QEAAXH_Z(CMFCPropertyGridProperty* pThis, int p0) {
    pThis->Enable(p0);
}
// Symbol: ?Expand@CMFCPropertyGridProperty@@QEAAXH@Z
// CMFCPropertyGridProperty::Expand
extern "C" void MS_ABI impl__Expand_CMFCPropertyGridProperty__QEAAXH_Z(CMFCPropertyGridProperty* pThis, int p0) {
    pThis->Expand(p0);
}
// Symbol: ?ExpandAll@CMFCPropertyGridCtrl@@QEAAXH@Z
// CMFCPropertyGridCtrl::ExpandAll
extern "C" void MS_ABI impl__ExpandAll_CMFCPropertyGridCtrl__QEAAXH_Z(CMFCPropertyGridCtrl* pThis, int p0) {
    pThis->ExpandAll(p0);
}
// Symbol: ?ExpandDeep@CMFCPropertyGridProperty@@IEAAXH@Z
// CMFCPropertyGridProperty::ExpandDeep
extern "C" void MS_ABI impl__ExpandDeep_CMFCPropertyGridProperty__IEAAXH_Z(CMFCPropertyGridProperty* pThis, int p0) {
    pThis->ExpandDeep(p0);
}
// Symbol: ?FindItemByData@CMFCPropertyGridCtrl@@QEBAPEAVCMFCPropertyGridProperty@@_KH@Z
// CMFCPropertyGridCtrl::FindItemByData
extern "C" CMFCPropertyGridProperty* MS_ABI impl__FindItemByData_CMFCPropertyGridCtrl__QEBAPEAVCMFCPropertyGridProperty___KH_Z(const CMFCPropertyGridCtrl* pThis, unsigned __int64 p0, int p1) {
    return (CMFCPropertyGridProperty*)pThis->FindItemByData(p0, p1);
}
// Symbol: ?FindSubItemByData@CMFCPropertyGridProperty@@IEBAPEAV1@_K@Z
// CMFCPropertyGridProperty::FindSubItemByData
extern "C" void* MS_ABI impl__FindSubItemByData_CMFCPropertyGridProperty__IEBAPEAV1__K_Z(const CMFCPropertyGridProperty* pThis, unsigned __int64 p0) {
    return (void*)pThis->FindSubItemByData(p0);
}
// Symbol: ?GetExpandedSubItems@CMFCPropertyGridProperty@@QEBAHH@Z
// CMFCPropertyGridProperty::GetExpandedSubItems
extern "C" int MS_ABI impl__GetExpandedSubItems_CMFCPropertyGridProperty__QEBAHH_Z(const CMFCPropertyGridProperty* pThis, int p0) {
    return (int)pThis->GetExpandedSubItems(p0);
}
// Symbol: ?GetHierarchyLevel@CMFCPropertyGridProperty@@QEBAHXZ
// CMFCPropertyGridProperty::GetHierarchyLevel
extern "C" int MS_ABI impl__GetHierarchyLevel_CMFCPropertyGridProperty__QEBAHXZ(const CMFCPropertyGridProperty* pThis) {
    return (int)pThis->GetHierarchyLevel();
}
// Symbol: ?GetOption@CMFCPropertyGridProperty@@QEBAPEB_WH@Z
// CMFCPropertyGridProperty::GetOption
extern "C" const wchar_t* MS_ABI impl__GetOption_CMFCPropertyGridProperty__QEBAPEB_WH_Z(const CMFCPropertyGridProperty* pThis, int p0) {
    return (const wchar_t*)pThis->GetOption(p0);
}
// Symbol: ?GetOptionCount@CMFCPropertyGridProperty@@QEBAHXZ
// CMFCPropertyGridProperty::GetOptionCount
extern "C" int MS_ABI impl__GetOptionCount_CMFCPropertyGridProperty__QEBAHXZ(const CMFCPropertyGridProperty* pThis) {
    return (int)pThis->GetOptionCount();
}
// Symbol: ?GetProperty@CMFCPropertyGridCtrl@@QEBAPEAVCMFCPropertyGridProperty@@H@Z
// CMFCPropertyGridCtrl::GetProperty
extern "C" CMFCPropertyGridProperty* MS_ABI impl__GetProperty_CMFCPropertyGridCtrl__QEBAPEAVCMFCPropertyGridProperty__H_Z(const CMFCPropertyGridCtrl* pThis, int p0) {
    return (CMFCPropertyGridProperty*)pThis->GetProperty(p0);
}
// Symbol: ?GetSubItem@CMFCPropertyGridProperty@@QEBAPEAV1@H@Z
// CMFCPropertyGridProperty::GetSubItem
extern "C" void* MS_ABI impl__GetSubItem_CMFCPropertyGridProperty__QEBAPEAV1_H_Z(const CMFCPropertyGridProperty* pThis, int p0) {
    return (void*)pThis->GetSubItem(p0);
}
// Symbol: ?GetTotalItems@CMFCPropertyGridCtrl@@IEBAHH@Z
// CMFCPropertyGridCtrl::GetTotalItems
extern "C" int MS_ABI impl__GetTotalItems_CMFCPropertyGridCtrl__IEBAHH_Z(const CMFCPropertyGridCtrl* pThis, int p0) {
    return (int)pThis->GetTotalItems(p0);
}
// Symbol: ?IsParentExpanded@CMFCPropertyGridProperty@@QEBAHXZ
// CMFCPropertyGridProperty::IsParentExpanded
extern "C" int MS_ABI impl__IsParentExpanded_CMFCPropertyGridProperty__QEBAHXZ(const CMFCPropertyGridProperty* pThis) {
    return (int)pThis->IsParentExpanded();
}
// Symbol: ?IsSubItem@CMFCPropertyGridProperty@@IEBAHPEAV1@@Z
// CMFCPropertyGridProperty::IsSubItem
extern "C" int MS_ABI impl__IsSubItem_CMFCPropertyGridProperty__IEBAHPEAV1__Z(const CMFCPropertyGridProperty* pThis, void* p0) {
    return (int)pThis->IsSubItem(p0);
}
// Symbol: ?IsValueChanged@CMFCPropertyGridProperty@@MEBAHXZ
// CMFCPropertyGridProperty::IsValueChanged
extern "C" int MS_ABI impl__IsValueChanged_CMFCPropertyGridProperty__MEBAHXZ(const CMFCPropertyGridProperty* pThis) {
    return (int)pThis->IsValueChanged();
}
// Symbol: ?MarkModifiedProperties@CMFCPropertyGridCtrl@@QEAAXHH@Z
// CMFCPropertyGridCtrl::MarkModifiedProperties
extern "C" void MS_ABI impl__MarkModifiedProperties_CMFCPropertyGridCtrl__QEAAXHH_Z(CMFCPropertyGridCtrl* pThis, int p0, int p1) {
    pThis->MarkModifiedProperties(p0, p1);
}
// Symbol: ?OnCloseCombo@CMFCPropertyGridProperty@@UEAAXXZ
// CMFCPropertyGridProperty::OnCloseCombo
extern "C" void MS_ABI impl__OnCloseCombo_CMFCPropertyGridProperty__UEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->OnCloseCombo();
}
// Symbol: ?OnEndEdit@CMFCPropertyGridProperty@@UEAAHXZ
// CMFCPropertyGridProperty::OnEndEdit
extern "C" int MS_ABI impl__OnEndEdit_CMFCPropertyGridProperty__UEAAHXZ(CMFCPropertyGridProperty* pThis) {
    return (int)pThis->OnEndEdit();
}
// Symbol: ?OnRotateListValue@CMFCPropertyGridProperty@@MEAAHH@Z
// CMFCPropertyGridProperty::OnRotateListValue
extern "C" int MS_ABI impl__OnRotateListValue_CMFCPropertyGridProperty__MEAAHH_Z(CMFCPropertyGridProperty* pThis, int p0) {
    return (int)pThis->OnRotateListValue(p0);
}
// Symbol: ?OnSelectCombo@CMFCPropertyGridProperty@@UEAAXXZ
// CMFCPropertyGridProperty::OnSelectCombo
extern "C" void MS_ABI impl__OnSelectCombo_CMFCPropertyGridProperty__UEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->OnSelectCombo();
}
// Symbol: ?OnUpdateValue@CMFCPropertyGridProperty@@UEAAHXZ
// CMFCPropertyGridProperty::OnUpdateValue
extern "C" int MS_ABI impl__OnUpdateValue_CMFCPropertyGridProperty__UEAAHXZ(CMFCPropertyGridProperty* pThis) {
    return (int)pThis->OnUpdateValue();
}
// Symbol: ?Redraw@CMFCPropertyGridProperty@@QEAAXXZ
// CMFCPropertyGridProperty::Redraw
extern "C" void MS_ABI impl__Redraw_CMFCPropertyGridProperty__QEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->Redraw();
}
// Symbol: ?RemoveAll@CMFCPropertyGridCtrl@@QEAAXXZ
// CMFCPropertyGridCtrl::RemoveAll
extern "C" void MS_ABI impl__RemoveAll_CMFCPropertyGridCtrl__QEAAXXZ(CMFCPropertyGridCtrl* pThis) {
    pThis->RemoveAll();
}
// Symbol: ?RemoveAllOptions@CMFCPropertyGridProperty@@QEAAXXZ
// CMFCPropertyGridProperty::RemoveAllOptions
extern "C" void MS_ABI impl__RemoveAllOptions_CMFCPropertyGridProperty__QEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->RemoveAllOptions();
}
// Symbol: ?RemoveSubItem@CMFCPropertyGridProperty@@QEAAHAEAPEAV1@H@Z
// CMFCPropertyGridProperty::RemoveSubItem
extern "C" int MS_ABI impl__RemoveSubItem_CMFCPropertyGridProperty__QEAAHAEAPEAV1_H_Z(CMFCPropertyGridProperty* pThis, void** p0, int p1) {
    return (int)pThis->RemoveSubItem((*p0), p1);
}
// Symbol: ?ResetOriginalValue@CMFCPropertyGridProperty@@UEAAXXZ
// CMFCPropertyGridProperty::ResetOriginalValue
extern "C" void MS_ABI impl__ResetOriginalValue_CMFCPropertyGridProperty__UEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->ResetOriginalValue();
}
// Symbol: ?ResetOriginalValues@CMFCPropertyGridCtrl@@QEAAXH@Z
// CMFCPropertyGridCtrl::ResetOriginalValues
extern "C" void MS_ABI impl__ResetOriginalValues_CMFCPropertyGridCtrl__QEAAXH_Z(CMFCPropertyGridCtrl* pThis, int p0) {
    pThis->ResetOriginalValues(p0);
}
// Symbol: ?SetAlphabeticMode@CMFCPropertyGridCtrl@@QEAAXH@Z
// CMFCPropertyGridCtrl::SetAlphabeticMode
extern "C" void MS_ABI impl__SetAlphabeticMode_CMFCPropertyGridCtrl__QEAAXH_Z(CMFCPropertyGridCtrl* pThis, int p0) {
    pThis->SetAlphabeticMode(p0);
}
// Symbol: ?SetBoolLabels@CMFCPropertyGridCtrl@@QEAAXPEB_W0@Z
// CMFCPropertyGridCtrl::SetBoolLabels
extern "C" void MS_ABI impl__SetBoolLabels_CMFCPropertyGridCtrl__QEAAXPEB_W0_Z(CMFCPropertyGridCtrl* pThis, const wchar_t* p0, const wchar_t* p1) {
    pThis->SetBoolLabels(p0, p1);
}
// Symbol: ?SetCurSel@CMFCPropertyGridCtrl@@QEAAXPEAVCMFCPropertyGridProperty@@H@Z
// CMFCPropertyGridCtrl::SetCurSel
extern "C" void MS_ABI impl__SetCurSel_CMFCPropertyGridCtrl__QEAAXPEAVCMFCPropertyGridProperty__H_Z(CMFCPropertyGridCtrl* pThis, CMFCPropertyGridProperty* p0, int p1) {
    pThis->SetCurSel(p0, p1);
}
// Symbol: ?SetDescriptionRows@CMFCPropertyGridCtrl@@QEAAXH@Z
// CMFCPropertyGridCtrl::SetDescriptionRows
extern "C" void MS_ABI impl__SetDescriptionRows_CMFCPropertyGridCtrl__QEAAXH_Z(CMFCPropertyGridCtrl* pThis, int p0) {
    pThis->SetDescriptionRows(p0);
}
// Symbol: ?SetGroupNameFullWidth@CMFCPropertyGridCtrl@@QEAAXHH@Z
// CMFCPropertyGridCtrl::SetGroupNameFullWidth
extern "C" void MS_ABI impl__SetGroupNameFullWidth_CMFCPropertyGridCtrl__QEAAXHH_Z(CMFCPropertyGridCtrl* pThis, int p0, int p1) {
    pThis->SetGroupNameFullWidth(p0, p1);
}
// Symbol: ?SetListDelimiter@CMFCPropertyGridCtrl@@QEAAX_W@Z
// CMFCPropertyGridCtrl::SetListDelimiter
extern "C" void MS_ABI impl__SetListDelimiter_CMFCPropertyGridCtrl__QEAAX_W_Z(CMFCPropertyGridCtrl* pThis, wchar_t p0) {
    pThis->SetListDelimiter(p0);
}
// Symbol: ?SetModifiedFlag@CMFCPropertyGridProperty@@IEAAXXZ
// CMFCPropertyGridProperty::SetModifiedFlag
extern "C" void MS_ABI impl__SetModifiedFlag_CMFCPropertyGridProperty__IEAAXXZ(CMFCPropertyGridProperty* pThis) {
    pThis->SetModifiedFlag();
}
// Symbol: ?SetName@CMFCPropertyGridProperty@@QEAAXPEB_WH@Z
// CMFCPropertyGridProperty::SetName
extern "C" void MS_ABI impl__SetName_CMFCPropertyGridProperty__QEAAXPEB_WH_Z(CMFCPropertyGridProperty* pThis, const wchar_t* p0, int p1) {
    pThis->SetName(p0, p1);
}
// Symbol: ?SetOwnerList@CMFCPropertyGridProperty@@IEAAXPEAVCMFCPropertyGridCtrl@@@Z
// CMFCPropertyGridProperty::SetOwnerList
extern "C" void MS_ABI impl__SetOwnerList_CMFCPropertyGridProperty__IEAAXPEAVCMFCPropertyGridCtrl___Z(CMFCPropertyGridProperty* pThis, CMFCPropertyGridCtrl* p0) {
    pThis->SetOwnerList(p0);
}
// Symbol: ?SetValue@CMFCPropertyGridProperty@@UEAAXAEBVCOleVariant@@@Z
// CMFCPropertyGridProperty::SetValue
extern "C" void MS_ABI impl__SetValue_CMFCPropertyGridProperty__UEAAXAEBVCOleVariant___Z(CMFCPropertyGridProperty* pThis, const COleVariant* p0) {
    pThis->SetValue((*p0));
}
// Symbol: ?SetOriginalValue@CMFCPropertyGridProperty@@UEAAXAEBVCOleVariant@@@Z
// CMFCPropertyGridProperty::SetOriginalValue
extern "C" void MS_ABI impl__SetOriginalValue_CMFCPropertyGridProperty__UEAAXAEBVCOleVariant___Z(CMFCPropertyGridProperty* pThis, const COleVariant* p0) {
    pThis->SetOriginalValue((*p0));
}
