// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ?ActivateTopParent@CWnd@@QEAAXXZ
// CWnd::ActivateTopParent
extern "C" void MS_ABI impl__ActivateTopParent_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->ActivateTopParent();
}
// Symbol: ?Attach@CWnd@@QEAAHPEAUHWND__@@@Z
// CWnd::Attach
extern "C" int MS_ABI impl__Attach_CWnd__QEAAHPEAUHWND_____Z(CWnd* pThis, HWND__* p0) {
    return (int)pThis->Attach(p0);
}
// Symbol: ?AttachControlSite@CWnd@@IEAAXPEAVCHandleMap@@@Z
// CWnd::AttachControlSite
extern "C" void MS_ABI impl__AttachControlSite_CWnd__IEAAXPEAVCHandleMap___Z(CWnd* pThis, CHandleMap* p0) {
    pThis->AttachControlSite(p0);
}
// Symbol: ?BindDefaultProperty@CWnd@@QEAAXJGPEB_WPEAV1@@Z
// CWnd::BindDefaultProperty
extern "C" void MS_ABI impl__BindDefaultProperty_CWnd__QEAAXJGPEB_WPEAV1__Z(CWnd* pThis, long p0, unsigned short p1, const wchar_t* p2, void* p3) {
    pThis->BindDefaultProperty(p0, p1, p2, p3);
}
// Symbol: ?BindProperty@CWnd@@QEAAXJPEAV1@@Z
// CWnd::BindProperty
extern "C" void MS_ABI impl__BindProperty_CWnd__QEAAXJPEAV1__Z(CWnd* pThis, long p0, void* p1) {
    pThis->BindProperty(p0, p1);
}
// Symbol: ?CancelToolTips@CWnd@@SAXH@Z
// Static: CWnd::CancelToolTips
extern "C" void MS_ABI impl__CancelToolTips_CWnd__SAXH_Z(int p0) {
    CWnd::CancelToolTips(p0);
}
// Symbol: ?CenterWindow@CWnd@@QEAAXPEAV1@@Z
// CWnd::CenterWindow
extern "C" void MS_ABI impl__CenterWindow_CWnd__QEAAXPEAV1__Z(CWnd* pThis, void* p0) {
    pThis->CenterWindow(p0);
}
// Symbol: ?CheckDlgButton@CWnd@@QEAAXHI@Z
// CWnd::CheckDlgButton
extern "C" void MS_ABI impl__CheckDlgButton_CWnd__QEAAXHI_Z(CWnd* pThis, int p0, unsigned int p1) {
    pThis->CheckDlgButton(p0, p1);
}
// Symbol: ?CheckRadioButton@CWnd@@QEAAXHHH@Z
// CWnd::CheckRadioButton
extern "C" void MS_ABI impl__CheckRadioButton_CWnd__QEAAXHHH_Z(CWnd* pThis, int p0, int p1, int p2) {
    pThis->CheckRadioButton(p0, p1, p2);
}
// Symbol: ?ClientToScreen@CWnd@@QEBAXPEAUtagRECT@@@Z
// CWnd::ClientToScreen
extern "C" void MS_ABI impl__ClientToScreen_CWnd__QEBAXPEAUtagRECT___Z(const CWnd* pThis, RECT* p0) {
    pThis->ClientToScreen(p0);
}
// Symbol: ?CreateControlContainer@CWnd@@MEAAHPEAPEAVCOleControlContainer@@@Z
// CWnd::CreateControlContainer
extern "C" int MS_ABI impl__CreateControlContainer_CWnd__MEAAHPEAPEAVCOleControlContainer___Z(CWnd* pThis, COleControlContainer** p0) {
    return (int)pThis->CreateControlContainer(p0);
}
// Symbol: ?CreateDlg@CWnd@@IEAAHPEB_WPEAV1@@Z
// CWnd::CreateDlg
extern "C" int MS_ABI impl__CreateDlg_CWnd__IEAAHPEB_WPEAV1__Z(CWnd* pThis, const wchar_t* p0, void* p1) {
    return (int)pThis->CreateDlg(p0, p1);
}
// Symbol: ?CreateObject@CWnd@@SAPEAVCObject@@XZ
// Static: CWnd::CreateObject
extern "C" CObject* MS_ABI impl__CreateObject_CWnd__SAPEAVCObject__XZ() {
    return (CObject*)CWnd::CreateObject();
}
// Symbol: ?Default@CWnd@@IEAA_JXZ
// CWnd::Default
extern "C" __int64 MS_ABI impl__Default_CWnd__IEAA_JXZ(CWnd* pThis) {
    return (__int64)pThis->Default();
}
// Symbol: ?DeleteTempMap@CWnd@@SAXXZ
// Static: CWnd::DeleteTempMap
extern "C" void MS_ABI impl__DeleteTempMap_CWnd__SAXXZ() {
    CWnd::DeleteTempMap();
}
// Symbol: ?Detach@CWnd@@QEAAPEAUHWND__@@XZ
// CWnd::Detach
extern "C" HWND__* MS_ABI impl__Detach_CWnd__QEAAPEAUHWND____XZ(CWnd* pThis) {
    return (HWND__*)pThis->Detach();
}
// Symbol: ?DoD2DPaint@CWnd@@IEAAHXZ
// CWnd::DoD2DPaint
extern "C" int MS_ABI impl__DoD2DPaint_CWnd__IEAAHXZ(CWnd* pThis) {
    return (int)pThis->DoD2DPaint();
}
// Symbol: ?DrawItem@CMenu@@UEAAXPEAUtagDRAWITEMSTRUCT@@@Z
// CMenu::DrawItem
extern "C" void MS_ABI impl__DrawItem_CMenu__UEAAXPEAUtagDRAWITEMSTRUCT___Z(CMenu* pThis, DRAWITEMSTRUCT* p0) {
    pThis->DrawItem(p0);
}
// Symbol: ?EnableScrollBarCtrl@CWnd@@QEAAXHH@Z
// CWnd::EnableScrollBarCtrl
extern "C" void MS_ABI impl__EnableScrollBarCtrl_CWnd__QEAAXHH_Z(CWnd* pThis, int p0, int p1) {
    pThis->EnableScrollBarCtrl(p0, p1);
}
// Symbol: ?EnableToolTips@CWnd@@QEAAHH@Z
// CWnd::EnableToolTips
extern "C" int MS_ABI impl__EnableToolTips_CWnd__QEAAHH_Z(CWnd* pThis, int p0) {
    return (int)pThis->EnableToolTips(p0);
}
// Symbol: ?EnableTrackingToolTips@CWnd@@QEAAHH@Z
// CWnd::EnableTrackingToolTips
extern "C" int MS_ABI impl__EnableTrackingToolTips_CWnd__QEAAHH_Z(CWnd* pThis, int p0) {
    return (int)pThis->EnableTrackingToolTips(p0);
}
// Symbol: ?ExecuteDlgInit@CWnd@@QEAAHPEAX@Z
// CWnd::ExecuteDlgInit
extern "C" int MS_ABI impl__ExecuteDlgInit_CWnd__QEAAHPEAX_Z(CWnd* pThis, void* p0) {
    return (int)pThis->ExecuteDlgInit(p0);
}
// Symbol: ?ExecuteDlgInit@CWnd@@QEAAHPEB_W@Z
// CWnd::ExecuteDlgInit
extern "C" int MS_ABI impl__ExecuteDlgInit_CWnd__QEAAHPEB_W_Z(CWnd* pThis, const wchar_t* p0) {
    return (int)pThis->ExecuteDlgInit(p0);
}
// Symbol: ?FilterToolTipMessage@CWnd@@QEAAXPEAUtagMSG@@@Z
// CWnd::FilterToolTipMessage
extern "C" void MS_ABI impl__FilterToolTipMessage_CWnd__QEAAXPEAUtagMSG___Z(CWnd* pThis, MSG* p0) {
    pThis->FilterToolTipMessage(p0);
}
// Symbol: ?FindSiteOrWnd@CWnd@@QEBAPEAU__POSITION@@PEBUCOleControlSiteOrWnd@@@Z
// CWnd::FindSiteOrWnd
extern "C" void* MS_ABI impl__FindSiteOrWnd_CWnd__QEBAPEAU__POSITION__PEBUCOleControlSiteOrWnd___Z(const CWnd* pThis, const COleControlSiteOrWnd* p0) {
    return (void*)pThis->FindSiteOrWnd(p0);
}
// Symbol: ?FindSiteOrWndWithFocus@CWnd@@QEBAPEAU__POSITION@@XZ
// CWnd::FindSiteOrWndWithFocus
extern "C" void* MS_ABI impl__FindSiteOrWndWithFocus_CWnd__QEBAPEAU__POSITION__XZ(const CWnd* pThis) {
    return (void*)pThis->FindSiteOrWndWithFocus();
}
// Symbol: ?GetAccessibilityHitTest@CWnd@@QEAAJJJPEAUtagVARIANT@@@Z
// CWnd::GetAccessibilityHitTest
extern "C" long MS_ABI impl__GetAccessibilityHitTest_CWnd__QEAAJJJPEAUtagVARIANT___Z(CWnd* pThis, long p0, long p1, VARIANT* p2) {
    return (long)pThis->GetAccessibilityHitTest(p0, p1, p2);
}
// Symbol: ?GetAccessibilityLocation@CWnd@@QEAAJUtagVARIANT@@PEAJ111@Z
// CWnd::GetAccessibilityLocation
extern "C" long MS_ABI impl__GetAccessibilityLocation_CWnd__QEAAJUtagVARIANT__PEAJ111_Z(CWnd* pThis, VARIANT p0, long* p1, long* p2, long* p3, long* p4) {
    return (long)pThis->GetAccessibilityLocation(p0, p1, p2, p3, p4);
}
// Symbol: ?GetAccessibleChild@CWnd@@QEAAJUtagVARIANT@@PEAPEAUIDispatch@@@Z
// CWnd::GetAccessibleChild
extern "C" long MS_ABI impl__GetAccessibleChild_CWnd__QEAAJUtagVARIANT__PEAPEAUIDispatch___Z(CWnd* pThis, VARIANT p0, IDispatch** p1) {
    return (long)pThis->GetAccessibleChild(p0, p1);
}
// Symbol: ?GetAccessibleChildCount@CWnd@@QEAAJXZ
// CWnd::GetAccessibleChildCount
extern "C" long MS_ABI impl__GetAccessibleChildCount_CWnd__QEAAJXZ(CWnd* pThis) {
    return (long)pThis->GetAccessibleChildCount();
}
// Symbol: ?GetAccessibleName@CWnd@@QEAAJUtagVARIANT@@PEAPEA_W@Z
// CWnd::GetAccessibleName
extern "C" long MS_ABI impl__GetAccessibleName_CWnd__QEAAJUtagVARIANT__PEAPEA_W_Z(CWnd* pThis, VARIANT p0, wchar_t** p1) {
    return (long)pThis->GetAccessibleName(p0, p1);
}
// Symbol: ?GetCheckedRadioButton@CWnd@@QEBAHHH@Z
// CWnd::GetCheckedRadioButton
extern "C" int MS_ABI impl__GetCheckedRadioButton_CWnd__QEBAHHH_Z(const CWnd* pThis, int p0, int p1) {
    return (int)pThis->GetCheckedRadioButton(p0, p1);
}
// Symbol: ?GetControlContainer@CWnd@@QEAAPEAVCOleControlContainer@@XZ
// CWnd::GetControlContainer
extern "C" COleControlContainer* MS_ABI impl__GetControlContainer_CWnd__QEAAPEAVCOleControlContainer__XZ(CWnd* pThis) {
    return (COleControlContainer*)pThis->GetControlContainer();
}
// Symbol: ?GetControlUnknown@CWnd@@QEAAPEAUIUnknown@@XZ
// CWnd::GetControlUnknown
extern "C" IUnknown* MS_ABI impl__GetControlUnknown_CWnd__QEAAPEAUIUnknown__XZ(CWnd* pThis) {
    return (IUnknown*)pThis->GetControlUnknown();
}
// Symbol: ?GetCurrentMessage@CWnd@@KAPEBUtagMSG@@XZ
// Static: CWnd::GetCurrentMessage
extern "C" const MSG* MS_ABI impl__GetCurrentMessage_CWnd__KAPEBUtagMSG__XZ() {
    return (const MSG*)CWnd::GetCurrentMessage();
}
// Symbol: ?GetDlgCtrlID@CWnd@@QEBAHXZ
// CWnd::GetDlgCtrlID
extern "C" int MS_ABI impl__GetDlgCtrlID_CWnd__QEBAHXZ(const CWnd* pThis) {
    return (int)pThis->GetDlgCtrlID();
}
// Symbol: ?GetDlgItemInt@CWnd@@QEBAIHPEAHH@Z
// CWnd::GetDlgItemInt
extern "C" unsigned int MS_ABI impl__GetDlgItemInt_CWnd__QEBAIHPEAHH_Z(const CWnd* pThis, int p0, int* p1, int p2) {
    return (unsigned int)pThis->GetDlgItemInt(p0, p1, p2);
}
// Symbol: ?GetDlgItemTextW@CWnd@@QEBAHHPEA_WH@Z
// CWnd::GetDlgItemTextW
extern "C" int MS_ABI impl__GetDlgItemTextW_CWnd__QEBAHHPEA_WH_Z(const CWnd* pThis, int p0, wchar_t* p1, int p2) {
    return (int)pThis->GetDlgItemTextW(p0, p1, p2);
}
// Symbol: ?GetDSCCursor@CWnd@@QEAAPEAUIUnknown@@XZ
// CWnd::GetDSCCursor
extern "C" IUnknown* MS_ABI impl__GetDSCCursor_CWnd__QEAAPEAUIUnknown__XZ(CWnd* pThis) {
    return (IUnknown*)pThis->GetDSCCursor();
}
// Symbol: ?GetExStyle@CWnd@@QEBAKXZ
// CWnd::GetExStyle
extern "C" unsigned long MS_ABI impl__GetExStyle_CWnd__QEBAKXZ(const CWnd* pThis) {
    return (unsigned long)pThis->GetExStyle();
}
// Symbol: ?GetGestureConfig@CWnd@@QEAAHPEAVCGestureConfig@@@Z
// CWnd::GetGestureConfig
extern "C" int MS_ABI impl__GetGestureConfig_CWnd__QEAAHPEAVCGestureConfig___Z(CWnd* pThis, CGestureConfig* p0) {
    return (int)pThis->GetGestureConfig(p0);
}
// Symbol: ?GetGestureStatus@CWnd@@MEAAKVCPoint@@@Z
// CWnd::GetGestureStatus
extern "C" unsigned long MS_ABI impl__GetGestureStatus_CWnd__MEAAKVCPoint___Z(CWnd* pThis, CPoint p0) {
    return (unsigned long)pThis->GetGestureStatus(p0);
}
// Symbol: ?GetInterfaceMap@CWnd@@MEBAPEBUAFX_INTERFACEMAP@@XZ
// CWnd::GetInterfaceMap
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetInterfaceMap_CWnd__MEBAPEBUAFX_INTERFACEMAP__XZ(const CWnd* pThis) {
    return (const AFX_INTERFACEMAP*)pThis->GetInterfaceMap();
}
// Symbol: ?GetNextDlgGroupItem@CWnd@@QEBAPEAUCOleControlSiteOrWnd@@PEAU2@@Z
// CWnd::GetNextDlgGroupItem
extern "C" COleControlSiteOrWnd* MS_ABI impl__GetNextDlgGroupItem_CWnd__QEBAPEAUCOleControlSiteOrWnd__PEAU2__Z(const CWnd* pThis, void* p0) {
    return (COleControlSiteOrWnd*)pThis->GetNextDlgGroupItem(p0);
}
// Symbol: ?GetNextDlgTabItem@CWnd@@QEBAPEAUCOleControlSiteOrWnd@@PEAU2@H@Z
// CWnd::GetNextDlgTabItem
extern "C" COleControlSiteOrWnd* MS_ABI impl__GetNextDlgTabItem_CWnd__QEBAPEAUCOleControlSiteOrWnd__PEAU2_H_Z(const CWnd* pThis, void* p0, int p1) {
    return (COleControlSiteOrWnd*)pThis->GetNextDlgTabItem(p0, p1);
}
// Symbol: ?GetOccDialogInfo@CWnd@@MEAAPEAU_AFX_OCC_DIALOG_INFO@@XZ
// CWnd::GetOccDialogInfo
extern "C" _AFX_OCC_DIALOG_INFO* MS_ABI impl__GetOccDialogInfo_CWnd__MEAAPEAU_AFX_OCC_DIALOG_INFO__XZ(CWnd* pThis) {
    return (_AFX_OCC_DIALOG_INFO*)pThis->GetOccDialogInfo();
}
// Symbol: ?GetOleControlSite@CWnd@@QEBAPEAVCOleControlSite@@I@Z
// CWnd::GetOleControlSite
extern "C" COleControlSite* MS_ABI impl__GetOleControlSite_CWnd__QEBAPEAVCOleControlSite__I_Z(const CWnd* pThis, unsigned int p0) {
    return (COleControlSite*)pThis->GetOleControlSite(p0);
}
// Symbol: ?GetParentFrame@CWnd@@QEBAPEAVCFrameWnd@@XZ
// CWnd::GetParentFrame
extern "C" CFrameWnd* MS_ABI impl__GetParentFrame_CWnd__QEBAPEAVCFrameWnd__XZ(const CWnd* pThis) {
    return (CFrameWnd*)pThis->GetParentFrame();
}
// Symbol: ?GetParentOwner@CWnd@@QEBAPEAV1@XZ
// CWnd::GetParentOwner
extern "C" void* MS_ABI impl__GetParentOwner_CWnd__QEBAPEAV1_XZ(const CWnd* pThis) {
    return (void*)pThis->GetParentOwner();
}
// Symbol: ?GetPrevDlgGroupItem@CWnd@@QEBAPEAUCOleControlSiteOrWnd@@PEAU2@@Z
// CWnd::GetPrevDlgGroupItem
extern "C" COleControlSiteOrWnd* MS_ABI impl__GetPrevDlgGroupItem_CWnd__QEBAPEAUCOleControlSiteOrWnd__PEAU2__Z(const CWnd* pThis, void* p0) {
    return (COleControlSiteOrWnd*)pThis->GetPrevDlgGroupItem(p0);
}
// Symbol: ?GetProperty@CWnd@@QEBAXJGPEAX@Z
// CWnd::GetProperty
extern "C" void MS_ABI impl__GetProperty_CWnd__QEBAXJGPEAX_Z(const CWnd* pThis, long p0, unsigned short p1, void* p2) {
    pThis->GetProperty(p0, p1, p2);
}
// Symbol: ?GetRenderTarget@CWnd@@QEAAPEAVCHwndRenderTarget@@XZ
// CWnd::GetRenderTarget
extern "C" CHwndRenderTarget* MS_ABI impl__GetRenderTarget_CWnd__QEAAPEAVCHwndRenderTarget__XZ(CWnd* pThis) {
    return (CHwndRenderTarget*)pThis->GetRenderTarget();
}
// Symbol: ?GetStyle@CWnd@@QEBAKXZ
// CWnd::GetStyle
extern "C" unsigned long MS_ABI impl__GetStyle_CWnd__QEBAKXZ(const CWnd* pThis) {
    return (unsigned long)pThis->GetStyle();
}
// Symbol: ?GetThisInterfaceMap@CWnd@@KAPEBUAFX_INTERFACEMAP@@XZ
// Static: CWnd::GetThisInterfaceMap
extern "C" const AFX_INTERFACEMAP* MS_ABI impl__GetThisInterfaceMap_CWnd__KAPEBUAFX_INTERFACEMAP__XZ() {
    return (const AFX_INTERFACEMAP*)CWnd::GetThisInterfaceMap();
}
// Symbol: ?GetTopLevelFrame@CWnd@@QEBAPEAVCFrameWnd@@XZ
// CWnd::GetTopLevelFrame
extern "C" CFrameWnd* MS_ABI impl__GetTopLevelFrame_CWnd__QEBAPEAVCFrameWnd__XZ(const CWnd* pThis) {
    return (CFrameWnd*)pThis->GetTopLevelFrame();
}
// Symbol: ?GetTopLevelOwner@CWnd@@QEBAPEAV1@XZ
// CWnd::GetTopLevelOwner
extern "C" void* MS_ABI impl__GetTopLevelOwner_CWnd__QEBAPEAV1_XZ(const CWnd* pThis) {
    return (void*)pThis->GetTopLevelOwner();
}
// Symbol: ?GetTopLevelParent@CWnd@@QEBAPEAV1@XZ
// CWnd::GetTopLevelParent
extern "C" void* MS_ABI impl__GetTopLevelParent_CWnd__QEBAPEAV1_XZ(const CWnd* pThis) {
    return (void*)pThis->GetTopLevelParent();
}
// Symbol: ?GetWindowedChildCount@CWnd@@QEAAJXZ
// CWnd::GetWindowedChildCount
extern "C" long MS_ABI impl__GetWindowedChildCount_CWnd__QEAAJXZ(CWnd* pThis) {
    return (long)pThis->GetWindowedChildCount();
}
// Symbol: ?GetWindowLessChildCount@CWnd@@QEAAJXZ
// CWnd::GetWindowLessChildCount
extern "C" long MS_ABI impl__GetWindowLessChildCount_CWnd__QEAAJXZ(CWnd* pThis) {
    return (long)pThis->GetWindowLessChildCount();
}
// Symbol: ?GetWindowPlacement@CWnd@@QEBAHPEAUtagWINDOWPLACEMENT@@@Z
// CWnd::GetWindowPlacement
extern "C" int MS_ABI impl__GetWindowPlacement_CWnd__QEBAHPEAUtagWINDOWPLACEMENT___Z(const CWnd* pThis, WINDOWPLACEMENT* p0) {
    return (int)pThis->GetWindowPlacement(p0);
}
// Symbol: ?GrayCtlColor@CWnd@@SAHPEAUHDC__@@PEAUHWND__@@IPEAUHBRUSH__@@K@Z
// Static: CWnd::GrayCtlColor
extern "C" int MS_ABI impl__GrayCtlColor_CWnd__SAHPEAUHDC____PEAUHWND____IPEAUHBRUSH____K_Z(HDC__* p0, HWND__* p1, unsigned int p2, HBRUSH__* p3, unsigned long p4) {
    return (int)CWnd::GrayCtlColor(p0, p1, p2, p3, p4);
}
// Symbol: ?HandleFloatingSysCommand@CWnd@@QEAAHI_J@Z
// CWnd::HandleFloatingSysCommand
extern "C" int MS_ABI impl__HandleFloatingSysCommand_CWnd__QEAAHI_J_Z(CWnd* pThis, unsigned int p0, __int64 p1) {
    return (int)pThis->HandleFloatingSysCommand(p0, p1);
}
// Symbol: ?InitControlContainer@CWnd@@IEAAHH@Z
// CWnd::InitControlContainer
extern "C" int MS_ABI impl__InitControlContainer_CWnd__IEAAHH_Z(CWnd* pThis, int p0) {
    return (int)pThis->InitControlContainer(p0);
}
// Symbol: ?IsD2DSupportEnabled@CWnd@@QEAAHXZ
// CWnd::IsD2DSupportEnabled
extern "C" int MS_ABI impl__IsD2DSupportEnabled_CWnd__QEAAHXZ(CWnd* pThis) {
    return (int)pThis->IsD2DSupportEnabled();
}
// Symbol: ?IsDlgButtonChecked@CWnd@@QEBAIH@Z
// CWnd::IsDlgButtonChecked
extern "C" unsigned int MS_ABI impl__IsDlgButtonChecked_CWnd__QEBAIH_Z(const CWnd* pThis, int p0) {
    return (unsigned int)pThis->IsDlgButtonChecked(p0);
}
// Symbol: ?IsTopParentActive@CWnd@@QEBAHXZ
// CWnd::IsTopParentActive
extern "C" int MS_ABI impl__IsTopParentActive_CWnd__QEBAHXZ(const CWnd* pThis) {
    return (int)pThis->IsTopParentActive();
}
// Symbol: ?IsTouchWindow@CWnd@@QEBAHXZ
// CWnd::IsTouchWindow
extern "C" int MS_ABI impl__IsTouchWindow_CWnd__QEBAHXZ(const CWnd* pThis) {
    return (int)pThis->IsTouchWindow();
}
// Symbol: ?MeasureItem@CMenu@@UEAAXPEAUtagMEASUREITEMSTRUCT@@@Z
// CMenu::MeasureItem
extern "C" void MS_ABI impl__MeasureItem_CMenu__UEAAXPEAUtagMEASUREITEMSTRUCT___Z(CMenu* pThis, MEASUREITEMSTRUCT* p0) {
    pThis->MeasureItem(p0);
}
// Symbol: ?MessageBoxW@CWnd@@QEAAHPEB_W0I@Z
// CWnd::MessageBoxW
extern "C" int MS_ABI impl__MessageBoxW_CWnd__QEAAHPEB_W0I_Z(CWnd* pThis, const wchar_t* p0, const wchar_t* p1, unsigned int p2) {
    return (int)pThis->MessageBoxW(p0, p1, p2);
}
// Symbol: ?ModifyStyle@CWnd@@SAHPEAUHWND__@@KKI@Z
// Static: CWnd::ModifyStyle
extern "C" int MS_ABI impl__ModifyStyle_CWnd__SAHPEAUHWND____KKI_Z(HWND__* p0, unsigned long p1, unsigned long p2, unsigned int p3) {
    return (int)CWnd::ModifyStyle(p0, p1, p2, p3);
}
// Symbol: ?ModifyStyleEx@CWnd@@SAHPEAUHWND__@@KKI@Z
// Static: CWnd::ModifyStyleEx
extern "C" int MS_ABI impl__ModifyStyleEx_CWnd__SAHPEAUHWND____KKI_Z(HWND__* p0, unsigned long p1, unsigned long p2, unsigned int p3) {
    return (int)CWnd::ModifyStyleEx(p0, p1, p2, p3);
}
// Symbol: ?OnActivateTopLevel@CWnd@@IEAA_J_K_J@Z
// CWnd::OnActivateTopLevel
extern "C" __int64 MS_ABI impl__OnActivateTopLevel_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnActivateTopLevel(p0, p1);
}
// Symbol: ?OnCharToItem@CWnd@@IEAAHIPEAVCListBox@@I@Z
// CWnd::OnCharToItem
extern "C" int MS_ABI impl__OnCharToItem_CWnd__IEAAHIPEAVCListBox__I_Z(CWnd* pThis, unsigned int p0, CListBox* p1, unsigned int p2) {
    return (int)pThis->OnCharToItem(p0, p1, p2);
}
// Symbol: ?OnChildNotify@CWnd@@MEAAHI_K_JPEA_J@Z
// CWnd::OnChildNotify
extern "C" int MS_ABI impl__OnChildNotify_CWnd__MEAAHI_K_JPEA_J_Z(CWnd* pThis, unsigned int p0, unsigned __int64 p1, __int64 p2, __int64* p3) {
    return (int)pThis->OnChildNotify(p0, p1, p2, p3);
}
// Symbol: ?OnCompareItem@CWnd@@IEAAHHPEAUtagCOMPAREITEMSTRUCT@@@Z
// CWnd::OnCompareItem
extern "C" int MS_ABI impl__OnCompareItem_CWnd__IEAAHHPEAUtagCOMPAREITEMSTRUCT___Z(CWnd* pThis, int p0, COMPAREITEMSTRUCT* p1) {
    return (int)pThis->OnCompareItem(p0, p1);
}
// Symbol: ?OnCtlColor@CWnd@@IEAAPEAUHBRUSH__@@PEAVCDC@@PEAV1@I@Z
// CWnd::OnCtlColor
extern "C" HBRUSH__* MS_ABI impl__OnCtlColor_CWnd__IEAAPEAUHBRUSH____PEAVCDC__PEAV1_I_Z(CWnd* pThis, CDC* p0, void* p1, unsigned int p2) {
    return (HBRUSH__*)pThis->OnCtlColor(p0, p1, p2);
}
// Symbol: ?OnDeleteItem@CWnd@@IEAAXHPEAUtagDELETEITEMSTRUCT@@@Z
// CWnd::OnDeleteItem
extern "C" void MS_ABI impl__OnDeleteItem_CWnd__IEAAXHPEAUtagDELETEITEMSTRUCT___Z(CWnd* pThis, int p0, DELETEITEMSTRUCT* p1) {
    pThis->OnDeleteItem(p0, p1);
}
// Symbol: ?OnDestroy@CWnd@@IEAAXXZ
// CWnd::OnDestroy
extern "C" void MS_ABI impl__OnDestroy_CWnd__IEAAXXZ(CWnd* pThis) {
    pThis->OnDestroy();
}
// Symbol: ?OnDisplayChange@CWnd@@IEAAXIHH@Z
// CWnd::OnDisplayChange
extern "C" void MS_ABI impl__OnDisplayChange_CWnd__IEAAXIHH_Z(CWnd* pThis, unsigned int p0, int p1, int p2) {
    pThis->OnDisplayChange(p0, p1, p2);
}
// Symbol: ?OnDragList@CWnd@@IEAA_J_K_J@Z
// CWnd::OnDragList
extern "C" __int64 MS_ABI impl__OnDragList_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnDragList(p0, p1);
}
// Symbol: ?OnDrawItem@CWnd@@IEAAXHPEAUtagDRAWITEMSTRUCT@@@Z
// CWnd::OnDrawItem
extern "C" void MS_ABI impl__OnDrawItem_CWnd__IEAAXHPEAUtagDRAWITEMSTRUCT___Z(CWnd* pThis, int p0, DRAWITEMSTRUCT* p1) {
    pThis->OnDrawItem(p0, p1);
}
// Symbol: ?OnEnterIdle@CWnd@@IEAAXIPEAV1@@Z
// CWnd::OnEnterIdle
extern "C" void MS_ABI impl__OnEnterIdle_CWnd__IEAAXIPEAV1__Z(CWnd* pThis, unsigned int p0, void* p1) {
    pThis->OnEnterIdle(p0, p1);
}
// Symbol: ?OnGetObject@CWnd@@IEAA_J_K_J@Z
// CWnd::OnGetObject
extern "C" __int64 MS_ABI impl__OnGetObject_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnGetObject(p0, p1);
}
// Symbol: ?OnHelp@CWnd@@QEAAXXZ
// CWnd::OnHelp
extern "C" void MS_ABI impl__OnHelp_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->OnHelp();
}
// Symbol: ?OnHelpFinder@CWnd@@QEAAXXZ
// CWnd::OnHelpFinder
extern "C" void MS_ABI impl__OnHelpFinder_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->OnHelpFinder();
}
// Symbol: ?OnHelpIndex@CWnd@@QEAAXXZ
// CWnd::OnHelpIndex
extern "C" void MS_ABI impl__OnHelpIndex_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->OnHelpIndex();
}
// Symbol: ?OnHelpInfo@CWnd@@IEAAHPEAUtagHELPINFO@@@Z
// CWnd::OnHelpInfo
extern "C" int MS_ABI impl__OnHelpInfo_CWnd__IEAAHPEAUtagHELPINFO___Z(CWnd* pThis, HELPINFO* p0) {
    return (int)pThis->OnHelpInfo(p0);
}
// Symbol: ?OnHelpUsing@CWnd@@QEAAXXZ
// CWnd::OnHelpUsing
extern "C" void MS_ABI impl__OnHelpUsing_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->OnHelpUsing();
}
// Symbol: ?OnHScroll@CWnd@@IEAAXIIPEAVCScrollBar@@@Z
// CWnd::OnHScroll
extern "C" void MS_ABI impl__OnHScroll_CWnd__IEAAXIIPEAVCScrollBar___Z(CWnd* pThis, unsigned int p0, unsigned int p1, CScrollBar* p2) {
    pThis->OnHScroll(p0, p1, p2);
}
// Symbol: ?OnMeasureItem@CWnd@@IEAAXHPEAUtagMEASUREITEMSTRUCT@@@Z
// CWnd::OnMeasureItem
extern "C" void MS_ABI impl__OnMeasureItem_CWnd__IEAAXHPEAUtagMEASUREITEMSTRUCT___Z(CWnd* pThis, int p0, MEASUREITEMSTRUCT* p1) {
    pThis->OnMeasureItem(p0, p1);
}
// Symbol: ?OnNcDestroy@CWnd@@IEAAXXZ
// CWnd::OnNcDestroy
extern "C" void MS_ABI impl__OnNcDestroy_CWnd__IEAAXXZ(CWnd* pThis) {
    pThis->OnNcDestroy();
}
// Symbol: ?OnNTCtlColor@CWnd@@IEAA_J_K_J@Z
// CWnd::OnNTCtlColor
extern "C" __int64 MS_ABI impl__OnNTCtlColor_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnNTCtlColor(p0, p1);
}
// Symbol: ?OnPaint@CWnd@@IEAAXXZ
// CWnd::OnPaint
extern "C" void MS_ABI impl__OnPaint_CWnd__IEAAXXZ(CWnd* pThis) {
    pThis->OnPaint();
}
// Symbol: ?OnParentNotify@CWnd@@IEAAXI_J@Z
// CWnd::OnParentNotify
extern "C" void MS_ABI impl__OnParentNotify_CWnd__IEAAXI_J_Z(CWnd* pThis, unsigned int p0, __int64 p1) {
    pThis->OnParentNotify(p0, p1);
}
// Symbol: ?OnSetFocus@CWnd@@IEAAXPEAV1@@Z
// CWnd::OnSetFocus
extern "C" void MS_ABI impl__OnSetFocus_CWnd__IEAAXPEAV1__Z(CWnd* pThis, void* p0) {
    pThis->OnSetFocus(p0);
}
// Symbol: ?OnSettingChange@CWnd@@IEAAXIPEB_W@Z
// CWnd::OnSettingChange
extern "C" void MS_ABI impl__OnSettingChange_CWnd__IEAAXIPEB_W_Z(CWnd* pThis, unsigned int p0, const wchar_t* p1) {
    pThis->OnSettingChange(p0, p1);
}
// Symbol: ?OnSysColorChange@CWnd@@IEAAXXZ
// CWnd::OnSysColorChange
extern "C" void MS_ABI impl__OnSysColorChange_CWnd__IEAAXXZ(CWnd* pThis) {
    pThis->OnSysColorChange();
}
// Symbol: ?OnTabletQuerySystemGestureStatus@CWnd@@IEAA_J_K_J@Z
// CWnd::OnTabletQuerySystemGestureStatus
extern "C" __int64 MS_ABI impl__OnTabletQuerySystemGestureStatus_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnTabletQuerySystemGestureStatus(p0, p1);
}
// Symbol: ?OnTouchMessage@CWnd@@IEAA_J_K_J@Z
// CWnd::OnTouchMessage
extern "C" __int64 MS_ABI impl__OnTouchMessage_CWnd__IEAA_J_K_J_Z(CWnd* pThis, unsigned __int64 p0, __int64 p1) {
    return (__int64)pThis->OnTouchMessage(p0, p1);
}
// Symbol: ?OnVKeyToItem@CWnd@@IEAAHIPEAVCListBox@@I@Z
// CWnd::OnVKeyToItem
extern "C" int MS_ABI impl__OnVKeyToItem_CWnd__IEAAHIPEAVCListBox__I_Z(CWnd* pThis, unsigned int p0, CListBox* p1, unsigned int p2) {
    return (int)pThis->OnVKeyToItem(p0, p1, p2);
}
// Symbol: ?OnVScroll@CWnd@@IEAAXIIPEAVCScrollBar@@@Z
// CWnd::OnVScroll
extern "C" void MS_ABI impl__OnVScroll_CWnd__IEAAXIIPEAVCScrollBar___Z(CWnd* pThis, unsigned int p0, unsigned int p1, CScrollBar* p2) {
    pThis->OnVScroll(p0, p1, p2);
}
// Symbol: ?PaintWindowlessControls@CWnd@@QEAAHPEAVCDC@@@Z
// CWnd::PaintWindowlessControls
extern "C" int MS_ABI impl__PaintWindowlessControls_CWnd__QEAAHPEAVCDC___Z(CWnd* pThis, CDC* p0) {
    return (int)pThis->PaintWindowlessControls(p0);
}
// Symbol: ?PostNcDestroy@CWnd@@MEAAXXZ
// CWnd::PostNcDestroy
extern "C" void MS_ABI impl__PostNcDestroy_CWnd__MEAAXXZ(CWnd* pThis) {
    pThis->PostNcDestroy();
}
// Symbol: ?PrepareForHelp@CWnd@@QEAAXXZ
// CWnd::PrepareForHelp
extern "C" void MS_ABI impl__PrepareForHelp_CWnd__QEAAXXZ(CWnd* pThis) {
    pThis->PrepareForHelp();
}
// Symbol: ?PreTranslateInput@CWnd@@QEAAHPEAUtagMSG@@@Z
// CWnd::PreTranslateInput
extern "C" int MS_ABI impl__PreTranslateInput_CWnd__QEAAHPEAUtagMSG___Z(CWnd* pThis, MSG* p0) {
    return (int)pThis->PreTranslateInput(p0);
}
// Symbol: ?ReflectChildNotify@CWnd@@IEAAHI_K_JPEA_J@Z
// CWnd::ReflectChildNotify
extern "C" int MS_ABI impl__ReflectChildNotify_CWnd__IEAAHI_K_JPEA_J_Z(CWnd* pThis, unsigned int p0, unsigned __int64 p1, __int64 p2, __int64* p3) {
    return (int)pThis->ReflectChildNotify(p0, p1, p2, p3);
}
// Symbol: ?ReflectLastMsg@CWnd@@KAHPEAUHWND__@@PEA_J@Z
// Static: CWnd::ReflectLastMsg
extern "C" int MS_ABI impl__ReflectLastMsg_CWnd__KAHPEAUHWND____PEA_J_Z(HWND__* p0, __int64* p1) {
    return (int)CWnd::ReflectLastMsg(p0, p1);
}
// Symbol: ?RunModalLoop@CWnd@@QEAAHK@Z
// CWnd::RunModalLoop
extern "C" int MS_ABI impl__RunModalLoop_CWnd__QEAAHK_Z(CWnd* pThis, unsigned long p0) {
    return (int)pThis->RunModalLoop(p0);
}
// Symbol: ?ScreenToClient@CWnd@@QEBAXPEAUtagRECT@@@Z
// CWnd::ScreenToClient
extern "C" void MS_ABI impl__ScreenToClient_CWnd__QEBAXPEAUtagRECT___Z(const CWnd* pThis, RECT* p0) {
    pThis->ScreenToClient(p0);
}
// Symbol: ?SendDlgItemMessageW@CWnd@@QEAA_JHI_K_J@Z
// CWnd::SendDlgItemMessageW
extern "C" __int64 MS_ABI impl__SendDlgItemMessageW_CWnd__QEAA_JHI_K_J_Z(CWnd* pThis, int p0, unsigned int p1, unsigned __int64 p2, __int64 p3) {
    return (__int64)pThis->SendDlgItemMessageW(p0, p1, p2, p3);
}
// Symbol: ?SendMessageToDescendants@CWnd@@SAXPEAUHWND__@@I_K_JHH@Z
// Static: CWnd::SendMessageToDescendants
extern "C" void MS_ABI impl__SendMessageToDescendants_CWnd__SAXPEAUHWND____I_K_JHH_Z(HWND__* p0, unsigned int p1, unsigned __int64 p2, __int64 p3, int p4, int p5) {
    CWnd::SendMessageToDescendants(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?SetDlgCtrlID@CWnd@@QEAAHH@Z
// CWnd::SetDlgCtrlID
extern "C" int MS_ABI impl__SetDlgCtrlID_CWnd__QEAAHH_Z(CWnd* pThis, int p0) {
    return (int)pThis->SetDlgCtrlID(p0);
}
// Symbol: ?SetDlgItemInt@CWnd@@QEAAXHIH@Z
// CWnd::SetDlgItemInt
extern "C" void MS_ABI impl__SetDlgItemInt_CWnd__QEAAXHIH_Z(CWnd* pThis, int p0, unsigned int p1, int p2) {
    pThis->SetDlgItemInt(p0, p1, p2);
}
// Symbol: ?SetDlgItemTextW@CWnd@@QEAAXHPEB_W@Z
// CWnd::SetDlgItemTextW
extern "C" void MS_ABI impl__SetDlgItemTextW_CWnd__QEAAXHPEB_W_Z(CWnd* pThis, int p0, const wchar_t* p1) {
    pThis->SetDlgItemTextW(p0, p1);
}
// Symbol: ?SetFocus@CWnd@@QEAAPEAV1@XZ
// CWnd::SetFocus
extern "C" void* MS_ABI impl__SetFocus_CWnd__QEAAPEAV1_XZ(CWnd* pThis) {
    return (void*)pThis->SetFocus();
}
// Symbol: ?SetGestureConfig@CWnd@@QEAAHPEAVCGestureConfig@@@Z
// CWnd::SetGestureConfig
extern "C" int MS_ABI impl__SetGestureConfig_CWnd__QEAAHPEAVCGestureConfig___Z(CWnd* pThis, CGestureConfig* p0) {
    return (int)pThis->SetGestureConfig(p0);
}
// Symbol: ?SetOccDialogInfo@CWnd@@MEAAHPEAU_AFX_OCC_DIALOG_INFO@@@Z
// CWnd::SetOccDialogInfo
extern "C" int MS_ABI impl__SetOccDialogInfo_CWnd__MEAAHPEAU_AFX_OCC_DIALOG_INFO___Z(CWnd* pThis, _AFX_OCC_DIALOG_INFO* p0) {
    return (int)pThis->SetOccDialogInfo(p0);
}
// Symbol: ?SetScrollInfo@CWnd@@QEAAHHPEAUtagSCROLLINFO@@H@Z
// CWnd::SetScrollInfo
extern "C" int MS_ABI impl__SetScrollInfo_CWnd__QEAAHHPEAUtagSCROLLINFO__H_Z(CWnd* pThis, int p0, SCROLLINFO* p1, int p2) {
    return (int)pThis->SetScrollInfo(p0, p1, p2);
}
// Symbol: ?SetScrollPos@CWnd@@QEAAHHHH@Z
// CWnd::SetScrollPos
extern "C" int MS_ABI impl__SetScrollPos_CWnd__QEAAHHHH_Z(CWnd* pThis, int p0, int p1, int p2) {
    return (int)pThis->SetScrollPos(p0, p1, p2);
}
// Symbol: ?SetScrollRange@CWnd@@QEAAXHHHH@Z
// CWnd::SetScrollRange
extern "C" void MS_ABI impl__SetScrollRange_CWnd__QEAAXHHHH_Z(CWnd* pThis, int p0, int p1, int p2, int p3) {
    pThis->SetScrollRange(p0, p1, p2, p3);
}
// Symbol: ?SetWindowPlacement@CWnd@@QEAAHPEBUtagWINDOWPLACEMENT@@@Z
// CWnd::SetWindowPlacement
extern "C" int MS_ABI impl__SetWindowPlacement_CWnd__QEAAHPEBUtagWINDOWPLACEMENT___Z(CWnd* pThis, const WINDOWPLACEMENT* p0) {
    return (int)pThis->SetWindowPlacement(p0);
}
// Symbol: ?SubclassDlgItem@CWnd@@QEAAHIPEAV1@@Z
// CWnd::SubclassDlgItem
extern "C" int MS_ABI impl__SubclassDlgItem_CWnd__QEAAHIPEAV1__Z(CWnd* pThis, unsigned int p0, void* p1) {
    return (int)pThis->SubclassDlgItem(p0, p1);
}
// Symbol: ?SubclassWindow@CWnd@@QEAAHPEAUHWND__@@@Z
// CWnd::SubclassWindow
extern "C" int MS_ABI impl__SubclassWindow_CWnd__QEAAHPEAUHWND_____Z(CWnd* pThis, HWND__* p0) {
    return (int)pThis->SubclassWindow(p0);
}
// Symbol: ?UnsubclassWindow@CWnd@@QEAAPEAUHWND__@@XZ
// CWnd::UnsubclassWindow
extern "C" HWND__* MS_ABI impl__UnsubclassWindow_CWnd__QEAAPEAUHWND____XZ(CWnd* pThis) {
    return (HWND__*)pThis->UnsubclassWindow();
}
// Symbol: ?UpdateData@CWnd@@QEAAHH@Z
// CWnd::UpdateData
extern "C" int MS_ABI impl__UpdateData_CWnd__QEAAHH_Z(CWnd* pThis, int p0) {
    return (int)pThis->UpdateData(p0);
}
// Symbol: ?UpdateDialogControls@CWnd@@QEAAXPEAVCCmdTarget@@H@Z
// CWnd::UpdateDialogControls
extern "C" void MS_ABI impl__UpdateDialogControls_CWnd__QEAAXPEAVCCmdTarget__H_Z(CWnd* pThis, CCmdTarget* p0, int p1) {
    pThis->UpdateDialogControls(p0, p1);
}
// Symbol: ?WalkPreTranslateTree@CWnd@@SAHPEAUHWND__@@PEAUtagMSG@@@Z
// Static: CWnd::WalkPreTranslateTree
extern "C" int MS_ABI impl__WalkPreTranslateTree_CWnd__SAHPEAUHWND____PEAUtagMSG___Z(HWND__* p0, MSG* p1) {
    return (int)CWnd::WalkPreTranslateTree(p0, p1);
}
// Symbol: ?EnableD2DSupport@CWnd@@QEAAXHH@Z
// CWnd::EnableD2DSupport
extern "C" void MS_ABI impl__EnableD2DSupport_CWnd__QEAAXHH_Z(CWnd* pThis, int p0, int p1) {
    pThis->EnableD2DSupport(p0, p1);
}
// Symbol: ?GetDCRenderTarget@CWnd@@QEAAPEAVCDCRenderTarget@@XZ
// CWnd::GetDCRenderTarget
extern "C" CDCRenderTarget* MS_ABI impl__GetDCRenderTarget_CWnd__QEAAPEAVCDCRenderTarget__XZ(CWnd* pThis) {
    return (CDCRenderTarget*)pThis->GetDCRenderTarget();
}
// Symbol: ?EnableDynamicLayout@CWnd@@QEAAXH@Z
// CWnd::EnableDynamicLayout
extern "C" void MS_ABI impl__EnableDynamicLayout_CWnd__QEAAXH_Z(CWnd* pThis, int p0) {
    pThis->EnableDynamicLayout(p0);
}
// Symbol: ?InitDynamicLayout@CWnd@@IEAAXXZ
// CWnd::InitDynamicLayout
extern "C" void MS_ABI impl__InitDynamicLayout_CWnd__IEAAXXZ(CWnd* pThis) {
    pThis->InitDynamicLayout();
}
// Symbol: ?LoadDynamicLayoutResource@CWnd@@IEAAHPEB_W@Z
// CWnd::LoadDynamicLayoutResource
extern "C" int MS_ABI impl__LoadDynamicLayoutResource_CWnd__IEAAHPEB_W_Z(CWnd* pThis, const wchar_t* p0) {
    return (int)pThis->LoadDynamicLayoutResource(p0);
}
// Symbol: ?ResizeDynamicLayout@CWnd@@MEAAXXZ
// CWnd::ResizeDynamicLayout
extern "C" void MS_ABI impl__ResizeDynamicLayout_CWnd__MEAAXXZ(CWnd* pThis) {
    pThis->ResizeDynamicLayout();
}
