// CtorDtorPlacement — OpenMFC implementation.
// Sources: global_ctordtor_placement.cpp

// AUTO-GENERATED by tools/harvest/gen_ctordtor.py -- real default-ctor/dtor thunks
// for header-defined constructible classes.
#include "openmfc/afxwin.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxole.h"
#include "openmfc/afxdisp.h"
#include "openmfc/afxdao.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include <new>
#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

// Symbol: ??0CMFCCaptionButton@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCCaptionButton__QEAA_XZ(void* pThis) { return new (pThis) CMFCCaptionButton(); }
// Symbol: ??0CMFCDesktopAlertWnd@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCDesktopAlertWnd__QEAA_XZ(void* pThis) { return new (pThis) CMFCDesktopAlertWnd(); }
// Symbol: ??0CMFCHeaderCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CMFCHeaderCtrl__QEAA_XZ(void* pThis) { return new (pThis) CMFCHeaderCtrl(); }
// Symbol: ??0CVSListBox@@QEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBox__QEAA_XZ(void* pThis) { return new (pThis) CVSListBox(); }
// Symbol: ??0CVSListBoxBase@@IEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBoxBase__IEAA_XZ(void* pThis) { return new (pThis) CVSListBoxBase(); }
// Symbol: ??0CVSListBoxEditCtrl@@QEAA@XZ
extern "C" void* MS_ABI impl___0CVSListBoxEditCtrl__QEAA_XZ(void* pThis) { return new (pThis) CVSListBoxEditCtrl(); }
// Symbol: ??1CMFCCaptionButton@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCCaptionButton__UEAA_XZ(void* pThis) { static_cast<CMFCCaptionButton*>(pThis)->~CMFCCaptionButton(); }
// Symbol: ??1CMFCDesktopAlertWnd@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCDesktopAlertWnd__UEAA_XZ(void* pThis) { static_cast<CMFCDesktopAlertWnd*>(pThis)->~CMFCDesktopAlertWnd(); }
// Symbol: ??1CMFCHeaderCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CMFCHeaderCtrl__UEAA_XZ(void* pThis) { static_cast<CMFCHeaderCtrl*>(pThis)->~CMFCHeaderCtrl(); }
// Symbol: ??1CVSListBox@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBox__UEAA_XZ(void* pThis) { static_cast<CVSListBox*>(pThis)->~CVSListBox(); }
// Symbol: ??1CVSListBoxBase@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBoxBase__UEAA_XZ(void* pThis) { static_cast<CVSListBoxBase*>(pThis)->~CVSListBoxBase(); }
// Symbol: ??1CVSListBoxEditCtrl@@UEAA@XZ
extern "C" void MS_ABI impl___1CVSListBoxEditCtrl__UEAA_XZ(void* pThis) { static_cast<CVSListBoxEditCtrl*>(pThis)->~CVSListBoxEditCtrl(); }
