#!/usr/bin/env python3
"""Generate assembly stubs (GAS .S format) for symbols the auto-generator
can't handle.  These bypass C++ type checking entirely — each stub returns
a default value in RAX.  The linker resolves the impl_XXX names."""

import argparse, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import demangle_msvc
demangle_msvc.RESOLVE_TYPE_NAMES = False
from demangle_msvc import demangle


def stub_name(symbol: str) -> str:
    stub = re.sub(r'[?@]', '_', symbol)
    stub = re.sub(r'[^a-zA-Z0-9_]', '_', stub)
    if not stub[0].isalpha() and stub[0] != '_':
        stub = '_' + stub
    if len(stub) > 200:
        stub = stub[:100] + '_' + stub[-100:]
    return 'impl_' + stub


RETURN_X86 = {
    'void': 'xor eax, eax',
    'int': 'xor eax, eax',
    'long': 'xor eax, eax',
    'unsigned int': 'xor eax, eax',
    'unsigned long': 'xor eax, eax',
    'short': 'xor eax, eax',
    'unsigned short': 'xor eax, eax',
    'char': 'xor eax, eax',
    'unsigned char': 'xor eax, eax',
    'bool': 'xor eax, eax',
    '__int64': 'xor rax, rax',
    'unsigned __int64': 'xor rax, rax',
    'float': 'pxor xmm0, xmm0',
    'double': 'pxor xmm0, xmm0',
    'wchar_t': 'xor eax, eax',
}


def generate(skip_file: str) -> str:
    skip_path = Path(skip_file)
    symbols = [l.strip() for l in skip_path.read_text().splitlines()
               if l.strip() and not l.startswith('#')]

    lines = []
    lines.append('// Assembly stubs for auto-generator-unhandled symbols\n')
    lines.append('// Generated by tools/gen_asm_stubs.py\n')
    lines.append('// Use .intel_syntax for GAS, MinGW-w64 COFF compatible\n')
    lines.append('\n')
    lines.append('.intel_syntax noprefix\n')
    lines.append('.text\n')
    lines.append('\n')

    count = 0
    for symbol in symbols:
        info = demangle(symbol)
        name = stub_name(symbol)
        is_ctor = symbol.startswith('??0')
        ret = info.ret_type if info.ret_type else 'void'

        asm_setup = 'xor rax, rax' if (is_ctor or '*' in ret) else \
            RETURN_X86.get(ret, 'xor rax, rax')

        lines.append(f'// Symbol: {symbol}\n')
        lines.append(f'.globl {name}\n')
        lines.append(f'{name}:\n')
        lines.append(f'    {asm_setup}\n')
        lines.append(f'    ret\n')
        lines.append('\n')
        count += 1

    lines.append(f'// Generated {count} asm stubs\n')
    return ''.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="phase4/src/asm_stubs.S")
    args = parser.parse_args()
    skip_file = Path(__file__).parent / 'thunks_skip.txt'
    if not skip_file.exists():
        print(f"Error: {skip_file} not found", file=sys.stderr)
        return 1
    content = generate(str(skip_file))
    Path(args.out).write_text(content, encoding="ascii", errors="replace")
    print(f"Generated: {args.out} ({len(content)} bytes, {content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
