#!/usr/bin/env python3
"""
Render PROGRESS.md from the export manifest produced by gen_manifest.py.

PROGRESS.md used to claim it was generated by gen_manifest.py, but that tool
only emits .json/.txt -- the markdown was maintained by hand and drifted badly
(it claimed 1,188 real implementations when the true figure was 5,881). This
script closes that gap so the document can be regenerated mechanically.

Usage:
  python3 tools/gen_manifest.py --out /tmp/manifest.json
  python3 tools/gen_progress_md.py --manifest /tmp/manifest.json --out PROGRESS.md
"""

import argparse
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Hand-written rationales for the largest skip-list entries. Keyed by class;
# classes without an entry simply render a blank cell rather than an invented
# reason.
SKIP_REASONS = {
    'CWnd': 'Overloads with incompatible signatures',
    'CMFCVisualManager': 'Complex drawing overloads',
    'CRichEditCtrl': 'ABI struct incompatibilities',
    'CHttpFile': 'QueryInfo overloads',
    'CHtmlView': 'Navigate2/event handlers',
    'CTaskDialog': 'Button/task management overloads',
    'COleSafeArray': 'Attach/Create/Copy/Detach',
    'COleDocument': 'EditChangeIcon/EditConvert',
    'CFile': 'CommonInit/Remove/Rename',
    'COleClientItem': 'Activate/ActivateAs/GetClassID',
}

ARCHITECTURE = """```
MSVC .def file ({total:,} exports)
         │
         ▼
  extern "C" MS_ABI wrapper functions
         │
    ┌────┴────┐
    ▼         ▼
  thunks    stubs
  (real)    (return 0)
```"""


def pct(n, total):
    return f'{100.0 * n / total:.1f}%'


def ranked(counter, limit=None):
    """Counter entries as (key, count), highest first, ties broken by key.

    Counter.most_common() sorts only on the count and relies on sort stability,
    so equal counts come back in dict-insertion order -- which tracks whatever
    order the manifest happened to list symbols in. That is stable in practice
    but not guaranteed by anything, and a reordering upstream would silently
    reshuffle rows in the generated document. Sorting on (-count, key) pins it.
    """
    items = sorted(counter.items(), key=lambda kv: (-kv[1], kv[0]))
    return items[:limit] if limit is not None else items


def render(manifest):
    real = manifest['real']
    skip = manifest['skip']
    stub = manifest['stub']
    stale = manifest['stale']
    total = len(real) + len(skip) + len(stub)

    by_file = collections.Counter(e['file'] for e in real if e.get('file'))
    thunks = by_file.get('thunks.cpp', 0)
    manual = len(real) - thunks

    real_by_class = collections.Counter(e['class'] for e in real if e.get('class'))
    skip_by_class = collections.Counter(e['class'] for e in skip if e.get('class'))
    stale_by_file = collections.Counter(e['file'] for e in stale if e.get('file'))

    L = []
    add = L.append

    add('# OpenMFC Implementation Progress')
    add('')
    add('> Generated by `tools/gen_progress_md.py` from the manifest that')
    add('> `tools/gen_manifest.py` emits. Regenerate after every thunks')
    add('> regeneration; do not edit the tables by hand.')
    add('')
    add('## Overall ABI Coverage')
    add('')
    add('| Category | Count | % of Total |')
    add('|----------|-------|------------|')
    add(f'| **Total MSVC exports** | {total:,} | 100% |')
    add(f'| **Real implementations** | {len(real):,} | {pct(len(real), total)} |')
    add(f'| ├─ Auto-generated thunks (`thunks.cpp`) | {thunks:,} | {pct(thunks, total)} |')
    add(f'| └─ Manual implementations (other `phase4/src/*.cpp`) | {manual:,} | {pct(manual, total)} |')
    add(f'| **Skip list** (signature mismatch, return defaults) | {len(skip):,} | {pct(len(skip), total)} |')
    add(f'| **Remaining stubs** (return 0/nullptr/void) | {len(stub):,} | {pct(len(stub), total)} |')
    add('')

    if stale:
        add(f'⚠ **{len(stale)} stale `// Symbol:` comments** — markers naming symbols')
        add('that are not exports.')
        add('')
        add('Most are harmless: `build_phase4.sh` builds its `AUTO_EXCLUDES` list by')
        add('grepping these markers, and excluding a symbol that was never an export')
        add('is a no-op. The export surface is unaffected.')
        add('')
        add('The damaging subset is the one where a *real* export exists under a')
        add('different mangling — typically the 32-bit form (`PAV`/`QBA`/`UBA`) where')
        add('retail exports the 64-bit one (`PEAV`/`QEBA`/`UEBA`). There the marker,')
        add('and the `impl__` function name derived from it, both miss the export.')
        add('The `.def` still aliases the export to the correctly-mangled `impl__`')
        add('symbol, which the stub generator then defines — so the export resolves')
        add('to a stub returning 0, while the hand-written implementation next to the')
        add('marker is orphaned and never reachable. Every metric counts it as done.')
        add('')
        add('| Source file | Stale markers |')
        add('|-------------|---------------|')
        for fname, n in ranked(stale_by_file):
            add(f'| `{fname}` | {n} |')
        add('')

    add('## Per-File Breakdown')
    add('')
    add('| Source file | Implemented symbols |')
    add('|-------------|-------------------|')
    for fname, n in ranked(by_file, 40):
        label = f'`{fname}` (auto-generated)' if fname == 'thunks.cpp' else f'`{fname}`'
        add(f'| {label} | {n:,} |')
    if len(by_file) > 40:
        rest = sum(n for _, n in ranked(by_file)[40:])
        add(f'| *(+{len(by_file) - 40} further files)* | {rest:,} |')
    add('')

    add('## Per-Class Implementation Counts')
    add('')
    add('### Top implemented classes')
    add('| Class | Implemented | Skip list |')
    add('|-------|-------------|-----------|')
    for cls, n in ranked(real_by_class, 25):
        add(f'| **{cls}** | {n} | {skip_by_class.get(cls, 0)} |')
    add('')

    mid = sorted(
        (c for c, n in real_by_class.items() if 5 <= n <= 9),
        key=lambda c: (-real_by_class[c], c),
    )
    add('### Partially implemented classes (5–9 symbols)')
    add(', '.join(f'{c} ({real_by_class[c]})' for c in mid) or '*(none)*')
    add('')

    add('### Top skip-list offenders')
    add('| Class | Skip count | Reason |')
    add('|-------|-----------|--------|')
    for cls, n in ranked(skip_by_class, 10):
        add(f'| {cls} | {n} | {SKIP_REASONS.get(cls, "")} |')
    add('')

    add('## Architecture')
    add('')
    add(ARCHITECTURE.format(total=total))
    add('')
    add(f'- **thunks**: Call real C++ method implementations via `pThis->Method(args)` — {thunks:,} auto-generated')
    add(f'- **manual implementations**: Implemented directly in `phase4/src/*.cpp` with `// Symbol:` comments — {manual:,} symbols')
    add(f'- **skip list**: Correct ABI signatures but return defaults because method signatures fundamentally differ from MSVC exports — {len(skip):,} symbols')
    add(f'- **stubs**: Generated by `gen_typed_stubs.py`, return 0/nullptr/void — {len(stub):,} symbols')
    add('')

    add('## Key Tools')
    add('')
    add('| Tool | Purpose |')
    add('|------|---------|')
    add('| `tools/gen_thunks.py` | Auto-generates routing wrappers from header declarations |')
    add('| `tools/gen_manifest.py` | Generates accurate export-by-export status manifest |')
    add('| `tools/gen_progress_md.py` | Renders this document from that manifest |')
    add('| `tools/class_coverage.py` | Per-class coverage (`--list-partial`, `--list-none`, `--near`) |')
    add('| `tools/gen_typed_stubs.py` | Generates properly-typed stubs for all remaining exports |')
    add('| `tools/gen_rtti.py` | Generates RTTI metadata |')
    add('| `tools/demangle_msvc.py` | MSVC name demangler used by all tools |')
    add('| `tools/thunks_skip.txt` | Symbols excluded from auto-generation (signature mismatch) |')
    add('| `phase4/scripts/build_phase4.sh` | Build script — compile + link DLL |')
    add('')

    add('## How to Add More Implementations')
    add('')
    add('1. Add method declaration to the appropriate header (`include/openmfc/afx*.h`)')
    add('2. Add implementation to the matching source file (`phase4/src/*.cpp`) **without** `// Symbol:` comment')
    add('3. Run: `python3 tools/gen_thunks.py --mapping mfc_complete_ordinal_mapping.json --source-dir phase4/src --include-dir include/openmfc --out phase4/src/thunks.cpp`')
    add('4. Run: `python3 tools/gen_manifest.py --out /tmp/manifest.json` to verify accounting')
    add('5. Build: `bash phase4/scripts/build_phase4.sh`')
    add('6. If build fails due to signature mismatch: add the symbol to `tools/thunks_skip.txt`')
    add('')

    add('## Accounting')
    add('')
    add('- Regenerate with:')
    add('  ```sh')
    add('  python3 tools/gen_manifest.py --out /tmp/manifest.json')
    add('  python3 tools/gen_progress_md.py --manifest /tmp/manifest.json --out PROGRESS.md')
    add('  ```')
    add('- `gen_manifest.py` parses exports from `mfc_complete_ordinal_mapping.json` and cross-references with `// Symbol:` comments and `thunks_skip.txt`')
    add('- Never trust manual counts — always run the manifest generator')
    add('')

    return '\n'.join(L)


def main():
    ap = argparse.ArgumentParser(description='Render PROGRESS.md from an export manifest')
    ap.add_argument('--manifest', required=True, help='manifest .json from gen_manifest.py')
    ap.add_argument('--out', default=str(ROOT / 'PROGRESS.md'))
    args = ap.parse_args()

    with open(args.manifest, encoding='utf-8') as f:
        manifest = json.load(f)

    text = render(manifest)
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write(text)
    print(f'Wrote {args.out}')


if __name__ == '__main__':
    main()
