#!/usr/bin/env python3
"""Generate manual thunks with proper parameter counts and return types.
These are ABI-compatible stubs for symbols where our C++ method signatures
differ from the MSVC DLL exports, preventing auto-generation.

Usage:
    python3 tools/gen_manual_thunks.py --out phase4/src/manual_thunks.cpp

After generating, empty thunks_skip.txt and regenerate thunks.cpp.
"""

import argparse, re, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import demangle_msvc
demangle_msvc.RESOLVE_TYPE_NAMES = False
from demangle_msvc import demangle


def stub_name(symbol: str) -> str:
    stub = re.sub(r'[?@]', '_', symbol)
    stub = re.sub(r'[^a-zA-Z0-9_]', '_', stub)
    if not stub[0].isalpha() and stub[0] != '_':
        stub = '_' + stub
    if len(stub) > 200:
        stub = stub[:100] + '_' + stub[-100:]
    return 'impl_' + stub


RETURN_CTYPE = {
    'void': 'void', 'void*': 'void*', 'void* /*class*/': 'void*', 'void* /*struct*/': 'void*',
    'int': 'int', 'long': 'long',
    'unsigned int': 'unsigned int', 'unsigned long': 'unsigned long',
    'short': 'short', 'unsigned short': 'unsigned short',
    'char': 'char', 'unsigned char': 'unsigned char',
    'bool': 'bool', '__int64': '__int64', 'unsigned __int64': 'unsigned __int64',
    'float': 'float', 'double': 'double', 'wchar_t': 'wchar_t',
}

RETURN_STMT = {
    'void': '', 'void*': 'return nullptr;',
    'void* /*class*/': 'return nullptr;', 'void* /*struct*/': 'return nullptr;',
    'int': 'return 0;', 'long': 'return 0L;',
    'unsigned int': 'return 0u;', 'unsigned long': 'return 0UL;',
    'short': 'return 0;', 'unsigned short': 'return 0;',
    'char': 'return 0;', 'unsigned char': 'return 0;',
    'bool': 'return false;', '__int64': 'return 0LL;', 'unsigned __int64': 'return 0ULL;',
    'float': 'return 0.0f;', 'double': 'return 0.0;', 'wchar_t': 'return 0;',
}


def get_ret(info) -> tuple:
    """Return (c_type, return_stmt)."""
    ret = info.ret_type
    if ret in RETURN_CTYPE:
        return RETURN_CTYPE[ret], RETURN_STMT[ret]
    if 'void*' in ret:
        return 'void*', 'return nullptr;'
    if '*' in ret:
        return 'void*', 'return nullptr;'
    return 'void*', 'return nullptr;'


def generate(skip_file: str) -> str:
    skip_path = Path(skip_file)
    symbols = [l.strip() for l in skip_path.read_text().splitlines()
               if l.strip() and not l.startswith('#')]

    hdr = '''// Manually-written thunks for symbols the auto-generator cannot handle.
// Generated by tools/gen_manual_thunks.py
// These thunks provide proper parameter counts and return types (ABI-compatible),
// but return default values since our C++ method signatures differ from
// the MSVC DLL exports for these symbols.

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
#define MS_ABI __attribute__((ms_abi))
#else
#define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"
#include <cstring>

'''

    lines = hdr.splitlines(True)
    count = 0

    for symbol in symbols:
        info = demangle(symbol)
        name = stub_name(symbol)
        is_ctor = symbol.startswith('??0')
        is_dtor = symbol.startswith('??1')
        num_params = len(info.params) if info.params else 0
        c_ret, ret_stmt = get_ret(info)

        # Build param list: this + N void* params
        params = []
        if is_ctor or is_dtor:
            params.append('void* pThis')
        elif not info.is_data and (info.params or info.is_static):
            if not info.is_static:
                params.append('void* pThis')
        for i in range(num_params):
            params.append(f'void* p{i}')
        if not params:
            params.append('void* unused')

        params_str = ', '.join(params)

        lines.append(f'// Symbol: {symbol}\n')
        lines.append(f'extern "C" {c_ret} MS_ABI {name}({params_str}) {{\n')

        for p in params:
            lines.append(f'    (void){p.split()[-1]};\n')

        if is_ctor:
            lines.append('    return nullptr;\n')
        elif c_ret != 'void':
            lines.append(f'    {ret_stmt}\n')

        lines.append('}\n\n')
        count += 1

    lines.append(f'// Generated {count} manual thunks\n')
    return ''.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="phase4/src/manual_thunks.cpp")
    args = parser.parse_args()
    skip_file = Path(__file__).parent / 'thunks_skip.txt'
    if not skip_file.exists():
        print(f"Error: {skip_file} not found", file=sys.stderr)
        return 1
    content = generate(str(skip_file))
    Path(args.out).write_text(content, encoding="ascii", errors="replace")
    print(f"Generated: {args.out} ({len(content)} bytes, {content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
