#!/usr/bin/env python3
"""
Generated typed stubs for OpenMFC.

Replaces the auto-generated weak_stubs.cpp with properly-typed stubs.
Uses the MSVC demangler to determine return types and parameter counts
for each remaining symbol, generating extern "C" MS_ABI thunks with
correct signatures instead of the generic void() stubs.

Usage:
    python3 tools/gen_typed_stubs.py \
        --mapping mfc_complete_ordinal_mapping.json \
        --exclude "symbol1,symbol2,..." \
        --demangler tools/demangle_msvc.py \
        --out build-phase4/typed_stubs.cpp
"""

import argparse
import json
import re
import sys
from pathlib import Path

# Import the demangler
sys.path.insert(0, str(Path(__file__).parent))
from demangle_msvc import demangle


def generate_stub_name(symbol: str) -> str:
    """Generate a valid C identifier from MSVC mangled name."""
    stub = re.sub(r'[?@]', '_', symbol)
    stub = re.sub(r'[^a-zA-Z0-9_]', '_', stub)
    if not stub[0].isalpha() and stub[0] != '_':
        stub = '_' + stub
    if len(stub) > 200:
        stub = stub[:100] + '_' + stub[-100:]
    return 'impl_' + stub


def generate_typed_stubs(entries, excluded_symbols):
    """Generate typed stub implementations for non-excluded symbols."""
    
    excluded_set = set(excluded_symbols)
    lines = []
    
    lines.append('// Auto-generated TYPED stubs for OpenMFC')
    lines.append('//')
    lines.append('// Generated by gen_typed_stubs.py')
    lines.append('// Uses MSVC demangler for correct signatures.')
    lines.append('// All stubs return safe defaults (0/nullptr/void).')
    lines.append('')
    lines.append('#include <cstddef>')
    lines.append('')
    lines.append('#if defined(__GNUC__)')
    lines.append('  #define MS_ABI __attribute__((ms_abi))')
    lines.append('#else')
    lines.append('  #define MS_ABI')
    lines.append('#endif')
    lines.append('')
    
    lines.append('// ============================================================')
    lines.append('// DATA EXPORTS (global variables, static members)')
    lines.append('// ============================================================')
    lines.append('')
    
    data_count = 0
    func_count = 0
    error_count = 0
    skipped_template_count = 0
    
    # First pass: data exports
    for entry in entries:
        symbol = entry.get("symbol", "")
        if not symbol or symbol in excluded_set:
            continue
        
        # Check if data
        if not symbol.endswith('Z'):
            info = demangle(symbol)
            if info.is_data:
                stub_name = generate_stub_name(symbol)
                lines.append(f'// {symbol}')
                lines.append(f'extern "C" {info.data_type} MS_ABI {stub_name} = {{}};')
                lines.append('')
                data_count += 1
    
    lines.append('// ============================================================')
    lines.append('// FUNCTION EXPORTS')
    lines.append('// ============================================================')
    lines.append('')
    
    # Second pass: function exports
    for entry in entries:
        symbol = entry.get("symbol", "")
        if not symbol or symbol in excluded_set:
            continue
        
        # Skip data exports (already handled)
        if not symbol.endswith('Z'):
            continue
        
        info = demangle(symbol)
        
        if not info.params and info.ret_type == 'void' and '?' not in info.symbol:
            # Probably couldn't parse — count as error
            error_count += 1
            continue
        
        stub_name = generate_stub_name(symbol)
        
        # Generate parameter list
        param_decls = []
        for i, p in enumerate(info.params):
            param_decls.append(f"{p.c_type} p{i}")
        
        params_str = ", ".join(param_decls)
        
        # Generate return type and default return
        ret = info.ret_type
        
        # Clean up return type for C
        ret_clean = ret.replace(' /*class*/', '').replace(' /*struct*/', '').replace(' /*enum*/', '')
        
        # Generate appropriate stub based on return type
        if ret_clean == 'void':
            lines.append(f'// {symbol}')
            if params_str:
                lines.append(f'extern "C" void MS_ABI {stub_name}({params_str}) {{}}')
            else:
                lines.append(f'extern "C" void MS_ABI {stub_name}() {{}}')
        elif ret_clean in ('int', 'long', 'unsigned int', 'unsigned long', 'short', 'unsigned short'):
            default_val = '0'
            if ret_clean == 'int':
                ret_str = 'int'
            elif ret_clean == 'long':
                ret_str = 'long'
            elif ret_clean == 'unsigned int':
                ret_str = 'unsigned int'
            elif ret_clean == 'unsigned long':
                ret_str = 'unsigned long'
            elif ret_clean == 'short':
                ret_str = 'short'
            else:
                ret_str = 'unsigned short'
            
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" {ret_str} MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return {default_val};')
            lines.append(f'}}')
        elif ret_clean == 'bool' or ret_clean == '_N':
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" int MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return 0;  // false')
            lines.append(f'}}')
        elif ret_clean in ('float', 'double', '__int64', 'unsigned __int64'):
            default = '0.0' if ret_clean in ('float', 'double') else '0'
            c_type = ret_clean
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" {c_type} MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return {default};')
            lines.append(f'}}')
        elif ret_clean == 'wchar_t':
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" wchar_t MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return 0;')
            lines.append(f'}}')
        elif ret_clean == 'char':
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" char MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return 0;')
            lines.append(f'}}')
        else:
            # Pointer or complex type — return nullptr
            lines.append(f'// {symbol}')
            lines.append(f'extern "C" void* MS_ABI {stub_name}({params_str}) {{')
            lines.append(f'    return nullptr;')
            lines.append(f'}}')
        
        lines.append('')
        func_count += 1
    
    lines.append(f'// Generated {func_count} function stubs + {data_count} data stubs')
    lines.append(f'// Errors (could not parse): {error_count}')
    lines.append(f'// Excluded (real implementations): {len(excluded_set)}')
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate typed stubs for OpenMFC")
    parser.add_argument("--mapping", required=True, help="Path to ordinal mapping JSON")
    parser.add_argument("--exclude", default="", help="Comma-separated list of symbols to exclude")
    parser.add_argument("--out", required=True, help="Output .cpp file path")
    args = parser.parse_args()
    
    mapping_path = Path(args.mapping)
    if not mapping_path.exists():
        print(f"Error: Mapping file not found: {mapping_path}", file=sys.stderr)
        return 1
    
    data = json.loads(mapping_path.read_text())
    all_entries = data.get("exports", {}).get("mfc140u", [])
    
    excluded = [s.strip() for s in args.exclude.split(',') if s.strip()]
    
    print(f"Loaded {len(all_entries)} entries")
    print(f"Excluded {len(excluded)} symbols")
    
    content = generate_typed_stubs(all_entries, excluded)
    
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(content, encoding="ascii", errors="replace")
    
    print(f"Generated: {args.out}")
    print(f"Size: {Path(args.out).stat().st_size} bytes")


if __name__ == "__main__":
    main()
