// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CAsyncSocket@@QEAA@XZ
// Constructor: CAsyncSocket::CAsyncSocket
extern "C" void* MS_ABI impl___0CAsyncSocket__QEAA_XZ(void* pThis) {
    return new(pThis) CAsyncSocket();
}
// Symbol: ??0CInternetSession@@QEAA@PEB_W_KK00K@Z
// Constructor: CInternetSession::CInternetSession
extern "C" void* MS_ABI impl___0CInternetSession__QEAA_PEB_W_KK00K_Z(void* pThis, const wchar_t* p0, unsigned __int64 p1, unsigned long p2, const wchar_t* p3, const wchar_t* p4, unsigned long p5) {
    return new(pThis) CInternetSession(p0, p1, p2, p3, p4, p5);
}
// Symbol: ??0CSocket@@QEAA@XZ
// Constructor: CSocket::CSocket
extern "C" void* MS_ABI impl___0CSocket__QEAA_XZ(void* pThis) {
    return new(pThis) CSocket();
}
// Symbol: ??1CAsyncSocket@@UEAA@XZ
// Destructor: CAsyncSocket::~CAsyncSocket
extern "C" void MS_ABI impl___1CAsyncSocket__UEAA_XZ(void* pThis) {
    ((CAsyncSocket*)pThis)->~CAsyncSocket();
}
// Symbol: ??1CFtpConnection@@UEAA@XZ
// Destructor: CFtpConnection::~CFtpConnection
extern "C" void MS_ABI impl___1CFtpConnection__UEAA_XZ(void* pThis) {
    ((CFtpConnection*)pThis)->~CFtpConnection();
}
// Symbol: ??1CFtpFileFind@@UEAA@XZ
// Destructor: CFtpFileFind::~CFtpFileFind
extern "C" void MS_ABI impl___1CFtpFileFind__UEAA_XZ(void* pThis) {
    ((CFtpFileFind*)pThis)->~CFtpFileFind();
}
// Symbol: ??1CGopherConnection@@UEAA@XZ
// Destructor: CGopherConnection::~CGopherConnection
extern "C" void MS_ABI impl___1CGopherConnection__UEAA_XZ(void* pThis) {
    ((CGopherConnection*)pThis)->~CGopherConnection();
}
// Symbol: ??1CGopherFile@@UEAA@XZ
// Destructor: CGopherFile::~CGopherFile
extern "C" void MS_ABI impl___1CGopherFile__UEAA_XZ(void* pThis) {
    ((CGopherFile*)pThis)->~CGopherFile();
}
// Symbol: ??1CHttpConnection@@UEAA@XZ
// Destructor: CHttpConnection::~CHttpConnection
extern "C" void MS_ABI impl___1CHttpConnection__UEAA_XZ(void* pThis) {
    ((CHttpConnection*)pThis)->~CHttpConnection();
}
// Symbol: ??1CHttpFile@@UEAA@XZ
// Destructor: CHttpFile::~CHttpFile
extern "C" void MS_ABI impl___1CHttpFile__UEAA_XZ(void* pThis) {
    ((CHttpFile*)pThis)->~CHttpFile();
}
// Symbol: ??1CInternetConnection@@UEAA@XZ
// Destructor: CInternetConnection::~CInternetConnection
extern "C" void MS_ABI impl___1CInternetConnection__UEAA_XZ(void* pThis) {
    ((CInternetConnection*)pThis)->~CInternetConnection();
}
// Symbol: ??1CInternetFile@@UEAA@XZ
// Destructor: CInternetFile::~CInternetFile
extern "C" void MS_ABI impl___1CInternetFile__UEAA_XZ(void* pThis) {
    ((CInternetFile*)pThis)->~CInternetFile();
}
// Symbol: ??1CInternetSession@@UEAA@XZ
// Destructor: CInternetSession::~CInternetSession
extern "C" void MS_ABI impl___1CInternetSession__UEAA_XZ(void* pThis) {
    ((CInternetSession*)pThis)->~CInternetSession();
}
// Symbol: ??1CSocket@@UEAA@XZ
// Destructor: CSocket::~CSocket
extern "C" void MS_ABI impl___1CSocket__UEAA_XZ(void* pThis) {
    ((CSocket*)pThis)->~CSocket();
}
// Symbol: ??1CSocketFile@@UEAA@XZ
// Destructor: CSocketFile::~CSocketFile
extern "C" void MS_ABI impl___1CSocketFile__UEAA_XZ(void* pThis) {
    ((CSocketFile*)pThis)->~CSocketFile();
}
// Symbol: ?Accept@CSocket@@UEAAHAEAVCAsyncSocket@@PEAUsockaddr@@PEAH@Z
// CSocket::Accept
extern "C" int MS_ABI impl__Accept_CSocket__UEAAHAEAVCAsyncSocket__PEAUsockaddr__PEAH_Z(CSocket* pThis, CAsyncSocket* p0, sockaddr* p1, int* p2) {
    return (int)pThis->Accept((*p0), p1, p2);
}
// Symbol: ?AsyncSelect@CAsyncSocket@@QEAAHJ@Z
// CAsyncSocket::AsyncSelect
extern "C" int MS_ABI impl__AsyncSelect_CAsyncSocket__QEAAHJ_Z(CAsyncSocket* pThis, long p0) {
    return (int)pThis->AsyncSelect(p0);
}
// Symbol: ?Attach@CAsyncSocket@@QEAAH_KJ@Z
// CAsyncSocket::Attach
extern "C" int MS_ABI impl__Attach_CAsyncSocket__QEAAH_KJ_Z(CAsyncSocket* pThis, unsigned __int64 p0, long p1) {
    return (int)pThis->Attach(p0, p1);
}
// Symbol: ?AuxQueueAdd@CSocket@@KAXI_K_J@Z
// Static: CSocket::AuxQueueAdd
extern "C" void MS_ABI impl__AuxQueueAdd_CSocket__KAXI_K_J_Z(unsigned int p0, unsigned __int64 p1, __int64 p2) {
    CSocket::AuxQueueAdd(p0, p1, p2);
}
// Symbol: ?Bind@CAsyncSocket@@QEAAHIPEB_W@Z
// CAsyncSocket::Bind
extern "C" int MS_ABI impl__Bind_CAsyncSocket__QEAAHIPEB_W_Z(CAsyncSocket* pThis, unsigned int p0, const wchar_t* p1) {
    return (int)pThis->Bind(p0, p1);
}
// Symbol: ?CancelBlockingCall@CSocket@@QEAAXXZ
// CSocket::CancelBlockingCall
extern "C" void MS_ABI impl__CancelBlockingCall_CSocket__QEAAXXZ(CSocket* pThis) {
    pThis->CancelBlockingCall();
}
// Symbol: ?Close@CAsyncSocket@@UEAAXXZ
// CAsyncSocket::Close
extern "C" void MS_ABI impl__Close_CAsyncSocket__UEAAXXZ(CAsyncSocket* pThis) {
    pThis->Close();
}
// Symbol: ?Close@CInternetSession@@UEAAXXZ
// CInternetSession::Close
extern "C" void MS_ABI impl__Close_CInternetSession__UEAAXXZ(CInternetSession* pThis) {
    pThis->Close();
}
// Symbol: ?Close@CSocket@@UEAAXXZ
// CSocket::Close
extern "C" void MS_ABI impl__Close_CSocket__UEAAXXZ(CSocket* pThis) {
    pThis->Close();
}
// Symbol: ?Close@CSocketFile@@UEAAXXZ
// CSocketFile::Close
extern "C" void MS_ABI impl__Close_CSocketFile__UEAAXXZ(CSocketFile* pThis) {
    pThis->Close();
}
// Symbol: ?Command@CFtpConnection@@QEAAPEAVCInternetFile@@PEB_WW4CmdResponseType@1@K_K@Z
// CFtpConnection::Command
extern "C" CInternetFile* MS_ABI impl__Command_CFtpConnection__QEAAPEAVCInternetFile__PEB_WW4CmdResponseType_1_K_K_Z(CFtpConnection* pThis, const wchar_t* p0, CmdResponseType p1, CmdResponseType p2, unsigned long p3, unsigned __int64 p4) {
    return (CInternetFile*)pThis->Command(p0, p1, p2, p3, p4);
}
// Symbol: ?Connect@CAsyncSocket@@QEAAHPEB_WI@Z
// CAsyncSocket::Connect
extern "C" int MS_ABI impl__Connect_CAsyncSocket__QEAAHPEB_WI_Z(CAsyncSocket* pThis, const wchar_t* p0, unsigned int p1) {
    return (int)pThis->Connect(p0, p1);
}
// Symbol: ?ConnectHelper@CAsyncSocket@@MEAAHPEBUsockaddr@@H@Z
// CAsyncSocket::ConnectHelper
extern "C" int MS_ABI impl__ConnectHelper_CAsyncSocket__MEAAHPEBUsockaddr__H_Z(CAsyncSocket* pThis, const sockaddr* p0, int p1) {
    return (int)pThis->ConnectHelper(p0, p1);
}
// Symbol: ?Create@CAsyncSocket@@QEAAHIHJPEB_W@Z
// CAsyncSocket::Create
extern "C" int MS_ABI impl__Create_CAsyncSocket__QEAAHIHJPEB_W_Z(CAsyncSocket* pThis, unsigned int p0, int p1, long p2, const wchar_t* p3) {
    return (int)pThis->Create(p0, p1, p2, p3);
}
// Symbol: ?CreateLocator@CGopherConnection@@QEAA?AVCGopherLocator@@PEB_W0K@Z
// CGopherConnection::CreateLocator  [retval]
extern "C" void MS_ABI impl__CreateLocator_CGopherConnection__QEAA_AVCGopherLocator__PEB_W0K_Z(CGopherConnection* pThis, CGopherLocator* __ret, const wchar_t* p0, CGopherLocator* p1, unsigned long p2) {
    *__ret = pThis->CreateLocator(p0, p1, p2);
}
// Symbol: ?CreateLocator@CGopherConnection@@SA?AVCGopherLocator@@PEB_W@Z
// Static: CGopherConnection::CreateLocator  [retval]
extern "C" void MS_ABI impl__CreateLocator_CGopherConnection__SA_AVCGopherLocator__PEB_W_Z(CGopherLocator* __ret, const wchar_t* p0) {
    *__ret = CGopherConnection::CreateLocator(p0);
}
// Symbol: ?CreateLocator@CGopherConnection@@SA?AVCGopherLocator@@PEB_W00KG@Z
// Static: CGopherConnection::CreateLocator  [retval]
extern "C" void MS_ABI impl__CreateLocator_CGopherConnection__SA_AVCGopherLocator__PEB_W00KG_Z(CGopherLocator* __ret, const wchar_t* p0, CGopherLocator* p1, CGopherLocator* p2, unsigned long p3, unsigned short p4) {
    *__ret = CGopherConnection::CreateLocator(p0, p1, p2, p3, p4);
}
// Symbol: ?Detach@CAsyncSocket@@QEAA_KXZ
// CAsyncSocket::Detach
extern "C" unsigned __int64 MS_ABI impl__Detach_CAsyncSocket__QEAA_KXZ(CAsyncSocket* pThis) {
    return (unsigned __int64)pThis->Detach();
}
// Symbol: ?DetachHandle@CAsyncSocket@@SAX_KH@Z
// Static: CAsyncSocket::DetachHandle
extern "C" void MS_ABI impl__DetachHandle_CAsyncSocket__SAX_KH_Z(unsigned __int64 p0, int p1) {
    CAsyncSocket::DetachHandle(p0, p1);
}
// Symbol: ?DoCallBack@CAsyncSocket@@SAX_K_J@Z
// Static: CAsyncSocket::DoCallBack
extern "C" void MS_ABI impl__DoCallBack_CAsyncSocket__SAX_K_J_Z(unsigned __int64 p0, __int64 p1) {
    CAsyncSocket::DoCallBack(p0, p1);
}
// Symbol: ?EnableStatusCallback@CInternetSession@@QEAAHH@Z
// CInternetSession::EnableStatusCallback
extern "C" int MS_ABI impl__EnableStatusCallback_CInternetSession__QEAAHH_Z(CInternetSession* pThis, int p0) {
    return (int)pThis->EnableStatusCallback(p0);
}
// Symbol: ?EndRequest@CHttpFile@@QEAAHKPEAU_INTERNET_BUFFERSW@@_K@Z
// CHttpFile::EndRequest
extern "C" int MS_ABI impl__EndRequest_CHttpFile__QEAAHKPEAU_INTERNET_BUFFERSW___K_Z(CHttpFile* pThis, unsigned long p0, _INTERNET_BUFFERSW* p1, unsigned __int64 p2) {
    return (int)pThis->EndRequest(p0, p1, p2);
}
// Symbol: ?FindFile@CFtpFileFind@@UEAAHPEB_WK@Z
// CFtpFileFind::FindFile
extern "C" int MS_ABI impl__FindFile_CFtpFileFind__UEAAHPEB_WK_Z(CFtpFileFind* pThis, const wchar_t* p0, unsigned long p1) {
    return (int)pThis->FindFile(p0, p1);
}
// Symbol: ?GetFile@CFtpConnection@@QEAAHPEB_W0HKK_K@Z
// CFtpConnection::GetFile
extern "C" int MS_ABI impl__GetFile_CFtpConnection__QEAAHPEB_W0HKK_K_Z(CFtpConnection* pThis, const wchar_t* p0, const wchar_t* p1, int p2, unsigned long p3, unsigned long p4, unsigned __int64 p5) {
    return (int)pThis->GetFile(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?GetFtpConnection@CInternetSession@@QEAAPEAVCFtpConnection@@PEB_W00GH@Z
// CInternetSession::GetFtpConnection
extern "C" CFtpConnection* MS_ABI impl__GetFtpConnection_CInternetSession__QEAAPEAVCFtpConnection__PEB_W00GH_Z(CInternetSession* pThis, const wchar_t* p0, const wchar_t* p1, const wchar_t* p2, unsigned short p3, int p4) {
    return (CFtpConnection*)pThis->GetFtpConnection(p0, p1, p2, p3, p4);
}
// Symbol: ?GetGopherConnection@CInternetSession@@QEAAPEAVCGopherConnection@@PEB_W00G@Z
// CInternetSession::GetGopherConnection
extern "C" CGopherConnection* MS_ABI impl__GetGopherConnection_CInternetSession__QEAAPEAVCGopherConnection__PEB_W00G_Z(CInternetSession* pThis, const wchar_t* p0, const wchar_t* p1, const wchar_t* p2, unsigned short p3) {
    return (CGopherConnection*)pThis->GetGopherConnection(p0, p1, p2, p3);
}
// Symbol: ?GetHttpConnection@CInternetSession@@QEAAPEAVCHttpConnection@@PEB_WG00@Z
// CInternetSession::GetHttpConnection
extern "C" CHttpConnection* MS_ABI impl__GetHttpConnection_CInternetSession__QEAAPEAVCHttpConnection__PEB_WG00_Z(CInternetSession* pThis, const wchar_t* p0, unsigned short p1, const wchar_t* p2, const wchar_t* p3) {
    return (CHttpConnection*)pThis->GetHttpConnection(p0, p1, p2, p3);
}
// Symbol: ?GetHttpConnection@CInternetSession@@QEAAPEAVCHttpConnection@@PEB_WKG00@Z
// CInternetSession::GetHttpConnection
extern "C" CHttpConnection* MS_ABI impl__GetHttpConnection_CInternetSession__QEAAPEAVCHttpConnection__PEB_WKG00_Z(CInternetSession* pThis, const wchar_t* p0, unsigned long p1, unsigned short p2, const wchar_t* p3, const wchar_t* p4) {
    return (CHttpConnection*)pThis->GetHttpConnection(p0, p1, p2, p3, p4);
}
// Symbol: ?GetLength@CInternetFile@@UEBA_KXZ
// CInternetFile::GetLength
extern "C" unsigned __int64 MS_ABI impl__GetLength_CInternetFile__UEBA_KXZ(const CInternetFile* pThis) {
    return (unsigned __int64)pThis->GetLength();
}
// Symbol: ?OpenFile@CFtpConnection@@QEAAPEAVCInternetFile@@PEB_WKK_K@Z
// CFtpConnection::OpenFile
extern "C" CInternetFile* MS_ABI impl__OpenFile_CFtpConnection__QEAAPEAVCInternetFile__PEB_WKK_K_Z(CFtpConnection* pThis, const wchar_t* p0, unsigned long p1, unsigned long p2, unsigned __int64 p3) {
    return (CInternetFile*)pThis->OpenFile(p0, p1, p2, p3);
}
// Symbol: ?OpenRequest@CHttpConnection@@QEAAPEAVCHttpFile@@PEB_W00_KPEAPEB_W0K@Z
// CHttpConnection::OpenRequest
extern "C" CHttpFile* MS_ABI impl__OpenRequest_CHttpConnection__QEAAPEAVCHttpFile__PEB_W00_KPEAPEB_W0K_Z(CHttpConnection* pThis, const wchar_t* p0, const wchar_t* p1, const wchar_t* p2, unsigned __int64 p3, const wchar_t** p4, const wchar_t* p5, unsigned long p6) {
    return (CHttpFile*)pThis->OpenRequest(p0, p1, p2, p3, p4, p5, p6);
}
// Symbol: ?OpenURL@CInternetSession@@QEAAPEAVCStdioFile@@PEB_W_KK0K@Z
// CInternetSession::OpenURL
extern "C" CStdioFile* MS_ABI impl__OpenURL_CInternetSession__QEAAPEAVCStdioFile__PEB_W_KK0K_Z(CInternetSession* pThis, const wchar_t* p0, unsigned __int64 p1, unsigned long p2, const wchar_t* p3, unsigned long p4) {
    return (CStdioFile*)pThis->OpenURL(p0, p1, p2, p3, p4);
}
// Symbol: ?PutFile@CFtpConnection@@QEAAHPEB_W0K_K@Z
// CFtpConnection::PutFile
extern "C" int MS_ABI impl__PutFile_CFtpConnection__QEAAHPEB_W0K_K_Z(CFtpConnection* pThis, const wchar_t* p0, const wchar_t* p1, unsigned long p2, unsigned __int64 p3) {
    return (int)pThis->PutFile(p0, p1, p2, p3);
}
// Symbol: ?QueryInfoStatusCode@CHttpFile@@QEBAHAEAK@Z
// CHttpFile::QueryInfoStatusCode
extern "C" int MS_ABI impl__QueryInfoStatusCode_CHttpFile__QEBAHAEAK_Z(const CHttpFile* pThis, unsigned long* p0) {
    return (int)pThis->QueryInfoStatusCode((*p0));
}
// Symbol: ?QueryOption@CInternetSession@@QEBAHKPEAXPEAK@Z
// CInternetSession::QueryOption
extern "C" int MS_ABI impl__QueryOption_CInternetSession__QEBAHKPEAXPEAK_Z(const CInternetSession* pThis, unsigned long p0, void* p1, unsigned long* p2) {
    return (int)pThis->QueryOption(p0, p1, p2);
}
// Symbol: ?Read@CInternetFile@@UEAAIPEAXI@Z
// CInternetFile::Read
extern "C" unsigned int MS_ABI impl__Read_CInternetFile__UEAAIPEAXI_Z(CInternetFile* pThis, void* p0, unsigned int p1) {
    return (unsigned int)pThis->Read(p0, p1);
}
// Symbol: ?Read@CSocketFile@@UEAAIPEAXI@Z
// CSocketFile::Read
extern "C" unsigned int MS_ABI impl__Read_CSocketFile__UEAAIPEAXI_Z(CSocketFile* pThis, void* p0, unsigned int p1) {
    return (unsigned int)pThis->Read(p0, p1);
}
// Symbol: ?Receive@CAsyncSocket@@UEAAHPEAXHH@Z
// CAsyncSocket::Receive
extern "C" int MS_ABI impl__Receive_CAsyncSocket__UEAAHPEAXHH_Z(CAsyncSocket* pThis, void* p0, int p1, int p2) {
    return (int)pThis->Receive(p0, p1, p2);
}
// Symbol: ?Receive@CSocket@@UEAAHPEAXHH@Z
// CSocket::Receive
extern "C" int MS_ABI impl__Receive_CSocket__UEAAHPEAXHH_Z(CSocket* pThis, void* p0, int p1, int p2) {
    return (int)pThis->Receive(p0, p1, p2);
}
// Symbol: ?Remove@CFtpConnection@@QEAAHPEB_W@Z
// CFtpConnection::Remove
extern "C" int MS_ABI impl__Remove_CFtpConnection__QEAAHPEB_W_Z(CFtpConnection* pThis, const wchar_t* p0) {
    return (int)pThis->Remove(p0);
}
// Symbol: ?Rename@CFtpConnection@@QEAAHPEB_W0@Z
// CFtpConnection::Rename
extern "C" int MS_ABI impl__Rename_CFtpConnection__QEAAHPEB_W0_Z(CFtpConnection* pThis, const wchar_t* p0, const wchar_t* p1) {
    return (int)pThis->Rename(p0, p1);
}
// Symbol: ?Seek@CInternetFile@@UEAA_K_JI@Z
// CInternetFile::Seek
extern "C" unsigned __int64 MS_ABI impl__Seek_CInternetFile__UEAA_K_JI_Z(CInternetFile* pThis, __int64 p0, unsigned int p1) {
    return (unsigned __int64)pThis->Seek(p0, p1);
}
// Symbol: ?Seek@CSocketFile@@UEAA_K_JI@Z
// CSocketFile::Seek
extern "C" unsigned __int64 MS_ABI impl__Seek_CSocketFile__UEAA_K_JI_Z(CSocketFile* pThis, __int64 p0, unsigned int p1) {
    return (unsigned __int64)pThis->Seek(p0, p1);
}
// Symbol: ?Send@CAsyncSocket@@UEAAHPEBXHH@Z
// CAsyncSocket::Send
extern "C" int MS_ABI impl__Send_CAsyncSocket__UEAAHPEBXHH_Z(CAsyncSocket* pThis, const void* p0, int p1, int p2) {
    return (int)pThis->Send(p0, p1, p2);
}
// Symbol: ?Send@CSocket@@UEAAHPEBXHH@Z
// CSocket::Send
extern "C" int MS_ABI impl__Send_CSocket__UEAAHPEBXHH_Z(CSocket* pThis, const void* p0, int p1, int p2) {
    return (int)pThis->Send(p0, p1, p2);
}
// Symbol: ?SendRequest@CHttpFile@@QEAAHPEB_WKPEAXK@Z
// CHttpFile::SendRequest
extern "C" int MS_ABI impl__SendRequest_CHttpFile__QEAAHPEB_WKPEAXK_Z(CHttpFile* pThis, const wchar_t* p0, unsigned long p1, void* p2, unsigned long p3) {
    return (int)pThis->SendRequest(p0, p1, p2, p3);
}
// Symbol: ?SendRequestEx@CHttpFile@@QEAAHKK_K@Z
// CHttpFile::SendRequestEx
extern "C" int MS_ABI impl__SendRequestEx_CHttpFile__QEAAHKK_K_Z(CHttpFile* pThis, unsigned long p0, unsigned long p1, unsigned __int64 p2) {
    return (int)pThis->SendRequestEx(p0, p1, p2);
}
// Symbol: ?SendRequestEx@CHttpFile@@QEAAHPEAU_INTERNET_BUFFERSW@@0K_K@Z
// CHttpFile::SendRequestEx
extern "C" int MS_ABI impl__SendRequestEx_CHttpFile__QEAAHPEAU_INTERNET_BUFFERSW__0K_K_Z(CHttpFile* pThis, _INTERNET_BUFFERSW* p0, _INTERNET_BUFFERSW* p1, unsigned long p2, unsigned __int64 p3) {
    return (int)pThis->SendRequestEx(p0, p1, p2, p3);
}
// Symbol: ?SendTo@CAsyncSocket@@QEAAHPEBXHIPEB_WH@Z
// CAsyncSocket::SendTo
extern "C" int MS_ABI impl__SendTo_CAsyncSocket__QEAAHPEBXHIPEB_WH_Z(CAsyncSocket* pThis, const void* p0, int p1, unsigned int p2, const wchar_t* p3, int p4) {
    return (int)pThis->SendTo(p0, p1, p2, p3, p4);
}
// Symbol: ?SetReadBufferSize@CInternetFile@@QEAAHI@Z
// CInternetFile::SetReadBufferSize
extern "C" int MS_ABI impl__SetReadBufferSize_CInternetFile__QEAAHI_Z(CInternetFile* pThis, unsigned int p0) {
    return (int)pThis->SetReadBufferSize(p0);
}
// Symbol: ?SetWriteBufferSize@CInternetFile@@QEAAHI@Z
// CInternetFile::SetWriteBufferSize
extern "C" int MS_ABI impl__SetWriteBufferSize_CInternetFile__QEAAHI_Z(CInternetFile* pThis, unsigned int p0) {
    return (int)pThis->SetWriteBufferSize(p0);
}
// Symbol: ?Write@CSocketFile@@UEAAXPEBXI@Z
// CSocketFile::Write
extern "C" void MS_ABI impl__Write_CSocketFile__UEAAXPEBXI_Z(CSocketFile* pThis, const void* p0, unsigned int p1) {
    pThis->Write(p0, p1);
}
