// Thunks — OpenMFC implementation.
// Sources: thunks.cpp

#define OPENMFC_APPCORE_IMPL

// Auto-generated thunks ? routes DLL exports through real C++ implementations
// Generated by tools/gen_thunks.py
// DO NOT EDIT

#define OPENMFC_APPCORE_IMPL

#ifdef __GNUC__
  #define MS_ABI __attribute__((ms_abi))
#else
  #define MS_ABI
#endif

#include "openmfc/afxwin.h"
#include "openmfc/afxole.h"
#include "openmfc/afxmfc.h"
#include "openmfc/afxdb.h"
#include "openmfc/afxinet.h"
#include "openmfc/afxsock.h"
#include "openmfc/afx.h"

// For memcpy
#include <cstring>












































































































































































































































































































































































































































































































































































// CMFCBaseTabCtrl::AddTab lived here under 32-bit markers (PAVCWnd/PB_W) that
// matched no export, and the resource-id overload was one parameter short of
// its retail signature. Both are now in ctrl_mfcbasetabctrl_addtab.cpp with the
// correct 64-bit mangling. They are NOT emitted by gen_thunks.py, so keeping
// them here would lose them on the next regeneration.













































































































































































































































































































































































































































































































































// Generated 1074 thunks
// Errors (could not parse): 0
// Symbol: ??0CEnumFormatEtc@@QEAA@XZ
// Constructor: CEnumFormatEtc::CEnumFormatEtc
extern "C" void* MS_ABI impl___0CEnumFormatEtc__QEAA_XZ(void* pThis) {
    return new(pThis) CEnumFormatEtc();
}
// Symbol: ??0COleControl@@QEAA@XZ
// Constructor: COleControl::COleControl
extern "C" void* MS_ABI impl___0COleControl__QEAA_XZ(void* pThis) {
    return new(pThis) COleControl();
}
// Symbol: ??0COleCurrency@@QEAA@JJ@Z
// Constructor: COleCurrency::COleCurrency
extern "C" void* MS_ABI impl___0COleCurrency__QEAA_JJ_Z(void* pThis, long p0, long p1) {
    return new(pThis) COleCurrency(p0, p1);
}
// Symbol: ??0COleDataObject@@QEAA@XZ
// Constructor: COleDataObject::COleDataObject
extern "C" void* MS_ABI impl___0COleDataObject__QEAA_XZ(void* pThis) {
    return new(pThis) COleDataObject();
}
// Symbol: ??0COleDataSource@@QEAA@XZ
// Constructor: COleDataSource::COleDataSource
extern "C" void* MS_ABI impl___0COleDataSource__QEAA_XZ(void* pThis) {
    return new(pThis) COleDataSource();
}
// Symbol: ??0COleDocument@@QEAA@XZ
// Constructor: COleDocument::COleDocument
extern "C" void* MS_ABI impl___0COleDocument__QEAA_XZ(void* pThis) {
    return new(pThis) COleDocument();
}
// Symbol: ??0COleDropSource@@QEAA@XZ
// Constructor: COleDropSource::COleDropSource
extern "C" void* MS_ABI impl___0COleDropSource__QEAA_XZ(void* pThis) {
    return new(pThis) COleDropSource();
}
// Symbol: ??0COleDropTarget@@QEAA@XZ
// Constructor: COleDropTarget::COleDropTarget
extern "C" void* MS_ABI impl___0COleDropTarget__QEAA_XZ(void* pThis) {
    return new(pThis) COleDropTarget();
}
// Symbol: ??0COleIPFrameWnd@@QEAA@XZ
// Constructor: COleIPFrameWnd::COleIPFrameWnd
extern "C" void* MS_ABI impl___0COleIPFrameWnd__QEAA_XZ(void* pThis) {
    return new(pThis) COleIPFrameWnd();
}
// Symbol: ??0COleLinkingDoc@@QEAA@XZ
// Constructor: COleLinkingDoc::COleLinkingDoc
extern "C" void* MS_ABI impl___0COleLinkingDoc__QEAA_XZ(void* pThis) {
    return new(pThis) COleLinkingDoc();
}
// Symbol: ??0COleMessageFilter@@QEAA@XZ
// Constructor: COleMessageFilter::COleMessageFilter
extern "C" void* MS_ABI impl___0COleMessageFilter__QEAA_XZ(void* pThis) {
    return new(pThis) COleMessageFilter();
}
// Symbol: ??0COlePropertyPage@@QEAA@II@Z
// Constructor: COlePropertyPage::COlePropertyPage
extern "C" void* MS_ABI impl___0COlePropertyPage__QEAA_II_Z(void* pThis, unsigned int p0, unsigned int p1) {
    return new(pThis) COlePropertyPage(p0, p1);
}
// Symbol: ??0COleServerDoc@@QEAA@XZ
// Constructor: COleServerDoc::COleServerDoc
extern "C" void* MS_ABI impl___0COleServerDoc__QEAA_XZ(void* pThis) {
    return new(pThis) COleServerDoc();
}
// Symbol: ??0COleTemplateServer@@QEAA@XZ
// Constructor: COleTemplateServer::COleTemplateServer
extern "C" void* MS_ABI impl___0COleTemplateServer__QEAA_XZ(void* pThis) {
    return new(pThis) COleTemplateServer();
}
// Symbol: ??1CEnumFormatEtc@@UEAA@XZ
// Destructor: CEnumFormatEtc::~CEnumFormatEtc
extern "C" void MS_ABI impl___1CEnumFormatEtc__UEAA_XZ(void* pThis) {
    ((CEnumFormatEtc*)pThis)->~CEnumFormatEtc();
}
// Symbol: ??1CEnumOleVerb@@UEAA@XZ
// Destructor: CEnumOleVerb::~CEnumOleVerb
extern "C" void MS_ABI impl___1CEnumOleVerb__UEAA_XZ(void* pThis) {
    ((CEnumOleVerb*)pThis)->~CEnumOleVerb();
}
// Symbol: ??1COleBusyDialog@@UEAA@XZ
// Destructor: COleBusyDialog::~COleBusyDialog
extern "C" void MS_ABI impl___1COleBusyDialog__UEAA_XZ(void* pThis) {
    ((COleBusyDialog*)pThis)->~COleBusyDialog();
}
// Symbol: ??1COleChangeIconDialog@@UEAA@XZ
// Destructor: COleChangeIconDialog::~COleChangeIconDialog
extern "C" void MS_ABI impl___1COleChangeIconDialog__UEAA_XZ(void* pThis) {
    ((COleChangeIconDialog*)pThis)->~COleChangeIconDialog();
}
// Symbol: ??1COleChangeSourceDialog@@UEAA@XZ
// Destructor: COleChangeSourceDialog::~COleChangeSourceDialog
extern "C" void MS_ABI impl___1COleChangeSourceDialog__UEAA_XZ(void* pThis) {
    ((COleChangeSourceDialog*)pThis)->~COleChangeSourceDialog();
}
// Symbol: ??1COleClientItem@@UEAA@XZ
// Destructor: COleClientItem::~COleClientItem
extern "C" void MS_ABI impl___1COleClientItem__UEAA_XZ(void* pThis) {
    ((COleClientItem*)pThis)->~COleClientItem();
}
// Symbol: ??1COleControl@@UEAA@XZ
// Destructor: COleControl::~COleControl
extern "C" void MS_ABI impl___1COleControl__UEAA_XZ(void* pThis) {
    ((COleControl*)pThis)->~COleControl();
}
// Symbol: ??1COleControlContainer@@UEAA@XZ
// Destructor: COleControlContainer::~COleControlContainer
extern "C" void MS_ABI impl___1COleControlContainer__UEAA_XZ(void* pThis) {
    ((COleControlContainer*)pThis)->~COleControlContainer();
}
// Symbol: ??1COleControlSite@@UEAA@XZ
// Destructor: COleControlSite::~COleControlSite
extern "C" void MS_ABI impl___1COleControlSite__UEAA_XZ(void* pThis) {
    ((COleControlSite*)pThis)->~COleControlSite();
}
// Symbol: ??1COleConvertDialog@@UEAA@XZ
// Destructor: COleConvertDialog::~COleConvertDialog
extern "C" void MS_ABI impl___1COleConvertDialog__UEAA_XZ(void* pThis) {
    ((COleConvertDialog*)pThis)->~COleConvertDialog();
}
// Symbol: ??1COleDataSource@@UEAA@XZ
// Destructor: COleDataSource::~COleDataSource
extern "C" void MS_ABI impl___1COleDataSource__UEAA_XZ(void* pThis) {
    ((COleDataSource*)pThis)->~COleDataSource();
}
// Symbol: ??1COleDocObjectItem@@UEAA@XZ
// Destructor: COleDocObjectItem::~COleDocObjectItem
extern "C" void MS_ABI impl___1COleDocObjectItem__UEAA_XZ(void* pThis) {
    ((COleDocObjectItem*)pThis)->~COleDocObjectItem();
}
// Symbol: ??1COleDocument@@UEAA@XZ
// Destructor: COleDocument::~COleDocument
extern "C" void MS_ABI impl___1COleDocument__UEAA_XZ(void* pThis) {
    ((COleDocument*)pThis)->~COleDocument();
}
// Symbol: ??1COleDropTarget@@UEAA@XZ
// Destructor: COleDropTarget::~COleDropTarget
extern "C" void MS_ABI impl___1COleDropTarget__UEAA_XZ(void* pThis) {
    ((COleDropTarget*)pThis)->~COleDropTarget();
}
// Symbol: ??1COleFrameHook@@UEAA@XZ
// Destructor: COleFrameHook::~COleFrameHook
extern "C" void MS_ABI impl___1COleFrameHook__UEAA_XZ(void* pThis) {
    ((COleFrameHook*)pThis)->~COleFrameHook();
}
// Symbol: ??1COleInsertDialog@@UEAA@XZ
// Destructor: COleInsertDialog::~COleInsertDialog
extern "C" void MS_ABI impl___1COleInsertDialog__UEAA_XZ(void* pThis) {
    ((COleInsertDialog*)pThis)->~COleInsertDialog();
}
// Symbol: ??1COleIPFrameWnd@@UEAA@XZ
// Destructor: COleIPFrameWnd::~COleIPFrameWnd
extern "C" void MS_ABI impl___1COleIPFrameWnd__UEAA_XZ(void* pThis) {
    ((COleIPFrameWnd*)pThis)->~COleIPFrameWnd();
}
// Symbol: ??1COleLinkingDoc@@UEAA@XZ
// Destructor: COleLinkingDoc::~COleLinkingDoc
extern "C" void MS_ABI impl___1COleLinkingDoc__UEAA_XZ(void* pThis) {
    ((COleLinkingDoc*)pThis)->~COleLinkingDoc();
}
// Symbol: ??1COleLinksDialog@@UEAA@XZ
// Destructor: COleLinksDialog::~COleLinksDialog
extern "C" void MS_ABI impl___1COleLinksDialog__UEAA_XZ(void* pThis) {
    ((COleLinksDialog*)pThis)->~COleLinksDialog();
}
// Symbol: ??1COleMessageFilter@@UEAA@XZ
// Destructor: COleMessageFilter::~COleMessageFilter
extern "C" void MS_ABI impl___1COleMessageFilter__UEAA_XZ(void* pThis) {
    ((COleMessageFilter*)pThis)->~COleMessageFilter();
}
// Symbol: ??1COleObjectFactory@@UEAA@XZ
// Destructor: COleObjectFactory::~COleObjectFactory
extern "C" void MS_ABI impl___1COleObjectFactory__UEAA_XZ(void* pThis) {
    ((COleObjectFactory*)pThis)->~COleObjectFactory();
}
// Symbol: ??1COlePasteSpecialDialog@@UEAA@XZ
// Destructor: COlePasteSpecialDialog::~COlePasteSpecialDialog
extern "C" void MS_ABI impl___1COlePasteSpecialDialog__UEAA_XZ(void* pThis) {
    ((COlePasteSpecialDialog*)pThis)->~COlePasteSpecialDialog();
}
// Symbol: ??1COlePropertyPage@@UEAA@XZ
// Destructor: COlePropertyPage::~COlePropertyPage
extern "C" void MS_ABI impl___1COlePropertyPage__UEAA_XZ(void* pThis) {
    ((COlePropertyPage*)pThis)->~COlePropertyPage();
}
// Symbol: ??1COleServerDoc@@UEAA@XZ
// Destructor: COleServerDoc::~COleServerDoc
extern "C" void MS_ABI impl___1COleServerDoc__UEAA_XZ(void* pThis) {
    ((COleServerDoc*)pThis)->~COleServerDoc();
}
// Symbol: ??1COleServerItem@@UEAA@XZ
// Destructor: COleServerItem::~COleServerItem
extern "C" void MS_ABI impl___1COleServerItem__UEAA_XZ(void* pThis) {
    ((COleServerItem*)pThis)->~COleServerItem();
}
// Symbol: ??1COleStreamFile@@UEAA@XZ
// Destructor: COleStreamFile::~COleStreamFile
extern "C" void MS_ABI impl___1COleStreamFile__UEAA_XZ(void* pThis) {
    ((COleStreamFile*)pThis)->~COleStreamFile();
}
// Symbol: ??1COleUpdateDialog@@UEAA@XZ
// Destructor: COleUpdateDialog::~COleUpdateDialog
extern "C" void MS_ABI impl___1COleUpdateDialog__UEAA_XZ(void* pThis) {
    ((COleUpdateDialog*)pThis)->~COleUpdateDialog();
}
// Symbol: ?AccessData@COleSafeArray@@QEAAXPEAPEAX@Z
// COleSafeArray::AccessData
extern "C" void MS_ABI impl__AccessData_COleSafeArray__QEAAXPEAPEAX_Z(COleSafeArray* pThis, void** p0) {
    pThis->AccessData(p0);
}
// Symbol: ?ActivateAndShow@COleDocObjectItem@@IEAAXXZ
// COleDocObjectItem::ActivateAndShow
extern "C" void MS_ABI impl__ActivateAndShow_COleDocObjectItem__IEAAXXZ(COleDocObjectItem* pThis) {
    pThis->ActivateAndShow();
}
// Symbol: ?AddFormat@COlePasteSpecialDialog@@QEAAXAEBUtagFORMATETC@@PEA_W1K@Z
// COlePasteSpecialDialog::AddFormat
extern "C" void MS_ABI impl__AddFormat_COlePasteSpecialDialog__QEAAXAEBUtagFORMATETC__PEA_W1K_Z(COlePasteSpecialDialog* pThis, const FORMATETC* p0, wchar_t* p1, wchar_t* p2, unsigned long p3) {
    pThis->AddFormat((*p0), p1, p2, p3);
}
// Symbol: ?AddLinkEntry@COlePasteSpecialDialog@@QEAA?AW4tagOLEUIPASTEFLAG@@I@Z
// COlePasteSpecialDialog::AddLinkEntry  [retval]
extern "C" void MS_ABI impl__AddLinkEntry_COlePasteSpecialDialog__QEAA_AW4tagOLEUIPASTEFLAG__I_Z(COlePasteSpecialDialog* pThis, tagOLEUIPASTEFLAG* __ret, unsigned int p0) {
    *__ret = pThis->AddLinkEntry(p0);
}
// Symbol: ?AddStandardFormats@COlePasteSpecialDialog@@QEAAXH@Z
// COlePasteSpecialDialog::AddStandardFormats
extern "C" void MS_ABI impl__AddStandardFormats_COlePasteSpecialDialog__QEAAXH_Z(COlePasteSpecialDialog* pThis, int p0) {
    pThis->AddStandardFormats(p0);
}
// Symbol: ?AmbientAppearance@COleControl@@QEAAFXZ
// COleControl::AmbientAppearance
extern "C" short MS_ABI impl__AmbientAppearance_COleControl__QEAAFXZ(COleControl* pThis) {
    return (short)pThis->AmbientAppearance();
}
// Symbol: ?AmbientBackColor@COleControl@@QEAAKXZ
// COleControl::AmbientBackColor
extern "C" unsigned long MS_ABI impl__AmbientBackColor_COleControl__QEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->AmbientBackColor();
}
// Symbol: ?AmbientFont@COleControl@@QEAAPEAUIFontDisp@@XZ
// COleControl::AmbientFont
extern "C" IFontDisp* MS_ABI impl__AmbientFont_COleControl__QEAAPEAUIFontDisp__XZ(COleControl* pThis) {
    return (IFontDisp*)pThis->AmbientFont();
}
// Symbol: ?AmbientForeColor@COleControl@@QEAAKXZ
// COleControl::AmbientForeColor
extern "C" unsigned long MS_ABI impl__AmbientForeColor_COleControl__QEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->AmbientForeColor();
}
// Symbol: ?AmbientLocaleID@COleControl@@QEAAKXZ
// COleControl::AmbientLocaleID
extern "C" unsigned long MS_ABI impl__AmbientLocaleID_COleControl__QEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->AmbientLocaleID();
}
// Symbol: ?AmbientShowGrabHandles@COleControl@@QEAAHXZ
// COleControl::AmbientShowGrabHandles
extern "C" int MS_ABI impl__AmbientShowGrabHandles_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->AmbientShowGrabHandles();
}
// Symbol: ?AmbientShowHatching@COleControl@@QEAAHXZ
// COleControl::AmbientShowHatching
extern "C" int MS_ABI impl__AmbientShowHatching_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->AmbientShowHatching();
}
// Symbol: ?AmbientTextAlign@COleControl@@QEAAFXZ
// COleControl::AmbientTextAlign
extern "C" short MS_ABI impl__AmbientTextAlign_COleControl__QEAAFXZ(COleControl* pThis) {
    return (short)pThis->AmbientTextAlign();
}
// Symbol: ?AmbientUIDead@COleControl@@QEAAHXZ
// COleControl::AmbientUIDead
extern "C" int MS_ABI impl__AmbientUIDead_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->AmbientUIDead();
}
// Symbol: ?AmbientUserMode@COleControl@@QEAAHXZ
// COleControl::AmbientUserMode
extern "C" int MS_ABI impl__AmbientUserMode_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->AmbientUserMode();
}
// Symbol: ?Attach@COleDataObject@@QEAAXPEAUIDataObject@@H@Z
// COleDataObject::Attach
extern "C" void MS_ABI impl__Attach_COleDataObject__QEAAXPEAUIDataObject__H_Z(COleDataObject* pThis, IDataObject* p0, int p1) {
    pThis->Attach(p0, p1);
}
// Symbol: ?Attach@COleStreamFile@@QEAAXPEAUIStream@@@Z
// COleStreamFile::Attach
extern "C" void MS_ABI impl__Attach_COleStreamFile__QEAAXPEAUIStream___Z(COleStreamFile* pThis, IStream* p0) {
    pThis->Attach(p0);
}
// Symbol: ?AttachClipboard@COleDataObject@@QEAAHXZ
// COleDataObject::AttachClipboard
extern "C" int MS_ABI impl__AttachClipboard_COleDataObject__QEAAHXZ(COleDataObject* pThis) {
    return (int)pThis->AttachClipboard();
}
// Symbol: ?AttachDataObject@COleClientItem@@QEBAXAEAVCOleDataObject@@@Z
// COleClientItem::AttachDataObject
extern "C" void MS_ABI impl__AttachDataObject_COleClientItem__QEBAXAEAVCOleDataObject___Z(const COleClientItem* pThis, COleDataObject* p0) {
    pThis->AttachDataObject((*p0));
}
// Symbol: ?BeginBusyState@COleMessageFilter@@UEAAXXZ
// COleMessageFilter::BeginBusyState
extern "C" void MS_ABI impl__BeginBusyState_COleMessageFilter__UEAAXXZ(COleMessageFilter* pThis) {
    pThis->BeginBusyState();
}
// Symbol: ?BeginEnumFormats@COleDataObject@@QEAAXXZ
// COleDataObject::BeginEnumFormats
extern "C" void MS_ABI impl__BeginEnumFormats_COleDataObject__QEAAXXZ(COleDataObject* pThis) {
    pThis->BeginEnumFormats();
}
// Symbol: ?BoundPropertyChanged@COleControl@@QEAAXJ@Z
// COleControl::BoundPropertyChanged
extern "C" void MS_ABI impl__BoundPropertyChanged_COleControl__QEAAXJ_Z(COleControl* pThis, long p0) {
    pThis->BoundPropertyChanged(p0);
}
// Symbol: ?BoundPropertyRequestEdit@COleControl@@QEAAHJ@Z
// COleControl::BoundPropertyRequestEdit
extern "C" int MS_ABI impl__BoundPropertyRequestEdit_COleControl__QEAAHJ_Z(COleControl* pThis, long p0) {
    return (int)pThis->BoundPropertyRequestEdit(p0);
}
// Symbol: ?CacheData@COleDataSource@@QEAAXGPEAUtagSTGMEDIUM@@PEAUtagFORMATETC@@@Z
// COleDataSource::CacheData
extern "C" void MS_ABI impl__CacheData_COleDataSource__QEAAXGPEAUtagSTGMEDIUM__PEAUtagFORMATETC___Z(COleDataSource* pThis, unsigned short p0, STGMEDIUM* p1, FORMATETC* p2) {
    pThis->CacheData(p0, p1, p2);
}
// Symbol: ?CacheGlobalData@COleDataSource@@QEAAXGPEAXPEAUtagFORMATETC@@@Z
// COleDataSource::CacheGlobalData
extern "C" void MS_ABI impl__CacheGlobalData_COleDataSource__QEAAXGPEAXPEAUtagFORMATETC___Z(COleDataSource* pThis, unsigned short p0, void* p1, FORMATETC* p2) {
    pThis->CacheGlobalData(p0, p1, p2);
}
// Symbol: ?CanActivate@COleClientItem@@MEAAHXZ
// COleClientItem::CanActivate
extern "C" int MS_ABI impl__CanActivate_COleClientItem__MEAAHXZ(COleClientItem* pThis) {
    return (int)pThis->CanActivate();
}
// Symbol: ?Close@COleClientItem@@QEAAXW4tagOLECLOSE@@@Z
// COleClientItem::Close
extern "C" void MS_ABI impl__Close_COleClientItem__QEAAXW4tagOLECLOSE___Z(COleClientItem* pThis, tagOLECLOSE p0) {
    pThis->Close(p0);
}
// Symbol: ?CommonConstruct@COleObjectFactory@@IEAAXAEBU_GUID@@PEAUCRuntimeClass@@HHPEB_W@Z
// COleObjectFactory::CommonConstruct
extern "C" void MS_ABI impl__CommonConstruct_COleObjectFactory__IEAAXAEBU_GUID__PEAUCRuntimeClass__HHPEB_W_Z(COleObjectFactory* pThis, const _GUID* p0, CRuntimeClass* p1, int p2, int p3, const wchar_t* p4) {
    pThis->CommonConstruct((*p0), p1, p2, p3, p4);
}
// Symbol: ?ConvertTo@COleClientItem@@UEAAHAEBU_GUID@@@Z
// COleClientItem::ConvertTo
extern "C" int MS_ABI impl__ConvertTo_COleClientItem__UEAAHAEBU_GUID___Z(COleClientItem* pThis, const _GUID* p0) {
    return (int)pThis->ConvertTo((*p0));
}
// Symbol: ?CopyToClipboard@COleClientItem@@QEAAXH@Z
// COleClientItem::CopyToClipboard
extern "C" void MS_ABI impl__CopyToClipboard_COleClientItem__QEAAXH_Z(COleClientItem* pThis, int p0) {
    pThis->CopyToClipboard(p0);
}
// Symbol: ?CopyToClipboard@COleServerItem@@QEAAXH@Z
// COleServerItem::CopyToClipboard
extern "C" void MS_ABI impl__CopyToClipboard_COleServerItem__QEAAXH_Z(COleServerItem* pThis, int p0) {
    pThis->CopyToClipboard(p0);
}
// Symbol: ?Create@COleSafeArray@@QEAAXGKPEAUtagSAFEARRAYBOUND@@@Z
// COleSafeArray::Create
extern "C" void MS_ABI impl__Create_COleSafeArray__QEAAXGKPEAUtagSAFEARRAYBOUND___Z(COleSafeArray* pThis, unsigned short p0, unsigned long p1, SAFEARRAYBOUND* p2) {
    pThis->Create(p0, p1, p2);
}
// Symbol: ?CreateControl@COleControlSite@@UEAAJPEAVCWnd@@AEBU_GUID@@PEB_WKAEBUtagRECT@@IPEAVCFile@@HPEA_W@Z
// COleControlSite::CreateControl
extern "C" long MS_ABI impl__CreateControl_COleControlSite__UEAAJPEAVCWnd__AEBU_GUID__PEB_WKAEBUtagRECT__IPEAVCFile__HPEA_W_Z(COleControlSite* pThis, CWnd* p0, const _GUID* p1, const wchar_t* p2, unsigned long p3, const RECT* p4, unsigned int p5, CFile* p6, int p7, wchar_t* p8) {
    return (long)pThis->CreateControl(p0, (*p1), p2, p3, (*p4), p5, p6, p7, p8);
}
// Symbol: ?CreateFromClipboard@COleClientItem@@QEAAHW4tagOLERENDER@@GPEAUtagFORMATETC@@@Z
// COleClientItem::CreateFromClipboard
extern "C" int MS_ABI impl__CreateFromClipboard_COleClientItem__QEAAHW4tagOLERENDER__GPEAUtagFORMATETC___Z(COleClientItem* pThis, tagOLERENDER p0, unsigned short p1, FORMATETC* p2) {
    return (int)pThis->CreateFromClipboard(p0, p1, p2);
}
// Symbol: ?CreateFromData@COleClientItem@@QEAAHPEAVCOleDataObject@@W4tagOLERENDER@@GPEAUtagFORMATETC@@@Z
// COleClientItem::CreateFromData
extern "C" int MS_ABI impl__CreateFromData_COleClientItem__QEAAHPEAVCOleDataObject__W4tagOLERENDER__GPEAUtagFORMATETC___Z(COleClientItem* pThis, COleDataObject* p0, tagOLERENDER p1, unsigned short p2, FORMATETC* p3) {
    return (int)pThis->CreateFromData(p0, p1, p2, p3);
}
// Symbol: ?CreateItem@COleInsertDialog@@QEAAHPEAVCOleClientItem@@@Z
// COleInsertDialog::CreateItem
extern "C" int MS_ABI impl__CreateItem_COleInsertDialog__QEAAHPEAVCOleClientItem___Z(COleInsertDialog* pThis, COleClientItem* p0) {
    return (int)pThis->CreateItem(p0);
}
// Symbol: ?CreateItem@COlePasteSpecialDialog@@QEAAHPEAVCOleClientItem@@@Z
// COlePasteSpecialDialog::CreateItem
extern "C" int MS_ABI impl__CreateItem_COlePasteSpecialDialog__QEAAHPEAVCOleClientItem___Z(COlePasteSpecialDialog* pThis, COleClientItem* p0) {
    return (int)pThis->CreateItem(p0);
}
// Symbol: ?CreateLinkFromClipboard@COleClientItem@@QEAAHW4tagOLERENDER@@GPEAUtagFORMATETC@@@Z
// COleClientItem::CreateLinkFromClipboard
extern "C" int MS_ABI impl__CreateLinkFromClipboard_COleClientItem__QEAAHW4tagOLERENDER__GPEAUtagFORMATETC___Z(COleClientItem* pThis, tagOLERENDER p0, unsigned short p1, FORMATETC* p2) {
    return (int)pThis->CreateLinkFromClipboard(p0, p1, p2);
}
// Symbol: ?CreateNewItem@COleClientItem@@QEAAHAEBU_GUID@@W4tagOLERENDER@@GPEAUtagFORMATETC@@@Z
// COleClientItem::CreateNewItem
extern "C" int MS_ABI impl__CreateNewItem_COleClientItem__QEAAHAEBU_GUID__W4tagOLERENDER__GPEAUtagFORMATETC___Z(COleClientItem* pThis, const _GUID* p0, tagOLERENDER p1, unsigned short p2, FORMATETC* p3) {
    return (int)pThis->CreateNewItem((*p0), p1, p2, p3);
}
// Symbol: ?CreateStaticFromClipboard@COleClientItem@@QEAAHW4tagOLERENDER@@GPEAUtagFORMATETC@@@Z
// COleClientItem::CreateStaticFromClipboard
extern "C" int MS_ABI impl__CreateStaticFromClipboard_COleClientItem__QEAAHW4tagOLERENDER__GPEAUtagFORMATETC___Z(COleClientItem* pThis, tagOLERENDER p0, unsigned short p1, FORMATETC* p2) {
    return (int)pThis->CreateStaticFromClipboard(p0, p1, p2);
}
// Symbol: ?Deactivate@COleClientItem@@QEAAXXZ
// COleClientItem::Deactivate
extern "C" void MS_ABI impl__Deactivate_COleClientItem__QEAAXXZ(COleClientItem* pThis) {
    pThis->Deactivate();
}
// Symbol: ?DelayRenderData@COleDataSource@@QEAAXGPEAUtagFORMATETC@@@Z
// COleDataSource::DelayRenderData
extern "C" void MS_ABI impl__DelayRenderData_COleDataSource__QEAAXGPEAUtagFORMATETC___Z(COleDataSource* pThis, unsigned short p0, FORMATETC* p1) {
    pThis->DelayRenderData(p0, p1);
}
// Symbol: ?DelayRenderFileData@COleDataSource@@QEAAXGPEAUtagFORMATETC@@@Z
// COleDataSource::DelayRenderFileData
extern "C" void MS_ABI impl__DelayRenderFileData_COleDataSource__QEAAXGPEAUtagFORMATETC___Z(COleDataSource* pThis, unsigned short p0, FORMATETC* p1) {
    pThis->DelayRenderFileData(p0, p1);
}
// Symbol: ?Destroy@COleSafeArray@@QEAAXXZ
// COleSafeArray::Destroy
extern "C" void MS_ABI impl__Destroy_COleSafeArray__QEAAXXZ(COleSafeArray* pThis) {
    pThis->Destroy();
}
// Symbol: ?DestroyControl@COleControlSite@@UEAAHXZ
// COleControlSite::DestroyControl
extern "C" int MS_ABI impl__DestroyControl_COleControlSite__UEAAHXZ(COleControlSite* pThis) {
    return (int)pThis->DestroyControl();
}
// Symbol: ?Detach@COleDataObject@@QEAAPEAUIDataObject@@XZ
// COleDataObject::Detach
extern "C" IDataObject* MS_ABI impl__Detach_COleDataObject__QEAAPEAUIDataObject__XZ(COleDataObject* pThis) {
    return (IDataObject*)pThis->Detach();
}
// Symbol: ?Detach@COleStreamFile@@QEAAPEAUIStream@@XZ
// COleStreamFile::Detach
extern "C" IStream* MS_ABI impl__Detach_COleStreamFile__QEAAPEAUIStream__XZ(COleStreamFile* pThis) {
    return (IStream*)pThis->Detach();
}
// Symbol: ?DoChangeIcon@COleChangeIconDialog@@QEAAHPEAVCOleClientItem@@@Z
// COleChangeIconDialog::DoChangeIcon
extern "C" int MS_ABI impl__DoChangeIcon_COleChangeIconDialog__QEAAHPEAVCOleClientItem___Z(COleChangeIconDialog* pThis, COleClientItem* p0) {
    return (int)pThis->DoChangeIcon(p0);
}
// Symbol: ?DoConvert@COleConvertDialog@@QEAAHPEAVCOleClientItem@@@Z
// COleConvertDialog::DoConvert
extern "C" int MS_ABI impl__DoConvert_COleConvertDialog__QEAAHPEAVCOleClientItem___Z(COleConvertDialog* pThis, COleClientItem* p0) {
    return (int)pThis->DoConvert(p0);
}
// Symbol: ?DoDragDrop@COleDataSource@@QEAAKKPEBUtagRECT@@PEAVCOleDropSource@@@Z
// COleDataSource::DoDragDrop
extern "C" unsigned long MS_ABI impl__DoDragDrop_COleDataSource__QEAAKKPEBUtagRECT__PEAVCOleDropSource___Z(COleDataSource* pThis, unsigned long p0, const RECT* p1, COleDropSource* p2) {
    return (unsigned long)pThis->DoDragDrop(p0, p1, p2);
}
// Symbol: ?DoModal@COleBusyDialog@@UEAA_JXZ
// COleBusyDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleBusyDialog__UEAA_JXZ(COleBusyDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleChangeIconDialog@@UEAA_JXZ
// COleChangeIconDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleChangeIconDialog__UEAA_JXZ(COleChangeIconDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleChangeSourceDialog@@UEAA_JXZ
// COleChangeSourceDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleChangeSourceDialog__UEAA_JXZ(COleChangeSourceDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleConvertDialog@@UEAA_JXZ
// COleConvertDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleConvertDialog__UEAA_JXZ(COleConvertDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleInsertDialog@@QEAA_JK@Z
// COleInsertDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleInsertDialog__QEAA_JK_Z(COleInsertDialog* pThis, unsigned long p0) {
    return (__int64)pThis->DoModal(p0);
}
// Symbol: ?DoModal@COleInsertDialog@@UEAA_JXZ
// COleInsertDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleInsertDialog__UEAA_JXZ(COleInsertDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleLinksDialog@@UEAA_JXZ
// COleLinksDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleLinksDialog__UEAA_JXZ(COleLinksDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COlePasteSpecialDialog@@UEAA_JXZ
// COlePasteSpecialDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COlePasteSpecialDialog__UEAA_JXZ(COlePasteSpecialDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COlePropertiesDialog@@UEAA_JXZ
// COlePropertiesDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COlePropertiesDialog__UEAA_JXZ(COlePropertiesDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoModal@COleUpdateDialog@@UEAA_JXZ
// COleUpdateDialog::DoModal
extern "C" __int64 MS_ABI impl__DoModal_COleUpdateDialog__UEAA_JXZ(COleUpdateDialog* pThis) {
    return (__int64)pThis->DoModal();
}
// Symbol: ?DoPropExchange@COleControl@@UEAAXPEAVCPropExchange@@@Z
// COleControl::DoPropExchange
extern "C" void MS_ABI impl__DoPropExchange_COleControl__UEAAXPEAVCPropExchange___Z(COleControl* pThis, CPropExchange* p0) {
    pThis->DoPropExchange(p0);
}
// Symbol: ?DoVerb@COleClientItem@@UEAAHJPEAVCView@@PEAUtagMSG@@@Z
// COleClientItem::DoVerb
extern "C" int MS_ABI impl__DoVerb_COleClientItem__UEAAHJPEAVCView__PEAUtagMSG___Z(COleClientItem* pThis, long p0, CView* p1, MSG* p2) {
    return (int)pThis->DoVerb(p0, p1, p2);
}
// Symbol: ?Draw@COleClientItem@@QEAAHPEAVCDC@@PEBUtagRECT@@W4tagDVASPECT@@@Z
// COleClientItem::Draw
extern "C" int MS_ABI impl__Draw_COleClientItem__QEAAHPEAVCDC__PEBUtagRECT__W4tagDVASPECT___Z(COleClientItem* pThis, CDC* p0, const RECT* p1, tagDVASPECT p2) {
    return (int)pThis->Draw(p0, p1, p2);
}
// Symbol: ?Empty@COleDataSource@@QEAAXXZ
// COleDataSource::Empty
extern "C" void MS_ABI impl__Empty_COleDataSource__QEAAXXZ(COleDataSource* pThis) {
    pThis->Empty();
}
// Symbol: ?EnableWindow@COleControlSite@@UEAAHH@Z
// COleControlSite::EnableWindow
extern "C" int MS_ABI impl__EnableWindow_COleControlSite__UEAAHH_Z(COleControlSite* pThis, int p0) {
    if (!pThis || !pThis->m_hWnd) return 0;
    return ::EnableWindow(pThis->m_hWnd, p0);
}
// Symbol: ?EndBusyState@COleMessageFilter@@UEAAXXZ
// COleMessageFilter::EndBusyState
extern "C" void MS_ABI impl__EndBusyState_COleMessageFilter__UEAAXXZ(COleMessageFilter* pThis) {
    pThis->EndBusyState();
}
// Symbol: ?EnsureClipboardObject@COleDataObject@@QEAAXXZ
// COleDataObject::EnsureClipboardObject
extern "C" void MS_ABI impl__EnsureClipboardObject_COleDataObject__QEAAXXZ(COleDataObject* pThis) {
    pThis->EnsureClipboardObject();
}
// Symbol: ?ExecCommand@COleDocObjectItem@@QEAAJKKPEBU_GUID@@@Z
// COleDocObjectItem::ExecCommand
extern "C" long MS_ABI impl__ExecCommand_COleDocObjectItem__QEAAJKKPEBU_GUID___Z(COleDocObjectItem* pThis, unsigned long p0, unsigned long p1, const _GUID* p2) {
    return (long)pThis->ExecCommand(p0, p1, p2);
}
// Symbol: ?FindItem@COleControlContainer@@UEBAPEAVCOleControlSite@@I@Z
// COleControlContainer::FindItem
extern "C" COleControlSite* MS_ABI impl__FindItem_COleControlContainer__UEBAPEAVCOleControlSite__I_Z(const COleControlContainer* pThis, unsigned int p0) {
    return (COleControlSite*)pThis->FindItem(p0);
}
// Symbol: ?FireEvent@COleControl@@QEAAXJPEAEZZ
// COleControl::FireEvent
extern "C" void MS_ABI impl__FireEvent_COleControl__QEAAXJPEAEZZ(COleControl* pThis, long p0, unsigned char* p1) {
    pThis->FireEvent(p0, p1);
}
// Symbol: ?FireEventV@COleControl@@IEAAXJPEAEPEAD@Z
// COleControl::FireEventV
extern "C" void MS_ABI impl__FireEventV_COleControl__IEAAXJPEAEPEAD_Z(COleControl* pThis, long p0, unsigned char* p1, char* p2) {
    pThis->FireEventV(p0, p1, p2);
}
// Symbol: ?GetActiveView@COleDocObjectItem@@QEBAPEAUIOleDocumentView@@XZ
// COleDocObjectItem::GetActiveView
extern "C" IOleDocumentView* MS_ABI impl__GetActiveView_COleDocObjectItem__QEBAPEAUIOleDocumentView__XZ(const COleDocObjectItem* pThis) {
    return (IOleDocumentView*)pThis->GetActiveView();
}
// Symbol: ?GetAmbientProperty@COleControl@@QEAAHJGPEAX@Z
// COleControl::GetAmbientProperty
extern "C" int MS_ABI impl__GetAmbientProperty_COleControl__QEAAHJGPEAX_Z(COleControl* pThis, long p0, unsigned short p1, void* p2) {
    return (int)pThis->GetAmbientProperty(p0, p1, p2);
}
// Symbol: ?GetAppearance@COleControl@@QEAAFXZ
// COleControl::GetAppearance
extern "C" short MS_ABI impl__GetAppearance_COleControl__QEAAFXZ(COleControl* pThis) {
    return (short)pThis->GetAppearance();
}
// Symbol: ?GetBackColor@COleControl@@QEAAKXZ
// COleControl::GetBackColor
extern "C" unsigned long MS_ABI impl__GetBackColor_COleControl__QEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->GetBackColor();
}
// Symbol: ?GetBorderStyle@COleControl@@QEAAFXZ
// COleControl::GetBorderStyle
extern "C" short MS_ABI impl__GetBorderStyle_COleControl__QEAAFXZ(COleControl* pThis) {
    return (short)pThis->GetBorderStyle();
}
// Symbol: ?GetClipboardOwner@COleDataSource@@SAPEAV1@XZ
// Static: COleDataSource::GetClipboardOwner
extern "C" void* MS_ABI impl__GetClipboardOwner_COleDataSource__SAPEAV1_XZ() {
    return (void*)COleDataSource::GetClipboardOwner();
}
// Symbol: ?GetControlFlags@COleControl@@UEAAKXZ
// COleControl::GetControlFlags
extern "C" unsigned long MS_ABI impl__GetControlFlags_COleControl__UEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->GetControlFlags();
}
// Symbol: ?GetControlSize@COleControl@@QEAAXPEAH0@Z
// COleControl::GetControlSize
extern "C" void MS_ABI impl__GetControlSize_COleControl__QEAAXPEAH0_Z(COleControl* pThis, int* p0, int* p1) {
    pThis->GetControlSize(p0, p1);
}
// Symbol: ?GetData@COleDataObject@@QEAAHGPEAUtagSTGMEDIUM@@PEAUtagFORMATETC@@@Z
// COleDataObject::GetData
extern "C" int MS_ABI impl__GetData_COleDataObject__QEAAHGPEAUtagSTGMEDIUM__PEAUtagFORMATETC___Z(COleDataObject* pThis, unsigned short p0, STGMEDIUM* p1, FORMATETC* p2) {
    return (int)pThis->GetData(p0, p1, p2);
}
// Symbol: ?GetEmbeddedItem@COleServerDoc@@QEAAPEAVCOleServerItem@@XZ
// COleServerDoc::GetEmbeddedItem
extern "C" COleServerItem* MS_ABI impl__GetEmbeddedItem_COleServerDoc__QEAAPEAVCOleServerItem__XZ(COleServerDoc* pThis) {
    return (COleServerItem*)pThis->GetEmbeddedItem();
}
// Symbol: ?GetEnabled@COleControl@@QEAAHXZ
// COleControl::GetEnabled
extern "C" int MS_ABI impl__GetEnabled_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->GetEnabled();
}
// Symbol: ?GetExtent@COleClientItem@@QEAAHPEAUtagSIZE@@W4tagDVASPECT@@@Z
// COleClientItem::GetExtent
extern "C" int MS_ABI impl__GetExtent_COleClientItem__QEAAHPEAUtagSIZE__W4tagDVASPECT___Z(COleClientItem* pThis, SIZE* p0, tagDVASPECT p1) {
    return (int)pThis->GetExtent(p0, p1);
}
// Symbol: ?GetFileData@COleDataObject@@QEAAPEAVCFile@@GPEAUtagFORMATETC@@@Z
// COleDataObject::GetFileData
extern "C" CFile* MS_ABI impl__GetFileData_COleDataObject__QEAAPEAVCFile__GPEAUtagFORMATETC___Z(COleDataObject* pThis, unsigned short p0, FORMATETC* p1) {
    return (CFile*)pThis->GetFileData(p0, p1);
}
// Symbol: ?GetForeColor@COleControl@@QEAAKXZ
// COleControl::GetForeColor
extern "C" unsigned long MS_ABI impl__GetForeColor_COleControl__QEAAKXZ(COleControl* pThis) {
    return (unsigned long)pThis->GetForeColor();
}
// Symbol: ?GetGlobalData@COleDataObject@@QEAAPEAXGPEAUtagFORMATETC@@@Z
// COleDataObject::GetGlobalData
extern "C" void* MS_ABI impl__GetGlobalData_COleDataObject__QEAAPEAXGPEAUtagFORMATETC___Z(COleDataObject* pThis, unsigned short p0, FORMATETC* p1) {
    return (void*)pThis->GetGlobalData(p0, p1);
}
// Symbol: ?GetHwnd@COleControl@@QEAAIXZ
// COleControl::GetHwnd
extern "C" unsigned int MS_ABI impl__GetHwnd_COleControl__QEAAIXZ(COleControl* pThis) {
    return (unsigned int)pThis->GetHwnd();
}
// Symbol: ?GetIconicMetafile@COleClientItem@@QEAAPEAXXZ
// COleClientItem::GetIconicMetafile
extern "C" void* MS_ABI impl__GetIconicMetafile_COleClientItem__QEAAPEAXXZ(COleClientItem* pThis) {
    return (void*)pThis->GetIconicMetafile();
}
// Symbol: ?GetIDataObject@COleDataObject@@QEAAPEAUIDataObject@@H@Z
// COleDataObject::GetIDataObject
extern "C" IDataObject* MS_ABI impl__GetIDataObject_COleDataObject__QEAAPEAUIDataObject__H_Z(COleDataObject* pThis, int p0) {
    return (IDataObject*)pThis->GetIDataObject(p0);
}
// Symbol: ?GetLicenseKey@COleObjectFactory@@MEAAHKPEAPEA_W@Z
// COleObjectFactory::GetLicenseKey
extern "C" int MS_ABI impl__GetLicenseKey_COleObjectFactory__MEAAHKPEAPEA_W_Z(COleObjectFactory* pThis, unsigned long p0, wchar_t** p1) {
    return (int)pThis->GetLicenseKey(p0, p1);
}
// Symbol: ?GetMoniker@COleLinkingDoc@@UEAAPEAUIMoniker@@W4tagOLEGETMONIKER@@@Z
// COleLinkingDoc::GetMoniker
extern "C" IMoniker* MS_ABI impl__GetMoniker_COleLinkingDoc__UEAAPEAUIMoniker__W4tagOLEGETMONIKER___Z(COleLinkingDoc* pThis, tagOLEGETMONIKER p0) {
    return (IMoniker*)pThis->GetMoniker(p0);
}
// Symbol: ?GetNextClientItem@COleDocument@@QEBAPEAVCOleClientItem@@AEAPEAU__POSITION@@@Z
// COleDocument::GetNextClientItem
extern "C" COleClientItem* MS_ABI impl__GetNextClientItem_COleDocument__QEBAPEAVCOleClientItem__AEAPEAU__POSITION___Z(const COleDocument* pThis, void** p0) {
    return (COleClientItem*)pThis->GetNextClientItem((*p0));
}
// Symbol: ?GetNextFormat@COleDataObject@@QEAAHPEAUtagFORMATETC@@@Z
// COleDataObject::GetNextFormat
extern "C" int MS_ABI impl__GetNextFormat_COleDataObject__QEAAHPEAUtagFORMATETC___Z(COleDataObject* pThis, FORMATETC* p0) {
    return (int)pThis->GetNextFormat(p0);
}
// Symbol: ?GetPrimarySelectedItem@COleDocument@@UEAAPEAVCOleClientItem@@PEAVCView@@@Z
// COleDocument::GetPrimarySelectedItem
extern "C" COleClientItem* MS_ABI impl__GetPrimarySelectedItem_COleDocument__UEAAPEAVCOleClientItem__PEAVCView___Z(COleDocument* pThis, CView* p0) {
    return (COleClientItem*)pThis->GetPrimarySelectedItem(p0);
}
// Symbol: ?GetReadyState@COleControl@@QEAAJXZ
// COleControl::GetReadyState
extern "C" long MS_ABI impl__GetReadyState_COleControl__QEAAJXZ(COleControl* pThis) {
    return (long)pThis->GetReadyState();
}
// Symbol: ?GetSelectionType@COleConvertDialog@@QEBAIXZ
// COleConvertDialog::GetSelectionType
extern "C" unsigned int MS_ABI impl__GetSelectionType_COleConvertDialog__QEBAIXZ(const COleConvertDialog* pThis) {
    return (unsigned int)pThis->GetSelectionType();
}
// Symbol: ?GetSelectionType@COleInsertDialog@@QEBAIXZ
// COleInsertDialog::GetSelectionType
extern "C" unsigned int MS_ABI impl__GetSelectionType_COleInsertDialog__QEBAIXZ(const COleInsertDialog* pThis) {
    return (unsigned int)pThis->GetSelectionType();
}
// Symbol: ?GetSelectionType@COlePasteSpecialDialog@@QEBAIXZ
// COlePasteSpecialDialog::GetSelectionType
extern "C" unsigned int MS_ABI impl__GetSelectionType_COlePasteSpecialDialog__QEBAIXZ(const COlePasteSpecialDialog* pThis) {
    return (unsigned int)pThis->GetSelectionType();
}
// Symbol: ?GetStartPosition@COleDocument@@UEBAPEAU__POSITION@@XZ
// COleDocument::GetStartPosition
extern "C" void* MS_ABI impl__GetStartPosition_COleDocument__UEBAPEAU__POSITION__XZ(const COleDocument* pThis) {
    return (void*)pThis->GetStartPosition();
}
// Symbol: ?GetStream@COleStreamFile@@QEBAPEAUIStream@@XZ
// COleStreamFile::GetStream
extern "C" IStream* MS_ABI impl__GetStream_COleStreamFile__QEBAPEAUIStream__XZ(const COleStreamFile* pThis) {
    return (IStream*)pThis->GetStream();
}
// Symbol: ?GetStyle@COleControlSiteOrWnd@@QEBAKXZ
// COleControlSiteOrWnd::GetStyle
extern "C" unsigned long MS_ABI impl__GetStyle_COleControlSiteOrWnd__QEBAKXZ(const COleControlSiteOrWnd* pThis) {
    return (unsigned long)pThis->GetStyle();
}
// Symbol: ?GetText@COleControl@@QEAAPEA_WXZ
// COleControl::GetText
extern "C" wchar_t* MS_ABI impl__GetText_COleControl__QEAAPEA_WXZ(COleControl* pThis) {
    return (wchar_t*)pThis->GetText();
}
// Symbol: ?GiveFeedback@COleDropSource@@UEAAJK@Z
// COleDropSource::GiveFeedback
extern "C" long MS_ABI impl__GiveFeedback_COleDropSource__UEAAJK_Z(COleDropSource* pThis, unsigned long p0) {
    return (long)pThis->GiveFeedback(p0);
}
// Symbol: ?HasBlankItems@COleDocument@@QEBAHXZ
// COleDocument::HasBlankItems
extern "C" int MS_ABI impl__HasBlankItems_COleDocument__QEBAHXZ(const COleDocument* pThis) {
    return (int)pThis->HasBlankItems();
}
// Symbol: ?InvokeHelper@COleControlSite@@UEAAXJGGPEAXPEBEZZ
// COleControlSite::InvokeHelper
extern "C" void MS_ABI impl__InvokeHelper_COleControlSite__UEAAXJGGPEAXPEBEZZ(COleControlSite* pThis, long p0, unsigned short p1, unsigned short p2, void* p3, const unsigned char* p4) {
    pThis->InvokeHelper(p0, p1, p2, p3, p4);
}
// Symbol: ?InvokeHelperV@COleControlSite@@UEAAXJGGPEAXPEBEPEAD@Z
// COleControlSite::InvokeHelperV
extern "C" void MS_ABI impl__InvokeHelperV_COleControlSite__UEAAXJGGPEAXPEBEPEAD_Z(COleControlSite* pThis, long p0, unsigned short p1, unsigned short p2, void* p3, const unsigned char* p4, char* p5) {
    pThis->InvokeHelperV(p0, p1, p2, p3, p4, p5);
}
// Symbol: ?IsConnected@COleServerItem@@QEBAHXZ
// COleServerItem::IsConnected
extern "C" int MS_ABI impl__IsConnected_COleServerItem__QEBAHXZ(const COleServerItem* pThis) {
    return (int)pThis->IsConnected();
}
// Symbol: ?IsDataAvailable@COleDataObject@@QEAAHGPEAUtagFORMATETC@@@Z
// COleDataObject::IsDataAvailable
extern "C" int MS_ABI impl__IsDataAvailable_COleDataObject__QEAAHGPEAUtagFORMATETC___Z(COleDataObject* pThis, unsigned short p0, FORMATETC* p1) {
    return (int)pThis->IsDataAvailable(p0, p1);
}
// Symbol: ?IsLicenseValid@COleObjectFactory@@QEAAHXZ
// COleObjectFactory::IsLicenseValid
extern "C" int MS_ABI impl__IsLicenseValid_COleObjectFactory__QEAAHXZ(COleObjectFactory* pThis) {
    return (int)pThis->IsLicenseValid();
}
// Symbol: ?IsModified@COleClientItem@@QEBAHXZ
// COleClientItem::IsModified
extern "C" int MS_ABI impl__IsModified_COleClientItem__QEBAHXZ(const COleClientItem* pThis) {
    return (int)pThis->IsModified();
}
// Symbol: ?IsSubclassedControl@COleControl@@UEAAHXZ
// COleControl::IsSubclassedControl
extern "C" int MS_ABI impl__IsSubclassedControl_COleControl__UEAAHXZ(COleControl* pThis) {
    return (int)pThis->IsSubclassedControl();
}
// Symbol: ?LockRange@COleStreamFile@@UEAAX_K0@Z
// COleStreamFile::LockRange
extern "C" void MS_ABI impl__LockRange_COleStreamFile__UEAAX_K0_Z(COleStreamFile* pThis, unsigned __int64 p0, unsigned __int64 p1) {
    pThis->LockRange(p0, p1);
}
// Symbol: ?MapResult@COleDialog@@QEAAHI@Z
// COleDialog::MapResult
extern "C" int MS_ABI impl__MapResult_COleDialog__QEAAHI_Z(COleDialog* pThis, unsigned int p0) {
    return (int)pThis->MapResult(p0);
}
// Symbol: ?NotifyRename@COleServerDoc@@QEAAXPEB_W@Z
// COleServerDoc::NotifyRename
extern "C" void MS_ABI impl__NotifyRename_COleServerDoc__QEAAXPEB_W_Z(COleServerDoc* pThis, const wchar_t* p0) {
    pThis->NotifyRename(p0);
}
// Symbol: ?OnActivate@COleClientItem@@UEAAXXZ
// COleClientItem::OnActivate
extern "C" void MS_ABI impl__OnActivate_COleClientItem__UEAAXXZ(COleClientItem* pThis) {
    pThis->OnActivate();
}
// Symbol: ?OnAmbientPropertyChange@COleControl@@UEAAXJ@Z
// COleControl::OnAmbientPropertyChange
extern "C" void MS_ABI impl__OnAmbientPropertyChange_COleControl__UEAAXJ_Z(COleControl* pThis, long p0) {
    pThis->OnAmbientPropertyChange(p0);
}
// Symbol: ?OnBusyDialog@COleMessageFilter@@UEAAHPEAUHTASK__@@@Z
// COleMessageFilter::OnBusyDialog
extern "C" int MS_ABI impl__OnBusyDialog_COleMessageFilter__UEAAHPEAUHTASK_____Z(COleMessageFilter* pThis, HTASK__* p0) {
    return (int)pThis->OnBusyDialog(p0);
}
// Symbol: ?OnChange@COleClientItem@@UEAAXW4OLE_NOTIFICATION@@K@Z
// COleClientItem::OnChange
extern "C" void MS_ABI impl__OnChange_COleClientItem__UEAAXW4OLE_NOTIFICATION__K_Z(COleClientItem* pThis, OLE_NOTIFICATION p0, unsigned long p1) {
    pThis->OnChange(p0, p1);
}
// Symbol: ?OnChangeItemPosition@COleClientItem@@MEAAHAEBVCRect@@@Z
// COleClientItem::OnChangeItemPosition
extern "C" int MS_ABI impl__OnChangeItemPosition_COleClientItem__MEAAHAEBVCRect___Z(COleClientItem* pThis, const CRect* p0) {
    return (int)pThis->OnChangeItemPosition((*p0));
}
// Symbol: ?OnClose@COleControl@@UEAAXK@Z
// COleControl::OnClose
extern "C" void MS_ABI impl__OnClose_COleControl__UEAAXK_Z(COleControl* pThis, unsigned long p0) {
    pThis->OnClose(p0);
}
// Symbol: ?OnCmdMsg@COleTemplateServer@@MEAAHIHPEAXPEAUAFX_CMDHANDLERINFO@@@Z
// COleTemplateServer::OnCmdMsg
extern "C" int MS_ABI impl__OnCmdMsg_COleTemplateServer__MEAAHIHPEAXPEAUAFX_CMDHANDLERINFO___Z(COleTemplateServer* pThis, unsigned int p0, int p1, void* p2, AFX_CMDHANDLERINFO* p3) {
    return (int)pThis->OnCmdMsg(p0, p1, p2, p3);
}
// Symbol: ?OnCreateControlBars@COleIPFrameWnd@@UEAAHPEAVCFrameWnd@@0@Z
// COleIPFrameWnd::OnCreateControlBars
extern "C" int MS_ABI impl__OnCreateControlBars_COleIPFrameWnd__UEAAHPEAVCFrameWnd__0_Z(COleIPFrameWnd* pThis, CFrameWnd* p0, CFrameWnd* p1) {
    return (int)pThis->OnCreateControlBars(p0, p1);
}
// Symbol: ?OnCreateObject@COleObjectFactory@@MEAAPEAVCCmdTarget@@XZ
// COleObjectFactory::OnCreateObject
extern "C" CCmdTarget* MS_ABI impl__OnCreateObject_COleObjectFactory__MEAAPEAVCCmdTarget__XZ(COleObjectFactory* pThis) {
    return (CCmdTarget*)pThis->OnCreateObject();
}
// Symbol: ?OnCreateObject@COleTemplateServer@@MEAAPEAVCCmdTarget@@XZ
// COleTemplateServer::OnCreateObject
extern "C" CCmdTarget* MS_ABI impl__OnCreateObject_COleTemplateServer__MEAAPEAVCCmdTarget__XZ(COleTemplateServer* pThis) {
    return (CCmdTarget*)pThis->OnCreateObject();
}
// Symbol: ?OnDeactivate@COleClientItem@@UEAAXXZ
// COleClientItem::OnDeactivate
extern "C" void MS_ABI impl__OnDeactivate_COleClientItem__UEAAXXZ(COleClientItem* pThis) {
    pThis->OnDeactivate();
}
// Symbol: ?OnDiscardUndoState@COleClientItem@@MEAAXXZ
// COleClientItem::OnDiscardUndoState
extern "C" void MS_ABI impl__OnDiscardUndoState_COleClientItem__MEAAXXZ(COleClientItem* pThis) {
    pThis->OnDiscardUndoState();
}
// Symbol: ?OnDocActivate@COleFrameHook@@UEAAHH@Z
// COleFrameHook::OnDocActivate
extern "C" int MS_ABI impl__OnDocActivate_COleFrameHook__UEAAHH_Z(COleFrameHook* pThis, int p0) {
    return (int)pThis->OnDocActivate(p0);
}
// Symbol: ?OnDragEnter@COleDropTarget@@UEAAKPEAVCWnd@@PEAVCOleDataObject@@KVCPoint@@@Z
// COleDropTarget::OnDragEnter
extern "C" unsigned long MS_ABI impl__OnDragEnter_COleDropTarget__UEAAKPEAVCWnd__PEAVCOleDataObject__KVCPoint___Z(COleDropTarget* pThis, CWnd* p0, COleDataObject* p1, unsigned long p2, CPoint p3) {
    return (unsigned long)pThis->OnDragEnter(p0, p1, p2, p3);
}
// Symbol: ?OnDragLeave@COleDropTarget@@UEAAXPEAVCWnd@@@Z
// COleDropTarget::OnDragLeave
extern "C" void MS_ABI impl__OnDragLeave_COleDropTarget__UEAAXPEAVCWnd___Z(COleDropTarget* pThis, CWnd* p0) {
    pThis->OnDragLeave(p0);
}
// Symbol: ?OnDragOver@COleDropTarget@@UEAAKPEAVCWnd@@PEAVCOleDataObject@@KVCPoint@@@Z
// COleDropTarget::OnDragOver
extern "C" unsigned long MS_ABI impl__OnDragOver_COleDropTarget__UEAAKPEAVCWnd__PEAVCOleDataObject__KVCPoint___Z(COleDropTarget* pThis, CWnd* p0, COleDataObject* p1, unsigned long p2, CPoint p3) {
    return (unsigned long)pThis->OnDragOver(p0, p1, p2, p3);
}
// Symbol: ?OnDragScroll@COleDropTarget@@UEAAKPEAVCWnd@@KVCPoint@@@Z
// COleDropTarget::OnDragScroll
extern "C" unsigned long MS_ABI impl__OnDragScroll_COleDropTarget__UEAAKPEAVCWnd__KVCPoint___Z(COleDropTarget* pThis, CWnd* p0, unsigned long p1, CPoint p2) {
    return (unsigned long)pThis->OnDragScroll(p0, p1, p2);
}
// Symbol: ?OnDraw@COleControl@@UEAAXPEAVCDC@@AEBVCRect@@1@Z
// COleControl::OnDraw
extern "C" void MS_ABI impl__OnDraw_COleControl__UEAAXPEAVCDC__AEBVCRect__1_Z(COleControl* pThis, CDC* p0, const CRect* p1, const CRect* p2) {
    pThis->OnDraw(p0, (*p1), (*p2));
}
// Symbol: ?OnDrawEx@COleServerItem@@UEAAHPEAVCDC@@W4tagDVASPECT@@AEAVCSize@@@Z
// COleServerItem::OnDrawEx
extern "C" int MS_ABI impl__OnDrawEx_COleServerItem__UEAAHPEAVCDC__W4tagDVASPECT__AEAVCSize___Z(COleServerItem* pThis, CDC* p0, tagDVASPECT p1, CSize* p2) {
    return (int)pThis->OnDrawEx(p0, p1, (*p2));
}
// Symbol: ?OnDrop@COleDropTarget@@UEAAHPEAVCWnd@@PEAVCOleDataObject@@KVCPoint@@@Z
// COleDropTarget::OnDrop
extern "C" int MS_ABI impl__OnDrop_COleDropTarget__UEAAHPEAVCWnd__PEAVCOleDataObject__KVCPoint___Z(COleDropTarget* pThis, CWnd* p0, COleDataObject* p1, unsigned long p2, CPoint p3) {
    return (int)pThis->OnDrop(p0, p1, p2, p3);
}
// Symbol: ?OnDropEx@COleDropTarget@@UEAAKPEAVCWnd@@PEAVCOleDataObject@@KKVCPoint@@@Z
// COleDropTarget::OnDropEx
extern "C" unsigned long MS_ABI impl__OnDropEx_COleDropTarget__UEAAKPEAVCWnd__PEAVCOleDataObject__KKVCPoint___Z(COleDropTarget* pThis, CWnd* p0, COleDataObject* p1, unsigned long p2, unsigned long p3, CPoint p4) {
    return (unsigned long)pThis->OnDropEx(p0, p1, p2, p3, p4);
}
// Symbol: ?OnEditLinks@COleDocument@@IEAAXXZ
// COleDocument::OnEditLinks
extern "C" void MS_ABI impl__OnEditLinks_COleDocument__IEAAXXZ(COleDocument* pThis) {
    pThis->OnEditLinks();
}
// Symbol: ?OnEditProperty@COlePropertyPage@@UEAAHJ@Z
// COlePropertyPage::OnEditProperty
extern "C" int MS_ABI impl__OnEditProperty_COlePropertyPage__UEAAHJ_Z(COlePropertyPage* pThis, long p0) {
    return (int)pThis->OnEditProperty(p0);
}
// Symbol: ?OnGetControlInfo@COleControl@@UEAAXPEAUtagCONTROLINFO@@@Z
// COleControl::OnGetControlInfo
extern "C" void MS_ABI impl__OnGetControlInfo_COleControl__UEAAXPEAUtagCONTROLINFO___Z(COleControl* pThis, CONTROLINFO* p0) {
    pThis->OnGetControlInfo(p0);
}
// Symbol: ?OnGetExtent@COleServerItem@@UEAAHW4tagDVASPECT@@AEAVCSize@@@Z
// COleServerItem::OnGetExtent
extern "C" int MS_ABI impl__OnGetExtent_COleServerItem__UEAAHW4tagDVASPECT__AEAVCSize___Z(COleServerItem* pThis, tagDVASPECT p0, CSize* p1) {
    return (int)pThis->OnGetExtent(p0, (*p1));
}
// Symbol: ?OnGetItemPosition@COleClientItem@@MEAAXAEAVCRect@@@Z
// COleClientItem::OnGetItemPosition
extern "C" void MS_ABI impl__OnGetItemPosition_COleClientItem__MEAAXAEAVCRect___Z(COleClientItem* pThis, CRect* p0) {
    pThis->OnGetItemPosition((*p0));
}
// Symbol: ?OnMapPropertyToPage@COleControl@@UEAAHJPEAU_GUID@@PEAH@Z
// COleControl::OnMapPropertyToPage
extern "C" int MS_ABI impl__OnMapPropertyToPage_COleControl__UEAAHJPEAU_GUID__PEAH_Z(COleControl* pThis, long p0, _GUID* p1, int* p2) {
    return (int)pThis->OnMapPropertyToPage(p0, p1, p2);
}
// Symbol: ?OnMessagePending@COleMessageFilter@@UEAAHPEBUtagMSG@@@Z
// COleMessageFilter::OnMessagePending
extern "C" int MS_ABI impl__OnMessagePending_COleMessageFilter__UEAAHPEBUtagMSG___Z(COleMessageFilter* pThis, const MSG* p0) {
    return (int)pThis->OnMessagePending(p0);
}
// Symbol: ?OnMnemonic@COleControl@@UEAAXPEAUtagMSG@@@Z
// COleControl::OnMnemonic
extern "C" void MS_ABI impl__OnMnemonic_COleControl__UEAAXPEAUtagMSG___Z(COleControl* pThis, MSG* p0) {
    pThis->OnMnemonic(p0);
}
// Symbol: ?OnObjectsChanged@COlePropertyPage@@UEAAXXZ
// COlePropertyPage::OnObjectsChanged
extern "C" void MS_ABI impl__OnObjectsChanged_COlePropertyPage__UEAAXXZ(COlePropertyPage* pThis) {
    pThis->OnObjectsChanged();
}
// Symbol: ?OnProperties@COleControl@@UEAAHPEAUtagMSG@@PEAUHWND__@@PEBUtagRECT@@@Z
// COleControl::OnProperties
extern "C" int MS_ABI impl__OnProperties_COleControl__UEAAHPEAUtagMSG__PEAUHWND____PEBUtagRECT___Z(COleControl* pThis, MSG* p0, HWND__* p1, const RECT* p2) {
    return (int)pThis->OnProperties(p0, p1, p2);
}
// Symbol: ?OnRenderFileData@COleDataSource@@UEAAHPEAUtagFORMATETC@@PEAVCFile@@@Z
// COleDataSource::OnRenderFileData
extern "C" int MS_ABI impl__OnRenderFileData_COleDataSource__UEAAHPEAUtagFORMATETC__PEAVCFile___Z(COleDataSource* pThis, FORMATETC* p0, CFile* p1) {
    return (int)pThis->OnRenderFileData(p0, p1);
}
// Symbol: ?OnRenderGlobalData@COleDataSource@@UEAAHPEAUtagFORMATETC@@PEAPEAX@Z
// COleDataSource::OnRenderGlobalData
extern "C" int MS_ABI impl__OnRenderGlobalData_COleDataSource__UEAAHPEAUtagFORMATETC__PEAPEAX_Z(COleDataSource* pThis, FORMATETC* p0, void** p1) {
    return (int)pThis->OnRenderGlobalData(p0, p1);
}
// Symbol: ?OnRequestPositionChange@COleIPFrameWnd@@MEAAXPEBUtagRECT@@@Z
// COleIPFrameWnd::OnRequestPositionChange
extern "C" void MS_ABI impl__OnRequestPositionChange_COleIPFrameWnd__MEAAXPEBUtagRECT___Z(COleIPFrameWnd* pThis, const RECT* p0) {
    pThis->OnRequestPositionChange(p0);
}
// Symbol: ?OnResetState@COleControl@@UEAAXXZ
// COleControl::OnResetState
extern "C" void MS_ABI impl__OnResetState_COleControl__UEAAXXZ(COleControl* pThis) {
    pThis->OnResetState();
}
// Symbol: ?OnSetClientSite@COleControl@@UEAAXXZ
// COleControl::OnSetClientSite
extern "C" void MS_ABI impl__OnSetClientSite_COleControl__UEAAXXZ(COleControl* pThis) {
    pThis->OnSetClientSite();
}
// Symbol: ?OnSetExtent@COleServerItem@@UEAAHW4tagDVASPECT@@AEBVCSize@@@Z
// COleServerItem::OnSetExtent
extern "C" int MS_ABI impl__OnSetExtent_COleServerItem__UEAAHW4tagDVASPECT__AEBVCSize___Z(COleServerItem* pThis, tagDVASPECT p0, const CSize* p1) {
    return (int)pThis->OnSetExtent(p0, (*p1));
}
// Symbol: ?OnSetHostNames@COleServerDoc@@MEAAXPEB_W0@Z
// COleServerDoc::OnSetHostNames
extern "C" void MS_ABI impl__OnSetHostNames_COleServerDoc__MEAAXPEB_W0_Z(COleServerDoc* pThis, const wchar_t* p0, const wchar_t* p1) {
    pThis->OnSetHostNames(p0, p1);
}
// Symbol: ?OnSetObjectRects@COleControl@@UEAAHPEBUtagRECT@@0@Z
// COleControl::OnSetObjectRects
extern "C" int MS_ABI impl__OnSetObjectRects_COleControl__UEAAHPEBUtagRECT__0_Z(COleControl* pThis, const RECT* p0, const RECT* p1) {
    return (int)pThis->OnSetObjectRects(p0, p1);
}
// Symbol: ?OnSetPageSite@COlePropertyPage@@UEAAXXZ
// COlePropertyPage::OnSetPageSite
extern "C" void MS_ABI impl__OnSetPageSite_COlePropertyPage__UEAAXXZ(COlePropertyPage* pThis) {
    pThis->OnSetPageSite();
}
// Symbol: ?OnShowControlBars@COleClientItem@@UEAAHPEAVCFrameWnd@@H@Z
// COleClientItem::OnShowControlBars
extern "C" int MS_ABI impl__OnShowControlBars_COleClientItem__UEAAHPEAVCFrameWnd__H_Z(COleClientItem* pThis, CFrameWnd* p0, int p1) {
    return (int)pThis->OnShowControlBars(p0, p1);
}
// Symbol: ?OnShowItem@COleClientItem@@MEAAXXZ
// COleClientItem::OnShowItem
extern "C" void MS_ABI impl__OnShowItem_COleClientItem__MEAAXXZ(COleClientItem* pThis) {
    pThis->OnShowItem();
}
// Symbol: ?OnShowViews@COleDocument@@UEAAXH@Z
// COleDocument::OnShowViews
extern "C" void MS_ABI impl__OnShowViews_COleDocument__UEAAXH_Z(COleDocument* pThis, int p0) {
    pThis->OnShowViews(p0);
}
// Symbol: ?PreInitDialog@COleChangeSourceDialog@@UEAAXXZ
// COleChangeSourceDialog::PreInitDialog
extern "C" void MS_ABI impl__PreInitDialog_COleChangeSourceDialog__UEAAXXZ(COleChangeSourceDialog* pThis) {
    pThis->PreInitDialog();
}
// Symbol: ?QueryContinueDrag@COleDropSource@@UEAAJHK@Z
// COleDropSource::QueryContinueDrag
extern "C" long MS_ABI impl__QueryContinueDrag_COleDropSource__UEAAJHK_Z(COleDropSource* pThis, int p0, unsigned long p1) {
    return (long)pThis->QueryContinueDrag(p0, p1);
}
// Symbol: ?Read@COleStreamFile@@UEAAIPEAXI@Z
// COleStreamFile::Read
extern "C" unsigned int MS_ABI impl__Read_COleStreamFile__UEAAIPEAXI_Z(COleStreamFile* pThis, void* p0, unsigned int p1) {
    return (unsigned int)pThis->Read(p0, p1);
}
// Symbol: ?Register@COleDropTarget@@QEAAHPEAVCWnd@@@Z
// COleDropTarget::Register
extern "C" int MS_ABI impl__Register_COleDropTarget__QEAAHPEAVCWnd___Z(COleDropTarget* pThis, CWnd* p0) {
    return (int)pThis->Register(p0);
}
// Symbol: ?Register@COleMessageFilter@@QEAAHXZ
// COleMessageFilter::Register
extern "C" int MS_ABI impl__Register_COleMessageFilter__QEAAHXZ(COleMessageFilter* pThis) {
    return (int)pThis->Register();
}
// Symbol: ?Register@COleObjectFactory@@UEAAHXZ
// COleObjectFactory::Register
extern "C" int MS_ABI impl__Register_COleObjectFactory__UEAAHXZ(COleObjectFactory* pThis) {
    return (int)pThis->Register();
}
// Symbol: ?Register@COleTemplateServer@@UEAAHXZ
// COleTemplateServer::Register
extern "C" int MS_ABI impl__Register_COleTemplateServer__UEAAHXZ(COleTemplateServer* pThis) {
    return (int)pThis->Register();
}
// Symbol: ?RegisterAll@COleObjectFactory@@SAHXZ
// Static: COleObjectFactory::RegisterAll
extern "C" int MS_ABI impl__RegisterAll_COleObjectFactory__SAHXZ() {
    return (int)COleObjectFactory::RegisterAll();
}
// Symbol: ?RegisterIfServerAttached@COleLinkingDoc@@MEAAHPEB_WH@Z
// COleLinkingDoc::RegisterIfServerAttached
extern "C" int MS_ABI impl__RegisterIfServerAttached_COleLinkingDoc__MEAAHPEB_WH_Z(COleLinkingDoc* pThis, const wchar_t* p0, int p1) {
    return (int)pThis->RegisterIfServerAttached(p0, p1);
}
// Symbol: ?Release@COleDataObject@@QEAAXXZ
// COleDataObject::Release
extern "C" void MS_ABI impl__Release_COleDataObject__QEAAXXZ(COleDataObject* pThis) {
    pThis->Release();
}
// Symbol: ?ReleaseCapture@COleControl@@QEAAHXZ
// COleControl::ReleaseCapture
extern "C" int MS_ABI impl__ReleaseCapture_COleControl__QEAAHXZ(COleControl* pThis) {
    return (int)pThis->ReleaseCapture();
}
// Symbol: ?Reload@COleClientItem@@QEAAHXZ
// COleClientItem::Reload
extern "C" int MS_ABI impl__Reload_COleClientItem__QEAAHXZ(COleClientItem* pThis) {
    return (int)pThis->Reload();
}
// Symbol: ?Revoke@COleDropTarget@@UEAAXXZ
// COleDropTarget::Revoke
extern "C" void MS_ABI impl__Revoke_COleDropTarget__UEAAXXZ(COleDropTarget* pThis) {
    pThis->Revoke();
}
// Symbol: ?Revoke@COleLinkingDoc@@QEAAXXZ
// COleLinkingDoc::Revoke
extern "C" void MS_ABI impl__Revoke_COleLinkingDoc__QEAAXXZ(COleLinkingDoc* pThis) {
    pThis->Revoke();
}
// Symbol: ?Revoke@COleMessageFilter@@QEAAXXZ
// COleMessageFilter::Revoke
extern "C" void MS_ABI impl__Revoke_COleMessageFilter__QEAAXXZ(COleMessageFilter* pThis) {
    pThis->Revoke();
}
// Symbol: ?Revoke@COleObjectFactory@@QEAAXXZ
// COleObjectFactory::Revoke
extern "C" void MS_ABI impl__Revoke_COleObjectFactory__QEAAXXZ(COleObjectFactory* pThis) {
    pThis->Revoke();
}
// Symbol: ?RevokeAll@COleObjectFactory@@SAXXZ
// Static: COleObjectFactory::RevokeAll
extern "C" void MS_ABI impl__RevokeAll_COleObjectFactory__SAXXZ() {
    COleObjectFactory::RevokeAll();
}
// Symbol: ?SaveEmbedding@COleServerDoc@@QEAAXXZ
// COleServerDoc::SaveEmbedding
extern "C" void MS_ABI impl__SaveEmbedding_COleServerDoc__QEAAXXZ(COleServerDoc* pThis) {
    pThis->SaveEmbedding();
}
// Symbol: ?Seek@COleStreamFile@@UEAA_K_JI@Z
// COleStreamFile::Seek
extern "C" unsigned __int64 MS_ABI impl__Seek_COleStreamFile__UEAA_K_JI_Z(COleStreamFile* pThis, __int64 p0, unsigned int p1) {
    return (unsigned __int64)pThis->Seek(p0, p1);
}
// Symbol: ?Serialize@COleClientItem@@UEAAXAEAVCArchive@@@Z
// COleClientItem::Serialize
extern "C" void MS_ABI impl__Serialize_COleClientItem__UEAAXAEAVCArchive___Z(COleClientItem* pThis, CArchive* p0) {
    pThis->Serialize((*p0));
}
// Symbol: ?Serialize@COleControl@@MEAAXAEAVCArchive@@@Z
// COleControl::Serialize
extern "C" void MS_ABI impl__Serialize_COleControl__MEAAXAEAVCArchive___Z(COleControl* pThis, CArchive* p0) {
    pThis->Serialize((*p0));
}
// Symbol: ?SetAppearance@COleControl@@QEAAXF@Z
// COleControl::SetAppearance
extern "C" void MS_ABI impl__SetAppearance_COleControl__QEAAXF_Z(COleControl* pThis, short p0) {
    pThis->SetAppearance(p0);
}
// Symbol: ?SetBackColor@COleControl@@QEAAXK@Z
// COleControl::SetBackColor
extern "C" void MS_ABI impl__SetBackColor_COleControl__QEAAXK_Z(COleControl* pThis, unsigned long p0) {
    pThis->SetBackColor(p0);
}
// Symbol: ?SetBorderStyle@COleControl@@QEAAXF@Z
// COleControl::SetBorderStyle
extern "C" void MS_ABI impl__SetBorderStyle_COleControl__QEAAXF_Z(COleControl* pThis, short p0) {
    pThis->SetBorderStyle(p0);
}
// Symbol: ?SetCapture@COleControl@@QEAAPEAVCWnd@@XZ
// COleControl::SetCapture
extern "C" CWnd* MS_ABI impl__SetCapture_COleControl__QEAAPEAVCWnd__XZ(COleControl* pThis) {
    return (CWnd*)pThis->SetCapture();
}
// Symbol: ?SetClipboard@COleDataSource@@QEAAXXZ
// COleDataSource::SetClipboard
extern "C" void MS_ABI impl__SetClipboard_COleDataSource__QEAAXXZ(COleDataSource* pThis) {
    pThis->SetClipboard();
}
// Symbol: ?SetControlSize@COleControl@@QEAAHHH@Z
// COleControl::SetControlSize
extern "C" int MS_ABI impl__SetControlSize_COleControl__QEAAHHH_Z(COleControl* pThis, int p0, int p1) {
    return (int)pThis->SetControlSize(p0, p1);
}
// Symbol: ?SetCurrency@COleCurrency@@QEAAXJJ@Z
// COleCurrency::SetCurrency
extern "C" void MS_ABI impl__SetCurrency_COleCurrency__QEAAXJJ_Z(COleCurrency* pThis, long p0, long p1) {
    pThis->SetCurrency(p0, p1);
}
// Symbol: ?SetEnabled@COleControl@@QEAAXH@Z
// COleControl::SetEnabled
extern "C" void MS_ABI impl__SetEnabled_COleControl__QEAAXH_Z(COleControl* pThis, int p0) {
    pThis->SetEnabled(p0);
}
// Symbol: ?SetExtent@COleClientItem@@QEAAXAEBVCSize@@W4tagDVASPECT@@@Z
// COleClientItem::SetExtent
extern "C" void MS_ABI impl__SetExtent_COleClientItem__QEAAXAEBVCSize__W4tagDVASPECT___Z(COleClientItem* pThis, const CSize* p0, tagDVASPECT p1) {
    pThis->SetExtent((*p0), p1);
}
// Symbol: ?SetFont@COleControl@@QEAAXPEAUIFontDisp@@@Z
// COleControl::SetFont
extern "C" void MS_ABI impl__SetFont_COleControl__QEAAXPEAUIFontDisp___Z(COleControl* pThis, IFontDisp* p0) {
    pThis->SetFont(p0);
}
// Symbol: ?SetForeColor@COleControl@@QEAAXK@Z
// COleControl::SetForeColor
extern "C" void MS_ABI impl__SetForeColor_COleControl__QEAAXK_Z(COleControl* pThis, unsigned long p0) {
    pThis->SetForeColor(p0);
}
// Symbol: ?SetHelpInfo@COlePropertyPage@@QEAAXPEB_W0K@Z
// COlePropertyPage::SetHelpInfo
extern "C" void MS_ABI impl__SetHelpInfo_COlePropertyPage__QEAAXPEB_W0K_Z(COlePropertyPage* pThis, const wchar_t* p0, const wchar_t* p1, unsigned long p2) {
    pThis->SetHelpInfo(p0, p1, p2);
}
// Symbol: ?SetHostNames@COleClientItem@@QEAAXPEB_W0@Z
// COleClientItem::SetHostNames
extern "C" void MS_ABI impl__SetHostNames_COleClientItem__QEAAXPEB_W0_Z(COleClientItem* pThis, const wchar_t* p0, const wchar_t* p1) {
    pThis->SetHostNames(p0, p1);
}
// Symbol: ?SetIconicMetafile@COleClientItem@@QEAAHPEAX@Z
// COleClientItem::SetIconicMetafile
extern "C" int MS_ABI impl__SetIconicMetafile_COleClientItem__QEAAHPEAX_Z(COleClientItem* pThis, void* p0) {
    return (int)pThis->SetIconicMetafile(p0);
}
// Symbol: ?SetInitialSize@COleControl@@QEAAXHH@Z
// COleControl::SetInitialSize
extern "C" void MS_ABI impl__SetInitialSize_COleControl__QEAAXHH_Z(COleControl* pThis, int p0, int p1) {
    pThis->SetInitialSize(p0, p1);
}
// Symbol: ?SetModifiedFlag@COleControl@@QEAAXH@Z
// COleControl::SetModifiedFlag
extern "C" void MS_ABI impl__SetModifiedFlag_COleControl__QEAAXH_Z(COleControl* pThis, int p0) {
    pThis->SetModifiedFlag(p0);
}
// Symbol: ?SetModifiedFlag@COlePropertyPage@@QEAAXH@Z
// COlePropertyPage::SetModifiedFlag
extern "C" void MS_ABI impl__SetModifiedFlag_COlePropertyPage__QEAAXH_Z(COlePropertyPage* pThis, int p0) {
    pThis->SetModifiedFlag(p0);
}
// Symbol: ?SetPageName@COlePropertyPage@@QEAAXPEB_W@Z
// COlePropertyPage::SetPageName
extern "C" void MS_ABI impl__SetPageName_COlePropertyPage__QEAAXPEB_W_Z(COlePropertyPage* pThis, const wchar_t* p0) {
    pThis->SetPageName(p0);
}
// Symbol: ?SetProperty@COleControlSite@@UEAAXJGZZ
// COleControlSite::SetProperty
extern "C" void MS_ABI impl__SetProperty_COleControlSite__UEAAXJGZZ(COleControlSite* pThis, long p0, unsigned short p1) {
    pThis->SetProperty(p0, p1);
}
// Symbol: ?SetText@COleControl@@QEAAXPEB_W@Z
// COleControl::SetText
extern "C" void MS_ABI impl__SetText_COleControl__QEAAXPEB_W_Z(COleControl* pThis, const wchar_t* p0) {
    pThis->SetText(p0);
}
// Symbol: ?UnaccessData@COleSafeArray@@QEAAXXZ
// COleSafeArray::UnaccessData
extern "C" void MS_ABI impl__UnaccessData_COleSafeArray__QEAAXXZ(COleSafeArray* pThis) {
    pThis->UnaccessData();
}
// Symbol: ?UnlockRange@COleStreamFile@@UEAAX_K0@Z
// COleStreamFile::UnlockRange
extern "C" void MS_ABI impl__UnlockRange_COleStreamFile__UEAAX_K0_Z(COleStreamFile* pThis, unsigned __int64 p0, unsigned __int64 p1) {
    pThis->UnlockRange(p0, p1);
}
// Symbol: ?Unregister@COleObjectFactory@@QEAAHXZ
// COleObjectFactory::Unregister
extern "C" int MS_ABI impl__Unregister_COleObjectFactory__QEAAHXZ(COleObjectFactory* pThis) {
    return (int)pThis->Unregister();
}
// Symbol: ?Unregister@COleTemplateServer@@QEAAHXZ
// COleTemplateServer::Unregister
extern "C" int MS_ABI impl__Unregister_COleTemplateServer__QEAAHXZ(COleTemplateServer* pThis) {
    return (int)pThis->Unregister();
}
// Symbol: ?UnregisterAll@COleObjectFactory@@SAHXZ
// Static: COleObjectFactory::UnregisterAll
extern "C" int MS_ABI impl__UnregisterAll_COleObjectFactory__SAHXZ() {
    return (int)COleObjectFactory::UnregisterAll();
}
// Symbol: ?UpdateLink@COleClientItem@@QEAAHXZ
// COleClientItem::UpdateLink
extern "C" int MS_ABI impl__UpdateLink_COleClientItem__QEAAHXZ(COleClientItem* pThis) {
    return (int)pThis->UpdateLink();
}
// Symbol: ?UpdateRegistry@COleObjectFactory@@MEAAHH@Z
// COleObjectFactory::UpdateRegistry
extern "C" int MS_ABI impl__UpdateRegistry_COleObjectFactory__MEAAHH_Z(COleObjectFactory* pThis, int p0) {
    return (int)pThis->UpdateRegistry(p0);
}
// Symbol: ?UpdateRegistry@COleTemplateServer@@QEAAXW4OLE_APPTYPE@@PEAPEB_W1H@Z
// COleTemplateServer::UpdateRegistry
extern "C" void MS_ABI impl__UpdateRegistry_COleTemplateServer__QEAAXW4OLE_APPTYPE__PEAPEB_W1H_Z(COleTemplateServer* pThis, OLE_APPTYPE p0, const wchar_t** p1, const wchar_t** p2, int p3) {
    pThis->UpdateRegistry(p0, p1, p2, p3);
}
// Symbol: ?UpdateRegistryAll@COleObjectFactory@@SAHH@Z
// Static: COleObjectFactory::UpdateRegistryAll
extern "C" int MS_ABI impl__UpdateRegistryAll_COleObjectFactory__SAHH_Z(int p0) {
    return (int)COleObjectFactory::UpdateRegistryAll(p0);
}
// Symbol: ?VerifyLicenseKey@COleObjectFactory@@MEAAHPEA_W@Z
// COleObjectFactory::VerifyLicenseKey
extern "C" int MS_ABI impl__VerifyLicenseKey_COleObjectFactory__MEAAHPEA_W_Z(COleObjectFactory* pThis, wchar_t* p0) {
    return (int)pThis->VerifyLicenseKey(p0);
}
// Symbol: ?VerifyUserLicense@COleObjectFactory@@MEAAHXZ
// COleObjectFactory::VerifyUserLicense
extern "C" int MS_ABI impl__VerifyUserLicense_COleObjectFactory__MEAAHXZ(COleObjectFactory* pThis) {
    return (int)pThis->VerifyUserLicense();
}
// Symbol: ?Write@COleStreamFile@@UEAAXPEBXI@Z
// COleStreamFile::Write
extern "C" void MS_ABI impl__Write_COleStreamFile__UEAAXPEBXI_Z(COleStreamFile* pThis, const void* p0, unsigned int p1) {
    pThis->Write(p0, p1);
}
