#!/usr/bin/env python3
"""Regression tests for real-vs-fallback export classification."""

import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

import gen_manifest


SYMBOL = "?GetValue@CTest@@QEBAHXZ"
IMPL = "impl__GetValue_CTest__QEBAHXZ"


class ManifestClassificationTests(unittest.TestCase):
    def _write_source(self, directory, name, header):
        path = Path(directory) / name
        path.write_text(
            f"{header}\n"
            f"// Symbol: {SYMBOL}\n"
            f'extern "C" int MS_ABI {IMPL}() {{ return 0; }}\n',
            encoding="utf-8",
        )
        return path

    def test_handwritten_source_counts_as_real(self):
        with tempfile.TemporaryDirectory() as source_dir:
            self._write_source(source_dir, "CTest.cpp", "// Handwritten implementation")

            comments = gen_manifest.collect_symbol_comments(source_dir)
            functions = gen_manifest.collect_impl_functions(source_dir)

            self.assertIn(SYMBOL, comments)
            self.assertIn(IMPL, functions)

    def test_typed_fallback_does_not_count_as_real(self):
        with tempfile.TemporaryDirectory() as source_dir:
            self._write_source(
                source_dir,
                "renamed_fallback.cpp",
                "// Auto-generated TYPED stubs for OpenMFC\n"
                "// Generated by gen_typed_stubs.py\n"
                "// All stubs return safe defaults (0/nullptr/void).",
            )

            comments = gen_manifest.collect_symbol_comments(source_dir)
            functions = gen_manifest.collect_impl_functions(source_dir)
            manifest = gen_manifest.generate_manifest(
                {SYMBOL: {"ordinal": 1}}, comments, set(), functions
            )

            self.assertEqual({}, comments)
            self.assertEqual({}, functions)
            self.assertEqual([SYMBOL], [entry["symbol"] for entry in manifest["stub"]])
            self.assertEqual([], manifest["real"])

    def test_manual_generated_fallback_does_not_count_as_real(self):
        with tempfile.TemporaryDirectory() as source_dir:
            self._write_source(
                source_dir,
                "ManualThunks.cpp",
                "// Generated by tools/gen_manual_thunks.py\n"
                "// These ABI-compatible thunks return default values.",
            )

            self.assertEqual({}, gen_manifest.collect_symbol_comments(source_dir))
            self.assertEqual({}, gen_manifest.collect_impl_functions(source_dir))


if __name__ == "__main__":
    unittest.main()
